### ISSUE TITLE
database list in the dataset creation form is empty 

### ISSUE THREAD

**Issue by milad000cu** [apache/superset#19742] opened 2022-04-16 18:25 UTC
I installed Superset and connected the PostGres database to it, but the database list in the dataset creation form is empty and there is no database
https://pasteboard.co/gT0ocv1NjGDI.jpg
### Expected results

what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment] 2023-01-18 15:54
Hi there. I don't mean to be dismissive, but I'm going to close this since it doesn't include pertinent reproduction details. No version info, steps taken, and the screenshot seems to be long gone (I'd recommend just pasting the image into github itself). If you can provide more pertinent details to help us troubleshoot, we can re-open this. Or... perhaps it's not even an issue in newer versions of Superset, e.g. 2.0.x?

**Closed by rusackas** 2023-01-18 15:54 UTC
Labels: need:more-info, #bug, need:followup
