### ISSUE TITLE
Error in dual_line chart scale group by months

### ISSUE THREAD

**Issue by Provoo** [apache/superset#10960] opened 2020-09-18 17:14 UTC
How to modify the scale on dual_line chart with time, I have this issue:
I use count and sum 2 diferent variables, de X axis is the time variable, group by month but the scale appears with 21 days of diference: [https://apache-superset.slack.com/files/U01APJV08VC/F01AWHHD6CT/captura_de_pantalla_de_2020-09-17_09-54-21.png](url)

**Comment by JunlinC** [comment] 2020-09-19 07:37
hi Provoo, I'm not able to view the link, can you reproduce the issue? thanks.

**Comment by Provoo** [comment] 2020-09-28 20:34
![Captura de pantalla de 2020-09-28 15-30-28](https://user-images.githubusercontent.com/4282730/94482973-c31fc880-019f-11eb-842f-b66efcdef0c2.png)

Sorry something happend with the link aslo i think is releated with this issue: #11088

**Comment by junlincc** [comment] 2020-09-29 15:19
Thanks for reporting, we will get to this issue early next week and get back to you once it's fixed. 🙏

**Comment by betodealmeida** [comment] 2021-04-21 19:58
Closing this since I can't repro. Please feel free to reopen if you have a path to reproduce.

**Closed by betodealmeida** 2021-04-21 19:58 UTC
Labels: bug, viz:chart-line
