### ISSUE TITLE
 Changing the language takes you to the list of users

### ISSUE THREAD

**Issue by xavier-GitHub76** [apache/superset#29543] opened 2024-07-10 13:07 UTC
### Bug description

Whatever screen you are on, changing the language takes you to the list of users.
This is not logical, the current page should be updated and the most annoying thing is that any entries in progress (for example on the construction of a diagram) are lost

### How to reproduce the bug

Edit a chart
Change the language
The Users list is displayed, the chart edition is lost

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by rusackas** [comment] 2024-07-10 18:10
Closing as a duplicate of https://github.com/apache/superset/issues/12768

**Closed by rusackas** 2024-07-10 18:10 UTC
Labels: need:more-info
