### ISSUE TITLE
How to make gradient color for metric puted as bar in mixed chart in Superset 4.0.0.

### ISSUE THREAD

**Issue by do-you-zorya** [apache/superset#29564] opened 2024-07-11 17:52 UTC
How to make bars colors in  mixed chart to gradient?
My best shot is add color for my metric "test" in JSON metadata:

`"label_colors": {"plan": "#6C8CD5", "test": "#E98F11"},`

**Comment by rusackas** [comment] 2024-07-11 23:52
Unfortunately, this isn't currently supported. You can open an ideas thread in Github Discussions or open a PR/SIP to add support, but I'll close this for now as an Issue since it's not a bug.

**Closed by rusackas** 2024-07-11 23:52 UTC
