### ISSUE TITLE
Drag and drop of metrics in chart interface does not allow movement of order of metrics once placed (was previously able)

### ISSUE THREAD

**Issue by steele-boolkin** [apache/superset#28273] opened 2024-04-30 10:24 UTC
### Bug description

Previous to Superset 4.0.0 after placing a metric into the metric section of the chart interface, one could reorder and drag the order of the metrics in that section. Now the metrics are fixed in place so if you need to re-order them you have to replace all of them from scratch. 

### How to reproduce the bug

1. Go to charts
2. Create a pivot table chart
3. Place metrics in the metric section
4. Try to reorder the metrics

### Superset version

4.0.0

### Python version

I don't know

### Node version

I don't know

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment] 2024-04-30 11:54
Duplicate of https://github.com/apache/superset/issues/28013

**Comment by rusackas** [comment] 2024-04-30 15:15
Indeed... closing as duplicate, in favor of the other issue.

**Comment by Manoj-kumar-C** [comment] 2024-04-30 15:40
Hello steele-boolkin, I like to contribute to this project. Can you guide about the contribution

**Comment by Manoj-kumar-C** [comment] 2024-04-30 15:43
https://www.linkedin.com/in/manojkumar--c/

Can we connect through linkedin for guidance or through this issue is also fine for me

**Closed** 2024-05-01 05:45 UTC
