### ISSUE TITLE
[histogram] Allow configuration of x-axis range

### ISSUE THREAD

**Issue by serenajiang** [apache/superset#14758] opened 2021-05-21 21:33 UTC
**Is your feature request related to a problem? Please describe.**
The behavior of the histogram chart is sometimes confusing when dealing with integer values. For example, for a chart with x-axis values [1,2,3,4,5], 4 and 5 are grouped into the same bin even when 5 bins are specified:

![image](https://user-images.githubusercontent.com/14146019/119199237-9460a600-ba3f-11eb-8055-dcffcf9d3981.png)

**Describe the solution you'd like**

Users should be able to specify the range for the x-axis in `Chart Options`

For the above example, a user would be able to specify the range as `[1, 6)` with `5` bins. This would break the range into the bins [1,2), [2,3), [3, 4), [4, 5), [5, 6).

This is also useful because it allows users to ensure that the range of the chart not change as the data changes. Users would also be able to make sure the ranges of charts are aligned in a dashboard.

**Describe alternatives you've considered**
For the specific problem I mentioned, we could fix it by by tweaking bin calculations. Ex. if the max is an integer, use max + 1 for the x-axis max. However, this solution probably does not apply to all use cases, and it doesn't provide the other benefits mentioned above.

**Comment by junlincc** [comment] 2021-05-24 20:05
@serenajiang it makes sense! we will include the x range configuration in Echarts histogram.

**Comment by rusackas** [comment] 2023-01-04 20:35
Closing this one as "not planned" since it's not a bug per se, but a feature request for a legacy NVD3 chart, which is not likely to get support soon. If anyone seeing this has interest in either updating the NVD3 chart, or taking on a proper ECharts histogram chart feature, let's discuss in a new [Ideas discussion ](https://github.com/apache/superset/discussions/categories/ideas)

**Closed by rusackas** 2023-01-04 20:35 UTC
Labels: viz:charts:echarts, enhancement:committed, viz:charts:histogram
