### ISSUE TITLE
DRILL_TO_DETAIL Feature is not working

### ISSUE THREAD

**Issue by santoshmallah** [apache/superset#23234] opened 2023-02-28 12:20 UTC
I am using ```superset 2.0.1``` and want to use DRILL_TO_DETAIL feature 
 My superset_config.py file look like
```JSON
FEATURE_FLAGS = {
    'CLIENT_CACHE': False,
    'ENABLE_EXPLORE_JSON_CSRF_PROTECTION': False,
    'PRESTO_EXPAND_DATA': True,
    'ENABLE_TEMPLATE_PROCESSING': True,
    'ALERTS_ATTACH_REPORTS':True,
    'ALLOW_ADHOC_SUBQUERY':True,
    'DASHBOARD_CROSS_FILTERS':True,
    'DASHBOARD_RBAC':True,
    'DISABLE_LEGACY_DATASOURCE_EDITOR':True,
    'DRUID_JOINS':True,
    "ALERT_REPORTS": True,
    'EMBEDDABLE_CHARTS':True,
    'EMBEDDED_SUPERSET':True,
    'ENABLE_DND_WITH_CLICK_UX':True,
    'ENABLE_EXPLORE_DRAG_AND_DROP':True,
    'ENFORCE_DB_ENCRYPTION_UI':True,
    'ESCAPE_MARKDOWN_HTML':True,
    'LISTVIEWS_DEFAULT_CARD_VIEW':True,
    'SCHEDULED_QUERIES':True,
    'SQLLAB_BACKEND_PERSISTENCE':True,
    'SQL_VALIDATORS_BY_ENGINE':True,
    'THUMBNAILS':True,
    'ROW_LEVEL_SECURITY': True,
    'ALLOW_FULL_CSV_EXPORT': True,
    'THUMBNAILS_SQLA_LISTENERS': True,
    'DASHBOARD_FILTERS_EXPERIMENTAL': True,
    'DASHBOARD_NATIVE_FILTERS': True,
    'HORIZONTAL_FILTER_BAR': True,
    'ENABLE_DRUID_DASHBOARDING':True,
#    'ENABLE_FILTER_BOX_MIGRATION':True,
    'ENABLE_EXPLORE_DRAG_AND_DROP':True,
    'DYNAMIC_PLUGINS':True,
    'DASHBOARD_NATIVE_FILTERS_SET':True,
    'DASHBOARD_EDIT_CHART_IN_NEW_TAB':True,
    'CROSS_REFERENCES':True,
    **'DRILL_TO_DETAIL':True,**
    'FEATURE_DRILL_TO_DETAIL':True,
    'UX_BETA':True,
    'VERSIONED_EXPORT':True
}
```
I have added ```'DRILL_TO_DETAIL':True``` in my configuration file, but the Drill to Detail option is still unavailable in apache superset.

![image](https://user-images.githubusercontent.com/51262721/221852007-c8966a30-0d0a-478b-9e0a-cb987ca8b548.png)

- browser type and version: Chrome
- superset version: `2.0.1`
- python version: `3.8.0`
- node.js version: `v16.14.2`
- any feature flags active:   ```'DRILL_TO_DETAIL':True```

I have check preset chart drill to detail option is available in that.

![image](https://user-images.githubusercontent.com/51262721/221852280-93675f83-ee58-4f70-9eba-4964367f3a76.png)

How can I enable this feature in apache superset.

Thanks in advance.

**Comment by sfirke** [comment] 2023-03-01 03:13
I believe `DRILL_TO_DETAIL` was merged into Superset after 2.0.0 was released, and did not make it into 2.0.1 because 2.0.1 is a bugfix/patch release.  Preset runs a version of Superset that is closer to the latest master commit and it makes sense they would have this feature.

Maybe try out 2.1.0rc1, the release candidate for 2.1.0 that just came out for testing?  There will likely be another release candidate before the eventual 2.1.0 release, but that testing could answer your question - and if you find any bugs with `DRILL_TO_DETAIL` it could be handy.

**Comment by rusackas** [comment] 2023-03-06 18:26
@sfirke is correct. This is not a bug, but a release timing issue. You can try 2.1.0 (currently in voting and not yet ratified) or update to the latest `master` if you need this feature. It will not be coming to 2.0.x releases.

**Closed by rusackas** 2023-03-06 18:26 UTC
Labels: #bug

**Comment by HelloValue** [comment] 2023-03-18 17:20
@santoshmallah 
hi，Are your parameters（DASHBOARD_CROSS_FILTERS） valid?
