### ISSUE TITLE
UK Country Map chart not visible (extremly small in the screen)

### ISSUE THREAD

**Issue by zsellami** [apache/superset#11666] opened 2020-11-12 16:50 UTC
I added a country map UK with UK data but the map is really very small. Any explanation about it ? also the isle of man tooltip text are present when i hoover the cursor on the border of the map.

With other country and other data of country the map are visible.

My superset version is : 0.37.2
Web browser : Chrome, Firefox

### Expected results

what you expected to happen.

### Actual results

what actually happens.

#### Screenshots
![UK_Country_Map](https://user-images.githubusercontent.com/22955406/98969173-e1067a00-250e-11eb-84aa-312c76760296.PNG)

### Environment

(please complete the following information):

- superset version: `0.37.2`
- python version: `3.6`
- node.js version: `node -v` No node installed

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zufolo441** [comment] 2020-11-17 09:57
Usually it happens when the map has a very far overseasy territory. Search for some island near the edges.

**Comment by ktmud** [comment] 2021-04-09 23:37
Duplicate of https://github.com/apache/superset/issues/4568

**Closed by ktmud** 2021-04-09 23:37 UTC
Labels: bug
