### ISSUE TITLE
Upgrade to 0.37.1 has bug: column dbs.allow_cvas does not exist

### ISSUE THREAD

**Issue by sazary** [apache/superset#11080] opened 2020-09-26 13:53 UTC
Hi  
I just upgraded superset from 0.36.0 to 0.37.1 per instructions in docs. Now when I try to open any dashboard or slice, I get a 500 error.

### Expected results

The dashboards to open.

### Actual results

A 500 error, with this stacktrace:

```
Sorry, something went wrong
500 - Internal Server Error
Stacktrace
        Traceback (most recent call last):
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column dbs.allow_cvas does not exist
LINE 1: ...low_csv_upload, dbs.allow_ctas AS dbs_allow_ctas, dbs.allow_...
                                                             ^
HINT:  Perhaps you meant to reference the column "dbs.allow_ctas".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/superset/.env/superset/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/superset/.env/superset/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/superset/.env/superset/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/superset/.env/superset/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/superset/.env/superset/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/superset/.env/superset/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/superset/.env/superset/lib/python3.6/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/home/superset/.env/superset/lib/python3.6/site-packages/superset/views/core.py", line 1616, in dashboard
    for datasource, slices in datasources.items()
  File "/home/superset/.env/superset/lib/python3.6/site-packages/superset/views/core.py", line 1616, in <dictcomp>
    for datasource, slices in datasources.items()
  File "/home/superset/.env/superset/lib/python3.6/site-packages/superset/connectors/base/models.py", line 276, in data_for_slices
    data = self.data
  File "/home/superset/.env/superset/lib/python3.6/site-packages/superset/connectors/sqla/models.py", line 602, in data
    data_ = super().data
  File "/home/superset/.env/superset/lib/python3.6/site-packages/superset/connectors/base/models.py", line 244, in data
    "database": self.database.data,  # pylint: disable=no-member
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 287, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/orm/attributes.py", line 723, in get
    value = self.callable_(state, passive)
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 760, in _load_for_state
    session, state, primary_key_identity, passive
  File "<string>", line 1, in <lambda>
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/orm/strategies.py", line 850, in _emit_lazyload
    session.query(self.mapper), primary_key_identity
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 616, in _load_on_pk_identity
    result = list(bq.for_session(self.session).params(**params))
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/ext/baked.py", line 445, in __iter__
    return q._execute_and_instances(context)
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3528, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1014, in execute
    return meth(self, multiparams, params)
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1133, in _execute_clauseelement
    distilled_params,
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1318, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1512, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1278, in _execute_context
    cursor, statement, parameters, context
  File "/home/superset/.env/superset/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dbs.allow_cvas does not exist
LINE 1: ...low_csv_upload, dbs.allow_ctas AS dbs_allow_ctas, dbs.allow_...
                                                             ^
HINT:  Perhaps you meant to reference the column "dbs.allow_ctas".

[SQL: SELECT dbs.created_on AS dbs_created_on, dbs.changed_on AS dbs_changed_on, dbs.id AS dbs_id, dbs.verbose_name AS dbs_verbose_name, dbs.database_name AS dbs_database_name, dbs.sqlalchemy_uri AS dbs_sqlalchemy_uri, dbs.password AS dbs_password, dbs.cache_timeout AS dbs_cache_timeout, dbs.select_as_create_table_as AS dbs_select_as_create_table_as, dbs.expose_in_sqllab AS dbs_expose_in_sqllab, dbs.allow_run_async AS dbs_allow_run_async, dbs.allow_csv_upload AS dbs_allow_csv_upload, dbs.allow_ctas AS dbs_allow_ctas, dbs.allow_cvas AS dbs_allow_cvas, dbs.allow_dml AS dbs_allow_dml, dbs.force_ctas_schema AS dbs_force_ctas_schema, dbs.allow_multi_schema_metadata_fetch AS dbs_allow_multi_schema_metadata_fetch, dbs.extra AS dbs_extra, dbs.encrypted_extra AS dbs_encrypted_extra, dbs.impersonate_user AS dbs_impersonate_user, dbs.server_cert AS dbs_server_cert, dbs.created_by_fk AS dbs_created_by_fk, dbs.changed_by_fk AS dbs_changed_by_fk 
FROM dbs 
WHERE dbs.id = %(param_1)s]
[parameters: {'param_1': 2}]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

#### How to reproduce the bug

1. Install version 0.36.0
2. Setup some charts and dashboards
3. Upgrade to version 0.37.0 using commands written in docs:

```
pip install apache-superset --upgrade
superset db upgrade
superset init
```

4. Go to any dashboard/slice.

### Environment

(please complete the following information):

- superset version: `Superset 0.37.1`
- python version: `Python 3.6.11`

**Comment by zhaoyongjie** [comment] 2020-09-27 06:48
@sazary Hi, guy, must run database migration script:
```
$ superset db upgrade
```

**Comment by sazary** [comment] 2020-09-27 07:47
Hi
I did it, as I've mentioned in steps to reproduce
________________________________

**Comment by dpgaspar** [comment] 2020-09-28 09:59
Can you post the output from `superset db upgrade` ? Also are you using `docker-compose` or some other install method?

**Comment by sazary** [comment] 2020-09-28 12:36
sorry I don't have the output now, but as far as I could see there wasn't any error in it.  
I've installed & upgraded it using pip

**Comment by nh43de** [comment] 2020-10-23 17:36
I am having the same issue as well, when using 0.37.2 release, docker-compose up --build

**Comment by nh43de** [comment] 2020-10-23 17:52
Steps to reproduce:

1. Check out 0.37.2 tag
2.  `docker-compose up --build --force-recreate`
3.  < < wait for compose >> 
4. Shell into superset-app, run `superset db upgrade` and I get this error message.

```
superset@5c7e780d5110:/app$ superset db upgrade
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyarrow 0.17.0 (/usr/local/lib/python3.7/site-packages), Requirement.parse('pyarrow<1.1,>=1.0.1'), {'apache-superset'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 527, in get_command
    self._load_plugin_commands()
  File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 517, in _load_plugin_commands
    import pkg_resources
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 569, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyarrow<1.1,>=1.0.1' distribution was not found and is required by apache-superset
superset@5c7e780d5110:/app$

```

**Comment by mistercrunch** [comment] 2020-10-24 00:51
@nh43de , looks like a different error

**Comment by keehl1213** [comment] 2020-12-14 08:24
> Steps to reproduce:
> 
> 1. Check out 0.37.2 tag
> 2. `docker-compose up --build --force-recreate`
> 3. < < wait for compose >>
> 4. Shell into superset-app, run `superset db upgrade` and I get this error message.
> 
> (note: this problem does not happen in main/master branch, everything behaves normally)
> 
> ```
> superset@5c7e780d5110:/app$ superset db upgrade
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 567, in _build_master
>     ws.require(__requires__)
>   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 884, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 775, in resolve
>     raise VersionConflict(dist, req).with_context(dependent_req)
> pkg_resources.ContextualVersionConflict: (pyarrow 0.17.0 (/usr/local/lib/python3.7/site-packages), Requirement.parse('pyarrow<1.1,>=1.0.1'), {'apache-superset'})
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/superset", line 33, in <module>
>     sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
>     return super(FlaskGroup, self).main(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1254, in invoke
>     cmd_name, cmd, args = self.resolve_command(ctx, args)
>   File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1297, in resolve_command
>     cmd = self.get_command(ctx, cmd_name)
>   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 527, in get_command
>     self._load_plugin_commands()
>   File "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 517, in _load_plugin_commands
>     import pkg_resources
>   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3238, in <module>
>     @_call_aside
>   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 569, in _build_master
>     return cls._build_from_requirements(__requires__)
>   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 582, in _build_from_requirements
>     dists = ws.resolve(reqs, Environment())
>   File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 770, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'pyarrow<1.1,>=1.0.1' distribution was not found and is required by apache-superset
> superset@5c7e780d5110:/app$
> ```

I'm too.  Have you solved the problem?

**Comment by sazary** [comment] 2020-12-14 08:38
@keehl1213 no i just gave up

**Comment by Akitha** [comment] 2021-02-08 14:05
Any update

**Comment by etr2460** [comment] 2021-09-03 22:46
Since this problem doesn't happen in the most recent released versions of superset, and this is a bug from a 0.x version, i'm going to close it out

**Closed by etr2460** 2021-09-03 22:46 UTC
Labels: bug

**Comment by mingfang** [comment] 2022-03-29 13:38
I'm seeing this problem after upgrading to v1.4.2

**Comment by rvsoni** [comment] 2022-04-29 11:38
I have just upgraded to 1.4.2 seeing a problem.

superset_app            | [SQL: SELECT dbs.uuid AS dbs_uuid, dbs.created_on AS dbs_created_on, dbs.changed_on AS dbs_changed_on, dbs.id AS dbs_id, dbs.verbose_name AS dbs_verbose_name, dbs.database_name AS dbs_database_name, dbs.sqlalchemy_uri AS dbs_sqlalchemy_uri, dbs.password AS dbs_password, dbs.cache_timeout AS dbs_cache_timeout, dbs.select_as_create_table_as AS dbs_select_as_create_table_as, dbs.expose_in_sqllab AS dbs_expose_in_sqllab, dbs.configuration_method AS dbs_configuration_method, dbs.allow_run_async AS dbs_allow_run_async, dbs.allow_csv_upload AS dbs_allow_csv_upload, dbs.allow_ctas AS dbs_allow_ctas, dbs.allow_cvas AS dbs_allow_cvas, dbs.allow_dml AS dbs_allow_dml, dbs.force_ctas_schema AS dbs_force_ctas_schema, dbs.allow_multi_schema_metadata_fetch AS dbs_allow_multi_schema_metadata_fetch, dbs.extra AS dbs_extra, dbs.encrypted_extra AS dbs_encrypted_extra, dbs.impersonate_user AS dbs_impersonate_user, dbs.server_cert AS dbs_server_cert, dbs.created_by_fk AS dbs_created_by_fk, dbs.changed_by_fk AS dbs_changed_by_fk 
superset_app            | FROM dbs 
superset_app            | WHERE dbs.id = %(param_1)s]
superset_app            | [parameters: {'param_1': 1}]
superset_app            | (Background on this error at: http://sqlalche.me/e/13/f405)
superset_app            | Traceback (most recent call last):
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
superset_app            |     self.dialect.do_execute(
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
superset_app            |     cursor.execute(statement, parameters)
superset_app            | psycopg2.errors.UndefinedColumn: column dbs.allow_csv_upload does not exist
superset_app            | LINE 1: ...thod, dbs.allow_run_async AS dbs_allow_run_async, dbs.allow_...
superset_app            |                                                              ^
superset_app            | 
superset_app            | 
superset_app            | The above exception was the direct cause of the following exception:
superset_app            | 
superset_app            | Traceback (most recent call last):
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
superset_app            |     rv = self.dispatch_request()
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
superset_app            |     return self.view_functions[rule.endpoint](**req.view_args)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 104, in wraps
superset_app            |     return f(self, *args, **kwargs)
superset_app            |   File "/app/superset/views/base_api.py", line 85, in wraps
superset_app            |     raise ex
superset_app            |   File "/app/superset/views/base_api.py", line 82, in wraps
superset_app            |     duration, response = time_function(f, self, *args, **kwargs)
superset_app            |   File "/app/superset/utils/core.py", line 1471, in time_function
superset_app            |     response = func(*args, **kwargs)
superset_app            |   File "/app/superset/utils/log.py", line 242, in wrapper
superset_app            |     value = f(*args, **kwargs)
superset_app            |   File "/app/superset/charts/api.py", line 736, in data
superset_app            |     return self.get_data_response(command)
superset_app            |   File "/app/superset/charts/api.py", line 547, in get_data_response
superset_app            |     result = command.run(force_cached=force_cached)
superset_app            |   File "/app/superset/charts/commands/data.py", line 50, in run
superset_app            |     payload = self._query_context.get_payload(
superset_app            |   File "/app/superset/common/query_context.py", line 305, in get_payload
superset_app            |     query_results = [
superset_app            |   File "/app/superset/common/query_context.py", line 306, in <listcomp>
superset_app            |     get_query_results(
superset_app            |   File "/app/superset/common/query_actions.py", line 186, in get_query_results
superset_app            |     return result_func(query_context, query_obj, force_cached)
superset_app            |   File "/app/superset/common/query_actions.py", line 98, in _get_full
superset_app            |     payload = query_context.get_df_payload(query_obj, force_cached=force_cached)
superset_app            |   File "/app/superset/common/query_context.py", line 468, in get_df_payload
superset_app            |     query_result = self.get_query_result(query_obj)
superset_app            |   File "/app/superset/common/query_context.py", line 254, in get_query_result
superset_app            |     result = self.datasource.query(query_object.to_dict())
superset_app            |   File "/app/superset/connectors/sqla/models.py", line 1472, in query
superset_app            |     query_str_ext = self.get_query_str_extended(query_obj)
superset_app            |   File "/app/superset/connectors/sqla/models.py", line 764, in get_query_str_extended
superset_app            |     sqlaq = self.get_sqla_query(**query_obj)
superset_app            |   File "/app/superset/connectors/sqla/models.py", line 1003, in get_sqla_query
superset_app            |     template_processor = self.get_template_processor(**template_kwargs)
superset_app            |   File "/app/superset/connectors/sqla/models.py", line 761, in get_template_processor
superset_app            |     return get_template_processor(table=self, database=self.database, **kwargs)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 294, in __get__
superset_app            |     return self.impl.get(instance_state(instance), dict_)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 730, in get
superset_app            |     value = self.callable_(state, passive)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 759, in _load_for_state
superset_app            |     return self._emit_lazyload(
superset_app            |   File "<string>", line 1, in <lambda>
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/strategies.py", line 847, in _emit_lazyload
superset_app            |     q(session)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/baked.py", line 615, in _load_on_pk_identity
superset_app            |     result = list(bq.for_session(self.session).params(**params))
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/baked.py", line 444, in __iter__
superset_app            |     return q._execute_and_instances(context)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
superset_app            |     result = conn.execute(querycontext.statement, self._params)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
superset_app            |     return meth(self, multiparams, params)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
superset_app            |     return connection._execute_clauseelement(self, multiparams, params)
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
superset_app            |     ret = self._execute_context(
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
superset_app            |     self._handle_dbapi_exception(
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
superset_app            |     util.raise_(
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
superset_app            |     raise exception
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
superset_app            |     self.dialect.do_execute(
superset_app            |   File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
superset_app            |     cursor.execute(statement, parameters)
superset_app            | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dbs.allow_csv_upload does not exist
superset_app            | LINE 1: ...thod, dbs.allow_run_async AS dbs_allow_run_async, dbs.allow_...
superset_app            |                                                              ^
superset_app            |

**Comment by maahivikas** [comment] 2022-08-04 03:54
> Since this problem doesn't happen in the most recent released versions of superset, and this is a bug from a 0.x version, i'm going to close it out

still i am getting it in 1.4.1 and 1.4.2 version, same issue how to fix it ?

**Comment by koterin** [comment] 2022-12-26 09:33
Still facinf same issue in 1.5.2, 2.0.0, 2.0.1. Must be something with the settings, but what?
