### ISSUE TITLE
superset-frontend proxy is not working when superset backend decides to use zstd encoding

### ISSUE THREAD

**Issue by jakubjosef** [apache/superset#28366] opened 2024-05-07 11:42 UTC
### Bug description

Hi guys, my company is using Apache Superset and we just found weird situation.
Our new developer were using superset-frontend and he saw weird characters being displayed instead of "normal page".
After few hours of investigation we realised the problem was superset (python server) which served content using zstd encoding (instead of br encoding which other devs were using).
zstd encoding is not supported by superset's node js proxy (see: https://github.com/apache/superset/blob/10c78960a7c5e5628aaceb584c206a81f7fd12c8/superset-frontend/webpack.proxy-config.js#L123)
We managed to fix the problem using exactly same version of python packages from working machine, but it looks like some superset dependency was updated to serve using zstd by default. Unfortunately it looks like zstd is not supported in node.js yet, so we cannot just easily support zstd in webpack.proxy-config.js
Does anyone know which exact package can cause this? I tried to grep superset and werkzeug code for zstd but found nothing.
Thank you for your suggestions.

### How to reproduce the bug

1. Install latest superset
2. Start superset backend
3. Start superset frontend dev-server (npm run dev-server)
4. Go to dev-server and you will see bunch of question marks and weird characters instead of expected markup

### Superset version

master / latest-dev

### Python version

3.11

### Node version

18 or greater

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by mistercrunch** [comment] 2024-05-07 21:16
@jakubjosef so that would be on a fresh install from `pypi` as in `pip install apache-superset` ?

Doing a bit of guessing here, since all of our CI installs the pin packages in `requirements/development.txt`, maybe the unpinned version of Superset has this issue? If that's the case it points towards:
- as a workaround, you leveraging docker images build on top of pinned deps, or using the pinned deps in your installation scripts
- for us, we could run some CI tests against a vanilla `pip install apache-superset`, so at least we know when an open dependency breaks a build - which would inform pin-pointing the issue and changing the version range for that dep

**Comment by mistercrunch** [comment] 2024-05-23 17:58
> but I think we'll face the same issue eventually

My suggestion would be either: 
- use the base docker, which installs the pinned deps ahead of installing the apache-superset package
- fetch the requirements/base.txt from the repo (with the associated version tag you're trying to build as in `git checkout 4.0.0`) and pip install those pin deps ahead of installing the superset package (that has loose dependency ranges). At that point might as well `pip install -e .` to install from the repo as opposed to pypi, but should be same as `pip install apache-superset==4.0.0`

On our side, there's a question as to whether we should publish a more strict or "with depenencies pinned" version of the package to work around all this....

**Comment by eschutho** [comment] 2024-05-29 00:36
Hi @jakubjosef thanks for reporting this, and for the research into the cause. I ran into the same issue and found that adding `COMPRESS_REGISTER = False` into my superset_config.py file fixes it for me when developing locally. We'll look into either documenting this somewhere or fixing it more longer-term.

**Comment by Amylee520** [comment] 2024-06-05 10:25
I also encountered the same problem. After modifying config.py =>COMPRESS_REGISTER = False, the page no longer had strange symbols, but there were many resources on the page that failed to load; May I ask how I can solve this problem?
superset:3.1.3
python: 3.9.7
node: 16.20.2 
npm: 8.19.4
![supersetbug](https://github.com/apache/superset/assets/43265109/6a9088f5-2e72-46e5-ae95-6028aa2d755c)

**Comment by tyrius02** [comment] 2024-06-07 22:38
For me the culprit package was Flask-Compress 1.15.
Rolling back Flask-Compress to 1.14 and removing zstandard solved the problem.

You can `pip install pipdeptree` and then run `pipdeptree -r -p zstandard` to see what depends on zstandard.

**Comment by jakubjosef** [comment] 2024-06-08 08:46
@tyrius02 Thank you for identifying what exact package version is causing this problem, it can help others. We were not able to identify exact cause when we faced this problem.

**Comment by rebareba** [comment] 2024-07-31 11:41
```bash
$ cd superset-frontend
$ npm i simple-zstd -D 
```

Edit `superset-frontend/webpack.proxy-config.js` add `zstd` support :

```js
const {ZSTDDecompress} = require('simple-zstd');

...
function processHTML(proxyResponse, response) {
  ...

  } else if (responseEncoding === 'zstd') {
    uncompress = ZSTDDecompress();
  }
 ...
}
```

**Comment by jakubjosef** [comment] 2024-07-31 11:57
@rebareba Great, thank you for providing this code!

**Comment by rusackas** [comment] 2024-07-31 17:15
Sounds like we're discussing [this bug](https://github.com/apache/superset/issues/29678)... I'm excited to hear we're on the verge of a real fix here!

**Comment by rusackas** [comment] 2024-08-28 18:02
Fixed by https://github.com/apache/superset/pull/30034
Thanks to all (especially @rebareba) for the help here!

**Closed** 2024-08-28 18:02 UTC
