### ISSUE TITLE
Give a little space around the highest and lowest axis data points 

### ISSUE THREAD

**Issue by snehlata08** [apache/superset#21286] opened 2022-09-01 09:36 UTC
When a graph is plotted in superset the highest and the lowest axis data points are plotted in the graph which doesn't look that good. 
 
![image](https://user-images.githubusercontent.com/79985986/187882169-151b6b31-5a8e-493e-8be4-57c0b7e08976.png)

For eg, in grafana if the same graph is plotted it gives some white space on both the sides which makes the entire look quiet neat and clean.
![image](https://user-images.githubusercontent.com/79985986/187882568-5267d62c-70c0-4e45-9abc-094df51a0f92.png)

So it would be great if superset if comes up with something similar.

**Comment by rusackas** [comment] 2024-02-09 21:30
Closing this since it's (arguably, at least) not a bug... if you want to open a PR adding an option to include such padding, that would be cool. Otherwise, we can move this to a GitHub Discussion of the Ideas variety if you'd like :) Thanks!

**Closed by rusackas** 2024-02-09 21:30 UTC
