### ISSUE TITLE
REST API: Cant list more than 20 dashboards 

### ISSUE THREAD

**Issue by progressive-scaler** [apache/superset#25815] opened 2023-11-01 00:12 UTC
My goal is to list all the dashboards from superset, and for each dashboard, export the files and name them accordingly with its title, author and the date it was created.

The problem is that having 31 dashboards, i am only able to retrieve information of 20.

I tested the link in the following formats:

- https://superset-tests.myserver.com/api/v1/dashboard/
- https://superset-tests.myserver.com/api/v1/dashboard/?page=0&page_size=50
- https://superset-tests.myserver.com/api/v1/dashboard/?page=1

They all retrieve the same output

#### How to reproduce the bug

1. Access a valid Superset instance, with more than 20 dashboards, with the api call _**api/v1/dashboard/**_
2. Validate the number of dashboard retrieved is equal to the count attribute.

### Expected results

I expect that the number of items retrieved are equal to the total number of dashboards.

### Actual results

The number of items retrieved is always 20, even when you have more than 20 dashboards.

#### Screenshots

![image](https://github.com/apache/superset/assets/149486548/3cd1870a-58c5-49ef-9ee1-c2e04a258cc3)

### Environment

- Chrome Version 118.0.5993.118 (Official Build) (64-bit):
- superset version: `superset version`
- python version: N/D
- node.js version: N/D
- any feature flags active: N/D

**Comment by michael-s-molina** [comment] 2023-11-03 13:37
Duplicate of https://github.com/apache/superset/issues/24993.

**Closed by michael-s-molina** 2023-11-03 13:37 UTC
