### ISSUE TITLE
Some kind of bug with filters.

### ISSUE THREAD

**Issue by FFPavlik** [apache/superset#30547] opened 2024-10-08 12:05 UTC
### Bug description

Hello! I caught some bug with the filters. Previously, everything worked well, but from a certain point the filters began to behave incorrectly when opening a report, and the entire report froze.
The problem was solved by resetting the filters, but in order to reset them I had to spend a lot of time going into the filter settings and changing them before the report froze

### Screenshots/recordings

h

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [ ] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment] 2024-10-09 14:13
Hi @FFPavlik - I appreciate the bug report but right now this does not provide enough information to be actionable.  Could you at the very least retitle it to more specifically describe the problem?  The ideal would be if you can provide steps to reproduce the problem, or at least a video showing what you are talking about.

**Comment by rusackas** [comment] 2024-11-04 18:06
Closing since we haven't gotten any reproducible test cases yet. We're certainly happy to reopen this if we can get more details!

**Closed by rusackas** 2024-11-04 18:06 UTC
Labels: validation:required, need:more-info
