### ISSUE TITLE
Non-descriptive error when saving Dataset from SQL Lab with JINJA placeholder present

### ISSUE THREAD

**Issue by maxgillmaxgill** [apache/superset#26876] opened 2024-01-30 00:35 UTC
### Bug description

I get a "FATAL ERROR" when I try to save a dataset from SQL Lab that looks like this:

`SELECT 
  COL_ID as ID,
  COL_DESCRIPTION as DESCRIPTION,
  COL_CREATEDDATE as CREATEDDATE,
  COL_TAG as TAG,
  COL_VIEWCOUNT as VIEWCOUNT
FROM {{ecx_schema}}.tbl_kbtag`

But I don't get an error if I save it like this:
`SELECT 
  COL_ID as ID,
  COL_DESCRIPTION as DESCRIPTION,
  COL_CREATEDDATE as CREATEDDATE,
  COL_TAG as TAG,
  COL_VIEWCOUNT as VIEWCOUNT
FROM my_schema.tbl_kbtag`

While it would be good to be able to save these datasets and pre-populate the jinja params in the new dataset, simply explaining the error instead of "Fatal Error" would be a good start.

### How to reproduce the bug

1. Go to SQL Lab
2. Create an SQL query with the schema name in a Jinja template
3. Click Save Dataset

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/26105090/6d504f27-121b-4f66-92ba-82888945bb31)

### Superset version

3.0.3

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by qleroy** [comment] 2024-01-30 03:35
#25786

**Comment by rusackas** [comment] 2024-05-13 18:03
Adding a link the relevant PR that would likely close this (I think?)

https://github.com/apache/superset/pull/27796

**Comment by amosanurag** [comment] 2024-06-20 06:31
The issue appears when you try to use jinja templating to save the query in SQLLab as a dataset. If you save the dataset and provide a default value in place of using any jinja templates.Then during the chart development process, you can make updates to the query and enter your jinja template. This won't lead to errors.

**Comment by rusackas** [comment] 2024-08-22 18:38
Closing as a duplicate of https://github.com/apache/superset/issues/25786... let's take the conversation (and hopefully a solution!) there.

**Closed by rusackas** 2024-08-22 18:38 UTC
