### ISSUE TITLE
Charts in tabs don't display until you unfold out of scope filters

### ISSUE THREAD

**Issue by jurbanhost** [apache/superset#22470] opened 2022-12-20 12:22 UTC
#### How to reproduce the bug

1. Create dashboard with that structure:
  Three charts in three tabs, with three dashboard filters, each filter for own tab.
  Scope of filter 1 is for tab 1, scope of filter 2 is for tab 2 and scope of filter 3 is for tab 3.
  Save this dashboard by name "bug_report_20221220"
  
  or (bestway)
  
  upload dashboard from file: [dashboard_export_20221220T112259.zip](https://drive.google.com/file/d/1lNKv9E-vifb-uwY438gcK-xHzPNF6Bs-/view?usp=sharing)
  Attention! used dataset "birth_names" from Examples

2. Go to "Dashboards" menu item of Superset.
3. Click to dashboard by name "bug_report_20221220"
4. You will see that charts in tabs don't display until you unfold out of scope filters.

Attention! You may need to open the dashboard "bug_report_20221220" twice to reproduce unexpected behavior.

### Expected results

Сharts in tabs will display without you unfold out of scope filters.

### Actual results

Сharts in tabs don't display until you unfold out of scope filters.

#### Video of unexpected behavior.

[superset filters with carts in tabs bug.wmv](https://drive.google.com/file/d/1xQRkUq1Nxe-Ra8lCTqg7cSBemgTBtCVi/view?usp=sharing)

### Environment

Apache Superset in docker from https://hub.docker.com/r/apache/superset latest version on 2022-12-20.

**Comment by jurbanhost** [comment] 2022-12-23 10:51
The same problem was found in the preset version

**Comment by sfirke** [comment] 2022-12-27 18:40
Sounds like the bug discussed here:https://github.com/apache/superset/discussions/21263#discussioncomment-3788816  Do those linked issues cover what's happening to you?

**Comment by jurbanhost** [comment] 2022-12-28 08:30
> Sounds like the bug discussed here:[#21263 (comment)](https://github.com/apache/superset/discussions/21263#discussioncomment-3788816) Do those linked issues cover what's happening to you? If so, yes, this is currently the worst bug in released Superset IMO. It couldn't be patched for 2.0.1 because the fix relies on a new version but it sounds likely for 2.1.0.

Yes, https://github.com/apache/superset/issues/20797 is the most relevant to my issue.

Thanks for the answer!

**Comment by rusackas** [comment] 2023-01-04 16:29
Closing this issue as a duplicate of #2079 (and/or #21263).

**Closed by rusackas** 2023-01-04 16:29 UTC
Labels: #bug
