### ISSUE TITLE
when updating the DB password in superset after upgrading to 2.0.0

### ISSUE THREAD

**Issue by prathavich** [apache/superset#22554] opened 2022-12-30 11:01 UTC
getting this error
any solution for this  
![image](https://user-images.githubusercontent.com/89897628/210063215-6677449a-2b30-4767-a7dc-de2b05bd6b1b.png)

**Comment by rusackas** [comment] 2023-01-13 22:49
Closing this since none of the issue reporting details have been filled out. Please let us know more information about your deployment and what reproduction steps we might hope to be able to follow to help diagnose this  issue.

**Closed by rusackas** 2023-01-13 22:49 UTC
