### ISSUE TITLE
Couldn't able to add reports

### ISSUE THREAD

**Issue by wargod797** [apache/superset#13195] opened 2021-02-18 03:53 UTC
![image](https://user-images.githubusercontent.com/43702120/108302906-eab51300-71ca-11eb-82b7-ac5236f1c00a.png)

After following doc from below link setup email config
https://superset.apache.org/docs/installation/email-reports

ENABLE_ALERTS = True
ENABLE_ALERTS = True

I'm using superset 1.0.0 Jan 21 Release

email schedule working fine
Add button is gray couldn't able add any alerts or reports

please help

**Comment by willbarrett** [comment] 2021-02-18 21:51
Closing as a duplicate of https://github.com/apache/superset/issues/13172

**Closed by willbarrett** 2021-02-18 21:51 UTC
Labels: #bug
