### ISSUE TITLE
Alert-Report disabled while using Superset 3.0.2 docker image 

### ISSUE THREAD

**Issue by Satish-Pnatics** [apache/superset#26221] opened 2023-12-08 06:58 UTC
#### How to reproduce the bug

1. run sudo TAG=3.0.2 docker compose -f docker-compose-non-dev.yml up
2. Login to Superset as admin user
3. Click on to setting at the right most corner 
4. Aletr-Report option is not available as Menu Item

Please note following feature flags are enabled in 
"ALERT_REPORTS": True,
    "DASHBOARD_RBAC": True,
    "ENABLE_EXPLORE_DRAG_AND_DROP": True,  # deprecated
    "ENABLE_ADVANCED_DATA_TYPES": True,
    "ALERTS_ATTACH_REPORTS": True,
   
### Expected results
Alert=Report  Menu item to be enabled 
what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment] 2023-12-08 19:13
Hello, it's very likely that this is a not a bug in Superset and instead a matter of how you configured it or are using it.

Can you confirm that your feature flag configuration is being loaded correctly?  E.g., add something like `"HORIZONTAL_FILTER_BAR": True` to the list and then confirm you are in fact able to use that feature.

Or perhaps your user does not have sufficient privileges for this action.  Try logging in as an admin user.

**Comment by Satish-Pnatics** [comment] 2023-12-09 03:58
Thanks , I checked , feature flag gets enabled , now it is working . However screenshot is not getting captured while sending report by mail

**Comment by sfirke** [comment] 2023-12-11 14:57
Good to hear the feature is enabled.  There can be a lot of reasons why it's not working, unfortunately.

I'm going to close this issue since it's not an actionable bug report for Superset.  If you would like help debugging your deployment, please share more info (like what's in the logs of your worker container) either in Github Discussions (feel free to @ me) or on the Superset Slack chat.  The link to join Slack is http://bit.ly/join-superset-slack.

**Closed by sfirke** 2023-12-11 14:57 UTC
Labels: #bug:cant-reproduce
