### ISSUE TITLE
Translation: missing terms in french

### ISSUE THREAD

**Issue by cchristofr** [apache/superset#25728] opened 2023-10-20 21:06 UTC
Some terms are not translated in the UI

#### How to reproduce the bug

1. Open a dashboard
2. Click on ADD/EDIT Filters
3. Add a Time range filter
4. Filter has default value  : Choose Last
5. Choose 'Last quarter'
6. Save

### Expected results

The value of the filter should be "Le trimestre dernier" 

### Actual results

But it is "Last quarter"

The same for each period: "Last day" to ... "Last year" are not translated as value for the filter.
#### Screenshots

![bug_french](https://github.com/apache/superset/assets/74195127/097f0b35-b667-483b-8172-897b5640e6cf)

### Environment

(please complete the following information):

- browser type and version:Firefox 118.0.2
- superset version: 2.1.0
- python version: 3.8.16
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment] 2023-11-09 20:02
This was fixed in https://github.com/apache/superset/pull/20078 🚀  Looks like that PR made it into 3.0.0.  If you're able to upgrade to that version or 3.0.1 (the latest), you should see it.  Please reply if that is not the case.

**Comment by aehanno** [comment] 2023-11-15 16:29
HI @sfirke, I upgrade my version in 3.0.1 and when I choose French, I got all those string in English
Before my upgrade I got that
![image](https://github.com/apache/superset/assets/104373599/1c5cb503-0176-45d7-970d-d3886eec56a1)
and now in 3.0.1, I have that
![image](https://github.com/apache/superset/assets/104373599/22a4a548-05a7-49e9-89d1-0bf0fed0cfb9)

**Comment by sfirke** [comment] 2023-11-15 16:38
Hmmm. To confirm, you're showing the translation coverage got *worse* when you upgraded to 3.0.0/3.0.1 ?

**Comment by aehanno** [comment] 2023-11-15 16:53
I was in 2.0.1

**Comment by aehanno** [comment] 2023-11-16 16:15
@sfirke and I just saw that there is custom and last that are not translate
But the other filter are correct
![image](https://github.com/apache/superset/assets/104373599/5be7aad9-debe-4793-91d8-fb084a3b94ce)

**Comment by sfirke** [comment] 2023-11-16 16:19
Ah @aehanno I see you authored that PR I linked (thank you!) - are you able to create a PR to add this coverage?

**Comment by aehanno** [comment] 2023-11-16 21:38
I did a PR https://github.com/apache/superset/pull/26010
Do you know, How we can do to have a review on it ?

**Comment by aehanno** [comment] 2023-11-17 21:10
@sfirke and @cchristofr  
The PR https://github.com/apache/superset/pull/26010 fix regression but we still don't have the translation in the filter
It's a more complicated fix than just translation so I didn't found how to fix it

**Comment by Ralkion** [comment] 2023-11-21 19:02
This seems related to #25994

**Closed** 2024-02-21 23:29 UTC
