### ISSUE TITLE
Select time grain "Original Value" is not working on first attempt

### ISSUE THREAD

**Issue by rumbin** [apache/superset#19504] opened 2022-04-04 08:44 UTC
The first attempt to choose "Original Value" as time grain results in "Day" being selected.
This is very confusing for both beginners for power users who might not even check teh result of their actions.

#### How to reproduce the bug

1. Go to Explore with any time-series chart. Make sure  that the set time grain is not "Day". Maybe set it to "Week" and then refresh the page.
2. Click on Time Grain
3. Select "Original Value"
4. See how the Time Grain is set to "Day" instead
5. repeat step 3
6. See how now the time grain is set as desired

### Expected results

Selecting "Original Value" works on the first attempt.

### Actual results

It takes 2 attempts after loading/reloading the page.
It seems that "Original Value" is only set correctly, if "Day" was set before.

#### Screenshots

![time_grain_original_value](https://user-images.githubusercontent.com/1220356/161505615-2b32a634-ad20-4d16-9af9-7bbe299f8cbd.gif)

### Environment

We use the official Docker images of 1.4.1 and 1.4.2, respectively.

- affected browsers: 
    - Chrome 99.0.4844.84, 64 bit
    - Edge 99.0.1150.36, 64 bit
    - 98.0.2, 64 bit
- superset version: 1.4.1; 1.4.2
- python version: python --version
- node.js version: ??
- any feature flags active: 

```python
    FEATURE_FLAGS = {
      # stable:
      "THUMBNAILS": True,
      "THUMBNAILS_SQLA_LISTENERS": True,
      "SQLLAB_BACKEND_PERSISTENCE": True,
      "ENABLE_TEMPLATE_PROCESSING": True,
      "DASHBOARD_CROSS_FILTERS": True,

      # experimental:
      "ALERT_REPORTS": True,
      "ALERTS_ATTACH_REPORTS": True,
      "DASHBOARD_NATIVE_FILTERS": True,

      # unclassified:
      "ENABLE_EXPLORE_DRAG_AND_DROP": True,
      "ENABLE_DND_WITH_CLICK_UX": True,

      # development:
      "DASHBOARD_NATIVE_FILTERS_SET": True
    }
```

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment] 2023-01-23 05:18
The controls are a bit different now as of 2.0.1 and possibly earlier (you just (X) out the time grain, rather than selecting "Original Value") but in any case it seems to work just fine now, and I could not reproduce this issue. Closing as fixed, but let me know if you encounter it in newer versions. Thanks!

**Closed by rusackas** 2023-01-23 05:18 UTC
Labels: #bug
