### ISSUE TITLE
x-aixs alias name same as original field name

### ISSUE THREAD

**Issue by HeathLee** [apache/superset#21755] opened 2022-10-10 11:26 UTC
When using [Apache Doris](https://doris.apache.org/) (compatible with MySQL protocol) as database and enabled GENERIC_CHART_AXES feature, the sql generated by superset can not be executed correctly.

#### How to reproduce the bug
1. Enable `GENERIC_CHART_AXES` feature
2. Explore doris dataset as below
![image](https://user-images.githubusercontent.com/7382922/194853777-a6b1b9e0-3d97-42ea-901e-8d78ff705576.png)

### Expected results

generated sql should have different alias name in `select` clause like
```sql
SELECT DATE(c_at) AS c_at_aliased,
       COUNT(*) AS count
FROM doris_db.table_xxx
GROUP BY DATE(c_at)
ORDER BY count DESC
LIMIT 10000;
```
or user can custome alias x-aixs name

### Environment

- superset version: `master at d1a6f0ebc4e2dd092580ad49da7c724c577e6ece`
- any feature flags active:
`GENERIC_CHART_AXES: true`
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment] 2022-10-11 13:05
@HeathLee Thanks for the report, I will follow this issue.

**Comment by HeathLee** [comment] 2022-11-10 02:40
Any update for this?

**Comment by sowo** [comment] 2022-12-23 09:13
Elasticsearch is also affected by this issue.

**Comment by emirkmo** [comment] 2023-01-26 13:42
This is not database specific. 

It is happening when GENERIC_CHART_AXES is enabled and V2 of the chart is being used. It can be fixed by running a query on the X-axis (or by using the old non V2 version of the chart).

```Python
Error: Orig exception: Code: 215. DB::Exception: Column `<columnname>` is not under aggregate function and not in GROUP BY: While processing <columnname> AS <column name>`.
```

**Comment by rusackas** [comment] 2023-01-26 21:12
Pinging @yousoph and @michael-s-molina since I _think_ you're now the right people to track GENERIC_CHART_AXES bugs... but let me know if I'm mistaken!

**Comment by michael-s-molina** [comment] 2023-01-31 21:52
@lilykuang I added you as one of the owners here 😉

**Comment by lilykuang** [comment] 2023-01-31 21:56
I tested with examples database with GENERIC_CHART_AXES and bar chart. I wasn't able to reproduce the issue. Did i miss any step?

![query_GENERIC_CHART_AXES](https://user-images.githubusercontent.com/5705598/215892414-03e919da-4452-46c5-bf0e-75ad8d6e8fb0.gif)

**Comment by sowo** [comment] 2023-02-01 17:26
Sorry, can't screen record. So here's what you get when using a dataset derived from Elasticsearch:
![image](https://user-images.githubusercontent.com/2765941/216116694-08c67a4b-a431-4789-9706-9af09d536191.png)

And here's the underlying query that produces the issue:

```
SELECT HISTOGRAM("DATE", INTERVAL 1 DAY) AS "DATE",
       count(*) AS count
FROM
  (select "DATE",
          "ITEM"
   from "table") AS virtual_table
GROUP BY "DATE"
ORDER BY count DESC
LIMIT 10000;
```

I think that Elastic gets confused by the column name "DATE" being used in the inner and outer queries.

**Comment by lilykuang** [comment] 2023-02-02 23:30
I am not sure how to reproduce the issue. I am using open distro elasticsearch database with GENERIC_CHART_AXES. @sowo not sure which step i missed
![odelasticsearch](https://user-images.githubusercontent.com/5705598/216473332-0b52f947-7797-4900-a169-d8adfceae3e5.gif)

**Comment by zhaoyongjie** [comment] 2023-02-03 07:14
> Sorry, can't screen record. So here's what you get when using a dataset derived from Elasticsearch: ![image](https://user-images.githubusercontent.com/2765941/216116694-08c67a4b-a431-4789-9706-9af09d536191.png)
> 
> And here's the underlying query that produces the issue:
> 
> ```
> SELECT HISTOGRAM("DATE", INTERVAL 1 DAY) AS "DATE",
>        count(*) AS count
> FROM
>   (select "DATE",
>           "ITEM"
>    from "table") AS virtual_table
> GROUP BY "DATE"
> ORDER BY count DESC
> LIMIT 10000;
> ```
> 
> I think that Elastic gets confused by the column name "DATE" being used in the inner and outer queries.

I guess that Elasticsearch confused keywords "DATE" so you can do a little change in the subquery that makes a alias for the "DATE" column, for instance:

```
select "DATE" as "data_column",
          "ITEM"
   from "table"
```

**Comment by sowo** [comment] 2023-02-03 08:51
> I am not sure how to reproduce the issue. I am using open distro elasticsearch database with GENERIC_CHART_AXES. @sowo not sure which step i missed ![odelasticsearch](https://user-images.githubusercontent.com/5705598/216473332-0b52f947-7797-4900-a169-d8adfceae3e5.gif) [ ![odelasticsearch](https://user-images.githubusercontent.com/5705598/216473332-0b52f947-7797-4900-a169-d8adfceae3e5.gif) ](https://user-images.githubusercontent.com/5705598/216473332-0b52f947-7797-4900-a169-d8adfceae3e5.gif) [ ](https://user-images.githubusercontent.com/5705598/216473332-0b52f947-7797-4900-a169-d8adfceae3e5.gif)

I think you need a virtual data set to reproduce the issue

**Comment by lilykuang** [comment] 2023-02-06 19:46
I was able to reproduce the same issue with GENERIC_CHART_AXES set to True or False. It maybe related to sql parsing. assigned to @betodealmeida to take a close look and removed the label for [flag:GENERIC_CHART_AXES](https://github.com/apache/superset/labels/flag%3AGENERIC_CHART_AXES)

**Comment by betodealmeida** [comment] 2023-02-06 20:16
The problem here is that this is invalid:

```sql
select "DATE" as "data_column",
          "ITEM"
   from "table"
```

It should be:

```sql
select "DATE" as `data_column`,
          "ITEM"
   from "table"
```

**Comment by betodealmeida** [comment] 2023-02-06 20:17
Let me push a fix to the ES driver.

**Comment by betodealmeida** [comment] 2023-02-06 21:18
Fix here: https://github.com/preset-io/elasticsearch-dbapi/pull/99

**Comment by michael-s-molina** [comment] 2023-02-08 20:47
Closing this given that @betodealmeida's fix was merged. Please feel free to reopen the issue if needed.

**Closed by michael-s-molina** 2023-02-08 20:47 UTC
Labels: #bug
