### ISSUE TITLE
Misleading zeros on a chart for missing data

### ISSUE THREAD

**Issue by GinkoValery** [apache/superset#25411] opened 2023-09-26 09:58 UTC
## Screenshot
![image](https://github.com/apache/superset/assets/113714043/aa859c01-47f1-40e7-9d9a-f8b93f5407e1)

## Description
When I build a **Bar_chart** with stacked series and I want to show values for each element of the bar I can see zeros for missing elements. There is no data for an element "b" in the second bar at the screen above, but I can see 0 which belongs to "b" and I can not see 7 for "a". Why is it so? How can I fix it?

And what can I do with the values which overlap each other (like at the third bar - 3 lies on top of 29).

**Comment by msghera** [comment] 2023-09-26 11:10
Have you tried the percentage threshold? 

The issue is well defined here ([https://github.com/apache/superset/issues/17281](https://github.com/apache/superset/issues/17281)).

**Comment by GinkoValery** [comment] 2023-09-29 12:21
@msghera, thank you for advice. As I understand percentage treshhold is implemented for bar chart and pie chart. But it is not implemented for a mixed chart containing a bar chart for one of the queries.

**Comment by rusackas** [comment] 2024-03-14 17:00
Looking at that thread, it seems a PR was merged to address this. Since it's been over five months since there's been a comment here, I'll assume all is well and close this out. Holler if this needs revisiting.

**Closed by rusackas** 2024-03-14 17:00 UTC
