### ISSUE TITLE
Charts in dashboards are subject to frequent errors with Chrome users

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#16742] opened 2021-09-20 06:51 UTC
Since Superset 1.x, all our Chrome users get recurrent errors on charts loading (in dashboards), forcing them to refresh the page

### Expected results

All the charts are displayed without errors.

### Actual results

The following error is (randomly ?) displayed : Unexpected error

When we click on "See More", here's the error we get : 

> \<html>
>\<head>\<title>502 Bad Gateway\</title>\</head>
> \<body>
> \<center>\<h1>502 Bad Gateway\</h1>\</center>
> \</body>
> \</html>
> \
> \
> \
> \
> \
> \

Important : 
* This can happen in one ore several charts.
* This usually disappears when refreshing the page once or twice
* This only happens in dashboards (we've never had this issue in "View chart in explore")
* This seems to concern only Chrome users (Firefox users did not complain about this)

#### Screenshots

What we can see in dashboards : 

![image](https://user-images.githubusercontent.com/79460908/133964682-578da6b7-859b-4d61-93fc-eff21d6a0fd2.png)

What we see in "See more" : 
![image](https://user-images.githubusercontent.com/79460908/133964881-01a3075a-1bf4-4079-ac99-85df6670c4b3.png)

#### How to reproduce the bug

1. Use Google Chrome
2. Open any dashboard

### Environment

superset version: 1.3.0
python version: 3.7.9
node.js version: doesn't apply, I run on Kubernetes, using gunicorn as server
source : Athena

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

/

**Comment by ShimiBaliti** [comment] 2021-11-02 20:01
@ValentinC-BR did you manage to solve this issue?

**Comment by ValentinC-BR** [comment] 2021-11-03 07:02
No.
I have no other choice than refreshing the page each time it occurs.

**Comment by nytai** [comment] 2021-11-10 18:20
@ValentinC-BR This error is being thrown by nginx or whichever proxy is in front of superset. 502 means the service(superset) is unavailable, either the superset server hash crashed (out of memory or cpu, etc.), or is too busy to serve your request. This is error is due to your deployment set up and there's nothing we can do on the superset application side, at least not without the log/stack trace for what actually caused the service to report as unavailable. 

Closing this issue as this is not actionable from an application perspective. If you do a root cause analysis that results in an issue with the superset application please feel free to reopen the ticket. For now I would suggest scaling up your superset deployment, either vertically or horizontally to see if that fixes it.

**Closed** 2021-11-10 19:33 UTC
Labels: #bug

**Comment by vivek-kandhvar** [comment] 2021-11-16 06:28
@ValentinC-BR Even we are seeing this issue with 1.3.0 very frequently. Just wanted check if you had not faced this issue prior 1.x. Can you confirm if you haven't changed anything before moving to 1.x?

**Comment by Pinimo** [comment] 2021-11-16 10:05
Hi @vivek-kandhvar ! Nice to see we're not alone :wink: On the whole, I can answer we did not change much configuration when moving to 1.x (1.1 and 1.2 in our case). But our config is constantly evolving so I cannot guarantee it with perfect certainty.

**Comment by mdeshmu** [comment] 2022-05-27 19:32
@ValentinC-BR @ShimiBaliti @vivek-kandhvar @Pinimo I was getting frequent 502 errors during loading of charts in my dashboard.

This is how traffic flows from my superset setup: AWS ALB --> Gunicorn --> Superset app
I am using official superset docker image.

I modified timeout settings i.e. GUNICORN_TIMEOUT and SUPERSET_WEBSERVER_TIMEOUT but it didn't resolve the problem.
I have already increased SERVER_WORKER_AMOUNT to 8 and using default thread value of 20 but it didn't resolve the issue.
My ECS task cpu/memory are underutilized so scaling is not a cause of the problem. 

Finally, I saw this blog which says solution is to keep Gunicorn --keep-alive more than alb idle timeout: https://www.tessian.com/blog/how-to-fix-http-502-errors/

Default value for --keep-alive is 2. Even Gunicorn's official documentation here https://docs.gunicorn.org/en/stable/settings.html#keepalive says:
"Generally set in the 1-5 seconds range for servers with direct connection to the client (e.g. when you don’t have separate load balancer). When gunicorn is deployed behind a load balancer, it often makes sense to set this to a higher value."

But run-server.sh in official docker image doesn't has an option for setting Gunicorn's --keep-alive to a custom value.
So I added this line in local copy of run-server.sh
	--keep-alive ${GUNICORN_KEEPALIVE:-65}
and created a custom image by overwriting run-server.sh file in official image. This finally solved my problem.

I hope this helps people with similar setup as mine.

**Comment by johnwillsey** [comment] 2024-07-11 21:27
Having this same issue in Safari.

**Comment by skannan-maf** [comment] 2024-10-04 07:24
I am in 3.1.0 and the issue still persists! This is marked as closed... but I wonder what is the fix?

**Comment by rusackas** [comment] 2024-10-04 20:47
> This error is being thrown by nginx or whichever proxy is in front of superset. 502 means the service(superset) is unavailable, either the superset server hash crashed (out of memory or cpu, etc.), or is too busy to serve your request. This is error is due to your deployment set up and there's nothing we can do on the superset application side, at least not without the log/stack trace for what actually caused the service to report as unavailable.

You're going to have to choose between (1) troubleshooting your server logs, (2) asking for assistance here (though the thread will remain closed) (3) asking for assistance in `#deploying-superset` on [slack](http://bit.ly/join-superset-slack), (4) avoiding all this by using a commercial/hosted Superset provider (I won't name names, but let me know if you need a recommendation).

**Comment by devysh1907** [comment] 2024-12-09 11:29
@rusackas ,
Please name some
