### ISSUE TITLE
After applying date range filter, dashboard not displaying data for selected date

### ISSUE THREAD

**Issue by mayur369** [apache/superset#25011] opened 2023-08-17 05:34 UTC
How to reproduce the bug

1. Go to 'Superset Dashboard'
2. Click on 'Filters'
3. apply the date range. ex - 2023-08-01 to 2023-08-05

### Expected results

what you expected to happen.
 it should display from 2023-08-01 to 2023-08-04
### Actual results

what actually happens.

it displays the data from 2023-08-02 to 2023-08-05
### Environment

(please complete the following information):

- browser type and version: Google Chrome
- superset version: `superset version` --> apache/superset:2.0.0    

![SupersetDashboard](https://github.com/apache/superset/assets/95526201/51fed552-47f5-4201-b821-a1be4f6eefb3)

**Comment by sfirke** [comment] 2023-08-17 15:34
What is the WHERE clause if you click View Query on that chart?

**Comment by ValentinC-BR** [comment] 2023-08-23 13:19
Same issue here.

The time filter didn't work on one chart (area chart) : all the data was displayed, even though the tooltip said there was a time filter : 
We dited the

**Comment by ValentinC-BR** [comment] 2023-08-23 13:21
Below was another area chart, based on a similar table (same structure), without any issue.

We updated the first chart by removing a filter, and now it works ...

At first, we thought that filtering (manually) on a date in the filter section (use case : remove data on a given time range) made the time filter break.

However, our second chart works with this configuration...
![image](https://github.com/apache/superset/assets/79460908/fbf0913d-82ad-481d-8ee9-94e8a1887840)

**Comment by PlutarcoII** [comment] 2023-09-08 19:25
Same issue here.

In dashboards or chart editing, time filter is not working properly. 

![Selección_261](https://github.com/apache/superset/assets/15706449/1165a233-f944-4004-8d2f-c923ed9df096)

Superset version: apache/superset:2.1.0

**Comment by sfirke** [comment] 2023-09-08 19:33
Some of this is sounding like a duplicate of https://github.com/apache/superset/issues/23773.  That should be fixed in 2.1.1 which just was released.  Are any of you able to upgrade and test this bug in that version?

**Comment by PlutarcoII** [comment] 2023-09-08 23:32
> Some of this is sounding like a duplicate of #23773. That should be fixed in 2.1.1 which just was released. Are any of you able to upgrade and test this bug in that version?

Hello sfirke

I have updated to apache-superset 2.1.1, But I have same issue.

![image](https://github.com/apache/superset/assets/15706449/9cc8a1ac-0b67-4512-8aa5-d237b2475bba)

**Comment by roshinis78** [comment] 2023-09-12 20:39
Observing the same issue [as @ValentinC-BR](https://github.com/apache/superset/issues/25011#issuecomment-1689952802). I'm on https://github.com/apache/superset/commit/e585db85b630c1b5c2f1b22933bb3e042d27ad15, which is about 2 weeks newer than https://github.com/apache/superset/commit/1f104a0c502047a8c60b0a52add5cbe3694e1d26 (2.1.1).

When I edit a chart in my dashboard that has a temporal column as a filter, the filter will break after the chart has been saved to the dashboard (i.e., it'll show _all_ available data, not just the data that's in the selected time range). This happens even if my edit didn't modify the chart's filters at all.

To temporarily fix any charts that have been broken like this, I have to edit the chart again, and manually set its temporal column filter to the same value that's currently set on the dashboard filter. Then, once the chart is saved to the dashboard, the chart's filter is once again synchronized with any changes to the dashboard filter.

**Comment by ValentinC-BR** [comment] 2023-09-13 06:10
I've been using the same workaround than @roshinis78 in the past few weeks.

However, this is a critical bug, as non-temporal charts (bar charts, geomap, pie charts, etc.) do not give any hint on the fact that they are not filtered on the right time range.

Most of our dashboard are affected. Is this a top issue on Superset / Preset side ?

**Comment by CzyerChen** [comment] 2023-11-13 03:49
I met the same problem, not only time range.

Version: 0.38.1

Problems：
1. set up "No filter" in chart, and import into a Dashboard, the default filter has been changed(like one time range filter at one moment cached by Superset forever). 
2. I can not choose the right point, I have to choose `No filter` then `real time range` manually.
<img width="902" alt="image" src="https://github.com/apache/superset/assets/22817918/02322537-2503-4b40-9ddd-6b3a362c1c46">

How to resolve:
1. edit `Dashboard` config
2. edit `JSON Metadata`, params from `"default_filters": "{\"11\": {\"__time_range\": \"2023-10-23T00:00:00 : 2023-10-25T00:00:00\"}}` to `"default_filters": "{\"11\": {\"__time_range\": \"No filter\"}}`
3. save config, then cached time range problem fixed.

**Comment by sfirke** [comment] 2023-11-13 20:26
Thanks @CzyerChen for sharing what worked for you.  Version 0.38.1 is very old, I would encourage anyone using that to try to carefully migrate to a newer version.

**Comment by rusackas** [comment] 2024-04-04 01:26
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and since it's been a while since this thread saw any activity, I'll close this as stale. If it is still an issue in Superset 3.x or newer, we can re-open this, but in this case it would probably be better to open a new issue with updated context. Thanks!

**Closed by rusackas** 2024-04-04 01:26 UTC
