### ISSUE TITLE
[explore][south tables] View sample will show 'no data' when user drop column and did not sync column in edit data set

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#17706] opened 2021-12-09 18:18 UTC
When user drop a column in datasource, View sample will show 'no data' if user did not sync column in edit dataset

#### How to reproduce the bug

Precondition:
User drop a column in the datasource and did not sync column in edit dataset in explore

1. Go to explore and query
2. Click on view sample
3. See error

### Expected results

There will be some warning msg to let user know to sync column in dataset

### Actual results

There is no warming msg or error msg and 'View sample' just return 'no data'

#### Screenshots

https://user-images.githubusercontent.com/81597121/145453150-107e5b66-2a8b-44e4-85b5-d5255d3c2325.mov

### Environment

(please complete the following information):

- browser type and version:
- superset version: latest master
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment] 2023-01-18 16:59
Assigning to @yousoph and @kgabryje in hopes that they can keep this on their radar. Looks like the fix PR was closed due to inactivity, and just fell between the couch cushions! Might be worth making sure this is still an issue in 2.0.x before going too deep on it, obviously!

**Comment by rusackas** [comment] 2023-01-26 16:07
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!

**Closed by rusackas** 2023-01-26 16:07 UTC
Labels: #bug, preset:QA
