### ISSUE TITLE
Apache Superset 1.2 installation error: itsdangerous<2.0,>=0.24' distribution was not found

### ISSUE THREAD

**Issue by bzmatteo72** [apache/superset#16197] opened 2021-08-11 14:47 UTC
Hello,
I'm trying to install from scratch of Apache Superset but I get this error which is stopping the installation:
ERROR: flask 1.1.4 has requirement itsdangerous<2.0,>=0.24, but you'll have itsdangerous 2.0.1 which is incompatible.
ERROR: flask-appbuilder 3.3.2 has requirement Flask-WTF<0.15.0,>=0.14.2, but you'll have flask-wtf 0.15.1 which is incompatible.

It looks that the Superset version has downloaded (pip install command) is 1.2.0 and the version of the itsdangerous installed is 2.0.1

Please could you help to resolve this issue?
I don't know how to go ahead and fix the problem.
Thanks
Matteo

### Environment

- superset version: `1.2.0`
- python version: `python 3.8`

**Comment by etr2460** [comment] 2021-09-03 23:10
closing as a duplicate of https://github.com/apache/superset/issues/15818

**Closed by etr2460** 2021-09-03 23:10 UTC
Labels: #bug
