### ISSUE TITLE
[sqllab]Database error Instance is not bound to a Session

### ISSUE THREAD

**Issue by beis0118** [apache/superset#16311] opened 2021-08-18 03:41 UTC
When i use the sqllab to query my data from databases(such as mysql and clickhouse) , the bug below happened.
Database error Instance <Query at 0x1b8f2ec1e50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/13/bhk3)

### Expected results

Get the right data from my databases.

### Actual results

Database error Instance <Query at 0x1b8f2ec1e50> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: http://sqlalche.me/e/13/bhk3).

#### Screenshots

![image](https://user-images.githubusercontent.com/59128541/129832948-8d915fad-10a2-4e7d-8fb0-c4432bac2f16.png)
![image](https://user-images.githubusercontent.com/59128541/129833035-b645d8d0-cbf5-4657-baca-f341cb403f68.png)

#### How to resolve the bug

1. Go to 'superset/views/core'
2. Find th method '_sql_json_sync'
3. annotation two line:
`            
payload = json.dumps(
                apply_display_max_row_limit(data),
                default=utils.pessimistic_json_iso_dttm_ser,
                ignore_nan=True,
                encoding=None,
            )
`
with
`            
payload = json.dumps(
                apply_display_max_row_limit(data),
                default=utils.pessimistic_json_iso_dttm_ser,
                #ignore_nan=True,
                #encoding=None,
            )
`

**Comment by junlincc** [comment] 2021-08-18 04:47
could you provide 1) version of superset, 2)which db exactly that causes this error,3) are you able to reproduce this by using one of our sample datasets?

**Comment by beis0118** [comment] 2021-08-18 05:15
> could you provide 1) version of superset, 2)which db exactly that causes this error,3) are you able to reproduce this by using one of our sample datasets?
> 
> @betodealmeida 🙏 looping in our data expert

Here: 
1. Superset version: 1.2.0 (clone from the master branch)
2. ClickHouse and Mysql data from examples.
3. Do you mean this?
![image](https://user-images.githubusercontent.com/59128541/129841022-fed34a0b-a2ee-4ccd-99fc-2c357a7fa654.png)
It looks good.

**Comment by rusackas** [comment] 2023-05-24 03:11
@beis0118 is this something you found a solution or workaround for? Hoping this is not happening anymore, but I don't want to close this one prematurely just because it's old.

**Comment by rusackas** [comment] 2024-03-04 04:06
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

**Closed by rusackas** 2024-03-04 04:06 UTC
Labels: sqllab, need:more-info, #bug
