### ISSUE TITLE
Unable to save report due to Add button not enable

### ISSUE THREAD

**Issue by badf007** [apache/superset#28149] opened 2024-04-19 18:47 UTC
### Bug description

While filling in all the required information there is still an error in the **Notification method** section where it shows that a recipient is missing even when valid emails are provided.

### How to reproduce the bug

1. Go to alerts and reports.
2. Go to the report section
3. Click Add report
4. Fill all required fields.

What should happen:
- The ADD button is enabled and the report can be saved

What is happening:
- The ADD button is not enabled and a red asterisk is shown in the EMAIL RECIPIENTS field.

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/18302510/0a8053aa-75d9-41d4-bf70-f7614b55db44)

![image](https://github.com/apache/superset/assets/18302510/a5974b9e-c94f-4c4a-9bbd-6f85c5f798ea)

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by cmartinezdnn** [comment] 2024-04-26 07:33
Same issue happening to me. It looks like there is bug in new superset 4.0 version.

**Comment by sfirke** [comment] 2024-05-08 13:43
Someone in Slack is seeing this too.  I am running 4.0.0 in production and can successfully create a new alert, so this is not universally broken.  My best guess is that there's something in the recipients validation checker that succeeds on my instance but fails for these people without telling them why.  CC @fisjac as I believe they wrote some of this new validation.

**Comment by alexkyurtev** [comment] 2024-05-08 13:45
please contact me if further information is needed , i`m also seeing this bug on my side

**Comment by fisjac** [comment] 2024-05-08 13:54
Looking into this.

**Comment by square-li** [comment] 2024-05-13 15:41
+1 also having this issue with 4.0. Thanks!

**Comment by rusackas** [comment] 2024-05-13 21:15
4.0.1 has been voted in... so this could become part of 4.0.2, coming soon. If you want to test/vote on these release candidates officially, please do join the dev@superset.apache.org email list (let me know if you want instructions). 

Normally we close issues with the PR that fixes them is merged to `master`. If that's the case here, we should close this, and the fix will be destined for the next release. Any objections?

**Comment by adimyth** [comment] 2024-05-16 14:11
@rusackas I checked the `release-announcements` channel & other relevant channels on slack, but couldn't find a tentative timeline for `4.0.2` release

Any idea when would it be released? 

PS - @fisjac thanks for fixing this 👍

**Comment by michael-s-molina** [comment] 2024-05-16 14:16
Hi @adimyth. We generally try to release a patch every month. We just released 4.0.1 on Monday so 4.0.2 will probably be released mid June. @eschutho @sadpandajoe are working on 4.1 but I don't know if it will be released sooner.

**Comment by sfirke** [comment] 2024-06-18 14:23
Alright folks watching this issue: Superset 4.0.2 is up for a vote!  Anyone is welcome to test out the release and vote on it.  Test it by deploying the docker image: [apache/superset/4.0.2rc1](https://hub.docker.com/layers/apache/superset/4.0.2rc1/images/sha256-c1dbdce290c7a41e4bb41c6d3f88c721eb684cf23bb99ff9e838ce3b3911700e?context=explore) or `apache/superset/4.0.2rc1-dev`.

Vote by subscribing to the public email list https://lists.apache.org/list.html?dev@superset.apache.org and replying to the email Michael sent this morning!  Please test that this bug is fixed and that everything else works as it should.  I am going to copy-paste this message onto a couple of other issues for visibility, sorry to folks who get multiple messages.

**Comment by giacomochiarella** [comment] 2024-06-26 07:30
Hi everyone! 4.0.2 is under voting. I went through the changelog [here](https://github.com/apache/superset/blob/4.0.2rc1/CHANGELOG/4.0.2.md) and I cannot see any reference to [this](https://github.com/apache/superset/issues/28712) or [this](https://github.com/apache/superset/pull/28409). Moreover this is still open. Anybody can give some clearance on this bug? I would down vote if this is not resolved actually (it is a regression, it was working in 4.0.0 and stopped in 4.0.1)

**Comment by michael-s-molina** [comment] 2024-06-26 11:23
Fixed by https://github.com/apache/superset/pull/28409

**Closed by michael-s-molina** 2024-06-26 11:23 UTC
