### ISSUE TITLE
Documentation - The Superset Documentation Pages are not Scrolling Vertically to the end of the page

### ISSUE THREAD

**Issue by virtualarchitectures** [apache/superset#18875] opened 2022-02-23 12:54 UTC
#### How to reproduce the bug

1. Go to https://superset.apache.org/docs/api
2. Scroll down the page.
3. You will see that the page will not scroll to the end. This applies to multiple pages in the documentation.

Pressing PgDown on keyboard or using documentation sidebar navigation also fails.

### Expected results

The user should be able to scroll through the full page of documentation to the end.

### Actual results

The screen won't scroll vertically below the text that was visible when the page loaded. The visible screen bounces back up to the beginning of the document.  

#### Screenshots

This is as far as the page scrolls.
![image](https://user-images.githubusercontent.com/10799911/155323085-47814de8-e40f-41fe-a965-ccd4c8a1a305.png)

### Environment

This has been tested in Chrome and Firefox on Windows 10.

**Comment by villebro** [comment] 2022-02-23 14:15
Duplicate of #18868, closing

**Closed by villebro** 2022-02-23 14:15 UTC
Labels: #bug
