### ISSUE TITLE
Cursor falling behind in SQL Lab

### ISSUE THREAD

**Issue by mapshen** [apache/superset#15749] opened 2021-07-16 20:36 UTC
When I type a SQL query in SQL Lab, the cursor doesn't align with where I'm actually typing. This can be reproduced in Chrome, Firefox and Edge.

I suspect this is related to the following issues and MRs:

- https://github.com/apache/superset/issues/9095
- https://github.com/apache/superset/pull/9183
- https://github.com/apache/superset/issues/9253
- https://github.com/apache/superset/pull/9264

Since I can apply this [fix](https://github.com/apache/superset/pull/9183#issuecomment-624204443) manually in the browser to get it working. 

### Expected results

The cursor can roughly lines up.

### Actual results

It doesn't.

#### How to reproduce the bug

1. Go to 'SQL Lab'
2. Type in your query

### Environment

`docker pull apache/superset:1.2.0`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rubenssoto** [comment] 2021-07-17 06:11
Hello,

is it your problem?
![image (12)](https://user-images.githubusercontent.com/36298331/126027718-051dd3fb-f4ea-4e1f-b475-3ea1bce4ba66.png)

some users are reporting that the cursor is over the letter

**Comment by mapshen** [comment] 2021-07-17 13:13
@rubenssoto Yes! Perhaps I should have included a screenshot but it is what you show in the screenshot and same as what was described in the issues I mentioned above.

**Comment by rumbin** [comment] 2021-07-20 21:35
We are encountering the same issue on version 1.0.1 (iirc, writing from a mobile right now).
The cursor offset can be so pronounced that it is a whole letter off to the left. This renders editing, copy pasting really tricky.
Refreshing the page (F5) temporarily remedies the situation. However, I haven't been successful with reproducibly triggering the issue again, so far.

**Comment by rubenssoto** [comment] 2021-07-21 21:41
Hi Guys,

Do you know anyone who can help us?

Thank you

**Comment by junlincc** [comment] 2021-07-23 00:16
https://github.com/apache/superset/pull/15820 

please check out lasted master. lmk thanks!

**Comment by mapshen** [comment] 2021-07-23 15:30
This is still happening when running the latest, which is based off of `9c854ff1f1ab80b26438a3b6d91ca9b44b5f2a7a`.

I think the root cause is similar to this: https://github.com/apache/superset/pull/9183#issuecomment-624204443. There are two `.ace_editor` classes applied to the editor. Disabling the `font-family` attribute in one and having the `font` attribute in another applied seem to be able to get the cursor properly aligned.

**Comment by rusackas** [comment] 2021-07-26 23:18
@mapshen A handful of us are unable to reproduce this issue, at least in Chrome/Safari/Firefox on Mac. Is everyone seeing the issue here using a PC? Our same group doesn't currently have a PC to test, if this is the case. @mapshen do you think you could troubleshoot a bit more and open a PR? I'd be happy to test it on all the mac browsers, if you're able to fix it for the PC browser(s) having a problem.

**Comment by rumbin** [comment] 2021-07-27 05:21
PC, Win 10 in our case

**Comment by mapshen** [comment] 2021-07-28 22:13
@rusackas I couldn't reproduce either on my own PC. It might be due to some policies enforced on our browsers in the corporate environment. We are trying to see if we can pinpoint it. Please let us know too if you have any leads on what policy might have caused this.

**Comment by zrait** [comment] 2021-07-29 01:31
I'm seeing this on Chrome PC using version 1.2 from PyPI

**Comment by mapshen** [comment] 2021-07-29 20:18
@rusackas We dug deep into this issue and it seems to be caused by the font "Lucida Consol" added https://github.com/apache/superset/pull/12423 as per https://github.com/apache/superset/pull/12423#discussion_r556716051.

We tried both Menlo (default on Mac) and Lucida Consol (manually installed), they work fine. However, on Win 10, Menlo is not available by default and Lucida Consol will be picked in sequence, which throws everything off. I am not clear why this is the case (not a frontend developer by trade :)), but removing Lucida Consol worked.

Can we remove "Lucida Consol"? Or even better, have we considered prepackage all the fonts needed into the docker image?

**Comment by rusackas** [comment] 2021-07-30 20:17
Thoughts @betodealmeida ?

In a perfect world, I'd love to use the font from the Superset Theme here (`theme.typography.families.monospace`) which would be `'Fira Code', 'Courier New', monospace`. But I'm hesitant to rock the boat on this thing! 😬

**Comment by mapshen** [comment] 2021-08-03 14:28
@rusackas @betodealmeida What would be the path forward? Can we remove "Lucida Consol"? This basically renders the SQL Lab useless, so your help would be greatly appreciated. Thanks!

**Comment by Dieken** [comment] 2021-09-12 10:10
```
perl -i.bak -pe "s/'Monaco\\\\'/'MonacoXXX\\\\'/g" ~/superset/assets/dist/vendors-major.facef8359e4e34d9cc58.chunk.js
```

This helps me, you may need clear your local browser cache first.

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/2365/132983616-3934abb3-e36b-4569-8ab2-f9ded2d7b78b.png">

**Comment by junlincc** [comment] 2021-09-17 22:03
@mapshen https://github.com/apache/superset/pull/16536 should have fixed the issue, can you double check and confirm? closing issue for now

**Closed by junlincc** 2021-09-17 22:03 UTC
Labels: #bug, v1.2

**Comment by mapshen** [comment] 2021-09-27 21:38
@junlincc Sorry for the late reply and appreciate your help on trying to fix this issue so far.

Unfortunately, in my test just now with the latest image `apache/superset:fcab489860399d38bc3a66fd26dd62b7c3e3ffd5`, the issue still persists.

**Comment by ziggekatten** [comment] 2021-11-09 08:13
This is driving me nuts....is there a way to work around this problem?

**Comment by PApostol** [comment] 2021-11-09 12:44
I'm having the same issue on version 1.3.0

**Comment by thomas-ca-pro** [comment] 2021-11-09 13:46
I think that as long as `menlo` appears first in the list of fonts used by ace-editor, I'll have this issue on credge.
I think that the incriminated line is [here](https://github.com/apache/superset/blob/5948a9fd0246b9d67fd2074a613f081e53a19670/superset-frontend/src/SqlLab/main.less#L373)

**Comment by nicovak** [comment] 2021-12-14 07:01
I still have the issue with Chrome + Windows 11

## With `font-family`
![Capture d’écran 2021-12-14 105852](https://user-images.githubusercontent.com/6214452/145948734-16c5229f-e2f2-410a-9fb7-b41f2991f18e.jpg)
![Capture d’écran 2021-12-14 105903](https://user-images.githubusercontent.com/6214452/145948736-46c53628-5aa9-454e-8dbc-90697d7e126f.jpg)

## Without `font-family`
![Capture d’écran 2021-12-14 105917](https://user-images.githubusercontent.com/6214452/145948741-8648c262-c367-4513-b08c-da914a64fd6e.jpg)
![Capture d’écran 2021-12-14 105925](https://user-images.githubusercontent.com/6214452/145948743-fddbdb61-d896-4088-8c51-07345a50988f.jpg)

**Comment by Naich** [comment] 2022-07-05 03:50
> This is still happening when running the latest, which is based off of `9c854ff1f1ab80b26438a3b6d91ca9b44b5f2a7a`.
> 
> I think the root cause is similar to this: [#9183 (comment)](https://github.com/apache/superset/pull/9183#issuecomment-624204443). There are two `.ace_editor` classes applied to the SQL editor. Disabling the `font-family` attribute in one and having the `font` attribute in another applied seem to be able to get the cursor properly aligned.
> 
> ![image](https://user-images.githubusercontent.com/7225879/126805832-99ec8e26-9108-4b6b-9de6-bdba4941d54d.png)
> 
> Before: ![image](https://user-images.githubusercontent.com/7225879/126805958-30d742f0-ee0a-402d-957f-dbec15dfab53.png)
> 
> After: ![image](https://user-images.githubusercontent.com/7225879/126806084-21193a5d-3805-4760-8c70-e14a9f1ec9f3.png)

Chrome 102.0.5005.63 + superset 1.5.1 same issue here, and disabling the first font-family css could solve it.
