### ISSUE TITLE
Connect to Clickhouse Error

### ISSUE THREAD

**Issue by Jcccxxx** [apache/superset#23065] opened 2023-02-13 04:02 UTC
#### How to reproduce the bug

1. Go to 'Database Connections'
2. Click on 'Add Database'
3. Click on 'TEST CONNECTION'

### Expected results

connection is successful

### Actual results

error

#### Screenshots

![screenshot-20230213-115933](https://user-images.githubusercontent.com/115602404/218367412-2ac0acd5-f098-40fd-8636-ed98587ea10b.png)

Does anyone know how to solve it?

Thanks!

**Comment by villebro** [comment] 2023-02-14 11:55
@Jcccxxx thanks for reporting. On which version of Superset is this happening? I'm currently working on improving compatibility of the ClickHouse spec, so if this is happening on master branch this should be fixed shortly.

**Comment by Jcccxxx** [comment] 2023-02-14 13:35
> @Jcccxxx thanks for reporting. On which version of Superset is this happening? I'm currently working on improving compatibility of the ClickHouse spec, so if this is happening on master branch this should be fixed shortly.

it display Version: 0.0.0.dev0.
i just used superset for a week, so maybe it's the latest version?
thanks

**Comment by villebro** [comment] 2023-02-14 15:03
How did you install it? Did you clone the repo?

**Comment by Jcccxxx** [comment] 2023-02-14 15:31
> How did you install it? Did you clone the repo?

I clone from git, and use 'docker-compose -f docker-compose-non-dev.yml up' to start

**Comment by villebro** [comment] 2023-02-14 16:01
Did you also add the ClickHouse connect driver?

**Comment by Jcccxxx** [comment] 2023-02-15 00:22
> Did you also add the ClickHouse connect driver?

yes, the version of clickhouse connect is 0.5.7

**Comment by genzgd** [comment] 2023-02-16 04:13
What port did you use in your SQLAlchemy URI?  ClickHouse Connect uses the ClickHouse HTTP interface, so if you are using the SQLAlchemy URL the port should normally be 8123 (for plain HTTP) or 8443 (for HTTPS).  I can reproduce your exact error if I use the wrong (native interface) port of 9440:

```
clickhousedb://play:clickhouse@play.clickhouse.com:9440
```
causes the "connection reset by peer error

```
clickhousedb://play:clickhouse@play.clickhouse.com:443
```

works correctly (play.clickhouse.com uses the standard HTTP port of 443 instead of 8443).

Please try the HTTP (8123) or HTTPS (8443) port on your server.

**Comment by javiermas** [comment] 2023-05-22 10:59
Same issue:
ERROR: (builtins.NoneType) None
[SQL: Error HTTPSConnectionPool(host='chi-chi-data-warehouse-0-0.clickhouse-operator.svc', port=8123): Max retries exceeded with url: /?wait_end_of_query=1 (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)'))) executing HTTP request https://chi-chi-data-warehouse-0-0.clickhouse-operator.svc:8123]
(Background on this error at: https://sqlalche.me/e/14/dbapi)

I tried with port 9000, 8123, 8443 and no luck. I can connect to the CH db normally on the port 9000, but no luck with superset @genzgd.

**Comment by javiermas** [comment] 2023-05-22 11:18
I ended up using clickhouse-driver and clickhouse-sqlalchemy instead of clickhouse-connector, like it was suggested in another issue (I believe by genzgd) and it seems to work fine (k8s-helm installation).

**Comment by genzgd** [comment] 2023-05-22 13:31
@javiermas That SSL error is associated with older versions of Python.  What Python version are you running?

**Comment by genzgd** [comment] 2023-06-06 12:11
@xRomZak The superset engine spec was removed from clickhouse-connect to make it consistent with all other Superset connectors.  clickhouse-connect now uses the ClickHouse engine spec in the main superset project that @villebro ported there a couple of months ago.  It still works very well with Superset.

**Comment by xRomZak** [comment] 2023-06-06 12:58
I recently reported clickhouse connectivity issue due to invalid/outdated connector here.
https://github.com/amancevice/docker-superset/issues/255

As fas as I understand to fix it I have to build a container myself incl. a proper driver?

**Comment by genzgd** [comment] 2023-06-06 14:10
You should be able to include it in the `superset/docker/requirements-local.txt` if you following the instructions for running Superset in docker compose locally (https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/).  

Use the the following in `requirements-local.txt` or as a pip install on your own container.

For using clickhouse-connect:

```
clickhouse-connect>=0.6.1
```

For using clickhouse-driver, I think you need:
```
clickhouse-driver>=0.2.6
clickhouse-sqlalchemy>=0.2.4
```

**Comment by rusackas** [comment] 2024-02-29 22:14
This is likely fixed by now, and is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue or a PR to address the problem.

**Closed by rusackas** 2024-02-29 22:14 UTC
Labels: data:connect:clickhouse, #bug
