### ISSUE TITLE
Double click on a chart legend category does not work properly in 2.1.0

### ISSUE THREAD

**Issue by josepfranquetf** [apache/superset#24039] opened 2023-05-12 09:43 UTC
In previous versions of Superset, whenever we double-clicked on a category in a chart with dimensions, it would become the only active category in the chart. However, in version 2.1.0, it doesn't seem to work as expected. Double-clicking on a category now has the same behavior as a single click, which deactivates the category from the chart.

#### How to reproduce the bug

1. Go to a Time-series chart (for example) with a dimension - see screenshot below as an example
2. Double Click on one of the categories found on the legend of the chart

### Expected results

As it happened in latest versions, it would be expected that the only category which would appear in the chart is the double clicked one. 

### Actual results

It's currently working as if it were a single click, by deactivating the double clicked category from the chart. 

#### Screenshots

![image](https://github.com/apache/superset/assets/102971028/160857b5-d7de-488d-9344-861110c4f1ed)

### Environment

- browser type and version: `Google Chrome v113.0.5672.93 `
- superset version: `2.1.0`
- python version: `3.8.10`
- node.js version: `Not installed`
- any feature flags active: Yes, the following ones -> `THUMBNAILS, LISTVIEWS_DEFAULT_CARD_VIEW, DASHBOARD_NATIVE_FILTERS, VERSIONED_EXPORT, ALERT_REPORTS, OMNIBAR, DASHBOARD_RBAC, THUMBNAILS_SQLA_LISTENERS, EMAIL_REPORTS_CRON_RESOLUTION, ENABLE_TEMPLATE_PROCESSING, CUSTOM_TEMPLATE_PROCESSORS`

### Checklist

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment] 2023-05-12 12:34
Looks like a duplicate of https://github.com/apache/superset/issues/23735 ?

**Comment by rusackas** [comment] 2023-05-18 16:08
The double click was a fairly obscure (at least in terms of discoverability) feature of the legacy/deprecated NVD3 line charts. ECharts does not support that, exactly. There are legend buttons for "all" and "inverse" that were merged recently which address this, but I don't _think_ those have been released in 2.1.0. They'll likely be in 3.0, coming soonish :)

**Closed by rusackas** 2023-05-18 16:08 UTC
Labels: #bug

**Comment by rusackas** [comment] 2023-05-18 16:17
I added a bit more context on the liked thread (thanks, @sfirke).
