### ISSUE TITLE
After forced refresh, other chart values cannot be displayed

### ISSUE THREAD

**Issue by jianxia84** [apache/superset#15735] opened 2021-07-16 09:21 UTC
After forced refresh, other chart values cannot be displayed

### Expected results

After forced refresh, all chart values are displayed normally

### Actual results

After forced refresh, the value of the current chart can be displayed, while other charts (values that have been displayed before) cannot be displayed

#### Screenshots

show second chart tooltip value
![image](https://user-images.githubusercontent.com/28744116/125922916-b015622c-559d-4020-b395-ccfdbf19eb74.png)

force refresh first chart 
![image](https://user-images.githubusercontent.com/28744116/125922982-f47abb7e-6dd3-47cf-8304-00d6691ffd7e.png)

can not show second chart tooltip value
![image](https://user-images.githubusercontent.com/28744116/125924598-9bfbec7d-b1c7-4f53-b815-707fcd879e43.png)

#### How to reproduce the bug

1. Go to dashborad

2. Hover the mouse over the second chart to display the value

3. Force refresh the first chart

4. The mouse hovers over the second chart, unable to display the value

### Environment

(please complete the following information):

- superset version: 1.2.0
- python version: 3.6.8
- node.js version: 12.18.3

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ * ] I have reproduced the issue with at least the latest released version of superset.
- [ * ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment] 2023-01-05 22:51
I'm happy to say I'm unable to reproduce this issue in the current `master` of Superset. Closing this as resolved.

**Closed by rusackas** 2023-01-05 22:51 UTC
Labels: validation:required, viz:charts:bar
