### ISSUE TITLE
Notification When Alerts or Reports fails

### ISSUE THREAD

**Issue by TheRealYoze** [apache/superset#24096] opened 2023-05-17 12:39 UTC
### Discussed in https://github.com/apache/superset/discussions/24077

<div type='discussions-op-text'>

<sup>Originally posted by **TheRealYoze** May 16, 2023</sup>
Here is the problem:
Sometimes, an alert or a report generation fails (see picture):
![image](https://github.com/apache/superset/assets/55165964/1486b9f9-40e7-4915-934e-204647179fbb)

I would like to get alerted whenever an error has occurred.
Is there a way to do that?

Thanks in advance!</div>

**Comment by rusackas** [comment] 2023-05-17 23:35
Thanks for opening the Discussion thread. That's the right place to have a feature discussion like this. I hope others are willing to take it up! I've moved it to the Ideas section, and will close this issue since it's not a bug. I think there _might_ be another discussion on the same topic as well, it'd be worth digging around a bit for that to consolidate things.

**Closed by rusackas** 2023-05-17 23:35 UTC
