### ISSUE TITLE
Superset deploy cache via Redis on Ubuntu 18.04 Error

### ISSUE THREAD

**Issue by vndroid** [apache/superset#25607] opened 2023-10-11 09:31 UTC
Simple

```
AttributeError: 'RedisCache' object has no attribute '_client'
```

#### How to reproduce the bug

According to Official Docs [Caching](https://superset.apache.org/docs/installation/cache), I add the follow config to my `superset_config.py`

```
FILTER_STATE_CACHE_CONFIG = {
    'CACHE_TYPE': 'RedisCache',
    'CACHE_DEFAULT_TIMEOUT': 86400,
    'CACHE_KEY_PREFIX': 'superset_filter_cache',
    'CACHE_REDIS_URL': 'redis://127.0.0.1:6379/0'
}
DATA_CACHE_CONFIG = CACHE_CONFIG
```

Then start the service

```bash
source /data/superset/venv/bin/activate
export SUPERSET_CONFIG_PATH=/data/superset/superset_config.py
export FLASK_APP=superset
gunicorn -w 10 -k gevent --worker-connections 1000 --timeout 120 -b 0.0.0.0:6666 --limit-request-line 0 --limit-request-field_size 0 "superset.app:create_app()"
```

and you can see the error log.

```
AttributeError: 'RedisCache' object has no attribute '_client'
```

Remove these configs from the superset_config.py, It can be run normally.

### Expected results

It can be run.

### Actual results

Can not be run.

#### Screenshots

<img width="1319" alt="Snipaste_2023-10-11_17-22-43" src="https://github.com/apache/superset/assets/15273693/4654f47d-0757-4d68-a051-7769430cb80e">

### Environment

(please complete the following information):

- browser type and version: null
- superset version: 3.0.0.
- python version: 3.9.18
- node.js version: null
- any feature flags active: null

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Redis use Docker container:

```bash
(venv) hadoop@hadoop:/data/superset$ docker container ls
CONTAINER ID   IMAGE                           COMMAND                  CREATED        STATUS                  PORTS                                                     NAMES
d86a82ded5bf   redis:7.0-alpine3.18            "docker-entrypoint.s…"   2 days ago     Up 2 days               0.0.0.0:6379->6379/tcp                                    redis
```

By another way, I found a problem.

https://github.com/rq/django-rq/issues/143

I try to install `django-redis-cache`, useless!

and it show me the follow info

```
Successfully built django-redis-cache
Installing collected packages: redis, django-redis-cache
  Attempting uninstall: redis
    Found existing installation: redis 4.6.0
    Uninstalling redis-4.6.0:
      Successfully uninstalled redis-4.6.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
apache-superset 3.0.0 requires redis<5.0,>=4.5.4, but you have redis 3.5.3 which is incompatible.
```

So reinstall the redis 4.6.0, it show me:

```
Installing collected packages: redis
  Attempting uninstall: redis
    Found existing installation: redis 3.5.3
    Uninstalling redis-3.5.3:
      Successfully uninstalled redis-3.5.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
django-redis-cache 3.0.1 requires redis<4.0, but you have redis 4.6.0 which is incompatible.
Successfully installed redis-4.6.0
```

Please advise if there is something wrong with my operation.

PS:  Flask-Caching already installed!

```
pip3 install Flask-Caching
Requirement already satisfied: Flask-Caching in ./venv/lib/python3.9/site-packages (1.11.1)
Requirement already satisfied: cachelib in ./venv/lib/python3.9/site-packages (from Flask-Caching) (0.10.2)
Requirement already satisfied: Flask in ./venv/lib/python3.9/site-packages (from Flask-Caching) (2.3.3)
Requirement already satisfied: Werkzeug>=2.3.7 in ./venv/lib/python3.9/site-packages (from Flask->Flask-Caching) (2.3.7)
Requirement already satisfied: Jinja2>=3.1.2 in ./venv/lib/python3.9/site-packages (from Flask->Flask-Caching) (3.1.2)
Requirement already satisfied: itsdangerous>=2.1.2 in ./venv/lib/python3.9/site-packages (from Flask->Flask-Caching) (2.1.2)
Requirement already satisfied: click>=8.1.3 in ./venv/lib/python3.9/site-packages (from Flask->Flask-Caching) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in ./venv/lib/python3.9/site-packages (from Flask->Flask-Caching) (1.6.3)
Requirement already satisfied: importlib-metadata>=3.6.0 in ./venv/lib/python3.9/site-packages (from Flask->Flask-Caching) (6.8.0)
Requirement already satisfied: zipp>=0.5 in ./venv/lib/python3.9/site-packages (from importlib-metadata>=3.6.0->Flask->Flask-Caching) (3.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.9/site-packages (from Jinja2>=3.1.2->Flask->Flask-Caching) (2.1.3)
```

**Comment by mdeshmu** [comment] 2023-10-12 02:05
please attach your `pip freeze` output

**Comment by vndroid** [comment] 2023-10-12 02:15
> pip freeze

```
alembic==1.12.0
amqp==5.1.1
apache-superset==3.0.0
apispec==6.3.0
async-timeout==4.0.3
attrs==23.1.0
Babel==2.13.0
backoff==2.2.1
bcrypt==4.0.1
billiard==4.1.0
blinker==1.6.3
Brotli==1.1.0
cachelib==0.10.2
celery==5.3.4
certifi==2023.7.22
cffi==1.16.0
click==8.1.7
click-didyoumean==0.3.0
click-option-group==0.5.6
click-plugins==1.1.1
click-repl==0.3.0
colorama==0.4.6
convertdate==2.4.0
cron-descriptor==1.4.0
croniter==1.4.1
cryptography==39.0.2
Deprecated==1.2.14
deprecation==2.1.0
dnspython==2.4.2
email-validator==1.3.1
exceptiongroup==1.1.3
Flask==2.3.3
Flask-AppBuilder==4.3.7
Flask-Babel==2.0.0
Flask-Caching==1.11.1
Flask-Compress==1.14
Flask-JWT-Extended==4.5.3
Flask-Limiter==3.5.0
Flask-Login==0.6.2
Flask-Migrate==3.1.0
Flask-SQLAlchemy==2.5.1
flask-talisman==1.1.0
Flask-WTF==1.2.1
func-timeout==4.3.5
geographiclib==2.0
geopy==2.4.0
gevent==23.9.1
greenlet==3.0.0
gunicorn==21.2.0
h11==0.14.0
hashids==1.3.1
hijri-converter==2.3.1
holidays==0.23
humanize==4.8.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.1.0
isodate==0.6.1
itsdangerous==2.1.2
Jinja2==3.1.2
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
kombu==5.3.2
korean-lunar-calendar==0.3.1
limits==3.6.0
Mako==1.2.4
Markdown==3.5
markdown-it-py==3.0.0
MarkupSafe==2.1.3
marshmallow==3.20.1
marshmallow-sqlalchemy==0.26.1
mdurl==0.1.2
msgpack==1.0.7
mysqlclient==2.2.0
nh3==0.2.14
numpy==1.23.5
ordered-set==4.1.0
outcome==1.2.0
packaging==23.2
pandas==1.5.3
paramiko==3.3.1
parsedatetime==2.6
pgsanity==0.2.9
Pillow==10.0.1
polyline==2.0.1
prison==0.2.1
prompt-toolkit==3.0.39
pyarrow==12.0.1
pycparser==2.21
Pygments==2.16.1
PyJWT==2.8.0
PyMeeus==0.5.12
PyNaCl==1.5.0
pyparsing==3.1.1
PySocks==1.7.1
python-dateutil==2.8.2
python-dotenv==1.0.0
python-geohash==0.8.5
pytz==2023.3.post1
PyYAML==6.0.1
redis==4.6.0
referencing==0.30.2
rich==13.6.0
rpds-py==0.10.4
selenium==4.9.1
shortid==0.1.2
simplejson==3.19.2
six==1.16.0
slack-sdk==3.23.0
sniffio==1.3.0
sortedcontainers==2.4.0
SQLAlchemy==1.4.49
SQLAlchemy-Utils==0.38.3
sqlparse==0.4.4
sshtunnel==0.4.0
tabulate==0.8.10
trio==0.22.2
trio-websocket==0.11.1
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.0.6
vine==5.0.0
wcwidth==0.2.8
Werkzeug==2.3.7
wrapt==1.15.0
wsproto==1.2.0
WTForms==3.0.1
WTForms-JSON==0.3.5
XlsxWriter==3.0.9
zipp==3.17.0
zope.event==5.0
zope.interface==6.1
```

**Comment by mliu2718** [comment] 2023-10-15 06:36
I got the same error.

**Comment by mliu2718** [comment] 2023-10-16 22:20
Root cause is in flask-caching, https://github.com/pallets-eco/flask-caching/issues/381
`pip install cachelib==0.8.0` solve this issue.

**Comment by vndroid** [comment] 2023-10-18 01:02
> cachelib

Okey, I will try it. Thanks a lot!

**Comment by bipinct** [comment] 2023-11-06 05:44
> Root cause is in flask-caching, [pallets-eco/flask-caching#381](https://github.com/pallets-eco/flask-caching/issues/381) `pip install cachelib==0.8.0` solve this issue.

Thanks you saved me

**Comment by rusackas** [comment] 2024-04-04 01:40
We're on cachelib 0.9.0, now, and this thread has been silent for a while, so I assume the solution above worked for everyone. Thanks for that! Closing :)

**Closed by rusackas** 2024-04-04 01:40 UTC
