### ISSUE TITLE
Predictive analytics not working out of the box when using docker.

### ISSUE THREAD

**Issue by maudrid** [apache/superset#24357] opened 2023-06-12 13:27 UTC
When deploying Superset using the official docker image, the predictive analytics functionality does not work.
This is due to missing dependencies.
#### How to reproduce the bug

1. Run Supserset using docker and the `apache/superset:2.1.0` image.
2. Create any Timeseries chart and check the  "ENABLE FORECAST' box under 'Predictive analytics'.
3. Update the chart and receive an error message: 'Error loading data from cache'. 

### Expected results

The chart to show predictions.

### Actual results

Update the chart and receive an error message: 'Error loading data from cache' and the log contains: 
```
force_cached (QueryContext): value not found for key f1510b265fdd1416331715b54d95d017
WARNING:superset.common.utils.query_cache_manager:force_cached (QueryContext): value not found for key f1510b265fdd1416331715b54d95d017
```

### Workaround / Fix
In order to remove the error, you need to build a new docker image with the following lines:
```
FROM apache/superset:2.1.0
USER root
RUN pip install --upgrade pip
RUN pip install lunarcalendar tqdm "pystan<3.0" && pip install "prophet>=1.0.1, <1.1"
```

Can these missing dependencies not be included in the docker image, so that the functionality will work out of the box?

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x ] I have reproduced the issue with at least the latest released version of superset.
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar. There are several issues where people struggle to get this to work, why not include it in the image so that we don't have to manually add this?

**Comment by sebastianliebscher** [comment] 2023-06-16 09:55
AFAIK Predictive forecasting is an optional feature introduced with https://github.com/apache/superset/pull/10324. So at the moment your current workaround is the actual intended way to enable this feature. To me this does not look like a bug, but I see two issues here:

- predictive forecasting should be mentioned in the Superset docs whether it's optional or not and how to enable it (from scratch install vs docker install)
- as predictive forecasting is baked into the UI independent of it is enabled or not, I also think it should be a default feature

Unfortunately, the integration tests for this feature are currently failing (at least for me). https://github.com/apache/superset/issues/24406

**Comment by maudrid** [comment] 2023-06-16 11:39
If this is an optional feature, there should be a feature flag that enables it.
Having pieces of the UI just fail with uninformative errors, is just bad.
In addition to a feature flag, there should be documentation on how to enable it.

**Comment by sebastianliebscher** [comment] 2023-06-16 12:10
In the UI, when enabling this feature it should cleanly prompt the information "missing requirement 'prophet'". Maybe your issue is related with caching activated which it is not by default. Can you test the same without caching?

**Comment by maZahaca** [comment] 2023-11-03 16:08
Any ready to go docker images available? like the one you have for `-dev` dev?

**Comment by Razikus** [comment] 2024-02-28 17:56
bump

**Comment by rusackas** [comment] 2024-02-28 21:52
@Razikus what version of Superset are you running? The rest of the thread is from the 2.x era. I wouldn't think we're seeing this in 3.1, and we should close this issue if not.

**Comment by Razikus** [comment] 2024-02-28 21:55
In prod version in 3.11 it's the same 
Prophet not installed

**Comment by rusackas** [comment] 2024-02-28 22:17
Ahh... [this PR](https://github.com/apache/superset/pull/10324) is the reason (and provides context). 

From Updating.md:
> Facebook Prophet has been introduced as an optional dependency to add support for timeseries forecasting in the chart data API. To enable this feature, install Superset with the optional dependency `prophet` or directly `pip install fbprophet`

I think with that, we probably ought to close this out, since it's not a bug, but I'll leave it open for now for further discussion, or in hopes that someone might have some cycles to improve the documentation so others don't get tripped up on this.

**Comment by maudrid** [comment] 2024-02-28 22:45
The issue ís that,since it is not installed by default, when users try to
use the feature in a chart, the get an obscure error message.
I propose that either the chart should disabled the UI for the predication,
or should show a user friendly error message.

**Comment by rusackas** [comment] 2024-02-28 22:51
No disagreement, I think that's the right thing to do. We can call that a bug for now. I'd encourage anyone interested in this thread to open a PR though, as I don't think any of the core committers have this high on their list.

**Comment by Razikus** [comment] 2024-02-29 00:07
Awesome guys thanks for quick answer 
For me finally it worked but it works only with time series not SQL

**Comment by rusackas** [comment] 2024-08-20 20:46
Hey all. It's been another 6 months since this thread was touched, so I'll go ahead and close it out as... uh... explained? Sounds like folks get the idea of the optionality. If there's a cool way to hide the control when the dependency is not present, we'd be open to that sort of "dynamic controls" PR.

**Closed by rusackas** 2024-08-20 20:46 UTC
Labels: #bug
