### ISSUE TITLE
Dashboard CSS keeps disappearing for v0.37

### ISSUE THREAD

**Issue by stevensuting** [apache/superset#10779] opened 2020-09-03 12:52 UTC
### Expected results

Once CSS is written on the Dashboard CSS feature, it should remain persistent. 

### Actual results

The CSS once applied reflects on the dashboard for the current session. In the subsequent login the CSS script disappears. The number of sessions are arbitrary. Sometimes it happens after one session, sometimes after several.

#### Screenshots
Before
![Before](https://user-images.githubusercontent.com/8875448/92116491-874c4a00-ee11-11ea-834d-e3544ea11c9b.png)
After
![After](https://user-images.githubusercontent.com/8875448/92116477-84515980-ee11-11ea-8ac6-958c8b5c6735.png)

#### How to reproduce the bug

1. Go to Dashboards -> Edit Record -> Scroll to CSS text box
2. Paste some CSS, like
```
.grid-container{
    margin: 18px;
}
.dashboard-header {
display: none;
}
```

3. Save and go to Dashboard. 
4. You will see the CSS changes. Now log out and log back in, CSS disappears.

### Environment
- superset version: `0.37`
- python version: `3.6.9`

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ Y] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ Y] I have reproduced the issue with at least the latest released version of superset.
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by JunlinC** [comment] 2020-09-04 03:37
🙏 @rusackas

**Comment by gtg472b** [comment] 2020-09-07 18:28
I think this has already been fixed. I had the issue a couple of months ago, but it's no longer a problem.

**Comment by willbarrett** [comment] 2020-09-08 18:14
I think this is related to https://github.com/apache/incubator-superset/issues/10655

**Comment by i2cute** [comment] 2020-09-11 04:39
I also facing the same problem. What is the solution for this?

**Comment by willbarrett** [comment] 2020-09-12 16:41
Some members of the community are working on a refactor of the related code, there are a number of related data handling issues. We do not have an ETA for completion or release, but the problem is being actively worked on.

**Comment by squalou** [comment] 2020-11-24 17:34
Same issue here, 0.37.2

**Comment by squalou** [comment] 2020-11-24 19:56
Seen it on 0.38.rc4 too

**Comment by stevensuting** [comment] 2020-12-05 16:34
I noticed when the CSS gets erased. It's not session based but rather editing an existing dashboard.

If you build a dashboard, add CSS then save. The CSS stays for good.
If you edit a dashboard that has some CSS on saving it erases all the CSS.

**Comment by suddjian** [comment] 2021-04-21 22:03
This appears to be fixed in the latest version.

**Closed by suddjian** 2021-04-21 22:03 UTC
Labels: bug
