### ISSUE TITLE
Unexpected Error on Exit Fullscreen

### ISSUE THREAD

**Issue by shilpaprotiviti** [apache/superset#25024] opened 2023-08-18 10:56 UTC
We are getting unexpected error in chart on click "Exit Fullscreen" button under dashboard. This is the error coming if we have set parametrized URL chart. On click of Exit Fullscreen button, parameters are getting removed and chart is unable to generate report from inputted dataset.

#### How to reproduce the bug

1. Go to 'Dashabord', enter required input parameter and click on Apply button
2. After loading of chart data, Click on 'Exit Fullscreen' button
3. Chart is now showing "Unexpected Error"
4. See error - Error: invalid input syntax for type date: "None"

### Expected results - Parameter of URL should remain still there after click on Exit fullscreen button. Report must be able to show same data as earlier.
dashboard URL:
https://XX-XX.XX.com/superset/dashboard/XXX/?standalone=true&permissionType=Accounts%20Payable&dateType=itemdate&AgingDateOn=duedate&payOpt=open&balanceDate=2043-08-18&fromDate=2023-08-01&toDate=2023-08-18

dashboard URL on click fullscreen:
https://XX-XX.XX.com/superset/dashboard/XXX/?preselect_filters=%7B%7D&native_filters_key=L8FOes-Lp7E626te7o_PErUvPMCcgNfh8A_TWHdGk7NaE_8oRz7d0pyD2FpOwhHJ

#### Screenshots
<img width="955" alt="UnexpectedError - Superset" src="https://github.com/apache/superset/assets/122963015/92cde9e0-7292-4c02-adf4-dd325fca5583">

### Environment

- browser type and version: chrome ,microsoft edge (all)
- superset version: `superset version` Version: 2.0.0
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

**Comment by michael-s-molina** [comment] 2023-08-18 13:59
Hi @shilpaprotiviti @MaheshKungaria. I'm not able to reproduce this bug on 2.1.1RC3 and 3.0.0RC2 which are currently under voting. This means that it was probably fixed on master already and will be available soon.

https://github.com/apache/superset/assets/70410625/abccb1ad-8cbf-48bf-92d1-fb6307a2c6e9

I'm not sure if you're able to reproduce this on 2.1.0. If not, then the solution is to upgrade your Superset version now. If 2.1.0 contains this bug, then you need to wait for 2.1.1 or 3.0.0 😄

**Comment by michael-s-molina** [comment] 2023-08-18 14:49
Thanks for reporting this issue @shilpaprotiviti  @MaheshKungaria. I submitted a fix [here](https://github.com/apache/superset/pull/25028) that will be cherry picked into 3.0.

**Closed** 2023-08-18 18:07 UTC

**Comment by MaheshKungaria** [comment] 2023-08-21 16:21
Thanks for the quick response @michael-s-molina please confirm which Superset version has this issue fixed?

**Comment by michael-s-molina** [comment] 2023-08-21 16:23
> Thanks for the quick response @michael-s-molina please confirm which Superset version has this issue fixed?

This will be included in 3.0.

**Comment by MaheshKungaria** [comment] 2023-08-21 17:04
May I know when Superset 3.0 will be releasing?

**Comment by michael-s-molina** [comment] 2023-08-21 17:09
> May I know when Superset 3.0 will be releasing?

3.0 is currently being voted. You can follow release updates on the #apache-releases Slack channel.
