### ISSUE TITLE
synchronize color hex values for labels across charts in a dashboard without having to explicitly call out color choices for each label.

### ISSUE THREAD

**Issue by kenandominic** [apache/superset#22049] opened 2022-11-07 20:47 UTC
Hi, I have a question which might turn into a feature request. Is it currently possible to synchronize color hex values for labels across charts in a dashboard without having to explicitly call out color choices for each label?
(I know about this; https://superset.apache.org/docs/frequently-asked-questions/#is-there-a-way-to-force-the-use-specific-colors)

I have many pie charts representing makeups of different categories across different dimensions and so share labels across them. by default these labels need not use the same color across different charts. there are also too many (20-30) to call out explicitly. is there a way of specifying something like the following in the dashboard metadata
```
{
    "synchronize_chart_label_colors": [
        "xxx",
        "yyy",
        "zzz"
    ]
}
```

that would then result in the charts xxx, yyy and zzz having the same color hex values for the same labels they share across them? thanks !

**Comment by ShaliniIruvuru** [comment] 2023-03-17 13:40
Working  fine.No need to add as feature.
If you add below metadata in Edit dashboard then it's working fine.
 {
 "label_colours" : { "girl" : "#FF0000" ,"boy" : "#00FF00" }
}

Screenshots:-

1.Without adding colours to labels
![image](https://user-images.githubusercontent.com/115684419/225920831-f4b1534c-12c8-40ae-9438-d8095f59a19b.png)
2.After adding colours to labels
![image](https://user-images.githubusercontent.com/115684419/225920963-7f6e512e-2af3-486f-b3b2-7907356a0af1.png)
![image](https://user-images.githubusercontent.com/115684419/225921094-883f057b-2ffc-4e33-ac02-9c386f8ec6fc.png)

**Comment by kenandominic** [comment] 2023-04-24 21:19
hey @ShaliniIruvuru you've answered the opposite of my request. stating it once again.

> Is it currently possible to synchronize color hex values for labels across charts in a dashboard **without having to explicitly call out color choices for each label?**

you're stating that it is possible by explicitly calling out each color choice. I'm aware of that. but when there are many categories (10+) this becomes rather cumbersome. also when you have many pie charts across different categorical sets.

**Comment by ShaliniIruvuru** [comment] 2023-04-26 07:40
Hi Kenandominic,It is possible to synchronize color hex values for labels across charts in a dashboard without having to explicitly call out color choices for each label.
Screenshot:-
![image](https://user-images.githubusercontent.com/115684419/234503894-55715337-0ef1-48c7-9181-e5c6fdb990d0.png)

If it is not your requirement,can you please provide the detail information.

**Comment by rusackas** [comment] 2024-02-26 22:58
Indeed, Superset now has much improved "color consistency" in dashboards. It's an annoyingly hard problem (each BI tool has its edge cases here) but we're in a pretty decent place now. Closing since we're likely in a "good enough" state in current Superset, but please feel free to open new/reproducible Issues for any failing cases, and we'll consider them!

**Closed by rusackas** 2024-02-26 22:58 UTC
