### ISSUE TITLE
Failure on creation of a new Presto dataset due to failure to load columns

### ISSUE THREAD

**Issue by eyalsh99** [apache/superset#25962] opened 2023-11-12 15:39 UTC
We have a Presto database connection working fine with virtual datasets (added throw SQLLab).
When trying to add a new dataset of a physical table we're getting an error.

### Reproducing the bug:

1. Go to Datasets
2. Click on '+ Dataset'
3. Select the a Presto DB
4. Select the Schema
5. Select the Table
7. See error

### Expected results

See the table columns on the right pane

### Actual results

An error message appears on the right pane:
"An Error Occurred
Unable to load columns for the selected table. Please select a different table."

Couldn't find any errors in the Superset app container log or any other container.

#### Screenshots

![image](https://github.com/apache/superset/assets/18547145/25531a55-b665-41f6-b7b6-46db5ab9a720)

### Environment

- Google Chrome, Version 119.0.6045.123
- Superset version: 3.0.1
- python version: 3.11.4
- node.js version: 20.9.0
- any feature flags active: none

### Checklist

- [+ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ +] I have reproduced the issue with at least the latest released version of superset.
- [ +] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment] 2023-11-14 17:34
Possibly a duplicate of https://github.com/apache/superset/issues/23982, do you have that sort of datetime partition / can you try a table without that to isolate the issue?  Specifically the comment https://github.com/apache/superset/issues/23982#issuecomment-1551430633 has a fix you could try.

**Comment by sfirke** [comment] 2023-11-14 17:35
@bkyryliuk you are listed as a Presto user in the database rolodex - do you have thoughts on this or that issue I linked?

**Comment by eyalsh99** [comment] 2023-11-19 17:31
> Possibly a duplicate of #23982, do you have that sort of datetime partition / can you try a table without that to isolate the issue? Specifically the comment [#23982 (comment)](https://github.com/apache/superset/issues/23982#issuecomment-1551430633) has a fix you could try.

@sfirke Thank for your comment but I don't think it's the same problem. It happens for all tables. The attached tables has only "string" columns.

**Comment by eyalsh99** [comment] 2023-11-19 17:37
I was able to debug the problem and found the it was caused by the stringification of the data type at [_create_column_info function](https://github.com/apache/superset/blob/2499a1cf5a7f298c1ee2f34b3d67ca1d18bb7457/superset/db_engine_specs/presto.py#L839). It expects to get a column type object and not a string representation of it.
Once changed I managed to get the table columns and create the dataset.

**Comment by sfirke** [comment] 2023-11-19 18:05
Nice problem solving! Thanks for the update. Are you able to propose a fix to the codebase and send a pull request?

**Comment by eyalsh99** [comment] 2023-11-20 15:03
> Nice problem solving! Thanks for the update. Are you able to propose a fix to the codebase and send a pull request?

Thanks. Sure, I'll send the PR.

**Comment by ameedbakri** [comment] 2024-02-05 13:25
@eyalsh99 
what you change to fix the issue?

**Comment by eyalsh99** [comment] 2024-02-07 07:57
> @eyalsh99 what you change to fix the issue?

You should go to superset/db_engine_specs/presto.py and in _create_column_info function do the following change:
"type": f"{data_type}", ==> "type": data_type,

**Comment by rusackas** [comment] 2024-03-01 17:33
@eyalsh99 are you still planning to open a PR for that change (and maybe add a test if we're lucky?)

**Comment by RyzhkovIlia** [comment] 2024-04-19 15:38
@eyalsh99 I am facing the same problem using Athena, maybe you know a solution for my case?

**Comment by sfirke** [comment] 2024-04-26 15:41
Someone in Slack just reported experiencing this in Athena, too.  Same issue or different?

**Comment by RyzhkovIlia** [comment] 2024-04-29 06:44
@sfirke Same issues but on Athena, not Presto. And athena.py doesn't have _create_column_info function

**Comment by eyalsh99** [comment] 2024-05-01 08:15
> @eyalsh99 are you still planning to open a PR for that change (and maybe add a test if we're lucky?)

Apologies for the late response. Submitted the PR: #28305

**Comment by john-bodley** [comment] 2024-05-21 18:40
Re-opening because the fix was reverted in https://github.com/apache/superset/pull/28613.

**Closed** 2024-05-28 15:56 UTC
Labels: data:connect:athena, data:connect:presto
