### ISSUE TITLE
Failed to set user for impala

### ISSUE THREAD

**Issue by KanaSukita** [apache/superset#22368] opened 2022-12-08 09:19 UTC
I was tring to configure a impala data source with spicified user, so that the datasource can only access to a few databases in hive. I am using cdh 6.3.2 cluster with sentry and no kerberos, and have aleardy configure a permission with user "test" which only has permission to a database called test_impala. When I use impala-shell with this user using the command "impala-shell -u test", I can only get access to the database test_impala.

I configured the data source with uri "impala://xx.xx.xx.xx" and extra parameters as below. I got success when testing the connection but with this data source I was still able to query data from databases besides test_impala.

```json
{
    "metadata_params": {},
    "engine_params": {
        "connect_args":{
            "port":21050,
            "user": "test",
            "database": "test_impala"
        }
    },
    "metadata_cache_timeout": {},
    "schemas_allowed_for_csv_upload": []
}
```

Can anyone provide a guide on how to configure the impala data source with spicified user?

**Comment by rusackas** [comment] 2022-12-12 23:57
Pinging @betodealmeida to see if they can refer us to anyone with Impala expertise. 

Also (for @betodealmeida's consideration), it may be warranted to convert this Issue to a Q&A Discussion, if it indeed represents a configuration question more so than a bug/regression that others are likely to encounter.

**Comment by betodealmeida** [comment] 2022-12-13 00:15
I'm not familiar with Impala, but looking at the source code I wonder if you also need to specify an `auth_mechanism`?

https://github.com/cloudera/impyla/blob/0f2be72e31feab9cc6d91b44dc873af306bcb97a/impala/dbapi.py#L41-L47

The default mechanism is `NOSASL`, which corresponds to "unsecured Impala". A user [has commented](https://github.com/cloudera/impyla/issues/393#issuecomment-607580685) that "in NOSASL mode, it use the pure socket connection to connect impala without user & password", so that could be the issue.

@KanaSukita does the user has a password? If so, can you try with:

```
{
    "metadata_params": {},
    "engine_params": {
        "connect_args":{
            "port":21050,
            "user": "test",
            "password": "XXX",
            "auth_mechanism": "PLAIN",
            "database": "test_impala"
        }
    },
    "metadata_cache_timeout": {},
    "schemas_allowed_for_csv_upload": []
}
```

**Comment by rusackas** [comment] 2024-01-24 17:30
Closing since the original author has not replied to the lead, and this issue is not reproducible.

**Closed by rusackas** 2024-01-24 17:30 UTC
