### ISSUE TITLE
Connect to Google Sheets - SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by GonzaloGit2020** [apache/superset#11513] opened 2020-10-31 22:16 UTC
i try to connect and query a Google Sheets, i am using gsheetdb, i have followed the steps from this link: https://superset.apache.org/docs/databases/google-sheets

But i am getting some issues. Could you help me to know why i can't connect to Google Sheet?

### Expected results

Connect and get the information from Google Sheets

### Actual results

I get the next error message: 

gsheets error: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: google_sheet_URL  (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))

- superset version: 0.37.2
- python version: Python 3.6.9 (SCL)

**Comment by dpgaspar** [comment] 2020-11-02 11:44
It seems strange the your superset server is not recognising google's certificate. Are you running locally? If yes take a look at: https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

**Comment by GonzaloGit2020** [comment] 2020-11-03 02:03
> It seems strange that your superset server is not recognising google's certificate. Are you running locally? If yes take a look at: https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

Yes, we are, we have a Linux server running Superset in the company where i work. I am not sure if the proxy's company is affecting the communication with google sheet, anyway let me look the link you shared.

Regards

**Comment by rusackas** [comment] 2022-12-20 22:00
Closing this because:
* it seems to be more of a help request than a bug report
* A LOT of people use this feature and there happens to be a lot more documentation about it these days
* The thread has gone cold, so I'll assume the problem is solved or the reporter has moved on. 

If this still needs problem solving, let's open a Q&A / Help thread on the Discussions page!

**Closed by rusackas** 2022-12-20 22:00 UTC
Labels: install:docker, change:backend
