### ISSUE TITLE
SFTP Reports Scheduling Feature Suggestion

### ISSUE THREAD

**Issue by rohitpawar2811** [apache/superset#24305] opened 2023-06-07 07:50 UTC
### Discussed in https://github.com/apache/superset/discussions/24296

<div type='discussions-op-text'>

<sup>Originally posted by **rohitpawar2811** June  6, 2023</sup>
**Proposing the SFTP Scheduling Feature in Superset**

I am about to contribute SFTP-Scheduling support feature currently working on it.

I have thoughts to make this feature like :

1. This one is just like Email, one SFTP is there which is configured through config-properties, and in UI you can simply select SFTP Method, and in the recipient section, we can give the target location of sftp to place the file. : Tested this idea and it is working.

![Screenshot from 2023-06-07 13-12-38](https://github.com/apache/superset/assets/72196393/2fc5f1eb-73cd-49a4-ad4f-652a5a1bb27a)

2. It's Totally different scenario In which, There are Multiple SFTPs that can be configured like databases, and on alert/reports UI on the selection of SFTP notification method we would show a selection box for available SFTP connections and the recipient things same as above **I need your suggestion on this path**

- In a second way, we would get the flexibility to use different-different SFTPs not stick to just one, and It will enable us to work in
multi-tenant scenarios.

- We can not deal with one SFTP with 100 or more users because SFTP has a limit on connection, R/W users, and concurrent access by 100 users which will lead us to a connection failure problem.

**I want your thoughts or suggestion on which way we have to go?, Or anyone has any Idea regards to the 2nd scenario?**

@eschutho
@rusackas
@betodealmeida</div>

**Comment by rusackas** [comment] 2023-06-07 20:52
I think it's an interesting feature idea, and well worthy of discussion, but since there already IS a discussion [here](https://github.com/apache/superset/discussions/24296), I think we should close this PR since it's not a bug, and it would only split the discussion in half.

**Closed by rusackas** 2023-06-07 20:52 UTC
