### ISSUE TITLE
Thumbnails at Dashboards Menu stop working after 4.1.1

### ISSUE THREAD

**Issue by pcajubr** [apache/superset#31271] opened 2024-12-03 21:44 UTC
### Bug description

After update version from 4.0.2 to 4.1.1 thumbnails are not working at Menu > Dashboards

From attatches you can sse working at Home and Charts

### Screenshots/recordings

![Superset thumbs - not working - dashboards](https://github.com/user-attachments/assets/7e34e1b5-5a95-4212-b3c2-13909945a611)
![Superset thumbs - working - charts](https://github.com/user-attachments/assets/d9efb75d-52be-47d9-b927-c314ac124948)
![Superset thumbs - working - home](https://github.com/user-attachments/assets/a00bf146-c918-4527-810f-013f408f9c84)

### Superset version

4.1.1

### Python version

I don't know

### Node version

I don't know

### Browser

Chrome

### Additional context

Python e Node verion is from Superset Image: "docker image build -t superset:4.1.1 ."

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [x] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by frlm** [comment] 2024-12-05 14:33
I'm observing the same issue

**Comment by sfirke** [comment] 2024-12-05 20:35
Could one of you check the logs when the thumbnail job runs and see if that yields anything? I'm wondering if it could be related to https://github.com/apache/superset/issues/31283

**Comment by pcajubr** [comment] 2024-12-06 17:02
I have this error you mentioned.

![logs](https://github.com/user-attachments/assets/fee13898-5648-470e-9580-92553f6d8654)

**Comment by sfirke** [comment] 2024-12-06 17:26
Thanks @pcajubr ! With that log, I think we can mark this a duplicate of #31283, which has a fix PR in progress that looks very close to the finish line. I will mark that PR for inclusion in the next patch release version, 4.1.2.

**Closed by sfirke** 2024-12-06 17:26 UTC
Labels: listview:dashboards
