### ISSUE TITLE
Superset v3 not running on dev

### ISSUE THREAD

**Issue by adarsh12102023** [apache/superset#25674] opened 2023-10-17 09:42 UTC
#### How to reproduce the bug

1. Checkout superset branch v3
2. Complete all the installation mentioned in the apache-superset documentation
3. Run 'npm run dev' from superset-frontend folder
4. See whether superset is running on browser or not

### Expected results
Superset should run on browser on mentioned port
what you expected to happen.

### Actual results

what actually happens.

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by adarsh12102023** [comment] 2023-11-02 16:28
Hi Apache/superset

I would again like to highlight the issue we are facing while running apache superset 3.0 locally. 
Please help me to fix this as soon as possible.

**Comment by sfirke** [comment] 2023-11-02 17:42
Can you try skipping the section "Build Javascript Assets" on this page? https://superset.apache.org/docs/installation/installing-superset-from-scratch/#installing-and-initializing-superset .  I think that's only for the case where you are trying to customize/extend Superset by modifying the codebase.  The first step would be to get Superset running, and I don't think you need to run `npm run` as part of that (though I'm not 100% sure as I have not installed from scratch).

For a troubleshooting question like this, where it's not a bug report, you may want to try asking in the Slack chat if you have not already.

**Comment by rusackas** [comment] 2024-03-21 18:36
Hi... closing this since it's not very actionable for a few reasons:
* You were using the 3.0 branch, rather than the 3.0 version, from what I can tell, but that needs clarifying.
* There's no indication of whether Superset was running correctly (with or without the UI) after starting it up, which would be a prerequisite for `npm run dev` to proxy to
* There are no logs/errors noted, from the console or the browser, so we don't have much to go on
* We've released 3.1, which seems to be working just fine for folks, as far as we can tell
* This thread has gone silent for 4 months.

If you're still facing this, and can provide more details, we're happy to keep diagnosing things.

**Closed by rusackas** 2024-03-21 18:36 UTC
Labels: need:more-info
