### ISSUE TITLE
JavaScript Embed SDK - Module not found: Can't resolve '@superset-ui/switchboard'

### ISSUE THREAD

**Issue by c-kirkeby** [apache/superset#22747] opened 2023-01-17 04:36 UTC
When I attempt to use the `@superset-ui/embedded-sdk` library in a Next.js application, it 

#### How to reproduce the bug

1. `git clone git@github.com:c-kirkeby/superset-miniral-reproduction.git`
3. `pnpm install` or `npm install` (it has lockfiles for both)
4. `pnpm run build` or `npm run build`
5. See the compile error in your terminal

### Expected results

Compile without error

### Actual results

```
❯ npm run build

> superset-minimal-reproduction@0.1.0 build
> next build

info  - Linting and checking validity of types  
info  - Creating an optimized production build  
Failed to compile.

./node_modules/@superset-ui/embedded-sdk/lib/index.js
Module not found: Can't resolve '@superset-ui/switchboard' in '/Users/christian/Projects/superset-minimal-reproduction/node_modules/@superset-ui/embedded-sdk/lib'

Import trace for requested module:
./node_modules/@superset-ui/embedded-sdk/lib/index.js


> Build failed because of webpack errors

```

### Environment

(please complete the following information):

- browser type and version: N/A
- superset version: "@superset-ui/embedded-sdk": "0.1.0-alpha.8"
- python version: N/A
- node.js version: `18.13.0` (also does not work on `16.19.0`)
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any. (Not applicable)
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
I encountered this while upgrading a Next.js project's dependencies. We hadn't encountered this error previously.

I've also created a minimal reproduction repo with Vite to rule out Next.js being an issue:

https://github.com/c-kirkeby/superset-minimal-reproduction-vite

**Comment by haivp3010** [comment] 2023-01-17 06:55
Duplicate of #22683.
Could the latest version of @superset-ui/switchboard, i.e. v0.18.26-1 be published by mistake? As I could see the package has nothing inside other than the `package.json` file.
https://www.npmjs.com/package/@superset-ui/switchboard/v/0.18.26-1?activeTab=explore

The related release workflow can be found here, though the failure to publish npm packages has been going on for some weeks I think
https://github.com/apache/superset/actions/runs/3840108687/jobs/6538761916#step:12:31

**Comment by c-kirkeby** [comment] 2023-01-17 07:02
> Duplicate of #22683. Could the latest version of @superset-ui/switchboard, i.e. v0.18.26-1 be published by mistake? As I could see the package has nothing inside other than the `package.json` file. https://www.npmjs.com/package/@superset-ui/switchboard/v/0.18.26-1?activeTab=explore ![image](https://user-images.githubusercontent.com/7151454/212830243-04b46a3b-ba30-4be0-8a05-536707bf2614.png)
> 
> The related release workflow can be found here, though failure to publish npm packages has been going on for some weeks I think https://github.com/apache/superset/actions/runs/3840108687/jobs/6538761916#step:12:31

Apologies, that issue did not come up when I searched for it. The temporary fix mentioned in that ticket unfortunately won't work as our CI won't have pre-existing `node_modules`.

**Comment by haivp3010** [comment] 2023-01-17 07:07
@c-kirkeby a workaround you could try explicitly installing v1.5.0 of `@superset-ui/switchboard`
```sh
yarn add @superset-ui/switchboard@1.5.0
```

**Comment by c-kirkeby** [comment] 2023-01-18 01:32
> @c-kirkeby a workaround you could try is explicitly installing v1.5.0 of `@superset-ui/switchboard` (or v0.18.26-0 if you feel like it, but I could see 1.5.0 is latest before 0.18.26-1)
> 
> ```shell
> yarn add @superset-ui/switchboard@^1.5.0
> ```

Thanks, that helped! I was able to get around this for the time being by explicitly installing the previous version.

**Comment by rusackas** [comment] 2024-02-15 03:06
I believe this was all solved, and was a temporary problem. If anyone is experiencing this in the current version, we can revisit/reopen.

**Closed by rusackas** 2024-02-15 03:06 UTC
Labels: #bug
