### ISSUE TITLE
Chart are not loading after upgrade from superset v2.0.0 to v3.1.1

### ISSUE THREAD

**Issue by ajitwadekar** [apache/superset#27299] opened 2024-02-29 07:29 UTC
### Bug description

We have upgraded the superset version from v2.0.0 to v3.1.1 
After the upgrade for the charts we are getting error as **"Unexpected Error"** and when clicked for more info it gives below 
Error is as below : 
Cannot read properties of undefined ( reading 'ForEach' 
Attaching the screen shot for your reference 

![errors-panels](https://github.com/apache/superset/assets/5318511/1398a495-0d4f-4ded-860d-44eac772f91f)

![3 1 1-Error](https://github.com/apache/superset/assets/5318511/af6eb021-30b6-4b86-9824-16b67951f9fc)

What should we for this error

### How to reproduce the bug

After the upgrade from v2.1.1 to v3.1.0 getting this error.

### Superset version

3.1.1

### Python version

I don't know

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment] 2024-02-29 16:09
Hi @ajitwadekar. In order to help you, we need more details. Could you share the stacktrace of the error that appears in the browser's console?

**Comment by ajitwadekar** [comment] 2024-03-05 05:57
![stack_trace_error](https://github.com/apache/superset/assets/5318511/514243aa-4a2a-4013-9328-c8cf4bcbe7dd)

**Comment by ajitwadekar** [comment] 2024-03-05 06:53
**For version 3.1.0** 
We were facing issue with Handle bars it was giving eval error, we added configuration 
TALISMAN_ENABLED = True
TALISMAN_CONFIG = {
     "content_security_policy": {
        "default-src": ["'self'", "'unsafe-inline'", "'unsafe-eval'"]
    }
}

After that the Handlebar issue was resolved and also the chart loading issue was resolved.

**For version 3.1.1**
The chart loading issue persists when we force refresh the page it works, but again if we load the page the errors 
so errors are seen in console, also no stack trace is printed in logs.

**Comment by michael-s-molina** [comment] 2024-03-06 18:12
@ajitwadekar That's weird. Generally the`Cannot read properties of undefined` error always appears in the console as well indicating which JS file is throwing it. Without that information, it's hard to pinpoint the problem. Pinging @rusackas who is more familiar with the Handlebar plugin and might know something about this issue.

**Comment by rusackas** [comment] 2024-03-07 16:38
That's interesting. I'll try to reproduce it. If you have an example handlebars chart that's doing this, using example datasets, that could be useful, so we're testing with the same scenario. I'll _try_ to look into it this afternoon.

**Comment by reidab** [comment] 2024-03-15 00:06
I'm hitting similar errors on 3.1.1.

From setting a global debugger on all exceptions, it seems that the undefined object here is `queriesResponse` on this line: https://github.com/apache/superset/blob/05d97b02e37a2ce191196b6cfc00ee7cd3a8f05b/superset-frontend/src/components/Chart/chartAction.js#L436

I first saw this error after attempting to enable `GLOBAL_ASYNC_QUERIES` on this deployment and I can confirm that disabling GAQ seems to prevent this error.

This recent change related to GAQ that modified chartAction.js just upstream of that line, thouhg it seems to just be a simple function extraction: https://github.com/apache/superset/commit/faaf14bcc47d892c68f442c73f3979bb082fe033

**Comment by marc-at-work** [comment] 2024-03-15 09:50
Hi,
having similar issues on 3.1.1. with `GLOBAL_ASYNC_QUERIES` enabled.

I want to give a few more information on what I observed (maybe it helps but maybe it is also unrelated)
- When setting the Chart Cache Timeout to `-1` (bypass cache), everything works fine just like when force refreshing cache.
- When trying to import a dashboard from another superset instance to a new one, it (rightfully so) also automatically tries to import the database connection. However, there are credentials missing, so the database connection does not work out of the box on the new superset instance. When I open the imported Dashboard for the first time, however, I do not get an error that the credentials are missing, but the error above as well (`Cannot read properties of undefined ( reading 'ForEach')`). The credentials error only shows up after force refreshing cache.
- I tried the same on 4.0.0rc1 and there I do not get the error message, but charts are not loading and the polling for async query results (requests of the form `/api/v1/async_event/?last_id=1710418422827-0`) always only return an empty list. Also, on a different note, I have a feeling that Chart Cache Timeout is "just ignored" and always falls back to Dataset Cache Timeout on 4.0.0rc1.)

**Comment by sazary** [comment] 2024-03-26 18:48
i had the same issue on 3.1.1

i tried turning off `GLOBAL_ASYNC_QUERIES` and it worked. then i turned it on again, the error happened again, but whenever i force refresh a chart or a dashboard the error goes away.

i did upgrade from `3.0.2`

**Comment by federico-zb** [comment] 2024-03-28 11:01
The issue is on 3.1.1.
The feature flag is defined as GLOBAL_ASYNC_QUERIES:
https://github.com/apache/superset/blob/49fee6c776fb742acf6a9a5c59ee2cf8d257f89b/superset-frontend/packages/superset-ui-core/src/utils/featureFlags.ts#L52
But here is referenced as GlobalAsyncQueries:
https://github.com/apache/superset/blob/49fee6c776fb742acf6a9a5c59ee2cf8d257f89b/superset-frontend/src/components/Chart/chartAction.js#L378

It is fixed in the current master branch

**Comment by michael-s-molina** [comment] 2024-03-28 11:52
Thank you for the investigation @federico-zb. You are correct. That was probably a merging problem not caught during the cherry-pick phase given that `chartAction` is not a Typescript file 😢. It will be fixed in 3.1.2.

**Comment by michael-s-molina** [comment] 2024-03-28 12:01
Closing the issue given that the fix is on master and will be part of 3.1.2.

**Closed by michael-s-molina** 2024-03-28 12:01 UTC
