### ISSUE TITLE
Temporal Preferences Get Erased When Syncing Data From Source

### ISSUE THREAD

**Issue by matthewphua** [apache/superset#15603] opened 2021-07-08 23:31 UTC
The Temporal Selection Checkbox get erased when you sync columns from datasource. Timestamps/date are automatically marked as temporal when you save a query as a dataset, so it would make sense that these columns would be remain temporal when you refresh the dataset.

### Expected results

The temporal preferences should be kept even when syncing data from source.

### Actual results

Temporal preferences appear to be erased. 

#### Screenshots
https://user-images.githubusercontent.com/85198947/125002441-c5a22f00-e009-11eb-8e4e-4d354bd1c51d.mov

#### How to reproduce the bug

1. Open Edit Dataset
2. Sync from datasource
3. See error

**Comment by junlincc** [comment] 2021-07-16 23:39
@matthewphua this is also a feature request...

**Comment by zhaoyongjie** [comment] 2021-07-19 06:34
Hi @matthewphua 
I can't reproduce this issue on the latest master.
cc @junlincc 

https://user-images.githubusercontent.com/2016594/126113528-ce80ff42-295c-44ce-aad2-57d40b2ef864.mp4

**Comment by ValentinC-BR** [comment] 2021-10-07 11:21
I have the exact same issue with Superset v1.3 ...

My config : 
- browser type and version: Google Chrome Version 94.0.4606.71 (Oficial build) (x86_64)
- superset version: 1.3.0
- python version: 3.7.9
- node.js version: doesn't apply, I run on Kubernetes, using gunicorn as server
- source : AWS Athena
- any feature flags active: /

**Comment by yousoph** [comment] 2021-11-16 00:00
@ValentinC-BR are you setting "is temporal" manually for the columns, then syncing and losing the preference? Or are the columns detected as "is temporal" then getting erased when you sync?

**Comment by ValentinC-BR** [comment] 2021-11-16 09:52
Both.

When I first create the table, the columns are detected with "is temporal" checked.
When I sync data, the information is lost.

I check it manually afterwards, to continue using the dataset.
And when I sync data again, the information is lost.

**Comment by villebro** [comment] 2021-11-16 10:34
Please upgrade to at least 1.3.1, which includes this PR that fixes the problem: https://github.com/apache/superset/pull/16776 Closing for now, feel free to reopen if this problem persists.

**Closed by villebro** 2021-11-16 10:34 UTC
Labels: need:validation, viz:explore:dataset, #bug, status:cant-reproduce
