### ISSUE TITLE
Filter 'IS NULL' in chart causes error in dashboard

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#12755] opened 2021-01-26 02:10 UTC
I have a time-series bar chart in which I am using a filter of 'IS NULL' on a column. It works fine in 'Chart Explore' view, but when added in a dashboard it shows **Unexpected Error: 'comparator'**.
I haven't tried this in all the chart types but I think the issue is common for all charts.

### Expected results

The chart should show data in dashboard as well.

### Actual results

The chart shows error when seen from dashboard

#### Screenshots

![image](https://user-images.githubusercontent.com/74634977/105790697-1b3ccf00-5fc8-11eb-9ba2-12a0404b17aa.png)

![image](https://user-images.githubusercontent.com/74634977/105790730-2859be00-5fc8-11eb-9e09-103f2bb80cf7.png)

![image](https://user-images.githubusercontent.com/74634977/105790853-65be4b80-5fc8-11eb-9417-0e881eb610df.png)

#### How to reproduce the bug

1. Create a Time-series bar or line chart with a filter of 'IS NULL' on a column(any column)
2. Save the chart and add to a dashboard
3. Open dashboard and notice error

### Environment

- superset version: 1.0.0
- python version: 3.7
Using official docker image. 

This issue is not reproduced on Superset 0.36.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

When clicking 'View Chart in Explore' from dashboard showing error, it leads to below error:
```
}
Sorry, something went wrong
500 - Internal Server Error
Stacktrace
        Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/app/superset/utils/log.py", line 164, in wrapper
    value = f(*args, **kwargs)
  File "/app/superset/views/core.py", line 745, in explore
    utils.merge_extra_filters(form_data)
  File "/app/superset/utils/core.py", line 1028, in merge_extra_filters
    and existing["comparator"] is not None
KeyError: 'comparator'
```
Logs from Docker:
```
Traceback (most recent call last):
File "/app/superset/views/base.py", line 180, in wraps
return f(self, *args, **kwargs)
File "/app/superset/utils/log.py", line 164, in wrapper
value = f(*args, **kwargs)
File "/app/superset/utils/cache.py", line 157, in wrapper
return f(*args, **kwargs)
File "/app/superset/views/core.py", line 612, in explore_json
return self.generate_json(viz_obj, response_type)
File "/app/superset/views/core.py", line 451, in generate_json
payload = viz_obj.get_payload()
File "/app/superset/viz.py", line 465, in get_payload
payload = self.get_df_payload(query_obj)
File "/app/superset/viz.py", line 497, in get_df_payload
query_obj = self.query_obj()
File "/app/superset/viz.py", line 338, in query_obj
self.process_query_filters()
File "/app/superset/viz.py", line 331, in process_query_filters
merge_extra_filters(self.form_data)
File "/app/superset/utils/core.py", line 1028, in merge_extra_filters
and existing["comparator"] is not None
KeyError: 'comparator'
ERROR:superset.views.base:'comparator'
Traceback (most recent call last):
File "/app/superset/views/base.py", line 180, in wraps
return f(self, *args, **kwargs)
File "/app/superset/utils/log.py", line 164, in wrapper
value = f(*args, **kwargs)
File "/app/superset/utils/cache.py", line 157, in wrapper
return f(*args, **kwargs)
File "/app/superset/views/core.py", line 612, in explore_json
return self.generate_json(viz_obj, response_type)
File "/app/superset/views/core.py", line 451, in generate_json
payload = viz_obj.get_payload()
File "/app/superset/viz.py", line 465, in get_payload
payload = self.get_df_payload(query_obj)
File "/app/superset/viz.py", line 497, in get_df_payload
query_obj = self.query_obj()
File "/app/superset/viz.py", line 338, in query_obj
self.process_query_filters()
File "/app/superset/viz.py", line 331, in process_query_filters
merge_extra_filters(self.form_data)
File "/app/superset/utils/core.py", line 1028, in merge_extra_filters
and existing["comparator"] is not None
KeyError: 'comparator'
172.17.0.1 - - [26/Jan/2021:02:14:13 +0000] "POST /superset/explore_json/?form_data=%7B%22slice_id%22%3A109%7D&force=true&dashboard_id=9 HTTP/1.1" 500 25 "http://localhost:8080/superset/dashboard/9/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
172.17.0.1 - - [26/Jan/2021:02:14:14 +0000] "POST /superset/log/?explode=events&dashboard_id=9 HTTP/1.1" 200 1 "http://localhost:8080/superset/dashboard/9/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
127.0.0.1 - - [26/Jan/2021:02:14:19 +0000] "GET /health HTTP/1.1" 200 2 "-" "curl/7.64.0"
```

**Comment by junlincc** [comment] 2021-01-26 03:02
![image](https://user-images.githubusercontent.com/67837651/105793559-2fd48500-5f3e-11eb-94f8-6633a8162cfe.png)

@kamalkeshavani-aiinside I'm not able to reproduce in master. i also tried other NVD3 charts. @villebro @zhaoyongjie any idea what this error means

**Comment by kamalkeshavani-aiinside** [comment] 2021-01-26 03:05
@junlincc I haven't tried on latest master, but could see this in 1.0.0. Let me check in master as well.

**Comment by kamalkeshavani-aiinside** [comment] 2021-01-26 04:06
> @junlincc I haven't tried on latest master, but could see this in 1.0.0. Let me check in master as well.

@junlincc I could also confirm, not reproduced in master.

**Comment by junlincc** [comment] 2021-01-27 08:19
thanks @kamalkeshavani-aiinside feel free to close this issue if everything looks good to you :)

**Closed** 2021-01-27 08:39 UTC
Labels: cant-reproduce

**Comment by krsnik93** [comment] 2021-02-23 16:32
Seeing this as well.
