### ISSUE TITLE
Unuseful column in export Excel

### ISSUE THREAD

**Issue by xavier-GitHub76** [apache/superset#29717] opened 2024-07-26 12:59 UTC
### Bug description

Hello,
the Excel export of data chart has an unuseful column :
![image](https://github.com/user-attachments/assets/e4a9d4bd-4e2b-4cc1-9ace-3b2e16f51dd9)
Regards

### How to reproduce the bug

1. Create a chart
2. Export data (Excel)
3. Open Excel file

### Superset version

master / latest-dev

### Python version

3.9

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment] 2024-07-26 14:34
Duplicate of https://github.com/apache/superset/issues/22981.  See the two open PRs linked in that discussion -- one is very close to mergeable 😣 🤞

**Closed by sfirke** 2024-07-26 14:34 UTC
Labels: viz:charts:export
