### ISSUE TITLE
Error running superset in docker with typing-extensions

### ISSUE THREAD

**Issue by vladaman** [apache/superset#21735] opened 2022-10-07 12:31 UTC
We are unable to run superset with docker.

## Steps to reproduce

Dockerfile:
```Dockerfile
FROM apache/superset
USER root
RUN pip install mysqlclient
RUN pip install elasticsearch-dbapi
RUN pip install psycopg2-binary
RUN pip install snowflake-sqlalchemy
RUN pip install "PyAthena>1.2.0"
RUN pip install pydruid
RUN pip install sqlalchemy-redshift
USER superset
```

## Followed by commands
```bash
docker build -t org/superset2 .
docker run -d -p 8080:8088 --name superset org/superset2
docker exec -it superset superset fab create-admin \
              --username admin \
              --firstname Superset \
              --lastname Admin \
              --email admin@superset.com \
              --password admin
```

## Produces error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (typing-extensions 4.4.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('typing-extensions<4,>=3.10'), {'apache-superset'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/superset", line 33, in <module>
    sys.exit(load_entry_point('apache-superset', 'console_scripts', 'superset')())
  File "/usr/local/bin/superset", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/superset/cli/main.py", line 28, in <module>
    from superset.cli.lib import normalize_token
  File "/app/superset/cli/lib.py", line 20, in <module>
    from superset import config
  File "/app/superset/config.py", line 46, in <module>
    import pkg_resources
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'typing-extensions<4,>=3.10' distribution was not found and is required by apache-superset
```

Looks related to https://github.com/apache/superset/issues/20863#issuecomment-1252238140

**Comment by ShaliniIruvuru** [comment] 2023-03-20 15:10
It is not a bug.We were able to run Superset with Docker.
Screenshots:-
![image](https://user-images.githubusercontent.com/115684419/226383104-705cd8ca-465d-4984-86fc-0cb8cfb523be.png)
![image](https://user-images.githubusercontent.com/115684419/226383169-06975576-87c9-409a-a550-d40122a58760.png)

**Comment by sfirke** [comment] 2023-06-22 15:19
Superset deploys with Docker generally.  I agree that your link to that other comment looks relevant, that is, that this is resulting from one of the packages you have added to your Dockerfile.

Did you resolve this problem?

**Comment by ShaliniIruvuru** [comment] 2023-06-23 05:48
Hi @sfirke ,
I didn't add any packages specifically,I just followed whatever @vladaman provided the steps to reproduce the bug.
After followed the steps I didn't get any error.FYI I added screenshots in above comment.Please go through...

**Comment by rusackas** [comment] 2023-07-07 03:40
Doesn't look like we're seeing a response from the original author, and the issue is neither clear nor reproducible. Closing, but open to further discussion.

**Closed by rusackas** 2023-07-07 03:40 UTC
Labels: #bug
