### ISSUE TITLE
How can ı change superset login page

### ISSUE THREAD

**Issue by OkancanOkan** [apache/superset#24944] opened 2023-08-10 08:52 UTC
## Screenshot

[drag & drop image(s) here!]

## Description

[describe the issue here!]

## Design input
[describe any input/collaboration you'd like from designers, and
tag accordingly. For design review, add the
label `design:review`. If this includes a design proposal,
include the label `design:suggest`]

I want to change login page HTML and CSS but  ı didn't find anything about that

**Comment by sfirke** [comment] 2023-08-10 16:40
Hello, I'm closing this issue as it is not a bug report.  A request for assistance like this is better suited to Apache Superset Slack chat or GitHub discussions, please feel free to post in either place.  I would suggest first searching both places for terms like "customize login page" as the topic has arisen before and you may find what you need.

**Closed by sfirke** 2023-08-10 16:40 UTC
