### ISSUE TITLE
How to add our angular code inside super set react app

### ISSUE THREAD

**Issue by pallaviMN** [apache/superset#25174] opened 2023-09-04 15:09 UTC
Hi Team,
I need to add one chatbot button, on click of it, i need to embed my angular code inside our superset app.
Please let us know what changes to be done in here?

**Comment by rusackas** [comment] 2024-03-08 20:58
Hi there. Closing this since it's not a bug. Please feel free to reach out to the community on [slack](http://bit.ly/join-superset-slack) for more help.

**Closed by rusackas** 2024-03-08 20:58 UTC
