### ISSUE TITLE
(Pinot) Time Series Area Chart not Rendering When `avg` function used in multiple metrics

### ISSUE THREAD

**Issue by ege-st** [apache/superset#26303] opened 2023-12-18 22:34 UTC
When using the Pinot connection, if you create a Time Series Area Chart, it fails to render when multiple metrics are added that use the same aggregation function. However, it does render correctly when different aggregation functions are used.

#### How to reproduce the bug

1. Create a Pinot dataset
2. Go to Charts and create a new Time Series Area Chart selecting the Pinot dataset
3. Add a metric, pick a numeric column, and choose `avg` as the function.
4. Add a second metric, pick a numeric column, and again choose `avg` as the function.
5. Click `Update Chart`
6. Nothing will render.

I ran a test with one metric column (using avg), 2 metric columns (one avg and one sum), and 2 metric columns (both avg). The correct Pinot Query is generated (and I tested the query against Pinot directly and through the `pinotdb` library and both work), but the last test only returns the results of a single metric column. 

So it appears as if, after receiving the results somewhere in Superset the last column is stripped from the result set and then the chart fails to render because the second metric column does not exist.

### Expected results

Both metrics should be rendered on the chart.

### Actual results

Nothing is rendered.

#### Screenshots

[screen-cast.webm](https://github.com/apache/superset/assets/134291879/055e3ae5-7811-4920-8ce0-72f680798a9f)

Screen shot of the result data for a query with a single avg metric column:
![1 - one_avg_in_query](https://github.com/apache/superset/assets/134291879/371caf81-dee5-4974-9c7d-6f96bffbcdbf)

Screenshot of the result data for a query with a `avg` metric column and a `sum` metric column (note there are two columns in addition to the timestamp column):
![2 - avg and sum in query](https://github.com/apache/superset/assets/134291879/f25d25c3-ccc0-4253-bf9e-94036563e5d7)

Screenshot of the result data for a query with 2 `avg` metric columns (note there is only one column in addition to the timestamp column):
![3 - avg and avg in query](https://github.com/apache/superset/assets/134291879/dbab27af-a110-47c3-9abd-e8d77c209a32)

This is the query that Superset sends to Pinot in the last screenshot (using one of Pinot's Quickstart data sets):

```
SELECT DATETIMECONVERT(mtime, '1:MILLISECONDS:EPOCH', '1:MILLISECONDS:EPOCH', '1:SECONDS'),
       AVG(rsvp_count) AS "AVG_1",
           AVG(group_id) AS "AVG_2"
FROM "default"."meetupRsvp"
GROUP BY DATETIMECONVERT(mtime, '1:MILLISECONDS:EPOCH', '1:MILLISECONDS:EPOCH', '1:SECONDS')
ORDER BY AVG(rsvp_count) DESC
LIMIT 10000;
```

### Environment

(please complete the following information):

- browser type and version: `Firefox 120.0.1`
- superset version: `2.1.0`
- python version: `3.10.12`
- node.js version: `18.17.1`
- any feature flags active: No

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment] 2024-04-18 21:16
Closing this since we no longer support Superset 2.x. If you can reproduce this in 3.1 or 4.0, we're more than happy to reopen it.

**Closed by rusackas** 2024-04-18 21:16 UTC
Labels: data:connect:pinot
