### ISSUE TITLE
Missing dataset The dataset associated with this chart no longer exists in create filter box chart

### ISSUE THREAD

**Issue by wugeer** [apache/superset#20624] opened 2022-07-06 14:01 UTC
I use the CLIENT_CACHE feature by setting CLIENT_CACHE to true in superset/config.py, when I choose a table of examples database and choose filter box to create a chart,  the result page comes with following error message: 
Missing dataset The dataset associated with this chart no longer exists in create filter box chart

# How to reproduce the bug
   1. Go to Charts -> + CHART
   2. choose a table and choose filter box chart
   3. Press CREATE NEW CHART

# Expected results

The create chart should run without any problem

# Actual results

Missing dataset
The dataset associated with this chart no longer exists

1st image
![图片](https://user-images.githubusercontent.com/20339490/177561479-f8ffe955-b1a6-4849-bc0b-be94e700c3a1.png)
2nd imag
![图片](https://user-images.githubusercontent.com/20339490/177561552-0508a702-045b-438c-9c27-1ee17de269fe.png)

# Environment
(please complete the following information):
   + browser type and version: Google Chrome Version  103.0.5060.53 (Official Build) (x86_64)
   + superset version: 1.5
   + python version: 3.8.13
   + node.js version:  node 16.15.0
   + any feature flags active: CLIENT_CACHE

Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

Additional context

Already present in the newest versions of Superset

Is there any configuration that I am might missing here? Is this fixable? Thanks in advance for any help and comment.

**Comment by dharley-atlastix** [comment] 2022-11-02 04:15
I've noticed the same error as above with Filter box and most other legacy charts such as World Maps. Trace below seems to indicate security permission issue. I was using an unmodified admin account. RBAC is disabled.

```
Nov 02 03:58:59 ubuntu-focal superset[717]: SupersetSecurityException
Nov 02 03:58:59 ubuntu-focal superset[717]: Traceback (most recent call last):
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 483, in check_datasource_perms
Nov 02 03:58:59 ubuntu-focal superset[717]:     datasource_id, datasource_type = get_datasource_info(
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 275, in get_datasource_info
Nov 02 03:58:59 ubuntu-focal superset[717]:     raise SupersetException(
Nov 02 03:58:59 ubuntu-focal superset[717]: superset.exceptions.SupersetException: The dataset associated with this chart no longer exists
Nov 02 03:58:59 ubuntu-focal superset[717]: The above exception was the direct cause of the following exception:
Nov 02 03:58:59 ubuntu-focal superset[717]: Traceback (most recent call last):
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/views/base.py", line 212, in wraps
Nov 02 03:58:59 ubuntu-focal superset[717]:     return f(self, *args, **kwargs)
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/utils/log.py", line 244, in wrapper
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/utils/log.py", line 244, in wrapper
Nov 02 03:58:59 ubuntu-focal superset[717]:     value = f(*args, **kwargs)
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/utils/cache.py", line 226, in wrapper
Nov 02 03:58:59 ubuntu-focal superset[717]:     response = f(*args, **kwargs)
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 440, in wrapper
Nov 02 03:58:59 ubuntu-focal superset[717]:     check_perms(*args, **kwargs)
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 487, in check_datasource_perms
Nov 02 03:58:59 ubuntu-focal superset[717]:     raise SupersetSecurityException(
Nov 02 03:58:59 ubuntu-focal superset[717]: superset.exceptions.SupersetSecurityException: The dataset associated with this chart no longer exists
Nov 02 03:58:59 ubuntu-focal superset[717]: 2022-11-02 03:58:59,088:WARNING:superset.views.base:SupersetSecurityException
Nov 02 03:58:59 ubuntu-focal superset[717]: Traceback (most recent call last):
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 483, in check_datasource_perms
Nov 02 03:58:59 ubuntu-focal superset[717]:     datasource_id, datasource_type = get_datasource_info(
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 275, in get_datasource_info
Nov 02 03:58:59 ubuntu-focal superset[717]:     raise SupersetException(
Nov 02 03:58:59 ubuntu-focal superset[717]: superset.exceptions.SupersetException: The dataset associated with this chart no longer exists
Nov 02 03:58:59 ubuntu-focal superset[717]: The above exception was the direct cause of the following exception:
Nov 02 03:58:59 ubuntu-focal superset[717]: Traceback (most recent call last):
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/views/base.py", line 212, in wraps
Nov 02 03:58:59 ubuntu-focal superset[717]:     return f(self, *args, **kwargs)
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/utils/log.py", line 244, in wrapper
Nov 02 03:58:59 ubuntu-focal superset[717]:     value = f(*args, **kwargs)
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/utils/cache.py", line 226, in wrapper
Nov 02 03:58:59 ubuntu-focal superset[717]:     response = f(*args, **kwargs)
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 440, in wrapper
Nov 02 03:58:59 ubuntu-focal superset[717]:     check_perms(*args, **kwargs)
Nov 02 03:58:59 ubuntu-focal superset[717]:   File "/usr/share/superset/venv/lib/python3.8/site-packages/superset/views/utils.py", line 487, in check_datasource_perms
Nov 02 03:58:59 ubuntu-focal superset[717]:     raise SupersetSecurityException(
Nov 02 03:58:59 ubuntu-focal superset[717]: superset.exceptions.SupersetSecurityException: The dataset associated with this chart no longer exists
```

**Comment by jtotoole** [comment] 2023-03-22 22:33
seeing the same issue when attempting to create mapbox-based charts

**Comment by vddenis** [comment] 2023-07-17 17:58
I have the same issue. Do not close this topic.

**Comment by alwyngo** [comment] 2023-12-25 04:10
How to solve the same problem as this？

**Comment by alwyngo** [comment] 2023-12-25 05:12
> How to solve the same problem as this？
config the FEATURE_FLAGS 
`CLIENT_CACHE: Fasle `
It works for me

**Comment by rusackas** [comment] 2024-02-23 18:39
Not sure the current status of this, but it seems to have gone silent. Hopefully it's fixed. The original issue involved Filter Box, which is deprecated, and will be gone in 4.0. If this is still an issue in 3.x, please open a new issue with updated context and a reproducible example. Thanks!

**Closed by rusackas** 2024-02-23 18:39 UTC
