### ISSUE TITLE
Does this strip_comments have to be True by default?

### ISSUE THREAD

**Issue by singhrajk** [apache/superset#22459] opened 2022-12-19 19:28 UTC
https://github.com/apache/superset/blob/858796b98fdeb55f21d913c59d42c36507601eb5/superset/sql_lab.py#L416

**Comment by rusackas** [comment] 2023-01-04 22:32
Closing this since it's not a bug, per se, but I believe the answer is "yes" this is considered to be the sensible default. 

If you feel that should not be the case, let us know here, or we can it that up in a [Discussion](https://github.com/apache/superset/discussions) or on [Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-1jp6hjzrq-H0PlFtToyLWuPiJDuRWCNw). 

I'll also CC @betodealmeida here for good measure, since they wrote the line in question.

Thanks!

**Closed by rusackas** 2023-01-04 22:32 UTC

**Comment by singhrajk** [comment] 2023-01-12 11:31
The link to join slack community is not working.

![image](https://user-images.githubusercontent.com/36836428/212055870-d3572daa-a26c-4308-ac15-e8c1a68b743b.png)

**Comment by rusackas** [comment] 2023-01-12 22:06
Apologies. Those links expire frequently. We're going to try keeping this link current from here on out:
http://bit.ly/join-superset-slack
