### ISSUE TITLE
[explore] Run button will disappear when browser size change

### ISSUE THREAD

**Issue by jinghua-qa** [apache/superset#15970] opened 2021-07-30 08:23 UTC
In explore, Run button will disappear when browser size change

### Expected results

Run button stay when window size change

### Actual results

Run button disappear when window size change

#### Screenshots

https://user-images.githubusercontent.com/81597121/127624054-a859ed30-88d1-4948-8257-f4781cc59921.mov

#### How to reproduce the bug

1. open explore and select explore function to run
2. do no click run button and change window size
3. See error

### Environment

(please complete the following information):

- superset version: `master`
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by Shazad-khan** [comment] 2023-03-15 10:54
![image](https://user-images.githubusercontent.com/100838455/225288279-2ec78e57-ccd4-4268-bbb6-b26d763a9f3f.png)


The issue is resolved in the recent release as now we don't have run button to run the query directly we can click on update chart to see the latest changes

**Closed** 2024-02-13 21:20 UTC
Labels: #bug, preset:QA
