### ISSUE TITLE
[SIP-63] Incorporating other map sources in Superset

### ISSUE THREAD

**Issue by gk1089** [apache/superset#9281] opened 2020-03-11 11:27 UTC
### Motivation

Superset currently uses MapBox to display maps which has its own limitations. There are other map sources available as Web Map Services (WMS). For example, Open Street Maps (OSM) that can be called upon using many js libraries like Leaflet or OpenLayers. This would pave way for more GIS functionalities in SuperSet in true open source spirit.

Later, the same could also apply to the deck,gl visualizations that simply use mapbox for its simplicity.

### Proposed Change

Module can be created that permit adding WMS services during the creation of charts. Other features may include:
1. Adding multiple layers and providing facility to turn them on/off.
2. Permitting clicking on features (points) to show a popup with more data/links on the map itself.

### New or Changed Public Interfaces

Same as described above.
### New dependencies
Leaflet (https://www.npmjs.com/package/leaflet) and OpenLayers (https://www.npmjs.com/package/ol)

### Migration Plan and Compatibility

Should work with existing setup.

### Rejected Alternatives
I am proposing considering the open data sources right now. So, no Google/Bing maps etc.

Describe alternative approaches that were considered and rejected.

I would like to attempt this but I am really at a loss for where to begin with implementing it. I have seen discussions about new chart types here and although the documentation is old regarding that, some of the issue threads provide pointers in the right direction.

I intend this thread to be something of the same kind where some of the developers may point us to the right section of the code where we can begin exploring and implementing open source mapping visualizations.

I hope the developers see some merit in it.

**Comment by dharamgajera** [comment] 2020-07-06 11:39
Any Update on this ?

**Comment by juen1jp** [comment] 2020-07-15 20:08
I would be interested in engaging with the community about this. MapBox is a non-starter for us and a solid block for us to use Superset. Are there plans to implement support for open mapping projects? We would be interested in helping to get open mapping projects added so the package is a truly open source solution.

**Comment by villebro** [comment] 2020-07-15 20:20
@juen1jp I'm sure a contribution would be warmly welcomed by the community. As it will probably be a major change, I would propose opening a SIP (Superset Improvement Proposal) to make sure the community is able to chime with ideas and concerns prior to any major development work taking place.

**Comment by gk1089** [comment] 2020-07-20 06:53
> 
> 
> @juen1jp I'm sure a contribution would be warmly welcomed by the community. As it will probably be a major change, I would propose opening a SIP (Superset Improvement Proposal) to make sure the community is able to chime with ideas and concerns prior to any major development work taking place.

@villebro I opened this thread as a SIP itself. Are you proposing a fresh SIP be opened? 

I just need a few indicators regarding what part of the code to look into, as in, the code files that make the mapbox magic happen. Just searching with 'mapbox' keyword in the code files has not given me much to go upon.

**Comment by villebro** [comment] 2020-07-20 07:05
@gk1089 my bad, I didn't notice this was in fact opened as a SIP as it wasn't indicated in the title. The title should be prefixed with `[SIP-XX]` where XX is the next available unused SIP id. I believe `SIP-50` is the next available id.

I assume most mapping systems require some for of token. This should be added to `config.py` so that it can be defined in the local `superset_config.py`. Currently the mapbox token is returned by `viz.py` to the relevant visualizations; I believe the plan is to return this type of data in the bootstrap payload in the future. The committers can surely help with the details once we get that far. I propose reaching out on Slack, e.g. the `#visualization_plugins` channel.

**Comment by gk1089** [comment] 2020-07-20 07:46
@villebro Thanks for your response. As far as I understand it, tokens are compulsory only for metered map services like MapBox, ESRI, Bing, Google map services etc. For the open map services like Open Street Map (OSM), this is not a requirement and maps can be accessed directly by including the corresponding (Web Map Service) WMS URL through some js libraries like Leaflet or OpenLayers.

For example, I found the WMS URL (http://maps.heigit.org/osm-wms/service?REQUEST=GetCapabilities&SERVICE=WMS) for a world map on the info section of https://www.osm-wms.de/, which in turn was found on the OSM page on WMS (https://wiki.openstreetmap.org/wiki/WMS). I can use this WMS URL to show a map in my own page and the corresponding Leaflet/OpenLayers library will provide me tools to navigate on the map, show popups, make measurements etc.

It would be great to have the same control through a custom Superset visualization. 

I shall try to join the slack and discuss it there and I request @juen1jp to chime in with his ideas. Meanwhile, may I request you to tag contributors who may have worked on the mapbox module in the past to share their take on this in this thread.

**Comment by gk1089** [comment] 2020-07-20 07:50
@villebro May I also request for this thread to be marked as active. It is currently marked as 'closed' by the activity bot.

**Comment by villebro** [comment] 2020-07-20 07:50
In case there is no need for a token, then this will be quite straight forward, and should not be any different from any other new viz plugin. Please see the [Hello World blog post](https://preset.io/blog/2020-07-02-hello-world/) on how to get started of you haven't already.

**Comment by gk1089** [comment] 2020-07-20 07:54
> In case there is no need for a token, then this will be quite straight forward, and should not be any different from any other new viz plugin. Please see the [Hello World blog post](https://preset.io/blog/2020-07-02-hello-world/) on how to get started of you haven't already.

Thanks! I was not aware of this post. 

While I have a go at it, for the sake of reusing the code is it possible to point to the files which deal with the existing MapBox code?

**Comment by roaur** [comment] 2020-08-24 18:42
That sounds fair. Between the [Hello World blog post](https://preset.io/blog/2020-07-02-hello-world/l) (thanks a lot, @villebro) and [ECharts examples](https://echarts.apache.org/en/download-extension.html) could a JS newbie implement the leaflet EChart example into Superset? Could you point me in other places you'd look if you were to implement such a chart into Superset?

**Comment by juen1jp** [comment] 2020-08-26 16:06
Keeping the alternate plugins outside seems like the smart way to go for me too. Perhaps we should instead close this and open another SIP focused on formalizing the plugin ecosystem (although I am assuming that is already on the roadmap)

**Comment by MihailGershkovich** [comment] 2020-12-29 14:35
we'll start to investigate those questions soon. Probably there will be some stuff that we can provide.

**Comment by sfkeller** [comment] 2021-04-10 22:23
> Keeping the alternate plugins outside seems like the smart way to go for me too. Perhaps we should instead close this 

I'd propose not to close this and to get the focus back on this SIP, which is incorporating another map library instead of Mapbox GL JS (which in turn accesses a freely accessible base map server).

Specifically it's about replacing "deckl.gl Scatterplot".

I would not take WMS as service protocol but stick to the raster tiles (XYZ) scheme, like Mapbox base maps - now based on free tile servers, like http://openwhatevermap.xyz shows. 

And to clarify this: You only need to exchange the Mapbox GL JS map library with Leaflet. You don't necessarily need to host the map tiles yourself.

mistercrunch commented:
> We recently made the resolution to use ECharts as our primary visualization library #10418
> 
> Do the maps in ECharts depend on mapbox?

There are about four map types at https://echarts.apache.org/en/download-extension.html , among them Mapbox - and echarts-leaflet.

echarts-leaflet is the one we want: https://github.com/gnijuohz/echarts-leaflet

Instead of a map token this would need a urlTemplate like  'https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png'

So: What's left to be done in order agree on this and to implement this?

**Comment by rusackas** [comment] 2021-04-21 21:02
Due to a numbering snafu, there was[ another SIP that was numbered SIP-53](https://github.com/apache/superset/issues/10894). While this issue is older, and really had the right to that number, the other one has already been voted through, so it should not be renumbered. I'll move this one to the next available SIP number, which is SIP-63. Sorry for the extra layer of awkwardness.

**Comment by igorwiese** [comment] 2022-08-18 13:49
Hi @villebro, How is the progress on this SIP? Is it approved? Is anyone working on this? Thank you! :)

**Comment by Doctor-Who** [comment] 2022-11-16 14:32
Maplibre integration or DeckGL enhancement as a true opensource project should be considered. 
Geographic preview and live maps are really useful on many dashboard made with superset.

**Comment by rusackas** [comment] 2022-12-08 18:28
This sip has not been put up for a [VOTE] thread on the dev@ mailing list yet. Is there any intent to carry that forward? I'm not sure the SIP is actually needed, since this is effectively about building additional plugins. We can close this out if the author and others agree.

**Comment by Stephane-Thales** [comment] 2022-12-09 00:24
Can this be kept alive until a solution is found ? Can the it be put to a vote ? Or is there a place to link-it for additional plugins request ?

**Comment by rusackas** [comment] 2022-12-09 00:31
Well, I have a few thoughts on the matter, personally, but curious to hear the opinions of others (including @gk1089)
* Is the intent here to add _additional_ mapping plugins? If so, I don't think a SIP is required.
* Is the intent here to _replace_ Mapbox? This is more contentious, and would need a SIP.
* If the idea is to add additional plugins, but the author doesn't have the intent to contribute them directly, this should probably be filed under an "Ideas" thread in the repo's Discussions.
* If the idea is that someone's taking this project under their wing, we greatly look forward to a PR, and would be happy to help with any tactical questions along the way either on the PR itself or in the #contributing channel of the Slack workspace.

Wondering if anyone (dis)agrees with the above, and we can decide what to do with the SIP status accordingly.

**Comment by villebro** [comment] 2022-12-09 07:13
I agree with @rusackas on the bullet list. The way I see it, I also agree it'd be great to add support for additional map sources. IMO we should have a `MAP_SOURCES` or similar config into which one could add entries for map sources that geospatial charts could use. Something like

```python
class MapSource(str, Enum):
    MAPBOX = "mapbox"
    LEAFLET = "leaflet"
    OPEN_LAYERS = "open_layers"
    ....


MAP_SOURCES: Dict[MapSource, Dict[str, Any]] = {
    MapSource.MAPBOX: {
        <mapbox params go here...>
    },
    MapSource.LEAFLET: {
        <leaflet params go here...>
    }
}
```
This info would then be passed along to the frontend in bootstrap data, and viz plugins would then have a dropdown where the end user could choose which of the enabled map sources they want to use for a specific geospatial chart. And if the config is empty, geospatial viz' would be completely disabled.

**Comment by gk1089** [comment] 2022-12-09 11:51
I am happy that this is still being considered. The following has been my reasoning behind initiating this issue and I think it still stands:

1. The mapbox chart extension, while very easy to use, is not in the true spirit of open source. It needs registration and requires a key. It does not support overlaying other layers that a user might find more relevant to their use case.
2. Overlaying WMS services as layers of choice can be a powerful way of customized representation. This is supported by many popular BI tools and should be a part of default charts and not left for the users to develop from scratch.
3. There are pretty straightforward and widely used JS libraries that make embedding a map possible, like Leaflet and OpenLayers. 
4. With my limited exposure to development for Superset, I think creating a chart for maps is more involved than other kinds of charts. Even the superset suggested charting library ECharts does not have support for WMS layers so there is even less building blocks to work upon.

I stand behind the suggestions of @rusackas and @villebro though to begin with even the option to add a WMS layer would be a great start since these can be easily published with customizations using widely available open source tools.

I have found Superset very useful and am willing to take up the challenge with some students that come work with me periodically. But the main challenges I face are a very restrictive internet environment that prohibits the use of many live discussions platforms. And even more than that, the lack of authoritative and updated information regarding starting from ground up and reaching the latest development build. If someone can give a focused push in getting us running, I am sure we can come up with something useful in the coming six months.

Cheers!

**Comment by rusackas** [comment] 2022-12-09 23:18
@gk1089 I think if we're not _replacing_ the mapbox plugin, but either adding new ones, or (better yet) making the current one more extensible as @villebro suggests, we can probably close this as an issue and cancel the SIP, and instead convert this to an "Ideas" discussion. Let me know if you have any objection.

Also, I'm happy (as is Ville, I'm sure) to find a way to collab with you and your students on this - are you able to join the Slack community or a Zoom call, when the time is right? If not, please feel free to [email me](mailto:rusackas@apache.org) and we'll sort something out.

**Comment by Stephane-Thales** [comment] 2023-02-09 08:37
Hi @rusackas and @gk1089 just checking in. Any news regarding this option ?

**Comment by gk1089** [comment] 2023-02-10 05:42
> Hi @rusackas and @gk1089 just checking in. Any news regarding this feature ?

I am working with my students and getting them up to speed is taking time. I hope to have some positive outcome in the next 3 months. I will definitely reach out to @rusackas & @villebro when I get stuck eventually.

**Comment by Doctor-Who** [comment] 2023-02-10 10:14
Many thanks for your work @gk1089 perhaps should consider maplibre instead using mapbox ? no key required, same powerfull features, maplibre is growing fast.

**Comment by Stephane-Thales** [comment] 2023-02-10 10:55
I've seen that Apache has took over Echarts, that contain lots of geo visualisation. I can't find if they are using Mapbox or another paying provider it look like it's fully community based ? So it's also an option ?

**Comment by villebro** [comment] 2023-02-10 10:57
@Stephane-Thales I suggest you check out this discussion: #21758

**Comment by Stephane-Thales** [comment] 2023-02-10 11:50
> @Stephane-Thales I suggest you check out this discussion: #21758

Thanks, interesting and there are perhaps some overlaps, but that's not exactly what we are discussing here.

**Comment by w4rell** [comment] 2023-05-22 12:10
Hi there,

Any news @gk1089 ? It would be awesome to be able to put maplibre links or have the opportunity to change the map tiles provider ;)

Thanks,

**Comment by Doctor-Who** [comment] 2023-05-22 13:36
It seems there is a plugin with openlayers but don't know how to install it :persevere: 
https://www.npmjs.com/package/superset-ol-plugin

**Comment by Stephane-Thales** [comment] 2023-05-23 00:13
> It seems there is a plugin with openlayers but don't know how to install it 😣 https://www.npmjs.com/package/superset-ol-plugin

Hi @Doctor-Who it's not part of the core superset so indeed it looks difficult to setup. You need to recompile superset if I understood correctly. Also, there is no descriptions of the features.

**Comment by jansule** [comment] 2023-06-14 14:00
> It seems there is a plugin with openlayers but don't know how to install it persevere
https://www.npmjs.com/package/superset-ol-plugin

I am currently working on moving the openlayers plugin to the core. I just have to fix some build issues, but I am sure that I will be able to open a first PR soon.

**Comment by w4rell** [comment] 2023-06-14 18:46
> > It seems there is a plugin with openlayers but don't know how to install it persevere
> > https://www.npmjs.com/package/superset-ol-plugin
> 
> I am currently working on moving the openlayers plugin to the core. I just have to fix some build issues, but I am sure that I will be able to open a first PR soon.

That's a really good news! Thanks for your dedication!

**Comment by Stephane-Thales** [comment] 2023-06-15 00:09
> > It seems there is a plugin with openlayers but don't know how to install it persevere
> > https://www.npmjs.com/package/superset-ol-plugin
> 
> I am currently working on moving the openlayers plugin to the core. I just have to fix some build issues, but I am sure that I will be able to open a first PR soon.

Thanks ! keep us posted here.

**Comment by Doctor-Who** [comment] 2023-06-16 10:49
Many thanks for you hard work !

**Comment by kashifjavedaddo** [comment] 2023-09-21 14:01
@jansule, Can you please update on the build issues regarding superset-ol-plugin. Have they been fixed? 

I have followed these steps so far:

cd /opt/superset/superset-frontend
nvm use 16.19.1
npm i superset-ol-plugin

_npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: superset@0.0.0-dev
npm ERR! Found: @ant-design/icons@5.2.6
npm ERR! node_modules/@ant-design/icons
npm ERR!   @ant-design/icons@"^5.0.1" from the root project
npm ERR!   peer @ant-design/icons@"^5.0.1" from @superset-ui/chart-controls@0.18.25
npm ERR!   packages/superset-ui-chart-controls
npm ERR!     @superset-ui/chart-controls@0.18.25
npm ERR!     node_modules/@superset-ui/chart-controls
npm ERR!       @superset-ui/chart-controls@"0.18.25" from @superset-ui/legacy-plugin-chart-time-table@0.18.25
npm ERR!       packages/superset-ui-demo/node_modules/@superset-ui/legacy-plugin-chart-time-table
npm ERR!         peer @superset-ui/legacy-plugin-chart-time-table@"*" from @superset-ui/demo@0.18.25
npm ERR!         packages/superset-ui-demo
npm ERR!       26 more (@superset-ui/legacy-plugin-chart-time-table, ...)
npm ERR!   1 more (@superset-ui/plugin-chart-pivot-table)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @ant-design/icons@"^4.2.2" from superset-ol-plugin@0.6.0
npm ERR! node_modules/superset-ol-plugin
npm ERR!   superset-ol-plugin@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /home/asupset/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/asupset/.npm/_logs/2023-09-21T13_57_33_253Z-debug-0.log__

Please note that I also tried with npm i superset-ol-plugin -- force and npm i superset-ol-plugin --legacy-peer-deps and was able to proceed to next step i.e. npm cli and again had to do npm cli -- force but after that npi run build keeps giving errors.

Looking forward to your reply.

**Comment by rusackas** [comment] 2023-10-02 22:01
This SIP has not been brought up for a vote, and the thread is a bit all over the map - I'm not quite sure the scope of the standing proposal that we'd be voting on. Does anyone feel like recapitulating the thread/proposal and calling a vote, or should we abandon this and start a new proposal when people have availability to pursue the renewed effort?

**Comment by Stephane-Thales** [comment] 2023-10-03 01:26
> This SIP has not been brought up for a vote, and the thread is a bit all over the map - I'm not quite sure the scope of the standing proposal that we'd be voting on. Does anyone feel like recapitulating the thread/proposal and calling a vote, or should we abandon this and start a new proposal when people have availability to pursue the renewed effort?

Hi @rusackas , for me the initial description of the issue is still relevant, i don't think the thread changed the scope. Can we reuse it ?

**Comment by jansule** [comment] 2023-11-06 10:08
A first PR for supporting cartodiagrams and external map sources (WMS, WFS, XYZ) was created: https://github.com/apache/superset/pull/25869

**Comment by rusackas** [comment] 2024-01-03 17:15
Looking forward to merging that cartodiagram! In the meantime, this SIP itself has gone dormant in terms of official consensus activity (proposed for Discussion in 2021 with no replies since). The original author doesn't seem to be here to put it to a vote. According to a recently voted process, we'll close this out as stale. If someone wishes to rekindle this effort, I think we should take the most important bits into a fresh SIP and start the process anew.

**Closed by rusackas** 2024-01-03 17:15 UTC
Labels: sip, .pinned, viz:dynamic-plugins, viz:charts:map

**Comment by d-saikrishna** [comment] 2024-08-30 06:09
This link suggests a way to replace mapbox basemaps with that of OSM. But I'm unable to find that code snipper in the superset_config.py file. 

https://www.restack.io/docs/superset-knowledge-superset-map-visualization-guide
