### ISSUE TITLE
issue while getting parameter value from url  in superset 1.3

### ISSUE THREAD

**Issue by suraj-12** [apache/superset#17317] opened 2021-11-02 07:42 UTC
I am using superset version 1.3 and not able to fetch parameter value from url which was working earlier in 0.3 version.

i am using url_param. 

query example ex:- CostCenter is not null and CostCenter  IN ({{url_param('costCenter')}})

**Comment by villebro** [comment] 2021-11-02 08:06
I am unable to reproduce both on 1.3.2 and master branch. I created a datasource with the following query:
```sql
select '{{ url_param('abc') }}' as qwerty
```
I then created a chart+dashboard with it and when calling the dashboard with the url param `abc=123` I am able to successfully render the following view:

![image](https://user-images.githubusercontent.com/33317356/139808748-6d954a02-cafb-45f5-9c2c-299253997fb6.png)

**Comment by suraj-12** [comment] 2021-11-08 05:34
not working when using elasticsearch as datasource and also wildcard is not working while creating table which was working in 0.38 version of superset.

**Comment by rusackas** [comment] 2023-01-06 21:35
I'm going to close this out since (a) it sounded like it wasn't reproducible, (b) if it was reproducible, that was on a no-longer-supported version of Superset, and (c) the issue hasn't seen any life for over a year. If anyone sees this behavior on current (1.5.x or 2.0.x) versions, let's add some more details to provide a more reliable reproduction flow in either this issue, or a new one. Thank you!!!

**Closed** 2023-01-06 21:35 UTC
Labels: #bug:cant-reproduce, validation:required, data:connect:elasticsearch, #bug
