### ISSUE TITLE
[Bug] Unable to edit mail list of existing alert & reports

### ISSUE THREAD

**Issue by pankajsoni22** [apache/superset#28709] opened 2024-05-27 04:32 UTC
### Bug description

When we create alert or report and want to sent to receivers using their mail id, it is working fine, we can create alerts and report successfully. 

BUT

If we want to add more recipients and try to edit and add more mail to alerts or reports it is not possible. looks like after saving alert/report the mail list edit area becomes read-only. 

### How to reproduce the bug

1. Go To "Alerts & Reports"
2. Click on edit button of some already existing Alert/Report
3. Try to remove or add mail, you won't be able to do so.

### Superset version

4.0.1

### Python version

I don't know

### Node version

I don't know

### Browser

Chrome

### Additional context

I'm using superset 4.0.1-dev version

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by aibunny** [comment] 2024-05-27 08:48
I also experienced a similar issue it looks like a frontend issue since the Add button is not activated when I have satified all the requirements to create an alert.
<img width="1512" alt="Untitled" src="https://github.com/apache/superset/assets/98146814/e73b221e-6d9f-4328-8962-73a9182920c6">

**Comment by aibunny** [comment] 2024-05-27 08:50
@pankajsoni22 could share the configs you used for the email alerts I am not able to setup mine I keep getting `report schedule refusing to compute`

**Comment by mitchgreen** [comment] 2024-05-29 06:04
I too am having this same issue

**Comment by sfirke** [comment] 2024-05-29 19:51
I believe this is a duplicate of https://github.com/apache/superset/issues/28149 which was fixed in https://github.com/apache/superset/pull/28409. The next release -- either 4.1.0 or 4.0.2 -- should have this fix incorporated.

If you believe this is different than the issue I linked, please feel free to comment and I'll reopen.

**Closed by sfirke** 2024-05-29 19:51 UTC
Labels: alert-reports
