### ISSUE TITLE
Issue while uploading csv/excel file in Apache Superset

### ISSUE THREAD

**Issue by GaryMam** [apache/superset#15708] opened 2021-07-15 14:41 UTC
[Test Excel.xlsx](https://github.com/apache/superset/files/6823868/Test.Excel.xlsx)
[Test Data.csv](https://github.com/apache/superset/files/6823869/Test.Data.csv)

Hi Team,

I am very new to Apache superset and trying to learn basic functionality which critical to learn for upcoming opportunity in my project but I am getting below error while using CSV or Excel using a datasource and getting below error :

Error :

{"errors": [{"message": "can only concatenate str (not \"list\") to str", "error_type": "GENERIC_BACKEND_ERROR", "level": "error", "extra": {"issue_codes": [{"code": 1011, "message": "Issue 1011 - Superset encountered an unexpected error."}]}}]}

Also I am getting this ERROR when I select "Upload a CSV option": Failed to fetch schemas allowed for csv upload in this database! Please contact your Superset Admin!

**Fix I tried :** Superset has its own DB name "examples" which is postgresql and I enabled CSV upload from there. Also its not even uploading very clean excel with just 5 to 6 records. I have attached sample csv and excel file for reference.

 I have installed Apache Superset on my MAC using below steps :

1.Mac OSX

Install Docker for Mac, which includes the Docker engine and a recent version of docker-compose out of the box.

Once you have Docker for Mac installed, open up the preferences pane for Docker, go to the "Resources" section and increase the allocated memory to 6GB. With only the 2GB of RAM allocated by default, Superset will fail to start.

2. I2. Clone Superset's Github repository(Using GitHub)

Clone Superset's repo in your terminal with the following command:

$ git clone https://github.com/apache/superset.git
Once that command completes successfully, you should see a new superset folder in your current directory.

Any quick help will be highly appreciated!!!!

Warm Regards,
Gary
email id : gmamgain77@gmail.com

**Comment by fuomag9** [comment] 2021-07-15 16:19
Duplicate of #15692

**Comment by junlincc** [comment] 2021-07-15 19:12
looking into it.

**Comment by GaryMam** [comment] 2021-07-15 19:32
Thank you @junlincc. I really need to get this fix by today. I really appreciate your help!!!

**Comment by yousoph** [comment] 2022-03-04 20:19
Closing since the duplicate ticket https://github.com/apache/superset/issues/15692 is closed as resolved

**Closed by yousoph** 2022-03-04 20:19 UTC
Labels: validation:required, data:csv
