### ISSUE TITLE
Add To Dashboard Modal dropdown is hidden

### ISSUE THREAD

**Issue by eugeniamz** [apache/superset#12521] opened 2021-01-14 14:05 UTC
When Saving a Chart the option to ADD TO DASHBOARD is hidden. 

![2021-01-14_09-01-04 (1)](https://user-images.githubusercontent.com/58375897/104600598-33ffc900-5647-11eb-8073-4fcdf84663e3.gif)

### Expected results

To show the dropdown list.

### Actual results

Shows only 1 dashboard and need to use scroll bar to see more 
#### Screenshots

In an instance with many dashboards available 
1. Go to any chart 
2. Click on save
3. Scroll down to ADD TO DASHBOARD 

### Environment

- superset version: 01/13/2021 release 
- 
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment] 2021-01-14 15:35
this is issue is duplicate of https://github.com/apache/superset/issues/12469
and had been address in another PR.
@eugeniamz could we double check the issue page before adding the "rush!" label? 🙏

**Comment by junlincc** [comment] 2021-01-14 15:42
@eugeniamz removing "rush!" and closing issue

**Closed by junlincc** 2021-01-14 15:42 UTC
Labels: #bug, preset-io
