### ISSUE TITLE
superset-frontend not working with latest node version(18)

### ISSUE THREAD

**Issue by tejaskatariya** [apache/superset#22657] opened 2023-01-10 07:26 UTC
Github Discussions is our new home for discussing features and improvements!

https://github.com/apache/superset/discussions/categories/ideas

We'd like to keep Github Issues focuses on bugs and SIP's (Superset Improvement Proposals)!

Please note that feature requests opened as Github Issues will be moved to Discussions.

**Comment by rusackas** [comment] 2023-01-13 17:08
@lilykuang were you the one looking at a Node upgrade, or was it someone else? Please feel free to redirect the assignment.

**Comment by csouchet** [comment] 2023-10-17 15:50
@rusackas Hi 👋🏻  
I'm also interested for superset-frontend in node 18 😊  
  
ℹ️ For your information, node 16 has been EOL since September 11th, 2023: https://nodejs.org/fr/blog/announcements/nodejs16-eol

**Comment by rusackas** [comment] 2024-03-19 22:59
Closing this since it's not a bug, and has generally gone silent. That said, there is a PR open that we can merge after the 4.0 release gets out the door:

https://github.com/apache/superset/pull/27198

**Closed by rusackas** 2024-03-19 22:59 UTC
