### ISSUE TITLE
Inconsistency in package dependency

### ISSUE THREAD

**Issue by sumitra19jha** [apache/superset#17966] opened 2022-01-07 15:41 UTC
#### How to reproduce the bug

1. Clone Superset repo on Mac
2. Install Packages
3. Run superset run -p 8088 --with-threads --reload --debugger
4. See an error on the screen

### Expected results

The complete dashboard should appear with the necessary example dataset

### Actual results

Dashboard doesn't appear and the following screen in the below image appears on screen

#### Screenshots

![82610735-87874900-9b84-11ea-98b1-306e7e6c93f4](https://user-images.githubusercontent.com/35868598/149528054-a9474eb4-77f3-445e-bb9c-c1cab190f528.png)

### Environment
- browser type and version: Chrome
- superset version: `superset  current version`
- python version: `python --3.8
- node.js version: `node -16.12.1`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ Y] I have checked the superset logs for python stack traces and included them here as text if there are any.
- [ Y] I have reproduced the issue with at least the latest released version of the superset.
- [ Y] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Same packages of different versions are utilised in the superset main folder and superset-frontend folder. This issue needs to be fixed.

**Comment by geido** [comment] 2022-01-10 16:27
Hello @sumitra19jha thanks for submitting this issue. Would you mind providing more info concerning the error that you are seeing?

**Comment by sumitra19jha** [comment] 2022-01-14 14:07
@geido Snapshot added

**Comment by sumitra19jha** [comment] 2022-01-14 14:27
I have resolved the above issue on my local system by removing package conflicts in the superset-frontend folder. During installation from scratch in order to remove the above error, I have to run `npm install` in a superset-frontend folder and then the dashboard appears. The superset-frontend folder shows logs that the package in the parent folder and one used there don't have the same version.

**Comment by sumitra19jha** [comment] 2022-01-14 14:28
Can I create the PR making sure that common packages across multiple folders have same version?

**Comment by geido** [comment] 2022-01-14 15:33
Hello @sumitra19jha that would be awesome! Are you already in the [Superset Slack](https://join.slack.com/t/apache-superset/shared_invite/zt-uxbh5g36-AISUtHbzOXcu0BIj7kgUaw)? I'd be happy to help you getting your PR reviewed and merged. You can find me there as geido.

**Comment by athul-sn** [comment] 2022-11-21 06:23
Hi @geido  I would like to work on this issue if nobody has already taken it up.
Thanks

**Comment by geido** [comment] 2022-11-21 15:26
> Hi @geido  I would like to work on this issue if nobody has already taken it up.
> Thanks

Are you still able to reproduce this issue? If so, sure you are more than welcome to pick it up and I can help you along the way.

**Comment by rusackas** [comment] 2024-02-13 21:42
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

**Closed by rusackas** 2024-02-13 21:42 UTC
Labels: good first issue, #bug
