### ISSUE TITLE
export to .CSV in embedding superset not working

### ISSUE THREAD

**Issue by baguskna** [apache/superset#21829] opened 2022-10-17 09:44 UTC
Hi, I have successfully embedded the dashboard and we want feature export to .CSV , but it is not working it said

```
Blocked opening 'URL' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.
Blocked form submission to 'URL' because the form's frame is sandboxed and the 'allow-forms' permission is not set.

```
I was able to override the iframe with this way
    
```
    const embed = await embedDashboard({
      id: dashboardId,
      supersetDomain: URL,
      mountPoint: document.querySelector("#superset-id"),
      fetchGuestToken: () => guestToken,
      dashboardUiConfig: {
        hideTitle: true,
        hideChartControls: false,
        hideTab: true,
      },
    });

    const size = await embed.getScrollSize();

    if (size.width !== 0) {
      const iframe = document.querySelector("iframe") as HTMLIFrameElement;
      iframe.setAttribute(
        "sandbox",
        "allow-same-origin allow-scripts allow-presentation allow-downloads allow-forms allow-popups allow-popups-to-escape-sandbox"
      );
    }
    
```
still it returns the same error as I mentioned above, by any chance is there a way we can fix this?

**Comment by fordsworth** [comment] 2022-10-22 06:40
I am getting the same error. I have tried few options but seems like you can't change the frame attributes

**Comment by blue-lm** [comment] 2022-10-31 08:38
I am getting the same error too.. I'll let you know in case I find a resolution

**Comment by blue-lm** [comment] 2022-11-01 08:32
Looks like the issue is in the SuperSetClient.ts file? A hiddenform is created in the code below, I guess we need to add the attributes that were suggested by @baguskna to this hiddenform? Not sure how to do this though:

```
async postForm(url: string, payload: Record<string, any>, target = '_blank') {
    if (url) {
      await this.ensureAuth();
      const hiddenForm = document.createElement('form');
      hiddenForm.action = url;
      hiddenForm.method = 'POST';
      hiddenForm.target = target;
```

**Comment by MMendozaEscalona** [comment] 2022-11-17 08:55
Hello @blue-lm if you put _self instead of _blank and .csv is downloading in the same page and dissapiar allow-popups error, but I still have allow-forms error althought I add it to iframe. I don't understand because in sdk allow-forms is added but after It don't apper and I have to add it...

**Comment by baguskna** [comment] 2022-11-17 09:13
Still not working, we ended up using post message to transfer the .CSV, it is working now

**Comment by prnth22** [comment] 2022-11-17 09:45
> Still not working, we ended up using post message to transfer the .CSV, it is working now

can you please post the code block

**Comment by nytai** [comment] 2022-11-20 07:01
A fix for this would probably be to provide a config for attributes to pass to the iframe.

**Comment by oyasuyuki** [comment] 2022-11-29 03:54
I am faced with the same problem.
I want to download CSV and open a new window from a tag in the table chart.

**Comment by oyasuyuki** [comment] 2022-12-01 08:16
I found the solution(but I don't know if this solution is correct)
The solution is to use `@preset-sdk/embedded` instead of `@superset-ui/embedded-sdk`.
I can download csv and open the new window.

`@superset-ui/embedded-sdk` is old and not updated.
superset-embedded-sdk in the superset repository is updated, but not reflected in the npm package.

**Comment by blue-lm** [comment] 2022-12-16 16:06
> I found the solution(but I don't know if this solution is correct) The solution is to use `@preset-sdk/embedded` instead of `@superset-ui/embedded-sdk`. I can download csv and open the new window.
> 
> `@superset-ui/embedded-sdk` is old and not updated. superset-embedded-sdk in the superset repository is updated, but not reflected in the npm package.

Thank you!! This resolved the issue for me

**Comment by blue-lm** [comment] 2023-01-10 08:26
Unfortunately I just encountered a new issue with this functionality - in the embedded dashboard the export CSV button appears to ignore filtering, or apply it incorrectly. So the table itself shows filtered data as expected, but the export CSV button shows unfiltered data, or at least the filtering appears to be applied incorrectly. I'm using the {{ current_username(add_to_cache_keys=False) }} value as part of filtering. The non-embedded dashboard works correctly. Does anyone know how I make the export CSV filtering work correctly in the embedded dashboard?

**Comment by rusackas** [comment] 2023-01-31 18:48
Related thread on Slack here: https://apache-superset.slack.com/archives/C01EP56QGTS/p1668673732265359

I'm going to close this issue as resolved, since it sounds like the original issue indeed _was_ resolved. If anyone objects to this, we can most certainly revisit. @blue-lm I think it might be worth opening a new issue describing what you're facing (and steps to replicate it) so that we can handle that in a new thread.

Thanks!

**Closed by rusackas** 2023-01-31 18:48 UTC
Labels: #bug

**Comment by duonghuyom** [comment] 2023-02-07 03:42
hi, can anyone help me with this problem ? I have tried to use both @preset-sdk/embedded and @superset-ui/embedded-sdk libs but I still can not see any export function in my embedded dashboard. Much appreciate if anyone have any solution 🙏
<img width="348" alt="Screenshot 2023-02-07 at 10 40 49" src="https://user-images.githubusercontent.com/107016964/217142640-d42fcc30-4c89-4a6b-a029-c93665d57714.png">

**Comment by baguskna** [comment] 2023-02-09 07:35
> hi, can anyone help me with this problem ? I have tried to use both @preset-sdk/embedded and @superset-ui/embedded-sdk libs but I still can not see any export function in my embedded dashboard. Much appreciate if anyone have any solution 🙏 <img alt="Screenshot 2023-02-07 at 10 40 49" width="348" src="https://user-images.githubusercontent.com/107016964/217142640-d42fcc30-4c89-4a6b-a029-c93665d57714.png">

It should be the role setting inside your superset, allow them to be `Downloadable`

**Comment by duonghuyom** [comment] 2023-02-09 07:43
> > hi, can anyone help me with this problem ? I have tried to use both @preset-sdk/embedded and @superset-ui/embedded-sdk libs but I still can not see any export function in my embedded dashboard. Much appreciate if anyone have any solution 🙏 <img alt="Screenshot 2023-02-07 at 10 40 49" width="348" src="https://user-images.githubusercontent.com/107016964/217142640-d42fcc30-4c89-4a6b-a029-c93665d57714.png">
> 
> It should be the role setting inside your superset, allow them to be `Downloadable`

can you show me where to set that ? many thanks

**Comment by baguskna** [comment] 2023-02-09 07:50
> > > hi, can anyone help me with this problem ? I have tried to use both @preset-sdk/embedded and @superset-ui/embedded-sdk libs but I still can not see any export function in my embedded dashboard. Much appreciate if anyone have any solution 🙏 <img alt="Screenshot 2023-02-07 at 10 40 49" width="348" src="https://user-images.githubusercontent.com/107016964/217142640-d42fcc30-4c89-4a6b-a029-c93665d57714.png">
> > 
> > 
> > It should be the role setting inside your superset, allow them to be `Downloadable`
> 
> can you show me where to set that ? i have set the permission 'can csv on Superset' but in my embedded dashboard, it still not display the 'Export CSV' option.

yea, you can try adding `can csv on Superset` in `Permissions`

**Comment by duonghuyom** [comment] 2023-02-09 08:20
> > > > hi, can anyone help me with this problem ? I have tried to use both @preset-sdk/embedded and @superset-ui/embedded-sdk libs but I still can not see any export function in my embedded dashboard. Much appreciate if anyone have any solution 🙏 <img alt="Screenshot 2023-02-07 at 10 40 49" width="348" src="https://user-images.githubusercontent.com/107016964/217142640-d42fcc30-4c89-4a6b-a029-c93665d57714.png">
> > > 
> > > 
> > > It should be the role setting inside your superset, allow them to be `Downloadable`
> > 
> > 
> > can you show me where to set that ? i have set the permission 'can csv on Superset' but in my embedded dashboard, it still not display the 'Export CSV' option.
> 
> Can you check, are you inserting the right role? Mine has these set up in embedded role, not sure if it helps <img alt="Screen Shot 2023-02-09 at 14 53 29" width="589" src="https://user-images.githubusercontent.com/53422369/217750755-7fe71081-6293-48fb-bb22-e96f1b6b9b7d.png">

i have added all the permission relate to csv but it still not display export csv option in my embedded dashboard, do i have to config anything else ?

**Comment by blue-lm** [comment] 2023-03-15 12:03
Hi @duonghuyom , just to be sure: do you have Superset v2.0.0 or higher installed? I believe the CSV export functionality wasn't available in older versions.

**Comment by duonghuyom** [comment] 2023-03-16 02:22
> Hi @duonghuyom , just to be sure: do you have Superset v2.0.0 or higher installed? I believe the CSV export functionality wasn't available in older versions.

I have updated the superset version and now it have the export csv function. Thank you

**Comment by mikkhait** [comment] 2023-08-17 21:25
> 

@duonghuyom, which version are you running right now?

I don't see on my version
<img width="335" alt="CleanShot 2023-08-17 at 14 24 44@2x" src="https://github.com/apache/superset/assets/1232731/516a2a2f-eb4e-46c4-9abc-a89f5e18dac3">
<img width="1159" alt="CleanShot 2023-08-17 at 14 25 14@2x" src="https://github.com/apache/superset/assets/1232731/10af31b2-46ce-467d-a9c6-cd79741d62fb">

**Comment by duonghuyom** [comment] 2023-08-18 10:51
hi @mikkhait, i used version 1.5.3

**Comment by mikkhait** [comment] 2023-10-31 20:53
I still have the same problem with 3.0.1
even with the following set of permissions
![CleanShot 2023-10-31 at 13 52 34@2x](https://github.com/apache/superset/assets/1232731/3162e558-3fe5-49ce-b173-5e9811ee26f7)
my tables do not get the csv export feature for the embedded dashboard. Non-embedded working fine

![CleanShot 2023-10-31 at 13 52 57@2x](https://github.com/apache/superset/assets/1232731/b6bd8236-463d-4b44-9ee4-10fb7436f94c)

**Comment by ikerd** [comment] 2024-05-21 14:30
Same here, using version 4.0.1, table can be exported to csv from superset instance but export menu does not appear, as shown in @mikkhait image.

**Comment by HeribertoAlves** [comment] 2024-05-23 14:03
@ikerd have you set the feature flag ALLOW_FULL_CSV_EXPORT ? I'm using 4.0.1 and no exports options and I want to use "View as Table" and "Drill to Detail"  but it show only "Force Refresh" and "Enter full screen".

**Comment by ikerd** [comment] 2024-05-23 14:55
> @ikerd have you set the feature flag ALLOW_FULL_CSV_EXPORT ? I'm using 4.0.1 and no exports options and I want to use "View as Table" and "Drill to Detail" but it show only "Force Refresh" and "Enter full screen".

@HeribertoAlves as far as I know ALLOW_FULL_CSV_EXPORT is a feature flag used to bypass table pagination on export, it allows using the "Export to Full CSV" or "Export to Full EXCEL" buttons. It does not have anything to do with the fact of the Download menu not appearing.

In our case it has been solved correctly setting the permissions for the GUEST role and not the one of the user used to get the authentication token.

**Comment by HeribertoAlves** [comment] 2024-05-23 17:08
> > @ikerd have you set the feature flag ALLOW_FULL_CSV_EXPORT ? I'm using 4.0.1 and no exports options and I want to use "View as Table" and "Drill to Detail" but it show only "Force Refresh" and "Enter full screen".
> 
> @HeribertoAlves as far as I know ALLOW_FULL_CSV_EXPORT is a feature flag used to bypass table pagination on export, it allows using the "Export to Full CSV" or "Export to Full EXCEL" buttons. It does not have anything to do with the fact of the Download menu not appearing.
> 
> In our case it has been solved correctly setting the permissions for the GUEST role and not the one of the user used to get the authentication token.

Thanks for your reply @ikerd ! 

I set GUEST_ROLE_NAME = "DashboardEmbedded". 
And then set DashboardEmbedded with all the permission mentioned above. But so far is not working. If possible, can you provide then permissions you have set?
