### ISSUE TITLE
Fatal Error when creating DB with hive

### ISSUE THREAD

**Issue by LIN-Yu-Ting** [apache/superset#24031] opened 2023-05-11 22:08 UTC
Hi, I have question on connecting superset with hive server or Apache Spark SQL. 

I have initialized a Spark cluster with hive server which I can already connect with beeline as you can see in the following image.
<img width="1440" alt="截圖 2023-05-12 上午5 51 21" src="https://github.com/apache/superset/assets/62418760/4f1cc246-e5a4-4294-a2d1-dfd5341d6d1d">

I try to first startup a superset instance located at the same instance of spark master node. However, I got a Fatal Error message without any detail information. In the following image, you can see that connection looks good.
<img width="1438" alt="截圖 2023-05-12 上午5 44 13" src="https://github.com/apache/superset/assets/62418760/7d671813-a2c2-47c5-9ccf-f67584a1b7de">

However, when clicking on Connect, you can see that there is a Database Creation Error.
<img width="1440" alt="截圖 2023-05-12 上午5 52 50" src="https://github.com/apache/superset/assets/62418760/df1477f2-804e-42b4-83b8-d1ffeef4ff08">

What does it mean ?

I also attach ERROR message obtained from superset instance.

```
2023-05-11 22:25:08,222:ERROR:flask_appbuilder.api:Object of type bytes is not JSON serializable
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask_appbuilder/api/__init__.py", line 110, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/superset/views/base_api.py", line 122, in wraps
    raise ex
  File "/usr/local/lib/python3.8/dist-packages/superset/views/base_api.py", line 113, in wraps
    duration, response = time_function(f, self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/superset/utils/core.py", line 1586, in time_function
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/superset/utils/log.py", line 266, in wrapper
    value = f(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/superset/views/base_api.py", line 85, in wraps
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/superset/databases/api.py", line 345, in post
    return self.response(201, id=new_model.id, result=item)
  File "/usr/local/lib/python3.8/dist-packages/flask_appbuilder/api/__init__.py", line 769, in response
    _ret_json = jsonify(kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 302, in jsonify
    f"{dumps(data, indent=indent, separators=separators)}\n",
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 132, in dumps
    return _json.dumps(obj, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 51, in default
    return super().default(o)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type bytes is not JSON serializable
```

It seems that even with Database Creation Error, there is still a Database Connection created.
<img width="1439" alt="截圖 2023-05-12 上午6 13 49" src="https://github.com/apache/superset/assets/62418760/ff9fb285-9a2a-468c-b8f1-c1b44217effd">

However, there is error which can not recognize correctly database and table. I try to use dataset function however it only detect database-level item.
<img width="1440" alt="截圖 2023-05-12 上午6 17 49" src="https://github.com/apache/superset/assets/62418760/441ba548-43d3-4f26-a43f-76655afbd4d7">

**Comment by TinTin-DXQ** [comment] 2023-05-16 02:42
i have the same error

**Comment by Siham-IT** [comment] 2023-05-19 16:29
Me too, I have the same problem with Apache Hive in version 2.1.0

**Comment by Siham-IT** [comment] 2023-05-20 15:10
Finally, we solved this problem by following Usiel's solution: 

https://github.com/Usiel/PyHive/commit/fb692d956758bca9d4aba980a8c418cc5788768d?diff=split

by changing those two lines in the sqlalchemy_hive.py file:

class HiveDialect(default.DefaultDialect):
    name = b'hive'
    driver = b'thrift'

to this:

class HiveDialect(default.DefaultDialect):
    name = 'hive'
    driver = 'thrift'


Alternatively, you can simply use the latest version of PyHive, which already contains these changes.

**Comment by vndroid** [comment] 2023-06-06 02:36
> Finally, we solved this problem by following Usiel's solution:
> 
> [Usiel/PyHive@fb692d9?diff=split](https://github.com/Usiel/PyHive/commit/fb692d956758bca9d4aba980a8c418cc5788768d?diff=split)
> 
> by changing those two lines in the sqlalchemy_hive.py file:
> 
> class HiveDialect(default.DefaultDialect): name = b'hive' driver = b'thrift'
> 
> to this:
> 
> class HiveDialect(default.DefaultDialect): name = 'hive' driver = 'thrift'
> 
> Alternatively, you can simply use the latest version of PyHive, which already contains these changes.

Amazing! Thanks a lot.

**Comment by bkyryliuk** [comment] 2023-08-24 15:51
It seems to be a duplicate of https://github.com/apache/superset/issues/22316
Give pyhive 0.7.0 a try, as I recall there was a contribution fixing this issue.

**Closed by bkyryliuk** 2023-08-24 15:51 UTC
Labels: data:connect:hive
