### ISSUE TITLE
Bug Report: Time Grain issue on pivot-table-v2 

### ISSUE THREAD

**Issue by gugupy** [apache/superset#24460] opened 2023-06-20 15:07 UTC
#### How to reproduce the bug

1. Create a Pivot-Table with `Time grain filter` .
2. Try to change the Time Grain filter value.

### Expected results
![606d34ab-29fc-4b46-8b53-a5d2568c2865](https://github.com/apache/superset/assets/28136162/6173e0fc-f7d3-450f-8662-0ab444355850)

This output because of I manually override the request `timeGrain` of the columns in the chart/data api.

``` python
        if json_body is None:
            return self.response_400(message=_("Request is not JSON"))

        # -----------Temp fix for timeGrain
        q, col = 0, 0

        try:
            # json_body['form_data']['time_grain_sqla'] = json_body.get("form_data").get('extra_form_data').get('time_grain_sqla')
            # print(json_body.get('queries'))
            # if isinstance(json_body.get('queries')[0]['columns'][0], dict):
            #     json_body.get('queries')[0]['columns'][0]['timeGrain'] = json_body.get("form_data").get('extra_form_data').get('time_grain_sqla')
            if json_body.get('queries'):
                for query in json_body.get('queries'):
                    # print(query.get('columns'))
                    if query.get('columns'):
                        for column in query.get('columns'):
                            # print(column)
                            if column.get('timeGrain'):
                                json_body['queries'][q]['columns'][col]['timeGrain'] = json_body.get("form_data").get('extra_form_data').get('time_grain_sqla')
        except Exception:
            pass

        # --------Time Grain fix end here

        try:	        try:
            query_context = self._create_query_context_from_form(json_body)	            query_context = self._create_query_context_from_form(json_body)
            command = ChartDataCommand(query_context)
```

This is not the right fix. I just made; to create an issue and **I am unable to find where the API request made**.

### Actual results

![image](https://github.com/apache/superset/assets/28136162/88f2ad19-d4ce-4ac6-a24a-1190010a9bc3)

### Environment

(please complete the following information):

- browser type and version: `Microsoft Edge`
- superset version: `superset version` `Superset 0.0.0-dev`
- python version: `python --version` `Python 3.10.6`
- node.js version: `node -v` `v18.16.0`
- any feature flags active:
   ```
   FEATURE_FLAGS = {
         "ALERT_REPORTS": True,
         "ENABLE_TEMPLATE_PROCESSING": True,
         "GENERIC_CHART_AXES": True
    }
   ```
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

https://apache-superset.slack.com/archives/C0170U650CQ/p1687178724798949

This is not happening when creating/editing the Chart, but while accessing the chart via dashboard.

After comparing both the `/api/v1/char/data` request, I could see the payload `queries[0].columns[0].timeGrain` value is always `P1D`.
```
{"datasource":{"id":90,"type":"table"},"force":false,"queries":[{"time_range":"Last year","filters":[{"col":"invoice_date","op":"TEMPORAL_RANGE","val":"Last year"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"invoice_date","label":"invoice_date","expressionType":"SQL"},"Product Group"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"net_billings_in_eur","description":null,"expression":null,"filterable":true,"groupby":true,"id":823,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE PRECISION","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(net_billings_in_eur)","optionName":"metric_n50h3hxsqw_k15ceqbn8qs","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"net_billings_in_eur","description":null,"expression":null,"filterable":true,"groupby":true,"id":823,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE PRECISION","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(net_billings_in_eur)","optionName":"metric_n50h3hxsqw_k15ceqbn8qs","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{"native_filters_key":"Tm4MUjZGIx0ffpDkQ5qYluYYwDaSVdCloUd7Pc8JTc93T3vEX38BVKvP04oUhXV1"},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"90__table","viz_type":"pivot_table_v2","slice_id":299,"url_params":{"native_filters_key":"Tm4MUjZGIx0ffpDkQ5qYluYYwDaSVdCloUd7Pc8JTc93T3vEX38BVKvP04oUhXV1"},"groupbyColumns":["invoice_date"],"groupbyRows":["Product Group"],"time_grain_sqla":"P1D","temporal_columns_lookup":{"invoice_date":true},"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"net_billings_in_eur","description":null,"expression":null,"filterable":true,"groupby":true,"id":823,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DOUBLE PRECISION","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(net_billings_in_eur)","optionName":"metric_n50h3hxsqw_k15ceqbn8qs","sqlExpression":null}],"metricsLayout":"COLUMNS","adhoc_filters":[{"clause":"WHERE","comparator":"Last year","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"invoice_date"}],"row_limit":10000,"series_limit_metric":null,"order_desc":true,"aggregateFunction":"Sum","valueFormat":"SMART_NUMBER","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[],"dashboards":[87],"extra_form_data":{"time_range":"Last year","time_grain_sqla":"P1M"},"label_colors":{},"shared_label_colors":{},"extra_filters":[],"dashboardId":87,"force":null,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}
```

**Comment by pnirtep** [comment] 2023-06-21 08:35
After switching version from 1.5.0 to 2.1.0, I noticed a problem with the fact that the Pivot table does not respond to the change in granularity. That is, by default, Pivot table on dashboard is loaded by month, but if you select a Quarter in the time grain filter and click apply, there are no changes. At the same time, if you then open this pivot table in Edit chart mode, then it will load in the editor with the desired granularity. By the way, after applying non-default time grain filter there is no changes in SQL-query. If i click View query i see still DATE_TRUNC(‘month’, datetime_field) but It should be DATE_TRUNC(‘quarter’, datetime_field).
Moreover, this time grain filter is applied correctly to the Time-series Bar Chart, the chart adapts to the choice of Month or Quarter, but it does not work with the Pivot table. if anything, by Pivot table, I mean the Pivot Table v2 chart (that’s what it used to be called, now it’s just Pivot table)

**Comment by michael-s-molina** [comment] 2023-07-07 14:41
@gugupy @pnirtep Are you able to reproduce this bug on master? I tried and it was working:

https://github.com/apache/superset/assets/70410625/365665af-e3b1-40e2-a91a-9fbb3caff47d

If you can't reproduce it on master, then you have the following options:
- Wait for 3.0 which will contain the fix and it's [already being voted](https://github.com/apache/superset/discussions/24581)
- If you can reproduce the bug in 2.1 then you can request the fix to be included [here](https://github.com/apache/superset/discussions/23993).

**Comment by gugupy** [comment] 2023-07-07 15:27
@michael-s-molina Thanks for your time to test this issue.

Even in your video looks only `TIME GRAIN` Month is working. 

Quarter and Year looks not working. Can you check the `SQL Query` for each `TIME GRAIN`

![image](https://github.com/apache/superset/assets/28136162/2e1349df-c923-4488-9fc8-1b56551b7001)

2004 Q4 coming more than once.

![image](https://github.com/apache/superset/assets/28136162/a147d2e2-d6ba-42b1-a993-c3a4b1982f08)

2004 coming more than a once.

**Comment by michael-s-molina** [comment] 2023-07-07 16:42
Oh you're right @gugupy! I think it's time for me to get some coffee! 

The bug still exists and we'll try to fix it before releasing 3.0.

**Comment by michael-s-molina** [comment] 2023-07-07 16:48
I added this bug to the 3.0.0rc1 discussion [here](https://github.com/apache/superset/discussions/24581#discussioncomment-6386616).

**Comment by yousoph** [comment] 2023-07-07 19:36
@hughhhh had started to look at this issue

**Comment by michael-s-molina** [comment] 2023-07-07 19:37
> @hughhhh had started to look at this issue

Thank you @yousoph! I assigned this ticket to @hughhhh

**Comment by hughhhh** [comment] 2023-07-07 20:16
Verified that the fix above @gugupy does work, and the main problem is on the POST api/v1/data with the time grain of the column not being set properly.

I'm pretty unfamiliar with this part of the codebase, but I'm assuming the client/native filter is suppose to update the payload for each query before sending to the server

@michael-s-molina do understand how native filters are suppose to update underlining charts in a dashboard?

**Comment by gugupy** [comment] 2023-07-08 03:09
@hughhhh the fix was actually for only convey the issue. It has to fixed where the API call invoked with the right `form_data`. I was tried but as I am not familiar with the codebase so couldn't find it.

**Comment by michael-s-molina** [comment] 2023-07-10 16:35
> @michael-s-molina do understand how native filters are suppose to update underlining charts in a dashboard?

@hughhhh I can take a look.

**Closed** 2023-07-13 14:33 UTC

**Comment by dcser123** [comment] 2026-04-15 09:18
Hi, I'm currently having the same issue. It appears that the time grain isn't making its way to the query in the pivot table. The formatting of the date values reflects the time grain but not the actual aggregation. My db is postgres and I'm not seeing the DATE_TRUNC() function within the query when loading it.
