### ISSUE TITLE
SQL Lab results table does not show some values

### ISSUE THREAD

**Issue by aobapirak** [apache/superset#26432] opened 2024-01-09 07:15 UTC
#### How to reproduce the bug

1. Go to 'SQL Lab'
2. Run these command or other command related to <...>
`select '<test> im not disappear <test>ABC<> Z <>' as test`
3. Click on 'Run' to run query
4. See error in result table below

### Expected results

`<test> im not disappear <test>ABC<> Z <>`

### Actual results

`im not disappear ABC Z`

#### Screenshots

![Screenshot 2567-01-09 at 09 39 39](https://github.com/apache/superset/assets/87610632/ccbf88bd-987a-4787-8160-e1db1a7d560a)

### Environment

- browser type and version:
- superset version: `3.0.1`
- python version: `3.9.6`
- node.js version: `16.20.2`
- any feature flags active: -

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment] 2024-01-09 16:55
I suspect (but am not certain) that it's related to this PR: https://github.com/apache/superset/pull/24368

**Comment by rusackas** [comment] 2024-03-12 20:47
Closing this as a duplicate of https://github.com/apache/superset/issues/25561

**Comment by rusackas** [comment] 2024-03-12 20:47
Still very much open to PRs around this!

**Closed by rusackas** 2024-03-12 20:47 UTC
Labels: preset:cares
