### ISSUE TITLE
Unable to create custom plugin in superset 3.0.0rc3/dev ( superset-frontend directory is almost empty) 

### ISSUE THREAD

**Issue by musicmuthu** [apache/superset#25257] opened 2023-09-11 14:09 UTC
i have download and run the superset image in my docker and inside the i am unable to anything in the superset-frontend except package.json.

i try to run superset Custom plugin  in superset 3.0
also i build the image except package.json nothing was left in superset-frontend.
any idea 
Even the new image from docker HUB superset:3.0.0.rc3/dev nothing was there in that directory 

[super@super1.io]$ docker run -d  --name superset apache/superset:3.0.0rc3-dev
f0a5cb670d83f1377ae8bfee8854e6db3ab53ee646dda2ae3b42fc75d1b2194a
[super@super1.io ~]$ docker container ls -a |grep superset
f0a5cb670d83        apache/superset:3.0.0rc3-dev           "/usr/bin/run-server…"   9 seconds ago       Up 7 seconds (health: starting)   8088/tcp                                           superset
[super@super1.io ~]$ docker exec -it f0a5cb670d83 /bin/bash
superset@f0a5cb670d83:/app$ cd /^C
superset@f0a5cb670d83:/app$ ls
MANIFEST.in  apache_superset.egg-info  requirements  superset           superset_home
README.md    pythonpath                setup.py      superset-frontend
superset@f0a5cb670d83:/app$ du -sch *
4.0K    MANIFEST.in
12K     README.md
160K    apache_superset.egg-info
0       pythonpath
28K     requirements
8.0K    setup.py
142M    superset
16K     superset-frontend
12K     superset_home
142M    total
superset@f0a5cb670d83:/app$ ls -lrth superset-frontend/
total 16K
-rw-r--r-- 1 superset superset 15K Aug 24 17:44 package.json
superset@f0a5cb670d83:/app$

**Comment by musicmuthu** [comment] 2023-10-13 04:38
Hi @michael-s-molina,
except package.json nothing is left in superset-frontend directory.
how to build the custom plugins.
based on the doc unable to find the "superset-frontend/src/visualizations/presets/MainPreset.js"

**Comment by yudiz-jayd** [comment] 2023-10-20 08:39
@musicmuthu did you get any solution on this I am having the same issue?

**Comment by michael-s-molina** [comment] 2023-10-20 11:25
@villebro Could you take a look?

**Comment by musicmuthu** [comment] 2023-10-23 18:29
> @musicmuthu did you get any solution on this I am having the same issue?

no solutions
also i try to build custom plugin in 3.0 it's not working previously it working fine with 2.0.0.

**Comment by musicmuthu** [comment] 2023-10-26 12:45
@villebro have you look into it ?

**Comment by yudiz-jayd** [comment] 2023-10-26 13:08
@musicmuthu , I am able to figure out this issue, it's storing evening under superset/static/assets, not under superset-frontend, and if you are not able to see your changes try to delete volume & recreate everything,

just the workaround here we need to do npm I & npm install in plugin as well as in superset-frontend before making docker up.

I hope this will fix your issue. if you still have any issues let me know I can help.

**Comment by musicmuthu** [comment] 2023-10-26 15:12
@yudiz-jayd where can I see the MainPreset.js file

**Comment by musicmuthu** [comment] 2023-11-02 18:22
@villebro  do you have the latest custom plugin document for superset 3.0 version

**Comment by rusackas** [comment] 2024-04-04 01:39
I'm going to close this since it's been silent for so long. It's also not a bug with Superset, but a custom code development issue, which we'll have a hard time supporting from afar.

If your superset-frontend directory is empty, it's probably because you're using some form of prepbuilt docker image, and all the frontend code is rendered out as static assets. If you're going to do plugin development, you should fork/clone the repo, and you'll have all of the code and dev tooling in superset-frontend.

The instructions for plugin development are unchanged from 2.0, as of 4.0.

**Closed by rusackas** 2024-04-04 01:39 UTC

**Comment by nathanbaleeta** [comment] 2024-04-04 22:19
> @yudiz-jayd where can I see the MainPreset.js file

Here is the path to `MainPreset.js` -  `superset-frontend/src/visualizations/presets/MainPreset.js`
