### ISSUE TITLE
Calendar Heatmap not working

### ISSUE THREAD

**Issue by jmpicaza** [apache/superset#23766] opened 2023-04-21 08:19 UTC
Is not possible to create a calendar heatmap because the section to provide the timeline variable is missing
 
#### How to reproduce the bug

1. Go to Charts 
2. Click on '+Chart' -> chose a datatet -> select Calendar Heatmap -> Create New Chart
3. In the Chart data column there is only the 'Query' and 'Filter' sections 
4. If you click on 'Update Chart' mesage error appears:
Unexpected error
Datetime column not provided as part table configuration and is required by this type of chart

### Expected results

visualization of the chart

### Actual results

error message

#### Screenshots

add screenshorts
![image](https://user-images.githubusercontent.com/2660543/233568669-457922bd-c829-443a-a818-4645c087c82e.png)

### Environment

(please complete the following information):

- browser type and version: google chrome Version 112.0.5615.137 (Official Build) (arm64)
- superset version: Superset 0.0.0-dev
- python version: `python --version` Python 3.8.16
- node.js version: `node -v` /bin/sh: 3: node: not found
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

none

**Comment by C-monC** [comment] 2023-05-29 15:14
I am also getting this bug on the calendar heatmap

**Comment by HeathLee** [comment] 2023-08-14 03:42
same issue

**Comment by rusackas** [comment] 2024-03-06 21:59
I'm not able to reproduce this in 3.x, so I think we're all good. Closing, but happy to revisit if needed.

**Closed by rusackas** 2024-03-06 21:59 UTC
Labels: #bug
