### ISSUE TITLE
Certified metric icons are various sizes

### ISSUE THREAD

**Issue by etr2460** [apache/superset#12628] opened 2021-01-20 18:56 UTC
## Screenshot
![image](https://user-images.githubusercontent.com/7409244/105221516-12eb1c80-5b0e-11eb-86eb-e9f12a5ec34b.png)

## Description
When multiple metrics are certified, it seems like the icons are different sizes. No clue why, but it seems to be introduced with the new dataset panel

## Design input
They should all be the same size

**Comment by junlincc** [comment] 2021-01-20 19:04
@etr2460 Thanks for reporting. we are aware of this issue. icon migration project has been put on-hold until v1.0.1 release.

**Comment by geido** [comment] 2021-01-21 08:25
Yep. I Will check those out first as soon as we can get the initial POC for the icons in

**Comment by geido** [comment] 2021-01-22 15:50
I have provided a quick fix for this as the issue is not related to the icon itself but to a styling issue, so it makes sense to keep this separate from the icons migration.

**Closed** 2021-01-22 21:14 UTC
Labels: design:explore, viz:explore:datapanel
