### ISSUE TITLE
Save connection database not working

### ISSUE THREAD

**Issue by pinduvn** [apache/superset#14764] opened 2021-05-22 15:24 UTC
hi, the latest tag in docker hub, when test connection on PostgreSQL ,return ok, but when I want save, return an error.
regards.

**Comment by alderson59** [comment] 2021-05-22 19:30
I was JUST about to open an issue on this. Perfect timing, glad I wasn't the only one. @pinduvn , I think it helps to describe your problem in greater detail so others can help you. I'll just do it for you, since I think we're facing the same problem.

After putting in the URI of my external postgres host correctly,
i.e. `postgresql://[user]:[passwd]@[host-ip]:[port]/[dbname]`
I clicked on Test Connection, which shows `Connection looks good!`

But when I click Connect, this is the error I get:
`An error occurred while creating databases: Fatal error`
I googled this error, but could not find it anywhere at all.

For context on how I installed it on my Ubuntu 20.0.4 host, I ran `git clone https://github.com/apache/superset`
then `cd superset` and `docker-compose -f docker-compose-non-dev.yml up -d`

Didn't tweak any further settings. Wanted a clean version up and running before changing any config, but alas, that didn't work right out of the box.

Based on the basic config, I was able to track down the fact that the bundled postgres db showed a FATAL error because role 'root' was missing, when I did a psql using root. Not sure if this is a contributing factor though, since the default .env and .env-non-dev should already have the `superset` user connecting to the `superset` db, with the `superset` password.

**Comment by pinduvn** [comment] 2021-05-24 10:30
hi @alderson59 , sorry for my pauper description in english. The full description of the problem that you describe, is exactly equals for the problem with latest image tag of the superset in docker hub.

**Comment by toms049** [comment] 2022-02-03 13:55
In case someone is still having a trouble, it could be also connected to this:

`Access denied; you need (at least one of) the SHOW DATABASES privilege(s) for this operation`

I did set it and it worked.

`GRANT SHOW DATABASES ON *.* TO 'superset'@'%';`

**Comment by pinduvn** [comment] 2022-02-03 14:53
Thank you, the issue is resolved when install latest version. regards

**Comment by scs001** [comment] 2022-03-20 14:28
> Thank you, the issue is resolved when install latest version. regards

When connect MySql, i have the same problem. Can you tell me how to insatll latest version.  very thanks

**Comment by scs001** [comment] 2022-03-20 14:33
> 

thanks  open the issue.When connect MySql, i have the same problem. Can you tell me how to insatll latest version. very thanks

**Comment by pinduvn** [comment] 2022-03-20 15:30
Hi, for install latest superset, i use this command for deploy in docker container. Here is the link of the documentation.

**Comment by pinduvn** [comment] 2022-03-20 15:32
Sorry, forgot to let the link https://hub.docker.com/r/apache/superset. Regards

**Comment by rusackas** [comment] 2023-01-20 16:48
Is anyone, particuarly @betodealmeida, still seeing reason to keep this open? It's gone largely stale, so if this is not an issue in newer versions, we should close it out.

**Comment by rusackas** [comment] 2023-01-26 16:09
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!

**Closed by rusackas** 2023-01-26 16:09 UTC
