### ISSUE TITLE
UI blurs for different browsers

### ISSUE THREAD

**Issue by airbots** [apache/superset#17637] opened 2021-12-03 00:36 UTC
#### How to reproduce the bug
Just using Superset 1.1, it blurs the webpage highly suspect it is related to UI 

### Expected results

what you expected to happen.

### Actual results

what actually happens.

#### Screenshots
Firefox
<img width="904" alt="Screen Shot 2021-12-02 at 4 32 41 PM" src="https://user-images.githubusercontent.com/250848/144524702-cb0a669a-1e79-40c9-a75c-ac95efefad34.png">
Chrome

<img width="874" alt="Screen Shot 2021-12-02 at 4 36 03 PM" src="https://user-images.githubusercontent.com/250848/144524765-4c914b0c-6036-49c5-ab12-bef451017bc7.png">

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by srinify** [comment] 2021-12-04 15:59
Hi @airbots I'm not able to replicate this issue. 

- Is there anything useful in the browser console w.r.t. errors?
- How are you installing / deploying Superset?

**Comment by geido** [comment] 2022-01-25 13:42
Hello @airbots as this issue could not reproduce and you didn't get back to us recently, I'm closing this issue. Feel free to ping me if you need more assistance. Thank you!

**Closed by geido** 2022-01-25 13:42 UTC
Labels: #bug
