### ISSUE TITLE
Deleting a database connection is not deleting the entries from ab_view_menu and ab_permission_view metadata tables

### ISSUE THREAD

**Issue by radhakvnr** [apache/superset#19058] opened 2022-03-08 08:03 UTC
Deleting a database connection is not deleting the entries from ab_view_menu and ab_permission_view_menu. which results many unnecessary rows present in the above mentioned tables in metadata.

#### How to reproduce the bug

1. Go to Database section
2. Click on add database
3. Create a new database connection and save
4. Delete the Database connection
5. go to the Metadata and query the ab_view_menu and ab_view_menu and ab_permission_view you can still see the entries of the deleted database.

### Expected results
Deleting a Database connection should delete the corresponding entries from the respective tables.

what you expected to happen.

### Actual results

Deleting a database connection is not deleting the entries from ab_view_menu and ab_permission_view metadata tables

### Environment

(please complete the following information):

- browser type and version:
- 1.3.2
- python version: 3.7.9
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment] 2022-03-09 06:31
Hi, @radhakvnr. Do you try to run `superset init`? I remember there are some cleanup steps in this command.

**Comment by cccs-rc** [comment] 2022-03-16 18:43
Hi, @zhaoyongjie . I stumbled across this issue while I was in the process of manually cleaning up these tables for this exact reason! We've renamed our DB connections several times and the permissions have never been cleaned up, which means they continue to appear as options in the "Edit Role" view. It's a minor annoyance for admins. 

Running ```superset init``` doesn't clean anything up for us (on 1.4.).

**Comment by radhakvnr** [comment] 2022-04-08 09:27
any update on this?

**Comment by rusackas** [comment] 2023-01-26 06:54
Curious if anyone is still running into this in current-era superset or is interested in opening a PR. If not, perhaps it's been long enough to close this one out? Also, as far as the `validation:required` tag, I assume this is still happening in 2.0.1 / `master`? Confirmation or denial would be helpful :)

**Comment by LeoDiep** [comment] 2023-02-17 11:33
> @zhaoyongjie unfortunately the superset init is not really deleting any un used or orphan connections. Even we rename a database connection the under lying permissions on top of that database is not renaming instead it is creating a new set of permissions with the new name. hence over load on Metadata

same problem here, now my permission of datasouce access ..... is a mess and I don't know how to clean it.
Is there any update on this problem

**Comment by giovannipapini-agilelab** [comment] 2023-05-24 12:02
> Curious if anyone is still running into this in current-era superset or is interested in opening a PR. If not, perhaps it's been long enough to close this one out? Also, as far as the `validation:required` tag, I assume this is still happening in 2.0.1 / `master`? Confirmation or denial would be helpful :)

yes, the problem is still there (v2.0.1 here) and quite annoying honestly. Wouldn't it be possible to perform an update operation instead of an insert one when performing any edit on the database connection?

**Comment by LeoDiep** [comment] 2023-06-07 08:47
I just check the version 2.1.0 and this problem was solved. When you change the dataset name, the role accessing datasource also update the new name. 
However there is a drawback, when I choose a dataset name for a role, that name don't dissapear on the list to choose as previous version

**Comment by michael-s-molina** [comment] 2024-02-23 21:34
Closing this as it seems the problem was solved in recent versions of Superset. Please reopen if that's not the case.

**Closed by michael-s-molina** 2024-02-23 21:34 UTC
Labels: validation:required, #bug, global:users
