### ISSUE TITLE
[dashboard] [native-filter] Unable to view Dashboard Native Filter's UI/Sidepanel with non-admin & non-owners users

### ISSUE THREAD

**Issue by usamaB** [apache/superset#18106] opened 2022-01-20 08:49 UTC
#### How to reproduce the bug

- Enable Dashboard native filter
- Create/publish a dashboard. 
- Dashboard native filters are only accessible by the owner of the dashboard or the admin, other users can't access it

### Expected results
![Screenshot 2022-01-20 at 09 38 02](https://user-images.githubusercontent.com/13015524/150303173-55766195-caaf-48d9-aab3-065091c31d11.jpg)

### Actual results

![Screenshot 2022-01-18 at 17 51 42](https://user-images.githubusercontent.com/13015524/150303217-54b72bf5-c661-4c93-ad8d-6ae4a364bca7.png)

### Environment

(please complete the following information):

- browser type and version: Google Chrome
- superset version: `superset version` 1.3.1/1.4.0
- python version: `python --version` 3.7
- any feature flags active: DASHBOARD_NATIVE_FILTERS, DASHBOARD_CROSS_FILTERS

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by usamaB** [comment] 2022-01-25 11:57
@geido can you explain what does need validation label means?

**Comment by geido** [comment] 2022-01-25 13:29
Hello @usamaB it simply means that a committer should verify whether the issue can be reproduced.

**Comment by usamaB** [comment] 2022-02-02 10:13
@geido How can I do that? It's just enabling the filter and it's not working for non-owners/Admins.

**Comment by isabellalacerda** [comment] 2022-05-09 22:10
Did you find any solutions? I have the same problem when I try to make a public dashboard

**Comment by byk0t** [comment] 2022-05-11 16:14
Hi, @isabellalacerda and @usamaB , I have fixed the issue by  adding **can_read on DashboardFilterStateRestApi** and **can_write on DashboardFilterStateRestApi** permissions for the Public role

**Comment by sfirke** [comment] 2022-05-17 15:54
@byk0t thank you!  I was stuck and those permissions fixed it.  I wish there was a list of which privileges are needed for public role to view dashboards (including those with native filters).

**Comment by byk0t** [comment] 2022-05-17 17:13
@sfirke Actually I have such list. You can check it out here https://gist.github.com/byk0t/bd6e9c3839967b4ac28a8da30f468b2a

**Comment by alanorth** [comment] 2022-06-10 12:00
> @sfirke Actually I have such list. You can check it out here https://gist.github.com/byk0t/bd6e9c3839967b4ac28a8da30f468b2a

@byk0t Thanks. So we need these permissions *in addition* to the ones from Gamma? On a related note, I don't want public users to be able to export CSVs or run SQL, so I have to manually remove those every time I sync from Gamma using `superset init`...

**Comment by byk0t** [comment] 2022-06-10 13:26
> > @sfirke Actually I have such list. You can check it out here https://gist.github.com/byk0t/bd6e9c3839967b4ac28a8da30f468b2a
> 
> @byk0t Thanks. So we need these permissions _in addition_ to the ones from Gamma? On a related note, I don't want public users to be able to export CSVs or run SQL, so I have to manually remove those every time I sync from Gamma using `superset init`...

@alanorth you don't need to sync with Gamma at all. You can remove this line `PUBLIC_ROLE_LIKE = "Gamma"`.

**Comment by byk0t** [comment] 2022-06-10 13:41
> @byk0t neither Gamma nor [the permissions in your `superset-public-permissions.json` example](https://gist.github.com/byk0t/bd6e9c3839967b4ac28a8da30f468b2a) were enough to let public/anonymous users view dashboards in my case (Superset 1.5.1). So what I did was sync with Gamma, then import yours, then manually remove all the permissions I didn't want anonymous to have (menu access, SQL Lab, Explore, CSV export, Swagger / OpenAPI, etc). I wish this was a bit more well documented...

@alanorth In my case Public user was able to see dashboards (for the latest version and for 1.5.0).  And I didn't sync with Gamma. Make sure you setup the permissions correctly.

**Comment by swordrada** [comment] 2022-09-14 08:35
@byk0t hi I have an opposite requirement that I don't want to display filter state navigation bar of a dashboard when visited by users not logged in.But when I cancel two permissions you mentioned above, superset will redirect to login page automatically.So how can I make this filter state navigation bar invisible when visited by anonymous users?

**Comment by rusackas** [comment] 2024-02-12 20:23
I'm guessing since everyone has a handle on the required permission, and can freely change that, it's safe to close this issue since it's been silent for a year and a half. If people are still encountering this in current versions (3.x) please open a new Issue with updated context or a PR/proposal to address the problem. Thanks!

**Closed by rusackas** 2024-02-12 20:23 UTC
Labels: validation:required, #bug
