### ISSUE TITLE
Blinking scrollbars (2.0.1)

### ISSUE THREAD

**Issue by squalou** [apache/superset#22784] opened 2023-01-19 11:29 UTC
## Screenshot

1.

![image](https://user-images.githubusercontent.com/4623644/213430694-443b257a-64a5-4cb2-80ed-eaa66a4d35c9.png)

2.

![image](https://user-images.githubusercontent.com/4623644/213430939-4d5c00e3-7577-435e-a9c8-de6a54ec54f8.png)

[drag & drop image(s) here!]

## Description

Look at these two screenshots, imagine your browser switching from one to the other 4 times per seconds.

(I didn't manage to capture a video).

Resizing the screen doesn't change anything.

This is completely driving people mad :)

**Comment by squalou** [comment] 2023-01-19 11:30
(happens with version 2.0.1)

**Comment by sfirke** [comment] 2023-01-19 15:21
Duplicate of https://github.com/apache/superset/issues/22393.  Agreed it's not good.

**Comment by rusackas** [comment] 2023-01-19 16:47
@AAfghahi Not sure if we can get internal resources to prioritize this, but it might be good to get a fix in for 2.0.2 if at all possible.

**Comment by svarcoe** [comment] 2023-01-19 22:41
We also are seeing this behavior. It only happens for tables in the Explorer view. The same chart inside a Dashboard does not have blinking scrollbars.

**Comment by artemonsh** [comment] 2023-01-23 12:42
Wasn't it solved here https://github.com/apache/superset/pull/20833?

**Comment by squalou** [comment] 2023-01-23 17:13
my 2  cents : I ran `git blame --  superset-frontend/plugins/plugin-chart-table/src/TableChart.tsx` on suorces tagged 2.0.1
and there's nothing more recent than 2022-05 (and nothing looking like the commit above), even if it's supposed to have landed in master.

**Comment by squalou** [comment] 2023-01-24 09:56
I tested a local build with superset-frontend/plugins/plugin-chart-table/src/TableChart.tsx from the mentioned pull request => looks good !

No idea why the commit was not included on master at some point.

**Comment by rusackas** [comment] 2023-02-09 17:50
Since this is fixed on `master` and slated for 2.0.2 per [this thread](https://github.com/apache/superset/discussions/22630), I think we can call this one done. Thanks @Antonio-RiveroMartnez for the fix!

@yousoph per the `preset:cares` tag, maybe it's worth confirming that any correlated issues we're concerned with are also resolved.

**Closed by rusackas** 2023-02-09 17:50 UTC
Labels: preset:cares, v2.0.2

**Comment by sfirke** [comment] 2023-02-27 18:12
Alas I'm seeing the blinking/flashing scrollbars in 2.1.0rc1 with a Heatmap chart ...

**Comment by squalou** [comment] 2023-03-14 07:17
Seen it *again* in 2.1.0rc1, have to try rc2 i guess :disappointed:
