### ISSUE TITLE
Translations files don't translate everything

### ISSUE THREAD

**Issue by AnaKuzina** [apache/superset#14848] opened 2021-05-26 17:02 UTC
Hello! I've modified Russian translations files. 
Everything worked great except header tabs and some menu data ("Data", "Charts" in headers tabs, "Manage" in Settings dropdown etc.). 
I don't understand what the problem is. Will appreciate any help, thanks!
<img width="706" alt="Снимок экрана 2021-05-26 в 19 59 17" src="https://user-images.githubusercontent.com/21035768/119701394-f284f300-be5c-11eb-8c6e-faee1cb6dbb8.png">

<img width="245" alt="Снимок экрана 2021-05-26 в 19 59 30" src="https://user-images.githubusercontent.com/21035768/119701387-f153c600-be5c-11eb-81c9-e22ef5c0c775.png">

**Comment by xch-jack** [comment] 2021-05-27 04:07
Hi，
AnaKuzina
There are punctuation problems in your translation file, please check carefully.

**Comment by AnaKuzina** [comment] 2021-05-27 09:20
> Hi，
> AnaKuzina
> There are punctuation errors in your translation file, please check carefully.

Hi, @xch-jack 

Can you please specify what type of punctuation error do I have? Do I need to exactly repeat every tab, spaces and comma that contains english string?

For example, I've translated like this:

> msgid ""
> "Encountered invalid NULL spatial "
> "entry,                                        please consider filtering "
> "those out"
> msgstr ""
> "Обнаружена недопустимая пространственная запись NULL, "
> "пожалуйста, рассмотрите возможность её фильтрации"

Is there any punctuation errors?
And I don't understand why most of the files are translated correctly.
Thanks in advance!

**Comment by xch-jack** [comment] 2021-05-27 10:16
Hi，
Open your  messages.json file, view the last line, and cannot add a comma.

**Comment by AnaKuzina** [comment] 2021-05-27 12:03
@xch-jack thanks for your help! 
The .json file seems to be correct, the last lines are the same as in the translations files here:

<img width="672" alt="Снимок экрана 2021-05-27 в 15 02 12" src="https://user-images.githubusercontent.com/21035768/119822611-8659cc00-befc-11eb-9d18-ca66050c3080.png">

Any idea what else can it be?

**Comment by xch-jack** [comment] 2021-05-27 12:31
Try modifying the meassage.mo file my screenshot location look at, which is the message.mo screenshot location you gave me.
![image](https://user-images.githubusercontent.com/81534879/119826007-2bd76480-bf2a-11eb-9de4-b9d30b46c8a4.png)

**Comment by xch-jack** [comment] 2021-05-27 12:35
This is my ru Language screenshot.It should be the screenshot in the meassage.mo file you gave to me.
![image](https://user-images.githubusercontent.com/81534879/119826908-1dd61380-bf2b-11eb-8ace-9368e6c5299d.png)

**Comment by xch-jack** [comment] 2021-05-27 13:01
Hi,AnaKuzina 
I don t know Russian sync grammar but by Chinese grammar the translation in Russian meassage.mo file has many punctuation errors.

**Comment by AnaKuzina** [comment] 2021-05-27 13:06
@xch-jack thank you for your help! I just don't understand why the easiest line aren't translated such as **Datasets** and **Manage** - there cannot be any punctuation errors.

I don't understand what is wrong on your screenshot with two wrong sentences... I will look through other languages as an example, thank you for the advice!

**Comment by AnaKuzina** [comment] 2021-05-28 13:43
@xch-jack hi! Thank you for your help yesterday, I've figured it out and it works. 

But now I have another problem. 

These buttons: "+ dashboard", "+ chart" and other on the main page are not translated. I don't see these strings in .po file as well. Do you know what can be the problem?
<img width="1414" alt="Снимок экрана 2021-05-28 в 16 42 46" src="https://user-images.githubusercontent.com/21035768/119992981-c344c200-bfd3-11eb-8c9b-32fc1328097b.png">

Thank you in advance!

**Comment by xch-jack** [comment] 2021-05-28 14:41
Hi，
The word translation here needs to find the correct word translation in the front end file, or directly modify in the front end file, it is very troublesome!
The location of the front-end file in superset\static\assets, recommends finding modifications with pycharm.

**Comment by AnaKuzina** [comment] 2021-05-28 15:47
@xch-jack thank you so much! Can you please show me some example of the lines of code where the words are translated in the frontend file?

The main problem is that I use docker file that takes all frontend files etc from the main superset project. So I can't modify it because I don't have permissions =)) 

And I don't understand why button **+ chart** is translated, but **+ sql query** is not... meanwhile you can see translated **+ sql запрос** below...
<img width="1411" alt="Снимок экрана 2021-05-28 в 18 44 55" src="https://user-images.githubusercontent.com/21035768/120009892-29861080-bfe5-11eb-8d16-b60b4463a6ab.png">

**Comment by xch-jack** [comment] 2021-05-28 16:17
Hi，
With Docker runtime your front end file is just under superset\static\assets. It is troublesome to modify completely, and you need to find the translated words yourself in the front-end file to modify more places.
There are many places that actually need translation and you have to understand front end files to do.

**Comment by xch-jack** [comment] 2021-05-28 16:32
I give an example that if you are using Pycharm, you can find "VIEW ALL", in the front end file you can find the location you want in your screenshot, there are generally 3 JS files. And this "VIEW ALL" actual word may be lower case may be capital, all you need to understand the front-end file to do the translation.

**Comment by xch-jack** [comment] 2021-05-28 16:53
Of course if you do use a docker-compose-f docker-compose-non-dev.yml up installation in Docker I can do nothing.

**Comment by hbruch** [comment] 2021-12-27 07:56
@AnaKuzina some of the untranslated messages should be translatable now via #17525.

Another issue is that docker-compose-non-dev.yml's apacha/superset:latest-dev image is built without a babel-compile step. I'll shortly submit a PR fixing this. 

Finally, there are some i.e. chart related messages which are not yet covered by the babel extraction process, which will hopefully be fixed as soon as the monorepo migration is completed.

**Comment by niknoi** [comment] 2022-09-08 10:53
https://github.com/apache/superset/issues/14848#issuecomment-850429281
Hi, Anna can you describe please, how are you fixed this problem

**Comment by AnaKuzina** [comment] 2022-11-04 13:16
> [#14848 (comment)](https://github.com/apache/superset/issues/14848#issuecomment-850429281)
> Hi, @AnaKuzina can you describe please, how are you fixed this problem

I haven't got any decision. I'm still trying to figure out how to translate main page after login. For example the tab with recent dashboards isn't translated. 

I found file EmptyState.tsx with the needed line https://github.com/apache/superset/blob/d49fd01ff3e3ee153e5e50352ec2151f028a5456/superset-frontend/src/views/CRUD/welcome/EmptyState.tsx#L77\

But I can't figure out how to pass it into translation. Any ideas?

**Comment by artemonsh** [comment] 2022-11-14 09:00
Guys, I am really happy to tell you that I've figured out how to apply all translations that we need. Enter virtual environment and run `pybabel compile -d superset/translations`. It will point out all the errors you have, for example:
```
error: superset/translations/ru/LC_MESSAGES/messages.po:189: placeholders are incompatible
error: superset/translations/ru/LC_MESSAGES/messages.po:6433: unknown named placeholder 'tableName'
error: superset/translations/ru/LC_MESSAGES/messages.po:6683: placeholders are incompatible
error: superset/translations/ru/LC_MESSAGES/messages.po:13100: placeholders are incompatible
error: superset/translations/ru/LC_MESSAGES/messages.po:13975: positional format placeholders are unbalanced
```
Then simply edit all of the messages to avoid errors and run the compile `command` again!

**Comment by rusackas** [comment] 2023-03-23 02:16
Closing this since I believe @artemonsh tackled the translations at hand, and all is well. Also, this is not a bug, per se, but just a long tail area that has always needed attention in Superset, and likely always will. If anyone has interest in contributing to this effort, please ping me on the Superset Slack, and perhaps we can start a working group that tackles this on a regular basis.

**Closed by rusackas** 2023-03-23 02:16 UTC
Labels: #bug

**Comment by hbruch** [comment] 2023-03-25 05:32
Whoever comes here because some messages appear untranslated, should have a look into the [CONTRIBUTING#translating section](https://github.com/apache/superset/blob/master/CONTRIBUTING.md#translating) which might already answer some questions. Also, the [Slack-localization channel](https://apache-superset.slack.com/archives/C01ABD5ESG4) might be a good place to coordinate work on translations.

**Comment by Atmostone** [comment] 2024-08-07 09:45
Still have similar issue in latest versions (4+)
When I set default language not to English

`BABEL_DEFAULT_LOCALE = 'ru'

LANGUAGES = {
    'ru': {'flag': 'ru', 'name': 'Русский'},
    'en': {'flag': 'us', 'name': 'English'},
}`

Then en version breaks at same places like in this issue

ru version: OK
![image](https://github.com/user-attachments/assets/75071dbb-4dd7-47ab-9f2a-19754c6aa757)
en version: broken
![image](https://github.com/user-attachments/assets/d33ebb4d-fb57-44ab-b99b-cc04c47bf57e)

**Comment by glebka-end** [comment] 2025-03-10 09:57
https://github.com/apache/superset/issues/14848#issuecomment-849619005

что ты изменил ?

**Comment by glebka-end** [comment] 2025-03-10 09:58
@AnaKuzina
