### ISSUE TITLE
New Box Plot ignore "Series Limit" when selecting "Distribute Across"

### ISSUE THREAD

**Issue by eugeniamz** [apache/superset#11669] opened 2020-11-12 17:15 UTC
Testing new echart Box Plot I notice that when selecting the Distribute Across, it ignores the "Series Limit" 

### Expected results

If I select "Series Limit", I should always that number of records 
### Actual results
When I select Distribute Across, Series limit is ignored and shows all the data points

#### Screenshots

![2020-11-12_10-54-21 (1)](https://user-images.githubusercontent.com/58375897/98972655-bac9e580-24e0-11eb-953f-bda0d75914ac.gif)

### Environment

Latest Master
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ X] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment] 2020-11-12 18:25
Thanks @eugeniamz , I know what the problem is and there's a few solutions, but I need to digest it a little more to find the optimal one.

**Comment by junlincc** [comment] 2020-11-12 19:24
<img width="887" alt="Screen Shot 2020-11-12 at 11 04 11 AM" src="https://user-images.githubusercontent.com/67837651/98986298-90c0f500-24d9-11eb-865a-a3452f99a68e.png">
<img width="896" alt="Screen Shot 2020-11-12 at 11 06 26 AM" src="https://user-images.githubusercontent.com/67837651/98986311-97e80300-24d9-11eb-8681-f27f511a2602.png">


@villebro also, can we show all x axis label by default, like the old chart does?

**Comment by villebro** [comment] 2020-11-12 22:35
@junlincc: https://github.com/apache-superset/superset-ui/pull/834

**Comment by junlincc** [comment] 2020-11-13 02:11
> @junlincc: [apache-superset/superset-ui#834](https://github.com/apache-superset/superset-ui/pull/834)

👍
let's keep rotate 45 by default for now🙏 we can explore 'smarter' solutions post 1.0.

**Comment by rusackas** [comment] 2022-12-20 22:02
Since this thread has gone cold, and revolves around old/unsupported versions of Superset, I'm going to close this issue. If the issue persists, let's by all means open a new issue with current-era screenshots and reproduction steps. Thanks!

**Closed** 2024-02-15 03:00 UTC
Labels: !deprecated-label:bug, #bug:cosmetic, viz:charts:boxplot
