### ISSUE TITLE
Minimal settings to embed charts

### ISSUE THREAD

**Issue by waleedshabbir1** [apache/superset#23875] opened 2023-04-29 01:29 UTC
What are minimal settings to embed charts in external website for production?

We want to use charts in our production external react website. Is there any way to do that without making dataset exposed and queries exposed?

**Comment by amulya-mishra** [comment] 2023-05-03 09:32
Can you try this approach?

In `superset/config.py` file:
1. In DEFAULT_FEATURE_FLAGS dict object, set 'EMBEDDED_SUPERSET' key value to True.
2. Ensure that HTTP_HEADERS={}.
Doing this will show embed dashboard option in the superset UI and the dashoboard ID that will be used for embedding.

You can follow the below article to embed dashboard in react app (you might need to do some work around if the superset in the production is using SSL).
Embedding superset dashboard in React app - https://medium.com/@khushbu.adav/embedding-superset-dashboards-in-your-react-application-7f282e3dbd88

For reference,
Github - https://github.com/apache/superset/tree/master/superset-embedded-sdk

**Comment by waleedshabbir1** [comment] 2023-05-10 11:28
@amulya-mishra but this is for embedding dashboards. For embedding dashboard documentation is straight forward. 

I am more interested in embedding charts only.

**Comment by ss-ravi** [comment] 2024-01-19 01:41
I'm also having trouble figuring this out.
Would love any help from here!

**Comment by rusackas** [comment] 2024-05-13 20:48
Closing this as it's a question, not a bug, and has gone dormant for quite some time. If anyone wants to keep working on this, I can happily reopen it and convert it to a github discussion. Thanks!

**Closed by rusackas** 2024-05-13 20:48 UTC
Labels: #bug
