### ISSUE TITLE
Line Chart annotations dont load on Time-Series Line Charts

### ISSUE THREAD

**Issue by sholtoarmstrong-iot** [apache/superset#21694] opened 2022-10-04 09:20 UTC
#### How to reproduce the bug

1. Go to a Time-Series Line Chart. (In the screenshots the "Top 10 California Names Timeseries" was converted from a **Line Chart** to a **Time-Series Line Chart**
2. Create an annotation layer
![Create annotation layer](https://user-images.githubusercontent.com/65215432/193779663-8f37a002-0539-4647-92d3-eaf32aed7574.png)
3. Configure, apply and save the annotation layer to point to any Line Chart. In the example "Num Births Trend" was used as it is easy to see.
![Configured annotation Layer](https://user-images.githubusercontent.com/65215432/193780431-0197d124-5740-43a2-b3d7-9522831d0a0d.png)
4. Save the chart as a new chart and let the page reload.
![Save Step](https://user-images.githubusercontent.com/65215432/193784124-5a4d5405-83a8-419f-809f-7c5eb0fc2d09.png)
6. The annotation layer is now listed under annotation layers but is not rendered in the plot.
![Saved Chart](https://user-images.githubusercontent.com/65215432/193780691-d123870e-33e0-4548-a0d8-aa9bdcf0c683.png)

### Expected results

I expected that the configured annotation layer would still be persisted after the reload and also show up in dashboards.

### Actual results

The annotation layer remains configured but does not show up in the chart in both the chart editor nor the dashboard.

### Environment

(please complete the following information):

- browser type and version: 
   - Brave Version 1.42.88  Chromium: 104.0.5112.81 (Official Build)  (64-bit)
   - Firefox 105.0.1 (64-bit)
   - Chrome Version 105.0.5195.125 (Official Build) (64-bit)
- superset version: Superset 2.0.0 (067495d954ee0015d35c1437245feb66984e4c49)
- python version: 
   - Python 3.8.13
- node.js version: 
   - v18.7.0
   - v16.17.0
- any feature flags active: None

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x ] I have reproduced the issue with at least the latest released version of superset.
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar. (Most similar found https://github.com/apache/superset/issues/20441, however there are no errors in the logs frontend or backend with this issue)

### Additional context

Tested both locally and in cluster with docker image. Same error persists. 
Does not happen when annotating a line chart with a line chart but annotating a time-series line chart with a line chart seems to cause issues.

**Comment by sfirke** [comment] 2022-11-03 19:31
I can reproduce with 2.0.0.  In fact I had a chart with annotations that worked, I created it in version 1.5.2, then when I edited it in 2.0.0 the annotations stopped displaying as described here.

If it's fixed on master branch, it would be good to figure out what fixed it and cherry-pick that for 2.0.1.

**Comment by sfirke** [comment] 2022-11-03 19:37
There's this error where annotations fail with an error message: https://github.com/apache/superset/issues/20845  It is apparently fixed by this merged PR https://github.com/apache/superset/pull/20651 which will be in 2.0.1.  This issue is slightly different in that annotations are failing to display silently, no error message.  TBD if #20651 fixes this one.

**Comment by sfirke** [comment] 2022-11-09 16:06
Can confirm this is broken still in 2.0.1rc2 and fixed on `latest`.

**2.0.1rc2**
I make a time-series line chart, add an annotation with the formula `24` to get a horizontal line.  The annotation saves, it shows up in the legend and the y-axis adjusts (if I make the formula `2000` it will increase the y-axis) but the line itself is not present.  
![image](https://user-images.githubusercontent.com/7569808/200878615-52730be9-b7a9-4cb6-8030-41d2cb9f61f0.png)

**latest**
Same thing but the line appears:
![image](https://user-images.githubusercontent.com/7569808/200880548-71f48058-f6df-4081-9b28-8a934843895d.png)

**Comment by rusackas** [comment] 2022-12-15 17:55
Thanks for the detective work @sfirke - if I'm understanding correctly, and this is fixed on `latest` then this is good news... it should be in line for 2.1.0, and it may be possible to `git bisect` to figure out where it was fixed in case there's a cherry to be added to a 2.0.2, and we can check to make sure there are tests to prevent a regression. Help appreciated if anyone reading this is up to the task.

All that having been said, if indeed this is fixed on `master` then I think it's fair to close the issue. Let me know if you (dis)agree.

**Comment by sfirke** [comment] 2022-12-15 21:08
I agree with all of that and yes, there's not a bug here that needs patching on master.  My only concern with closing is this getting lost in the shuffle when it comes to planning for 2.0.2 or 2.1.0.  Could it be tagged accordingly, or otherwise noted?

**Comment by rusackas** [comment] 2023-02-09 17:53
Closing since this is fixed on `master` and will be headed toward 2.1 and/or 3.0 (since both will include the fix). If this can be isolated to a single PR, we can also apply that to 2.0.2 by making the request on [this thread](https://github.com/apache/superset/discussions/22630).

**Closed by rusackas** 2023-02-09 17:53 UTC
Labels: #bug:cant-reproduce, #bug, explore:annotation
