### ISSUE TITLE
Some annotation lines are not visible when axis Y start to zero

### ISSUE THREAD

**Issue by Leandro-GPIN** [apache/superset#12734] opened 2021-01-25 12:54 UTC
When selected axis Y to start to zero, some annotation lines are not visible. 

### Actual results

![annotation-problem](https://user-images.githubusercontent.com/19553149/105707379-9aab9f00-5ef1-11eb-8bca-9f7f2dedb064.png)

#### Screenshots

![config-axis_y](https://user-images.githubusercontent.com/19553149/105707405-a8612480-5ef1-11eb-9c4c-4475385dea36.png)

![annotation-config-problem](https://user-images.githubusercontent.com/19553149/105708314-07736900-5ef3-11eb-9d86-029032144ae4.png)

#### How to reproduce the bug

1. Set axis Y to start to zero
2. Add annotation in graph line
3. See error

### Environment

(please complete the following information):

- superset version: 37 docker
- python version: `python --version`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ x ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x ] I have reproduced the issue with at least the latest released version of superset.
- [ x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment] 2021-01-25 23:47
Thanks for reporting, but im not able to reproduce,  can you provide more information? @Leandro-GPIN

**Comment by zuzana-vej** [comment] 2021-04-20 04:20
closing as can't reproduce

**Closed by zuzana-vej** 2021-04-20 04:20 UTC
Labels: cant-reproduce
