### ISSUE TITLE
Unwanted User-Information leak in Filter-Bar (Owner/Created-User)

### ISSUE THREAD

**Issue by Rohit-pawar902** [apache/superset#23094] opened 2023-02-16 10:51 UTC
Hi I have problem related to Filter-Box.
I have an user whom I have allowed roles and some data-source permission , And In Current nature of superset in Filter-Box in field (Owner/Created-User) all users information is exposed

![Screenshot from 2023-02-16 15-56-59](https://user-images.githubusercontent.com/72196393/219343370-3a9a5b09-5beb-439b-9e0b-482515b157cf.png)

**Expected :** User can see only those user name whose Dastasources allowed to that user

**Dependency :** 

- used superset-2.0.0-dev image

**Questions**

- Is this Resolved Already ? because I have seen that it is reported in some previous issue , but not solved by anyone
- What is the things recommended to solve this problem

Thankyou in advance
@rusackas @eschutho

**Comment by villebro** [comment] 2023-02-17 10:16
@Rohit-pawar902 you can customize which users are available by leveraging functionality introduced in this recently merged PR: #22526

**Comment by villebro** [comment] 2023-02-17 10:17
Closing, as this is not a bug, but rather a customization requirement that is already available.

**Closed by villebro** 2023-02-17 10:17 UTC
Labels: #bug
