### ISSUE TITLE
Dahsboard doesn't load data until I click the "Filters out of scope" button 

### ISSUE THREAD

**Issue by FaidJalal** [apache/superset#21980] opened 2022-10-31 06:55 UTC
I have few filters in dashboards and until i click on the **Filter button** in sidebar the dashboard data does not load. I have option **Select the first value** checked in one of the filter and unchecking the same loads the data easily.
But i need this selecting the first vale.

Any fix for this

**Comment by doornot** [comment] 2022-11-01 03:33
You could try to set defaultActiveKey in `FilterControls.tsx`

![截屏2022-11-01 上午11 30 21](https://user-images.githubusercontent.com/10323102/199152554-7fdc4379-2708-4f43-b792-bf668a00bc82.png)

**Comment by FaidJalal** [comment] 2022-11-01 07:32
@doornot Can't we make similiar change in advanced properties of dashboard

**Comment by sfirke** [comment] 2022-11-01 13:59
I believe this is a duplicate of a known bug, see https://github.com/apache/superset/issues/20797 and related issues.  Pull requests have been merged onto the master branch to address this.  Actually, if you could test this with release candidate 2 for version 2.0.1, that is 2.0.1rc2, and report back here https://github.com/apache/superset/issues/20930 whether this is fixed in 2.0.1rc2, that would be very helpful for getting the fix out there!

In the meantime this could be closed as a duplicate.

**Comment by sfirke** [comment] 2022-11-01 13:59
I believe this is a duplicate of a known bug, see https://github.com/apache/superset/issues/20797 and related issues.  Pull requests have been merged onto the master branch to address this.  Actually, if you could test this with release candidate 2 for version 2.0.1, that is 2.0.1rc2, and report back here https://github.com/apache/superset/issues/20930 whether this is fixed in 2.0.1rc2, that would be very helpful for getting the fix out there!

In the meantime this could be closed as a duplicate.

**Comment by meimiao0730** [comment] 2022-11-09 09:47
> @doornot我们不能对仪表板的高级属性进行类似的更改吗

Is there anything else need to do after the change?

**Comment by meimiao0730** [comment] 2022-11-09 09:57
> You could try to set `defaultActiveKey` in `FilterControls.tsx`
> 
> ![截屏2022-11-01 上午11 30 21](https://user-images.githubusercontent.com/10323102/199152554-7fdc4379-2708-4f43-b792-bf668a00bc82.png)
Is there anything else need to do after the change?

**Comment by meimiao0730** [comment] 2022-11-09 09:57
@doornot Is there anything else need to do after the change?

**Comment by sfirke** [comment] 2023-02-26 17:51
Turns out this bug is still present in 2.1.0rc1, which came out for testing last Wednesday.  @doornot thanks for looking into a fix, as far as I know one is not available - is that fix suitable for merging as a PR?

**Comment by kgabryje** [comment] 2023-03-08 14:53
This should be fixed now by #23299

**Closed by kgabryje** 2023-03-08 14:53 UTC
Labels: #bug, v2.1
