### ISSUE TITLE
cannot be filtered using Verbose_name

### ISSUE THREAD

**Issue by xuningyang** [apache/superset#11545] opened 2020-11-04 04:01 UTC
Columns and filters in the raw data cannot be filtered using Verbose_name
Dimensions in grouping aggregation can be filtered using Verbose_name
When filtering or selecting raw data columns, the last column cannot be displayed when there are too many columns

in Chinese：原始数据中列和筛选无法使用verbose_name进行筛选
分组聚合中维度可以使用verbose_name进行筛选
筛选或选择原始数据列时，当列过多时 最后一列无法显示

### Expected results

![image](https://user-images.githubusercontent.com/30031192/98067642-04894f00-1e95-11eb-832b-b6cdc7451b9c.png)

### Actual results

![image](https://user-images.githubusercontent.com/30031192/98067703-1c60d300-1e95-11eb-9419-c6310430c74b.png)

### Environment

python: python 3.6
npm: 6.14.6
Superset 0.999.0dev
node:v12.18.3

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

![GIF](https://user-images.githubusercontent.com/30031192/98082533-db2beb80-1eb3-11eb-83d3-288a00cf213a.gif)

**Comment by zhaoyongjie** [comment] 2020-11-04 07:08
@xuningyang  请问你的意思是说: 在 table viz 中的聚合tab中可以使用 verbose_name 进行搜索维度, **而非聚合 tab 无法使用verbose_name 搜索维度?**
我有点没有理解您的问题.

**Comment by xuningyang** [comment] 2020-11-04 07:10
> @xuningyang 请问你的意思是说: 在 table viz 中的聚合tab中可以使用 verbose_name 进行搜索维度, **而非聚合 tab 无法使用verbose_name 搜索维度?**
> 我有点没有理解您的问题.

@zhaoyongjie 是的 在非聚合查询中 列和筛选字段都无法使用verbose_name进行搜索

**Comment by zhaoyongjie** [comment] 2020-11-04 07:15
@xuningyang Oh.... I reproduced it. it seems a ui bug.

**Comment by xuningyang** [comment] 2020-11-04 08:10
@zhaoyongjie yes,but I don't know how to solve it

**Comment by xuningyang** [comment] 2020-11-04 08:11
@junlincc 🙏

**Comment by zhaoyongjie** [comment] 2020-11-04 09:00
I wil check codebase tonight

**Comment by zhaoyongjie** [comment] 2020-11-05 05:17
Hi @xuningyang. this issue root cause is `all_columns` control is missing `filterOption` in plugin-chart-table. but this component populated in `superset-ui` repo.

**Comment by xuningyang** [comment] 2020-12-02 06:57
> 嗨@xuningyang。此问题的根本原因是在plugin-chart-table中`all_columns`缺少控件`filterOption`。但是此组件已存储在`superset-ui`回购中。
> 
> 在中文
> plugin-chart-table这个组件中的all_columns过滤器选项选项（而此插件在superset-ui仓库中，并不在superset仓库）。您如果需要快速修复，可以自行添加一下。以后我会提交该PR

@zhaoyongjie Hi, I have another problem, when filtering, the field have verbose_name, but after selection, it still displays column_name,Could you please help to check it,thank you!
in chinese：
您好好，我还有一个问题，当筛选时，字段存在verbose_name，但是选择后，显示的仍然为column_name，您能帮忙看下吗，实际应该显示verbose_name

**Comment by junlincc** [comment] 2021-02-15 06:52
resolved - closing

the second issue still open but I'm not sure we should display verbose name instead of actual column name. @xuningyang

**Closed by junlincc** 2021-02-15 06:52 UTC
Labels: enhancement:request
