### ISSUE TITLE
Dependent filters not working as expected

### ISSUE THREAD

**Issue by vigodeltoro** [apache/superset#26101] opened 2023-11-27 09:00 UTC
Hi there, I have a problem with dependent native filters. Maybe somebody has any help ?

best and thanks..

#### How to reproduce the bug

1. Create at least two native filters from the same table
2. Sort all filter values ascending 
3. Choose for filter 1 "Select first filter value by default"
4. Choose for filter 2 "Values are dependent on other filters" ( filter 1)
5. Choose for filter 2 "Select first filter value by default"

### Expected results
The filter 2 should choose the first filter value of the resultset dependent to filter 1.

### Actual results
Filter 2 choose the first filter value of a generic filter 2 resultset without taking care of filter 1. Which means that there are filter results for filter 2 which are not working anymore, because the two filter values combined doesn't exist in that combination in the table.

If I remove the "choose first filter value by default" it is working. But I need the preselected first value to prevent sankey loops which creates errors at the chart. 
I guess it is a problem with the sequence the filters are triggered.

### Environment

(please complete the following information):

- All browsers
- superset version: 2.1.0, 2.1.2, 3.0
- prebuild docker containers ( docker hub)
- any feature flags active:

FEATURE_FLAGS = {
      "EMBEDDED_SUPERSET": True,
      "DASHBOARD_RBAC": True,
      "DASHBOARD_CROSS_FILTERS": True,
      "VERSIONED_EXPORT": True,
      "GENERIC_CHART_AXES": True,
      "HORIZONTAL_FILTER_BAR": True
    }

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ x] I have reproduced the issue with at least the latest released version of superset.
- [x ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfirke** [comment] 2023-11-28 17:55
I believe this is a duplicate of https://github.com/apache/superset/issues/22979.  Do you agree?

**Comment by vigodeltoro** [comment] 2023-11-30 07:56
Ah .. yes, I agree. I had a look

**Comment by sfirke** [comment] 2023-11-30 18:05
I agree it's disappointing 😔 I'm going to close this issue so we can track progress on this in a single place, that linked issue.  Thanks for filing it though!

**Closed by sfirke** 2023-11-30 18:05 UTC
