### ISSUE TITLE
How to embed view flow

### ISSUE THREAD

**Issue by villers3** [apache/superset#24059] opened 2023-05-15 16:57 UTC
I want to add a video stream chart to the dashboard for real-time monitoring by the webcam. What should I do?

**Comment by rusackas** [comment] 2023-05-17 23:41
Closing this since it's not a bug, but you might want to try to start up a conversation in an Ideas thread on Github Discussions, or start up a conversation in `#customizing-superset` on [Superset Slack](http://bit.ly/join-superset-slack). 

That said, I'm not sure what you mean by monitoring a webcam.... like... bandwidth data? Audio signal? 

In any case, Superset isn't set up for realtime data all that well, though it can refresh periodically. The ECharts-based line chart supports a stream chart mode, so you would just need to have it connect to that data (whatever the source is) and refresh frequently.

**Closed by rusackas** 2023-05-17 23:41 UTC
