### ISSUE TITLE
Public access to dashboard not working in 1.2.0rc2

### ISSUE THREAD

**Issue by eduardoperezitop** [apache/superset#15280] opened 2021-06-21 10:48 UTC
In the 1.2.0rc2 version the feature that allows logged-out users to consume some Superset features is not working. I didn´t have this error in 1.1.0 with the same config.

### Expected results

I expect logged-out users to be able to access some of my dashboards

### Actual results

They get an unexpected error screen

#### Screenshots

The configuration needed:
![image](https://user-images.githubusercontent.com/84771141/122750333-46310380-d286-11eb-994d-51bb134f4e16.png)
![image](https://user-images.githubusercontent.com/84771141/122750346-4b8e4e00-d286-11eb-8588-31f898218625.png)

Actual results:
![image](https://user-images.githubusercontent.com/84771141/122750428-652f9580-d286-11eb-8a5a-1a04bee9a781.png)

The were no errors in the logs
![image](https://user-images.githubusercontent.com/84771141/123249509-ee420900-d4e0-11eb-9368-0899cd224725.png)

### Environment

(please complete the following information):

- superset version: 1.2.0rc2

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by sfkeller** [comment] 2021-07-06 08:13
I can confirm this behavour. It's a show stopper.

**Comment by sfkeller** [comment] 2021-07-06 19:49
If there would be a test for Public role, it would fail, and this new Superset version would not have been released with this bug...

**Comment by baltom** [comment] 2021-07-07 09:02
Experiencing the same issue in 1.2.0 release

**Comment by sfkeller** [comment] 2021-07-18 15:44
Experiencing the same issue in 1.2.0 release.

**Comment by sfkeller** [comment] 2022-04-30 23:43
I respect that volunteering or busy maintainers have no time to look at a issues of such a great project.
But this issue is a fundamental feature of most usages of Superset (outside AirBnB?) and it's around since years.
See e.g. #19074, #17913 + #17914, #16718, #15280 and #14504. 
And there seems to be a fix with #16507 around which is unconfirmed!?

**Comment by rajraousb** [comment] 2022-10-21 17:58
Arbitrary public access to any dashboard will no longer work.
Users have to be part of Owner field or should have RBAC, i.e. a belong to a role which has been added to the dashboard's ROLE field in Dashboard Properties, basically making them Viewer.

**Comment by rusackas** [comment] 2024-01-29 16:25
> I respect that volunteering or busy maintainers have no time to look at all issues of such a great project.
This is definitely the case! We're trying to whittle down the huge backlog of Issues and PRs to something that the small handful of us can maintain. Since this issue is reported as not reproducible, and is from two major versions ago, I'm going to close it. If there are problems in 3.x, you're welcome to post a new/updated Issue, and we'll do our best (and contributions are always welcome, we can use more hands!)

**Closed by rusackas** 2024-01-29 16:25 UTC
Labels: #bug
