### ISSUE TITLE
[Boxplot]# observations &. # row is not matching

### ISSUE THREAD

**Issue by junlincc** [apache/superset#16218] opened 2021-08-12 04:02 UTC
Please see screenshot, I'm not 100% sure this is a bug or not. It's unclear to my what # observations is 

<img width="969" alt="Screen Shot 2021-08-11 at 8 58 50 PM" src="https://user-images.githubusercontent.com/67837651/129136396-e0c8dba6-8226-4c25-98e5-440e48da7551.png">

**Comment by villebro** [comment] 2021-08-12 04:45
This appears to be referencing the "Samples" page, which does not necessarily reflect the filters in the chart. Can you share any potential filters you have selected (timee & adhoc)? Also, should we consider applying the filters to the Samples query to make it more representative of the underlying data affecting the chart? see this example, which is applying a filter which doesn't return any values, despite of which "Samples" is showing lots of data:
![image](https://user-images.githubusercontent.com/33317356/129139349-14259a34-dc47-4ad7-9f56-2eeab7d533bf.png)

**Comment by villebro** [comment] 2021-08-20 08:12
Closing due to not being able to reproduce.

**Closed by villebro** 2021-08-20 08:12 UTC
Labels: question & help wanted, viz:chart-boxplot
