### ISSUE TITLE
[sqllqb] Superset always fires "show create view" although it is a table which results in "error while fetching table metadata"

### ISSUE THREAD

**Issue by rabindragogoi** [apache/superset#26740] opened 2024-01-22 12:28 UTC
### Bug description

Superset version : 3.0.3

Error in show table schema / fetching metadata
Superset always fires "show create view" although it is a table which results in "error while fetching table metadata"

### How to reproduce the bug

1. Go to sqllab.
2. select database
3. Select schema
4. Select a table (not view)

### Screenshots/recordings

Screenshot:
![image](https://github.com/apache/superset/assets/12514180/8fe47d7d-9546-44c9-9a0c-2121b8dafbd5)

UI Screenshot:
![image](https://github.com/apache/superset/assets/12514180/7155724e-3dd7-45d1-9b26-41fe2a390c3b)

### Superset version

master / latest-dev

### Python version

3.11

### Node version

Not applicable

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by michael-s-molina** [comment] 2024-01-22 13:01
@rabindragogoi Could you please upgrade your Superset version to 3.0.3 and see if the bug still happens? As pointed out by the issue instructions:

> If your environment does not match the alternatives, you need to upgrade your environment before submitting the issue as it may have already been fixed.

I'll close the issue but please re-open it if the bug persists in the latest version.

**Comment by rabindragogoi** [comment] 2024-01-22 16:08
@michael-s-molina  : In logs there shows up no error but in the UI still I can see the error popup though I am a user of the  Admin role  

![image](https://github.com/apache/superset/assets/12514180/2e4a05b3-f5f3-4add-a614-219ed1afd5c8)

**Comment by michael-s-molina** [comment] 2024-01-22 16:13
@rabindragogoi is this reproducible in 3.0.3?

**Comment by michael-s-molina** [comment] 2024-01-22 16:16
@rabindragogoi Thanks for checking. I reopened the issue and updated the version in the description.

**Comment by michael-s-molina** [comment] 2024-01-22 16:16
@justinpark Could you take a look?

**Comment by rabindragogoi** [comment] 2024-01-23 02:19
@justinpark  : we are not using which will call Trino.py. We are using pyhive.

**Comment by rabindragogoi** [comment] 2024-01-23 03:43
@justinpark : When the above error pops up for one of the table then in logs we see this.

![image](https://github.com/apache/superset/assets/12514180/1770d231-3ebd-46b5-9cf6-0f24b035965a)

Any idea?

**Comment by justinpark** [comment] 2024-01-23 05:08
@rabindragogoi Could you share the network error shown in the chrome dev. console here?

![Superset](https://github.com/apache/superset/assets/1392866/c1190135-2eb6-4b16-aed5-b94133cfe733)

**Comment by rabindragogoi** [comment] 2024-01-23 06:09
@justinpark :

   
![image](https://github.com/apache/superset/assets/12514180/5eee73fb-639f-4818-8d3f-a904b713fc8e)

**Comment by rabindragogoi** [comment] 2024-01-23 10:04
@justinpark , @michael-s-molina  : I noticed that if the table _has a partition then it throws up the error with the error popup_ where as _if the table does not have partition it returns results_. In backend presto cli ever

Could you please very that? 

In 3.0.0 version it was throwing error for all the tables but after upgrading from 3.0.0 to 3.0.3 only for few tables it is throwing error. I think we are almost there a slight modification will fix the code. (may be in file : 
site-packages/superset/db_engine_specs/presto.py )

**Comment by rabindragogoi** [comment] 2024-01-23 14:53
@justinpark : Any other work around you want me to try?

**Comment by justinpark** [comment] 2024-01-23 17:26
@rabindragogoi From the details in both the console and browser error logs, it appears that the issue might be stemming from your connection configuration, not necessarily from superset.

![298799015-0cff28b2-4f1c-4316-ab51-3ef600711902_png__1629×333_](https://github.com/apache/superset/assets/1392866/ca4e1fd8-d3d5-420c-b61b-e55b9ab22b96)
![298821842-5eee73fb-639f-4818-8d3f-a904b713fc8e_png__1868×758_](https://github.com/apache/superset/assets/1392866/55df5a9b-b1b2-463c-982f-cfed04839fca)

@john-bodley @betodealmeida Do you have any insights regarding this issue?

**Comment by rabindragogoi** [comment] 2024-01-23 18:03
@justinpark : This is a warning and this we had in superset 1.5.2 as well. In 1.5.2 we encountered no issue and all were working good. Once we upgrade to 3.0.0 snd 3.0.3 we are facing this issue.

**Comment by rabindragogoi** [comment] 2024-01-24 06:18
@justinpark , @michael-s-molina  :  Since it is showing error while querying on top of presto database connection, I created a new Trino connection and tried but it was failing. The same connection is working well in 1.5.2 but not in superset 3.0.3

I raised an another issue for it : https://github.com/apache/superset/issues/26768

Please let me know if you find any solution. 

Thanks

**Comment by john-bodley** [comment] 2024-05-21 18:40
Re-opening because the fix was reverted in https://github.com/apache/superset/pull/28613.

**Closed** 2024-05-28 15:56 UTC
