### ISSUE TITLE
Missing data (null) in Time Series Table when no filter applied | Not a data issue from our side

### ISSUE THREAD

**Issue by lctdulac** [apache/superset#11953] opened 2020-12-07 17:51 UTC
Hi SuperSet community.

We've been encountering an UI issue with SuperSet when plotting Time Series table. Some datapoints are missing from the graphs and showing ''nulls''. However, the weird thing is, when filtering the data in the dashboard to display only the rows where we witness the issue, those data points appear correctly.

### Expected results

We except the time series to be plotted without these missing data points (nulls) as there are no nulls in the data.

### Actual results

Some random nulls appear in the chart though there are data to display.
When filtering the data, the bug disappears. 

#### Screenshots

**Without filtering :**

![Screenshot 2020-12-07 at 10 35 57_censored](https://user-images.githubusercontent.com/46674763/101335015-ea1e0900-3878-11eb-9f6c-1be7eecb0148.jpg)

![Screenshot 2020-12-07 at 10 36 22_censored](https://user-images.githubusercontent.com/46674763/101335033-eee2bd00-3878-11eb-8340-3730cbaf76d0.jpg)

**After filtering to only the rows displayed above:**

![Screenshot 2020-12-07 at 10 37 20_censored](https://user-images.githubusercontent.com/46674763/101335078-fe620600-3878-11eb-9f7c-daa152ae2612.jpg)

#### How to reproduce the bug

1. Create Time Series table.
2. Add the time series table to a dashboard.
3. Filter down on the column used to group by in the time series table.
4. Compare

### Environment

The table used for the time series table is (Rows 166,645 | Cols 42) queried using Presto SQL Engine.
We are aggregating on a VARCHAR column and the data plotted is of type BIGINT.

- superset version: 0.37.2
- python version: 3.6.12

### Additional context

The dashboard is very big (close to the size limit).

**Comment by junlincc** [comment] 2020-12-08 07:16
thanks for reporting, we are looking into it! 

@eugeniamz do you have this issue? im not able to reproduce this issue with our sample datasets.

**Comment by eugeniamz** [comment] 2021-01-11 11:54
This chart has a limit of 5000 rows, check that it did not reach the limit 
![image](https://user-images.githubusercontent.com/58375897/104179360-b8e5ab00-53d9-11eb-9c7d-030d582a5a08.png)

@junlincc  the row limit seems to be fixed, we should allow users to change this limit as in other charts. is there a reason why is limited to 5K?

**Comment by lctdulac** [comment] 2021-02-01 14:43
Thanks for the answer @eugeniamz ! This is exactly our issue. I did not acknowledge the limit was so low but this is exactly the reason why some datapoints are missing in the charts as one row is one daily point on a chart. Any idea of a follow up action to increase that limit, or make it editable? 
Thanks all.

**Comment by nytai** [comment] 2021-04-21 19:39
fixed by ☝️

**Closed by nytai** 2021-04-21 19:39 UTC
Labels: assigned:flexiana, bug, viz:chart-time-table
