### ISSUE TITLE
SQL Lab saved query appears as "untitled" in new SQL Lab window

### ISSUE THREAD

**Issue by zuzana-vej** [apache/superset#11804] opened 2020-11-25 00:24 UTC
When user saves a SQL Lab query, and then opens a new browser tab and loads SQL Lab (or closes browser and opens SQL Lab again later), the earlier saved query is labeled as "untitled query". The query is however saved and view from the saved queries CRUD view.

### Expected results

The query tab should have the correct title of the saved query.

### Actual results

The query tab is labeled as untitled.

#### Screenshots

Step 1: Save a query.
![Screen Shot 2020-11-24 at 4 16 37 PM](https://user-images.githubusercontent.com/61221714/100166238-11d0a280-2e71-11eb-8add-f1722e2ca559.png)

Step 2:
Open SQL Lab in a new browser tab - see bug, the earlier saved query is Untitled.
![Screen Shot 2020-11-24 at 4 16 53 PM](https://user-images.githubusercontent.com/61221714/100166278-29a82680-2e71-11eb-896a-28b39aedc451.png)

Step 3:
It got saved into the saved queries list in crud view
![Screen Shot 2020-11-24 at 4 17 08 PM](https://user-images.githubusercontent.com/61221714/100166292-33318e80-2e71-11eb-991b-ee95f89cb415.png)

#### How to reproduce the bug

1. Go to SQL Lab
2. Write query and click on Save query
3. Open SQL in a new browser tab (or close existing tab and open SQL Lab again)
4. See issue - the earlier saved query is shown as unitled.

### Environment

(please complete the following information):

- superset version: `superset master`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

This is a regression, I noticed is couple days back first, it might have been introduced couple weeks back.

**Comment by nytai** [comment] 2020-11-25 00:31
@zuzana-vej do you have the feature flag `SQLLAB_BACKEND_PERSISTENCE` enabled in your environment?

**Comment by zuzana-vej** [comment] 2020-11-25 00:41
No I don't think so. Was there recent changes in this area though? (because this wasn't issue in the past)

**Comment by nytai** [comment] 2020-11-25 00:44
I'm not sure about recent changes, but things work quite differently depending if you have that flag enabled or not

**Comment by zuzana-vej** [comment] 2020-11-25 00:48
ok thanks for the suggestion, I will reopen if needed.

**Comment by nytai** [comment] 2020-11-25 00:53
@zuzana-vej I'm seeing the same issue even with the flag enabled. Looks like the saving the query only temporarily renames the tab? and reloading sqllab the tab state reverts back to what it was called before saving the query. Opening the query from the CRUD view results in a correct tab name though. 

The tab positions also seem to be moving around

**Comment by zuzana-vej** [comment] 2020-11-25 00:55
Yes exactly. It saves it at that moment, but not when you open SQL Lab in a new window. And yes - it saves it in the backend since it's then in the crud view, and opening from there, the tab is named correctly.

**Comment by yousoph** [comment] 2020-11-25 22:22
Hmmm, I'm having trouble repro-ing this on master today. Are you still seeing it, @zuzana-vej ?

**Comment by zuzana-vej** [comment] 2020-11-25 22:26
Yes, but I am few days behind. I will check again when I have new version. But based on flipping through closed PRs, I didn't see anything that was merged that would have fixed this in last few days. Initially the query name saves, but it's when you open SQL Lab in a new browser tab (or you close SQL Lab and open it again) when the title is again unknown.

**Comment by nytai** [comment] 2020-11-25 22:30
I can confirm this was an issue in the latest version yesterday. I think the repo steps are not so clear

**Comment by yousoph** [comment] 2020-12-17 18:43
This happens when SQLLAB_BACKEND_PERSISTENCE is True

**Comment by hughhhh** [comment] 2021-01-11 17:38
I not able to reproduce on master, so closing now.

https://www.loom.com/share/6417eef61a3247bf972aa794670ba152

**Comment by etr2460** [comment] 2021-01-15 17:50
@hughhhh did you try reproing this with `SQLLAB_BACKEND_PERSISTENCE=True`? I've been able to repro consistently with that setting active

**Comment by yousoph** [comment] 2021-01-15 19:16
Thanks @etr2460 ! Yeah, I think he was able to repro now so reopened the issue. I think the flag wasn't set properly earlier so it looked like it wasn't happening.

**Comment by etr2460** [comment] 2021-01-27 23:46
Thanks for the update @yousoph! Do you or @hughhhh have any update on resolving it?

**Comment by yousoph** [comment] 2021-01-28 22:34
Still on our radar! But we don't have a fix yet

**Comment by hughhhh** [comment] 2021-01-29 17:57
This PR has the fix:
https://github.com/apache/superset/pull/12607

**Comment by yousoph** [comment] 2021-01-29 18:45
I missed that PR, thanks @hughhhh !!! :)

**Closed** 2021-01-29 19:05 UTC
Labels: bug, sql_lab
