### ISSUE TITLE
Issue with display of labels with new Bar chart

### ISSUE THREAD

**Issue by sqja** [apache/superset#26159] opened 2023-12-01 14:47 UTC
Hello,

Previously with legacy bar chart widget (which is now deprecated), we can see a label under every bar.
![image](https://github.com/apache/superset/assets/130609036/c72b47c7-58c4-4223-a3e4-04f1d65f6487)

With new bar chart widget (with Superset v3.0.1 version), it seems there is no possibility to obtain the same result with a label for every bar, only one bar out of two gets a label.
![image](https://github.com/apache/superset/assets/130609036/fd1b0560-1546-49c6-9c78-fd9fbbfed451)

The field in X axis is a String, with legacy bar chart it was used in mandatory 'Dimensions' section of the configuration, with the new bar chart it is used in the mandatory 'x-axis' section of the configuration.

Could you please advise if there is a way to attain the same result with new bar chart widget or if it is a regression ?

Best regards

**Comment by michael-s-molina** [comment] 2023-12-01 18:05
@villebro I assigned this issue to you as I think you worked on a feature that might be related.

**Comment by villebro** [comment] 2023-12-04 22:23
@sqja this is intentional, and is to ensure the labels don't overlap. To force the labels to render, you can switch the rotation from 0 degrees to 45 degrees. See an example below with lots of categories:

<img width="846" alt="image" src="https://github.com/apache/superset/assets/33317356/f71b7464-bf3b-41a7-8618-24b6886aeb3f">

@sfirke I believe the behavior you're seeing is expected behavior - when the x-axis is numeric or temporal, it will dynamically calculate where to place the ticks/labels. To get the previous behavior (which was in fact a regression from 2.x to 3.0, IIRC), you can cast the numeric x-axis to a string, after which it should render correctly. As a follow-up, we may want to add a control for forcing numerical (or even temporal) x-axes to categorical ones to avoid having to cast to VARCHAR or other categorical type. Thoughts @sfirke @michael-s-molina ?

**Comment by michael-s-molina** [comment] 2023-12-05 15:06
> To get the previous behavior (which was in fact a regression from 2.x to 3.0, IIRC), you can cast the numeric x-axis to a string, after which it should render correctly. 

This might be a solution given that I didn't see a viable alternative using ECharts. One small change we can do is to add the 90° rotation to the rotation control. Right now it only contains 0° and 45° and even though you can manually enter 90°, it would help given that that's what you'll probably need if you have a large dataset.

Keep in mind that by converting temporal and numeric values to categories you will have the same problem outlined by https://github.com/apache/superset/issues/26034. So it's a trade-off that users need to evaluate but at least we give them the option.

> As a follow-up, we may want to add a control for forcing numerical (or even temporal) x-axes to categorical ones to avoid having to cast to VARCHAR or other categorical type.

I think having this control is important because manually forcing the conversion will be a painful experience.

**Comment by villebro** [comment] 2023-12-05 18:50
FYI, I believe we used to have a 90 degree option, but it was removed for some reason. I forget what it was, but I also propose adding it back.

**Closed** 2023-12-07 13:03 UTC
Labels: validation:validated

**Comment by sfirke** [comment] 2023-12-07 13:34
I'm satisfied with that resolution, thanks for the discussion and restoring the 90 degree rotation.

Can we add this to the release notes, as it will be a change that some users may notice and wish to undo? Even if it's not breaking since it's fixing a regression. Maybe we link back to this issue.

**Comment by michael-s-molina** [comment] 2023-12-07 13:51
> Can we add this to the release notes, as it will be a change that some users may notice and wish to undo? Even if it's not breaking since it's fixing a regression. Maybe we link back to this issue.

https://github.com/apache/superset/pull/26208

**Comment by eliaetzensperger** [comment] 2025-02-21 16:16
The legacy bar chart was more flexible for my opinion. My problem here is related to the present issue here. I also changed the rotation of the x axis to 45 degree but the chart is not performing well with long lables on the axis. The legacy bar chart on the other hand truncated the labels at a certain threshold so the chart was adequately embeded acording to the chart size. The new bar chart unfortunately tries to display the full label extent and as a result, the chart is completely shifted and distorted - the embeding is not suitable. Do you have a hint here?

legacy bar chart:

![Image](https://github.com/user-attachments/assets/9ca5265f-4faf-43e6-b6cf-e4a41acb7c37)

new bar chart:

![Image](https://github.com/user-attachments/assets/416d43d9-6f9b-4519-a881-20834250f26b)

**Comment by sfirke** [comment] 2025-02-21 16:53
@eliaetzensperger that second screenshot indeed looks awful. I think it would be reasonable to say that going from automatic truncation to no truncation of labels is a regression, and I would suggest searching for an existing issue and if none exists, opening a new one.

In the meantime though I would think a workaround could be to create a new calculated column that truncates the label column and then use that column in the chart.

**Comment by eliaetzensperger** [comment] 2025-02-24 09:56
@sfirke thank you for your response. Your recommended workaround is exactly what i have tried and it is indeed viable.
