### ISSUE TITLE
 Excel  exported  contains HTML content

### ISSUE THREAD

**Issue by PenneyHuang** [apache/superset#23690] opened 2023-04-14 08:03 UTC
I followed the steps in this issue #19391 to solve the URL embedding problem, but when exporting to Excel, it brought out HTML content. Is there a good solution
![image](https://user-images.githubusercontent.com/42743251/231983001-7cdbbb0a-a271-4c13-a636-453e50ee361f.png)

**Comment by PenneyHuang** [comment] 2023-04-14 08:08
#19391

**Comment by rusackas** [comment] 2023-04-20 20:42
Well, that HTML _is_ the data, which is accurate, so I think I'll close this since it's not a bug. 

That said, you could just delete the column in Excel if it's extraneous, or add a transformation formula on the Excel side to clean it up and leave the URL, if that's what's needed. 

Superset doesn't have either an "Exclude from export" option (which could be a new checkbox in the dataset editor) or a "strip HTML on export" option. If you're in need of a feature like that, we'd be happy to review a PR, or seek volunteers in an Issues thread on Github's Discussions tab.

**Closed by rusackas** 2023-04-20 20:42 UTC
Labels: #bug
