### ISSUE TITLE
The datasets used by native filters are not included in the dashboard export

### ISSUE THREAD

**Issue by rakeshadk7** [apache/superset#15531] opened 2021-07-02 17:34 UTC
When a dashboard is exported not all the associated datasets are exported. 
The datasets used by all the charts are exported but the datasets used only in native filters are missing in the exported zip file. 

### Expected results

The dashboard export should contain all the datasets used in the dashboard including the datasets used by native filters. 

### Actual results

The dashboard export contains the datasets used by the charts but is missing the datasets that are used only by native filters.

#### How to reproduce the bug

1. Go to a dashboard that uses native filters and has some charts. The native filters must use a dataset that is not used by any of the other charts
2. Export the dashboard
3. Unzip the exported zip file
4. Expand the datasets directory and notice that the datasets used by the charts are present but the dataset used by the filters are missing 

### Environment

- superset version: 1.3 branch
- Python version: Python 3.7.9
- node.js version: 14

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rakeshadk7** [comment] 2021-07-02 17:34
@amitmiran137

**Comment by amitmiran137** [comment] 2021-07-02 18:08
Thank you for reporting @rakeshadk7

**Comment by junlincc** [comment] 2021-07-02 22:06
duplicate of https://github.com/apache/superset/issues/15484
@amitmiran137 are you gonna work on it?

**Closed** 2021-08-02 13:10 UTC
Labels: #bug, P1, duplicate, v1.3, viz:dashboard:native-filter
