### ISSUE TITLE
[Cosmetic][Explore] Time Grain dropdown overlaps with Query Mode control

### ISSUE THREAD

**Issue by ktmud** [apache/superset#12325] opened 2021-01-07 08:51 UTC
## Screenshot

<img src="https://user-images.githubusercontent.com/335541/103871713-447dd580-5082-11eb-98b6-d346d1405110.png" width="400">

## Description

Time Grain dropdown z-index too low, it intertwines with Query Mode control.

**Comment by junlincc** [comment] 2021-01-07 14:15
it's duplicate of https://github.com/apache/superset/issues/12312
fixed by https://github.com/apache/superset/pull/12327

**Closed by junlincc** 2021-01-07 14:15 UTC
Labels: bug:cosmetic, viz:explore:control
