### ISSUE TITLE
[Dashboard] The popover menu does not show when selecting a text component

### ISSUE THREAD

**Issue by geido** [apache/superset#14555] opened 2021-05-10 18:10 UTC
When editing a dashboard, the popover menu for text-based components is not showing up

### Expected results

When editing a dashboard and selecting a text component, the popover menu should show up

### Actual results

It does not show up

#### Screenshots

<img width="831" alt="Screen Shot 2021-05-10 at 21 08 15" src="https://user-images.githubusercontent.com/60598000/117704859-04676480-b1d4-11eb-8c30-1600d8a19109.png">

#### How to reproduce the bug

1. Go to a dashboard and enable the edit mode
2. Click on a text component
3. The popover menu does not appear

**Comment by geido** [comment] 2021-05-10 18:10
@junlincc @rusackas

**Comment by junlincc** [comment] 2021-05-10 20:14
thanks for reporting! 
looks like edit menu is missing in multiple places 
expected behavior 
<img width="1789" alt="Screen Shot 2021-05-10 at 1 13 37 PM" src="https://user-images.githubusercontent.com/67837651/117718919-a0bc4780-b191-11eb-9b03-3a8b0d14561e.png">

**Comment by geido** [comment] 2021-05-11 14:58
For clarity, what this issue is reporting specifically is the missing popover menu for text components. I have forced it to show it in the screenshot below. It seems the position is messed up

<img width="710" alt="Screen Shot 2021-05-10 at 21 07 35" src="https://user-images.githubusercontent.com/60598000/117837499-2b7c6f80-b282-11eb-9d3a-35f78a67f37c.png">

This issue instead #14554 is reporting the problem with the missing row actions, which I think is what @junlincc  is referring to in the comment above

**Comment by geido** [comment] 2021-05-12 12:09
@pkdotson I am going to tackle this one

**Comment by geido** [comment] 2021-05-13 08:46
@junlincc @rusackas this now looks resolved on master

https://www.awesomescreenshot.com/video/3727489?key=956839d019ff263f990addb8a6f32b07

**Comment by suddjian** [comment] 2021-05-13 22:18
Agreed. Closing this.

**Closed by suddjian** 2021-05-13 22:18 UTC
Labels: #bug, Flexiana, P1, bash!
