### ISSUE TITLE
With GENERIC_CHART_AXES enabled, SORT BY doesn't seem to work

### ISSUE THREAD

**Issue by G0m3e** [apache/superset#20198] opened 2022-05-26 04:41 UTC
#### How to reproduce the bug

1. Dataset SQL as below
`SELECT 'Total' AS `TYPE`, 111 AS `T_NUM`
UNION ALL
SELECT 'Average of Go-live', 10
UNION ALL
SELECT 'Average of Project', 200`
2. Make a new Bar Chart v2 and select TYPE  as X-AXIS, 
3. "SORT BY" with custom sql below
`FIELD(TYPE, 'Total', 'Average of Project', 'Average of Go-live')`

### Expected results

x-axis shows in order of  'Total', 'Average of Project', 'Average of Go-live'

### Actual results

x-axis always shows in order of  'Average of Go-live', 'Average of Project', 'Total' no matter SORT BY is enabled or not
PS: the same SORT BY sql works with "Bar Chart"

#### Screenshots

![image](https://user-images.githubusercontent.com/19158762/170416177-a1e3b94f-e57c-4bdd-b323-d34d5353ac41.png)

### Environment

(please complete the following information):

- browser type and version: Edge  101.0.1210.53
- superset version: 1.5.0
- python version: 3.8.9
- node.js version: v16.13.2
- any feature flags active: GENERIC_CHART_AXES

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by kamalkeshavani-aiinside** [comment] 2022-05-26 05:58
@G0m3e 
The 'SORT BY' option here is to sort the series, when using series limit.
I don't think custom sorting of X-axis labels with GENERIC_CHART_AXES is supported yet, you should request that feature and close this issue.

**Comment by villebro** [comment] 2022-05-26 06:19
Thanks for answering @kamalkeshavani-aiinside . You're right, the sort by control is used for series limiting, as stated in the tooltip:
![image](https://user-images.githubusercontent.com/33317356/170428941-ae99c82b-9f0b-489a-b0f3-ab294fdb6bf0.png)
Closing, as this what the OP is referring to is a feature request, not a bug.

**Closed by villebro** 2022-05-26 06:19 UTC
Labels: #bug
