### ISSUE TITLE
How can I obtain all the content of a certain Kanban in the form of images on a regular basis?Thank u！

### ISSUE THREAD

**Issue by 81354791** [apache/superset#23487] opened 2023-03-25 14:36 UTC
I hope that all the charts and text of a certain dashboard can be automatically generated as downloadable images every day (on a regular basis). How can I obtain all the content of a certain Kanban in the form of images on a regular basis?Thank u！
我希望某一个看板的所有图表和文字能够每天（定时）自动生成为可下载的图片，请问我可以怎么以图片的形式定时获取某一看板的所有内容？

**Comment by mdeshmu** [comment] 2023-03-25 17:15
Q. I hope that all the charts and text of a certain dashboard can be automatically generated as downloadable images every day (on a regular basis).

A. Yes

**Comment by mdeshmu** [comment] 2023-03-28 01:30
I kind of answered in my last comment.

**Comment by mdeshmu** [comment] 2023-03-29 17:08
@81354791 can we close this issue? Otherwise please move it to a discussion as it is not a bug as such.

**Comment by qing-shan-z** [comment] 2023-05-06 03:01
Hello, the requirements you described are very similar to email reporting requirements. Regularly push screenshots of the dashboard to the email.

Official tutorial document: https://apache-superset.readthedocs.io/en/latest/installation.html#email -reports

**Comment by qing-shan-z** [comment] 2023-05-06 03:03
@81354791

**Comment by rusackas** [comment] 2024-02-28 06:32
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering issues in this area in current versions (currently 3.x) please open a new Issue or a PR to address the problem.

**Closed by rusackas** 2024-02-28 06:32 UTC
