### ISSUE TITLE
The docker image tagged latest does not deploy the latest stable version

### ISSUE THREAD

**Issue by qiaofeng1227** [apache/superset#16679] opened 2021-09-13 04:04 UTC
![image](https://user-images.githubusercontent.com/43192516/133022305-8fc23b3d-a8eb-4a2b-a9cb-b423eb52ab48.png)

![image](https://user-images.githubusercontent.com/43192516/133022379-7fcdcb6c-dc4b-47f9-9640-4489e407ae4b.png)

![image](https://user-images.githubusercontent.com/43192516/133022028-a591a2b9-529a-441d-97e9-354a2363cec2.png)

**Comment by qiaofeng1227** [comment] 2021-09-13 04:07
I want to use docker-compose.yml to get a product version of superset, but the version is 0.0.0dev.
There is something wrong with my operation. Please help me. Thank you very much.

**Comment by qiaofeng1227** [comment] 2021-09-14 01:28
I start superset follow the documentation:
https://superset.apache.org/docs/installation/installing-superset-using-docker-compose

**Comment by qqliang** [comment] 2021-09-14 02:17
I ran into the same problem. I wanna know the version of superset in docker, which is convenient for development.

**Comment by srinify** [comment] 2021-09-22 16:12
Hi y'all! 0.0.0dev refers to running a non-versioned release. For a versioned release, you can use:

- Pip: `pip install apache-superset==1.2.0`
- docker run for specific version of Superset: `apache/superset:1.3.0`
- docker compose, you can update the config file to use a hardcoded superset version (instead of latest)

**Comment by youngsol** [comment] 2021-10-04 14:49
![image](https://user-images.githubusercontent.com/4494723/135873085-4401cb33-410e-40c6-9162-7d85b011e9a0.png)
change this line to
```
apache/superset:1.3.0
```

**Comment by rusackas** [comment] 2023-02-02 20:08
This is an old/stale issue, but I fear it may still be relevant. Any input @hughhhh / @craig-rueda ?

**Comment by Robin-Brandt** [comment] 2023-02-24 17:37
I can confirm this issue still persists in the frontend on version `1.5.3`

**Comment by sfirke** [comment] 2023-03-01 21:10
What is the issue - that running a latest dev version shows '0.0.0dev` in the UI?  That doesn't feel like a bug necessarily but some of the friction here could be addressed by implementing a new tag like `official` and pointing people to that instead of `latest`, as discussed here: https://github.com/apache/superset/discussions/22244

**Comment by JoeJordan1** [comment] 2023-11-20 08:18
I can also confirm that this is still an issue. We also pull the latest version in docker, however the UI only shows `0.0.0dev`.  When looking in the running app, as explained here: https://github.com/apache/superset/issues/4634 I have checked both the package.json file and version_info.json but they also just list the version as `0.0.0dev`. 

I have recently upgraded superset to the latest 3.0.1 release, I believe, but I can't confirm whether the upgrade has worked, as I can't determine the version either prior to or after the upgrade. I think the only way to check is to trawl through the UI for features that may have been introduced, but this is by no means a reliable solution.

**Comment by sfirke** [comment] 2023-11-20 15:44
The Superset build process was recently changed so that the `latest` docker tag should point to the latest official release.  Right now that's 3.0.1.  See Pull Request https://github.com/apache/superset/pull/25322.  Unfortunately things still seem to need work here.

I am comparing the [contents of the latest image](https://hub.docker.com/layers/apache/superset/latest/images/sha256-c8df09d7013b9e00449280303bec766cec904c42fcf2057366f9a5f30095c80b?context=explore) with the [contents of the 3.0.1 image](https://hub.docker.com/layers/apache/superset/3.0.1/images/sha256-e0b0dcdcbc2c62aae9e3882bb8f4ac50510efbe8369232639f73fbe6953b392d?context=explore).  They are not identical.  The `latest` image was created 7 hours later on the same day (2023-10-18), it's bigger (1.29GB instead of 1.11GB), and most troubling when I switch from 3.0.1 to latest on the same metadata db the installation breaks due to an apparent database migration.

**What Superset administrators can do:** don't point to the `latest` image in your Docker or Kubernetes deployment, instead point to a specific release tag like 3.0.1.

**What developers & the project can do:** Have the latest tag be applied to the image so that `3.0.1` and `latest` are identical.  Ideally `latest` is just functioning like an alias.  This would mean that users see 3.0.1 as the version inside the UI.

**Comment by mistercrunch** [comment] 2024-02-01 22:01
I need docker hub push perms to re-publish releases! Currently it's only triggered by CI where the perms exist, and it's tricky to do since the GitHub action and docker logic is different in the old branches. 

Question though, are we mostly caring about overall latest builds here?

Wondering if there's such thing as "major" and "micro" latest tags as in `3.0-latest` (might point to 3.0.99), and `3-latest` might point to `3.99.99`

**Comment by mistercrunch** [comment] 2024-02-01 22:02
Note that I documented the work that I did here https://github.com/apache/superset/pull/26923/files#diff-3d81145232d337c575e1626a0d209c2e9219a42ade8fd214499acc13d8dbe185 , but it only affects builds moving forward for now.

**Comment by rusackas** [comment] 2024-05-31 17:50
Sounds like things are all fixed going forward, so we can likely close this out as an active issue. If anyone disagrees, we can certainly revisit/reopen as warranted.

**Closed by rusackas** 2024-05-31 17:50 UTC
Labels: validation:validated
