### ISSUE TITLE
Add Guide for connecting to Supabase 

### ISSUE THREAD

**Issue by J0** [apache/superset#21961] opened 2022-10-28 07:20 UTC
[Supabase](https://github.com/supabase/supabase) is an open source firebase alternative. It is built on top of Postgresql and contains services which provide Authentication, instant APIs, Edge Functions, Realtime subscriptions, and Storage. 

Since Supabase just makes use of Postgres, it should be fairly easy to connect Supabase to Superset. As this is something that I'd be keen to explore and try setting up, I'd be happy to write the corresponding guide and file a PR if it's something of interest to the community.

Let me know!

Disclaimer: I work for Supabase but am doing this in my own capacity as someone who wishes to try using Superset on top of Supabase

**Comment by rusackas** [comment] 2024-02-12 22:28
Hi there... closing this since it's not a bug, and it's been open for so long, but heck yeah, we're open to a contribution like this. Please let us know if you haven't found the docs/info you'd need to do it, and we'd be more than happy to review a PR for this!

**Closed by rusackas** 2024-02-12 22:28 UTC
