### ISSUE TITLE
Attach new report to the dashboard again, but there are no error messages on the page

### ISSUE THREAD

**Issue by tenglong3158** [apache/superset#18225] opened 2022-01-29 08:38 UTC
Attach new report to the dashboard again, but there are no error messages on the page.

#### How to reproduce the bug

1. Select a dashboard with reports and open it;
2. Then add a new report to the dashboard;
3. At this point, a 409 error will be reported, but there is no prompt on the page.
### Expected results

Error message displayed on the page

### Actual results

a 409 error will be reported, but there is no prompt on the page.

#### Screenshots

![image](https://user-images.githubusercontent.com/20203245/151653714-793284be-8f3a-4aac-ba6a-1f80b920ef55.png)

### Environment

(please complete the following information):

- browser type and version: chrome 97.0.4692.99
- superset version: 1.4.0 Source code deployment
- python version: Python 3.8.12
- node.js version: v14.15.5
- any feature flags active:  "ALERT_REPORTS": True,

**Comment by tenglong3158** [comment] 2022-01-29 08:55
![image](https://user-images.githubusercontent.com/20203245/151654423-2d5baa9a-4da8-4177-bba9-95be30ea1caf.png)
The value returned by this method 'getClientErrorObject' does not have the attribute 'message'.

From the screenshot below, you can see that the 'message' property of error is not assigned a value.

![image](https://user-images.githubusercontent.com/20203245/151654523-abc301d4-77c5-4d4d-bd8c-c2f52771061e.png)

**Comment by rusackas** [comment] 2023-01-26 16:06
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!

**Closed by rusackas** 2023-01-26 16:06 UTC
Labels: good first issue, #bug, preset:cares
