### ISSUE TITLE
Can not specify recipient for slack or email for Superset Reports 

### ISSUE THREAD

**Issue by steele-boolkin** [apache/superset#28712] opened 2024-05-27 11:59 UTC
### Bug description

HI, 

On Superset Reports, I can't add a recipient under the notification section (for slack or email). Its almost as if the validation (that it has been supplied) does not recognise it. 

On Superset Alerts i do not have this issue but it presents on Reports.

### How to reproduce the bug

1. Go to Superset Reports
2. Add a new report
3. Add a slack or email recipient

### Screenshots/recordings

![Screenshot 2024-05-27 at 13 57 26](https://github.com/apache/superset/assets/149177200/d988a2bd-0d2e-48e6-9a73-c58e7daf514d)

### Superset version

4.0.1

### Python version

3.10

### Node version

16

### Browser

Chrome

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [ ] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [ ] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by bennyhawk** [comment] 2024-05-27 14:19
+1 

I am facing the same issue. After a bit of shallow searching, this issue from early 2021 also seems to be somewhat similar, if it helps.

[Superset | Issue 12715](https://github.com/apache/superset/issues/12715)

**Comment by SkinnyPigeon** [comment] 2024-05-28 08:00
We've also got the same issue

**Comment by SkinnyPigeon** [comment] 2024-05-30 06:44
For us it is that issue and we're waiting on the fix to upgrade to 4.x.x

**Comment by giacomochiarella** [comment] 2024-06-02 08:00
same issue here, Superset 4.0.1. Cannot change existing alerts/reports recipients and cannot create new alerts/reports because the save button is not enabled after adding all the information. Looks like the issue is in the Notification settings because all the sections have the green thick except the notification section which has a red cross

**Comment by steele-boolkin** [comment] 2024-06-03 06:29
> Are you all talking about #28149 which was fixed in #28409? Or is this something different?

Thanks ! 

It looks like it. Where do we see if it will be included in 4.0.2?

**Comment by sfirke** [comment] 2024-06-03 11:01
4.0.2 hasn't been cut yet, I think @michael-s-molina is managing that release and I believe he has said to expect mid-June. When the release candidate comes out for testing and a vote, anyone can check that this is fixed. I personally would vote against a release that didn't have this fix but I'm sure it will be included. 

Anyone can subscribe to the dev@apache email list to stay informed about releases. And anyone can test the release candidates and vote on them.

**Closed** 2024-06-03 11:02 UTC
Labels: alert-reports

**Comment by sfirke** [comment] 2024-06-18 14:23
Alright folks watching this issue: Superset 4.0.2 is up for a vote!  Anyone is welcome to test out the release and vote on it.  Test it by deploying the docker image: [apache/superset/4.0.2rc1](https://hub.docker.com/layers/apache/superset/4.0.2rc1/images/sha256-c1dbdce290c7a41e4bb41c6d3f88c721eb684cf23bb99ff9e838ce3b3911700e?context=explore) or `apache/superset/4.0.2rc1-dev`.

Vote by subscribing to the public email list https://lists.apache.org/list.html?dev@superset.apache.org and replying to the email Michael sent this morning!  Please test that this bug is fixed and that everything else works as it should.  I am going to copy-paste this message onto a couple of other issues for visibility, sorry to folks who get multiple messages.
