### ISSUE TITLE
Can't start without authlib if OAUTH enabled

### ISSUE THREAD

**Issue by korjavin** [apache/superset#18138] opened 2022-01-22 16:39 UTC
#### How to reproduce the bug

1. Enable OAUTH
2. Try to start

### Actual results

```
 File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 259, in locate_app
    return find_app_by_string(script_info, module, app_name)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 184, in find_app_by_string
    app = call_factory(script_info, attr, args)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 119, in call_factory
    return app_factory()
  File "/app/superset/app.py", line 44, in create_app
    raise ex
  File "/app/superset/app.py", line 37, in create_app
    app_initializer.init_app()
  File "/app/superset/initialization/__init__.py", line 616, in init_app
    self.init_app_in_ctx()
  File "/app/superset/initialization/__init__.py", line 564, in init_app_in_ctx
    self.configure_fab()
  File "/app/superset/initialization/__init__.py", line 656, in configure_fab
    appbuilder.init_app(self.superset_app, db.session)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/base.py", line 202, in init_app
    self.sm = self.security_manager_class(self)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/sqla/manager.py", line 54, in __init__
    super(SecurityManager, self).__init__(appbuilder)
  File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/manager.py", line 263, in __init__
    from authlib.integrations.flask_client import OAuth
ModuleNotFoundError: No module named 'authlib'
```

**Comment by Ceridan** [comment] 2022-01-23 19:55
As far as I know, it is not a bug. This is expected behavior. OAuth is an option, so the required dependency is optional too. You may install it by yourself.
Check documentation [Custom OAuth2 Configuration](https://superset.apache.org/docs/installation/configuring-superset) section from the docs. It says:

> Make sure the pip package Authlib is installed on the webserver.

Additionally, if you start Superset locally with Docker, here are some notes in the README on how to add additional packages:
https://github.com/apache/superset/blob/master/docker/README.md#local-packages

**Comment by korjavin** [comment] 2022-01-24 00:09
I don't think it's normal to have an ability to break the app by adding a line into its config file.

What is the reason not to have authlib installed? To save 1 MB in docker image?

**Comment by geido** [comment] 2022-01-24 11:04
Hello @korjavin thanks for opening this issue. If you think the Authlib package should be installed by default feel free to open an enhancement request and we can discuss that further. I am closing this issue for the time being. Thank you!

**Closed by geido** 2022-01-24 11:04 UTC
