### ISSUE TITLE
[table] maximize broken

### ISSUE THREAD

**Issue by kamalkeshavani-aiinside** [apache/superset#15541] opened 2021-07-05 09:21 UTC
Maximize table chart crops the data in right side.
### Expected results
It should show full table

### Actual results
Table is cropped from right edge.

#### Screenshots
![image](https://user-images.githubusercontent.com/74634977/124448112-0a855600-ddbd-11eb-96bb-22e7742fa835.png)

#### How to reproduce the bug

1. Maximize table chart from dashboard

### Environment
- superset version: `superset 1.2`
- python version: `3.7`
- node.js version: `node -v`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context
https://github.com/apache/superset/issues/13600

**Comment by stephenLYZ** [comment] 2021-07-11 05:12
It looks normal in master branch.
![image](https://user-images.githubusercontent.com/11830681/125183501-86622100-e249-11eb-9872-bd33f0d01be4.png)

**Comment by suddjian** [comment] 2021-07-29 22:18
Closing this as can't reproduce. Feel free to reopen if more complete repro steps can be found.

**Closed by suddjian** 2021-07-29 22:18 UTC
Labels: #bug, P2, bash!, viz:chart-table, viz:dashboard:max
