### ISSUE TITLE
Pagination table chart downloading only first page

### ISSUE THREAD

**Issue by Narendra678** [apache/superset#19848] opened 2022-04-26 07:44 UTC
Hi Team,

Current behaviour: When download table chart it is downloading only first page.

Expected: When download table chart it should download all pages.

![image](https://user-images.githubusercontent.com/88739186/165248059-97b6766f-0ff2-45b3-9742-37868612ca56.png)
In above image, when i click on export csv it is downloading only first page. Needs to be download 16th page data.
Note: enabled Server pagination

Superset version: 1.3.1

Regards,
Naren

**Comment by Narendra678** [comment] 2022-04-28 07:31
Any one have solution for this or can i consider this as bug?
?

**Comment by rusackas** [comment] 2023-06-01 22:27
Hmm... this is right in the middle between bug and feature request. There's an `ALLOW_FULL_CSV_EXPORT` feature flag, which allows full CSV export of tables _from the dashboard context_, but it doesn't seem to be wired up to do so in the chart builder UI. Also, the reason this is a feature flag is because downloading the full dataset may bog down your server and/or browser, so it's super risky with giant datasets.

I'm tempted to close this thread as inactive, but thought I'd leave this open briefly to see if anyone wants to open a PR, or perhaps open a new [Ideas thread](https://github.com/apache/superset/discussions/categories/ideas) in our [Github Discussions](https://github.com/apache/superset/discussions) area.

**Comment by sfirke** [comment] 2023-09-01 13:01
@rusackas I think this is a bug but a duplicate of https://github.com/apache/superset/issues/20724 and can be closed for that reason.  I am closing but feel free to reopen if either of you disagree - in that case maybe we can note what's different about this case.

**Closed by sfirke** 2023-09-01 13:01 UTC
Labels: #bug
