### ISSUE TITLE
[SIP-15] time_range_endpoints not working on database extra parameters

### ISSUE THREAD

**Issue by rubenSastre** [apache/superset#11657] opened 2020-11-11 14:59 UTC
With SIP_15 the default time_range_endpoints = [start, end)
There is an option to set you own option on the database extra parameter.
The value for time_range_endpoints on database extra parameter is not working when you create a new chart.

### Expected results
While creating a new Chart it should get the value for extra param on the database configuration instead of "time_range_endpoints":["inclusive","exclusive"]

### Actual results

Although there is a value set on de database param as "time_range_endpoints":["inclusive","inclusive"] is taking  "time_range_endpoints":["inclusive","exclusive"]
#### Screenshots

![image](https://user-images.githubusercontent.com/25669722/98826661-46d30300-2436-11eb-9980-8abb56923b56.png)
![image](https://user-images.githubusercontent.com/25669722/98826742-610ce100-2436-11eb-8a5e-03728585082f.png)

#### How to reproduce the bug
1. Set  "time_range_endpoints":["inclusive","inclusive"]  on the database extra param
2. Create a new chart
3. Check on the form_data the value for time_range_endpoints

### Environment

- superset version: 0.37.2
- python version: 3.7
- node.js version: `node -v`

**Comment by villebro** [comment] 2020-11-11 15:28
Thanks for reporting @rubenSastre , I'll take a look

**Comment by rubenSastre** [comment] 2020-12-09 11:22
Any idea? i tried to look on the code but with my level I am not able to solve this part...

**Comment by rubenSastre** [comment] 2020-12-10 13:19
https://github.com/apache/incubator-superset/pull/11998

**Comment by rusackas** [comment] 2022-12-20 22:23
Since this issue was opened against a version of Superset that's no longer supported, and the thread hasn't seen any love in a long time, I'm going to go ahead and close this. If anyone can reproduce such an error in the current incarnations of Superset, let's open a fresh issue with updated context/screenshots/repro steps. Thank you!

**Closed by rusackas** 2022-12-20 22:23 UTC
Labels: !deprecated-label:bug
