### ISSUE TITLE
[Explore] Timepicker time range interval design 

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#12283] opened 2021-01-05 17:48 UTC
#### How to reproduce the bug

1. Go to explore view, click Date picker, choose **Previous** range type
2. Current month is Jan, previous month should **include 12/31**

### Actual results

<img width="756" alt="Screen Shot 2021-01-05 at 9 44 54 AM" src="https://user-images.githubusercontent.com/27990562/103680320-dbd81100-4f3a-11eb-9b71-b82b078c996f.png">

### Environment

latest master

cc @junlincc @zuzana-vej @zhaoyongjie

**Comment by junlincc** [comment] 2021-01-05 17:58
i do see it previous calendar month include 12/31? am i misunderstanding the issue? 

what's not clear to us yet is the setting for previous calendar week.(but we do have plan to address that issue by adding setting)

<img width="1726" alt="Screen Shot 2021-01-05 at 9 55 51 AM" src="https://user-images.githubusercontent.com/67837651/103681360-36be3800-4f3c-11eb-8b16-c6db36a2c848.png">
<img width="255" alt="Screen Shot 2021-01-05 at 9 57 49 AM" src="https://user-images.githubusercontent.com/67837651/103681561-7d139700-4f3c-11eb-9fc8-e381cfdb3805.png">

**Comment by graceguo-supercat** [comment] 2021-01-05 17:59
`2020-12-01 <= col < 2020-12-31` means include 12-01, not include 12-31.

**Comment by junlincc** [comment] 2021-01-05 18:14
looks like this is happening in all tine setting, and the default state

https://user-images.githubusercontent.com/67837651/103683191-ba792400-4f3e-11eb-877f-aaead2239279.mov

<img width="310" alt="Screen Shot 2021-01-05 at 10 11 42 AM" src="https://user-images.githubusercontent.com/67837651/103682987-725a0180-4f3e-11eb-9b2d-634bac2f4e8e.png">

**Comment by graceguo-supercat** [comment] 2021-01-05 18:20
for display, Previous month should display as `2020-12-01 <= col < 2021-01-01`

**Comment by junlincc** [comment] 2021-01-05 18:21
what about changing the END operator to "≤"?

**Comment by junlincc** [comment] 2021-01-05 18:26
acknowledging the severity of this regression as it is misleading users. my mad not catching it before we merged. Thanks for reporting! 🙏

**Comment by graceguo-supercat** [comment] 2021-01-05 19:27
i feel we should display `2020-12-01 <= col < 2021-01-01` not `2020-12-01 <= col <= 2021-12-31`.
This will **_be consistent with all other time range_** display format, which means include begin, exclude end.

**Comment by junlincc** [comment] 2021-01-05 20:04
im suggesting to make this change universal and i believe using "<" is a bug not by design 

looking at the old time picker, it had a similar problem on pill display. but actually including both start and end dates in the query. 

<img width="1130" alt="Screen Shot 2021-01-05 at 12 00 37 PM" src="https://user-images.githubusercontent.com/67837651/103693426-20b97300-4f4e-11eb-899b-de6f25a80e0b.png">

**Closed** 2021-01-06 18:09 UTC
Labels: P1, enhancement:committed, viz:explore:timepick

**Comment by john-bodley** [comment] 2021-01-07 00:14
@junlincc see [SIP-15](https://github.com/apache/superset/issues/6360) as to why the start and end time range intervals are inclusive of and exclusive  of respectively.
