### ISSUE TITLE
sortby dose not work?

### ISSUE THREAD

**Issue by wendy2017** [apache/superset#22599] opened 2023-01-05 07:05 UTC
![image](https://user-images.githubusercontent.com/22806386/210721581-7b297f8d-c842-4445-8353-c539a7eca8bb.png)

**Comment by zhaoyongjie** [comment] 2023-01-10 02:29
@wendy2017 Could you provide more detail for this case? for example, 1) what do you expect to sort? 2) the SQL for the chart.

**Comment by sfirke** [comment] 2023-01-10 17:10
What version of Superset are you running?  I find bar chart v2 sorting to be missing features in 2.0.1, but there is a PR merged into main branch that looks like it should fix that (https://github.com/apache/superset/pull/21993) if you try the latest version.

**Comment by wendy2017** [comment] 2023-01-11 10:20
for bar:
Use sortby to select a metric in the y-axis. It is expected that the y-axis can be arranged in a certain order, but it does not take effect in practice；
but Use x-axis sort by to take effect

**Comment by wendy2017** [comment] 2023-01-11 10:46
i have another question:
for interface(api/v1/chart/data?form_data=xxx),what's purpose of post-processing：{is_sort_index：number}

**Comment by wendy2017** [comment] 2023-01-11 10:50
Why sortby can't implement the function of xaxis sortby？i want to know the reason

**Comment by zhaoyongjie** [comment] 2023-01-11 16:36
> for bar: Use sortby to select a metric in the y-axis. It is expected that the y-axis can be arranged in a certain order, but it does not take effect in practice； but Use x-axis sort by to take effect

Hi @wendy2017 
I can't reproduce the issue. I make a screen recording for the axis sort with the y-axis and x-axis.


https://user-images.githubusercontent.com/2016594/211862763-b8e02620-bb11-4cfd-b2d9-60bd07f4b7a6.mov

**Comment by wendy2017** [comment] 2023-01-12 01:58
Can I use sortby instead of X-Axis sortby to realize the functions in video? Or can you showthe use of sortby

**Comment by zhaoyongjie** [comment] 2023-01-12 02:05
> Can I use sortby instead of X-Axis sortby to realize the functions in video? Or can you showthe use of sortby

the `Sort By` control affects **Order By** clause in the SQL while the `X-Axis Sort By` controls the order of the results in the query result.

**Comment by wendy2017** [comment] 2023-01-12 03:30
I don't understand
Use Sortby, but there is no change in eccharts
Is there any example that can demonstrate the sortby controls

**Comment by zhaoyongjie** [comment] 2023-01-12 03:43
the Sort By control affects SQL instead of charts.

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/2016594/211970594-4ed7f83d-a7cd-4909-9835-744ce4ba3a54.png">


> I don't understand Use Sortby, but there is no change in eccharts Is there any example that can demonstrate the sortby controls

**Comment by wendy2017** [comment] 2023-01-12 07:28
According to what your image，Will your data be sorted by AVG（”Sales")？

**Comment by wendy2017** [comment] 2023-01-12 07:30
![image](https://user-images.githubusercontent.com/22806386/212004662-4a24d01e-6ac3-4cc6-b783-cba2519a00b6.png)

i tried to do like your image,but my data is not sorted by AVG(TOTAL_CNT)

**Comment by zhaoyongjie** [comment] 2023-01-18 03:59
> ![image](https://user-images.githubusercontent.com/22806386/212004662-4a24d01e-6ac3-4cc6-b783-cba2519a00b6.png)
> 
> i tried to do like your image,but my data is not sorted by AVG(TOTAL_CNT)

try to add `AVG(TOTAL_CNT)` into `x-axis sort by` control because the data in results panel was pivot table rather than raw table.

**Comment by Cmagno13** [comment] 2023-02-10 16:54
Sorting on the 2v bar graph is not working. Any suggestions for correction.

![000000image](https://user-images.githubusercontent.com/97127080/218149797-4610770e-eed7-4604-b2e8-545e95922546.png)

**Comment by sfirke** [comment] 2023-03-21 16:34
A couple of PRs related to bar chart sorting were recently merged onto master branch, it would be good if someone could see if this behavior continues with `latest`.

**Comment by yousoph** [comment] 2023-07-26 22:44
Can't repro this on the latest master - if this is still happening please reopen or create a new issue with detailed repro steps. Thanks!

**Closed by yousoph** 2023-07-26 22:44 UTC
Labels: #bug
