### ISSUE TITLE
Chart cannot display result with over long integer but can display forecast value

### ISSUE THREAD

**Issue by unnyns-307** [apache/superset#24247] opened 2023-05-30 08:16 UTC
We found a problem that chart on Superset will display as no result when the metric value is long integer while it can display result of forecasting value when click ENABLE FORECAST. 

#### How to reproduce the bug

1. Create chart with metric that contain long integer value. for example value, 1137002859303050, etc.
2. Click on 'UPDATE CHART'
3. See blank chart but there is result in 'RESULTS' table below
![image](https://github.com/apache/superset/assets/82924994/9037b6c4-87d3-4d9f-9cba-c80dd2c72c8f)
4. Click 'ENABLE FORECAST'
5. Can see the chart display forecast value
![image](https://github.com/apache/superset/assets/82924994/ece6b875-1601-438d-8903-4ec368b2248a)

### Expected results
The data can be displayed or auto formatted in form that can show on the chart
![image](https://github.com/apache/superset/assets/82924994/edbf4c7f-87a6-41f9-8729-11a2e055d969)

what you expected to happen.

### Environment

(please complete the following information):

- browser type and version: Chrome
- superset version: 2.1.0
- python version: 3.8.16
- node.js version: 16
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

Is it possible to apply the auto formatted like forecasting value?

**Comment by rusackas** [comment] 2024-03-01 17:28
Hi there,

Is this still happening in 3.0?
Is there a reproducible case you can come up with using example or generated data?
Does casting your column as a FLOAT help?

Sorry for the questions, but if we can't reproduce this easily using supported versions, we'll have to close this issue as outdated.

**Comment by rusackas** [comment] 2024-09-06 17:49
Now that we're supporting 4.x mainly, and we don't have a reproducible test case, I'll close this as stale. Happy to re-open it if it's still occurring!

**Closed by rusackas** 2024-09-06 17:49 UTC
Labels: #bug
