### ISSUE TITLE
Is there a way to get our StarRocks database listed on the bottom of https://superset.apache.org/

### ISSUE THREAD

**Issue by alberttwong** [apache/superset#25660] opened 2023-10-16 15:57 UTC
![Screenshot 2023-10-16 at 8 56 39 AM](https://github.com/apache/superset/assets/749093/7dec83f8-799b-4877-9b2e-ff8203c36944)

The front page of https://superset.apache.org/ has a bunch of databases.   Is it possible to get our StarRocks database (starrocks.io) to also be listed there?

**Comment by Luwa-Tech** [comment] 2023-10-18 13:45
Hi, is this issue still open for contribution? i would like to work on it.

**Comment by michael-s-molina** [comment] 2023-10-19 11:45
Hi @Luwa-Tech. I think @rusackas might know what's the criteria to add logos. If not, we may add this to the next Town Hall agenda and discuss @sfirke.

**Comment by villebro** [comment] 2023-10-26 20:01
I don't see any reason why we can't add StarRocks to the main page. But I think it's a good idea to discuss at the next Town Hall to establish explicit guidelines for these.

**Comment by SyabAhmad** [comment] 2024-01-06 07:21
hello folks, Is the issue still open? I am going to try.

**Comment by Antismart** [comment] 2024-01-06 09:44
Can I work on this?

**Comment by villebro** [comment] 2024-01-06 20:07
Sure, feel free to open a PR 👍

**Comment by rusackas** [comment] 2024-05-13 15:58
Closing this since it's not a bug, but anyone here is still more than welcome to add a logo if they'd like!

On a side note, I'm not just being dismissive. We hope to align the DBs that are on our tesging/support matrix with the docs and readme (which currently don't even match each other!). So, it's a bit of a spring cleaning TODO, but we hope to be more comprehensive here soon.

**Closed** 2024-08-19 16:03 UTC
