### ISSUE TITLE
[TimeSeriesBarChart V2] Wrong row limit displayed

### ISSUE THREAD

**Issue by ValentinC-BR** [apache/superset#20378] opened 2022-06-14 11:26 UTC
The number of rows displayed at the top of a timeseries bar chart v2 is wrong.

When you reach the row limit (e.g. 1000), some data is missing in the chart, BUT the number of rows (at the top) is wrong.

This a big issue, as this leads to wrong interpretations of the results.

#### How to reproduce the bug

1. Create a timeseries bar chart v2
2. Group By a dimension
3. Set the limit to a small number (< total rows expected)
4. Run and watch the number of rows
5. Do the same with the previous timeseries chart
6. Look at the number of rows : the limit is reached

### Expected results

There should be a clear message indicating the the row limit was reached

### Actual results

According to the UI, the row limit is not reached

##### TimeSeries Bar Chart v2 (missing bars, "592 rows")
![image](https://user-images.githubusercontent.com/79460908/173566828-92de2a5e-3b8f-450f-ab65-8390b87c6ba8.png)

##### TimeSeries Bar Chart (legacy)
![image](https://user-images.githubusercontent.com/79460908/173566895-3c39221f-013e-4d2c-981d-93de73d2720e.png)

### Environment

(please complete the following information):

- browser type and version: Google Chrome Version 94.0.4606.71 (Oficial build) (x86_64)
- superset version: 1.5.0 (same issue in previous versions)
- python version: 3.7.9
- node.js version: doesn't apply, I run on Kubernetes, using gunicorn as server
- source : AWS Athena
- any feature flags active: /

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment] 2023-01-26 16:02
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!

**Closed** 2023-01-26 16:03 UTC
Labels: #bug, preset:cares
