### ISSUE TITLE
ERROR: Failed to fetch schemas allowed for csv upload in this database

### ISSUE THREAD

**Issue by GaryMam** [apache/superset#15763] opened 2021-07-17 15:37 UTC
Hi Github Fam,

I am now successfully able to configure new Postgres database and able to connect to SuperSet via it but I am still not able to use upload CSV option, it gives me error that "ERROR: Failed to fetch schemas allowed for csv upload in this database! Please contact your Superset Admin!".  I have already selected "allowed CSV upload" option from EXTRA tab. Please suggest.

Alternate solution - I created dummy data in database and then pulled it via SQL in Superset.

Warm Regards,

Gaurang M

**Comment by fuomag9** [comment] 2021-07-17 18:09
Duplicate of #15692

**Comment by aleksandrgordienko** [comment] 2021-07-30 09:35
Hi,
Is your user an admin? If not, have you added new permissions?

**Comment by GaryMam** [comment] 2021-07-30 14:51
Hello @aleksandrgordienko I have setup my apache superset using and logged in as user "data_driving" which has ADMIN access:
https://medium.com/geekculture/run-apache-superset-locally-in-10-minutes-30bc70ed808c

**Comment by fuomag9** [comment] 2021-07-30 14:52
@aleksandrgordienko @GaryMam We have a fix [here](https://github.com/apache/superset/issues/15692#issuecomment-881862635) but it has yet to be implemented/checked by mantainers

**Comment by GaryMam** [comment] 2021-07-30 14:57
Thank you @fuomag9. I will give a try.

**Closed** 2022-03-16 16:25 UTC
