### ISSUE TITLE
Sqllab broken

### ISSUE THREAD

**Issue by retry51776** [apache/superset#24007] opened 2023-05-10 15:51 UTC
I think there is frontend bug to sqllab, IDK how to reproduce it.
But it's something persists to an admin user(rules out permission issues).

#### How to reproduce the bug

Anywhere go to /sqllab will cause this issues.
I tried to switch different browser. Log off & log in. Clear cache. Delete ALL queries & datasets.

### Expected results

Sqllab show up.

### Actual results

blank page, header does works.

#### Screenshots

![image](https://github.com/apache/superset/assets/3774157/cf70a9f0-3082-4f46-86a0-cb224d013bb2)

### Environment

- browser type and version: Both Chrome & Edge
- superset version: Superset 0.0.0-dev
- python version: Python 3.8.16

### Additional context

```
react-dom.development.js:89  Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in ForwardRef (created by DatabaseSelector)
    in span (created by DatabaseSelector)
    in div (created by DatabaseSelector)
    in div (created by Styled(div))
    in Styled(div) (created by DatabaseSelector)
    in DatabaseSelector (created by TableSelector)
    in div (created by Styled(div))
    in Styled(div) (created by TableSelector)
    in TableSelector (created by TableSelectorMultiple)
    in TableSelectorMultiple (created by SqlEditorLeftBar)
    in div (created by Styled(div))
    in Styled(div) (created by SqlEditorLeftBar)
    in SqlEditorLeftBar (created by ResizableSidebar)
    in div (created by Styled(div))
    in Styled(div) (created by ResizableSidebar)
    in ResizableSidebar (created by SqlEditor)
    in Transition (created by CSSTransition)
    in CSSTransition (created by SqlEditor)
    in div (created by Styled(div))
    in Styled(div) (created by SqlEditor)
    in SqlEditor (created by TabbedSqlEditors)
    in div (created by TabPane)
    in TabPane (created by Styled(TabPane))
    in Styled(TabPane) (created by TabbedSqlEditors)
    in div (created by TabPanelList)
    in div (created by TabPanelList)
    in TabPanelList (created by ForwardRef(Tabs))
    in div (created by ForwardRef(Tabs))
    in ForwardRef(Tabs) (created by Tabs)
    in Tabs (created by EmotionCssPropInternal)
    in EmotionCssPropInternal (created by StyledTabs)
    in StyledTabs (created by Styled(StyledTabs))
    in Styled(StyledTabs) (created by TabbedSqlEditors)
    in TabbedSqlEditors (created by Connect(TabbedSqlEditors))
    in Connect(TabbedSqlEditors) (created by App)
    in div (created by Styled(div))
    in Styled(div) (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by Application)
    in ThemeProvider (created by Application)
    in Provider (created by Application)
    in QueryClientProvider (created by Queryprovider)
    in Queryprovider (created by Application)
    in Application
   ```

**Comment by rusackas** [comment] 2023-06-12 20:24
Closing since this seems to be an isolated incident, or everyone would be all over this.

Just curious... are you trying to run Superset on Windows, or is it being run/served on a supported OS?

**Closed by rusackas** 2023-06-12 20:24 UTC
Labels: #bug

**Comment by sathithyayogi05** [comment] 2023-06-17 14:51
I am running superset locally on my mac machine, suddenly getting this error.

Do you want any other information about my environment that i am running ?

**Comment by fazi1058** [comment] 2023-11-06 09:59
I am facing the exact same issue!

**Comment by rusackas** [comment] 2024-02-01 21:12
Is anyone able to reproduce this reliably? It might be worth filing a new bug with a reproducible use case involving a 3.x version.
