### ISSUE TITLE
ERROR: flask-appbuilder 3.4.4 has requirement Flask-WTF<0.15.0,>=0.14.2, but you'll have flask-wtf 1.0.0 which is incompatible.

### ISSUE THREAD

**Issue by dataf3l** [apache/superset#18723] opened 2022-02-14 21:04 UTC
ERROR: flask-appbuilder 3.4.4 has requirement Flask-WTF<0.15.0,>=0.14.2, but you'll have flask-wtf 1.0.0 which is incompatible.

#### How to reproduce the bug

1. Go to 'pip install apache-superset'

### Expected results

no pip error

### Actual results

ERROR: flask-appbuilder 3.4.4 has requirement Flask-WTF<0.15.0,>=0.14.2, but you'll have flask-wtf 1.0.0 which is incompatible.

### Environment

(please complete the following information):

- browser type and version: Ubuntu 20
- superset version: `
- superset version
Traceback (most recent call last):
  File "/home/superset/code/venv/bin/superset", line 8, in <module>
    sys.exit(superset())
  File "/home/superset/code/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/superset/code/venv/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/superset/code/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/superset/code/venv/lib/python3.8/site-packages/click/core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/home/superset/code/venv/lib/python3.8/site-packages/click/core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/home/superset/code/venv/lib/python3.8/site-packages/flask/cli.py", line 527, in get_command
    self._load_plugin_commands()
  File "/home/superset/code/venv/lib/python3.8/site-packages/flask/cli.py", line 523, in _load_plugin_commands
    self.add_command(ep.load(), ep.name)
  File "/home/superset/code/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2442, in load
    self.require(*args, **kwargs)
  File "/home/superset/code/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2465, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/superset/code/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (Flask-WTF 1.0.0 (/home/superset/code/venv/lib/python3.8/site-packages), Requirement.parse('Flask-WTF<0.15.0,>=0.14.2'))

- 
- 
- `
- python version: `Python 3.8.10`
- node.js version: `-v

Command 'node' not found, but can be installed with:

apt install nodejs
Please ask your administrator.`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar. (why would I do that?)

**Comment by zhaoyongjie** [comment] 2022-02-15 10:36
Hi @dataf3l, I can't reproduce in my local environment
- Debian buster
- Python 3.8.6
- pip 22.0.3

```
(testing-superset) zog@woody:~/workspace$ pip install apache-superset
Collecting apache-superset
  Downloading apache-superset-1.4.1.tar.gz (32.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 32.6/32.6 MB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting backoff>=1.8.0
  Downloading backoff-1.11.1-py2.py3-none-any.whl (13 kB)
Collecting bleach<4.0.0,>=3.0.2
  Downloading bleach-3.3.1-py2.py3-none-any.whl (146 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.6/146.6 KB 664.4 kB/s eta 0:00:00
Collecting cachelib<0.2,>=0.1.1
  Using cached cachelib-0.1.1-py3-none-any.whl (13 kB)
Collecting celery!=4.4.1,<5.0.0,>=4.3.0
  Using cached celery-4.4.7-py2.py3-none-any.whl (427 kB)
Collecting click<8
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting croniter>=0.3.28
  Downloading croniter-1.2.0-py2.py3-none-any.whl (17 kB)
Collecting cron-descriptor
  Using cached cron_descriptor-1.2.24-py3-none-any.whl
Collecting cryptography>=3.3.2
  Downloading cryptography-36.0.1-cp36-abi3-manylinux_2_24_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 1.7 MB/s eta 0:00:00
Collecting deprecation<2.2.0,>=2.1.0
  Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Collecting flask<2.0.0,>=1.1.0
  Downloading Flask-1.1.4-py2.py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.6/94.6 KB 448.7 kB/s eta 0:00:00
Collecting flask-appbuilder<4.0.0,>=3.4.3
  Downloading Flask_AppBuilder-3.4.4-py3-none-any.whl (1.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 2.4 MB/s eta 0:00:00
Collecting flask-caching>=1.10.0
  Using cached Flask_Caching-1.10.1-py3-none-any.whl (34 kB)
Collecting flask-compress
  Downloading Flask_Compress-1.10.1-py3-none-any.whl (7.9 kB)
Collecting flask-talisman
  Downloading flask_talisman-0.8.1-py2.py3-none-any.whl (18 kB)
Collecting flask-migrate
  Downloading Flask_Migrate-3.1.0-py3-none-any.whl (20 kB)
Collecting flask-wtf
  Downloading Flask_WTF-1.0.0-py3-none-any.whl (12 kB)
Collecting geopy
  Downloading geopy-2.2.0-py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.9/118.9 KB 280.2 kB/s eta 0:00:00
Collecting graphlib-backport
  Using cached graphlib_backport-1.0.3-py3-none-any.whl (5.1 kB)
Collecting gunicorn>=20.1.0
  Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 KB 373.5 kB/s eta 0:00:00
Collecting holidays==0.10.3
  Using cached holidays-0.10.3-py3-none-any.whl
Collecting humanize
  Downloading humanize-4.0.0-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.7/97.7 KB 448.7 kB/s eta 0:00:00
Collecting itsdangerous<2.0.0,>=1.0.0
  Using cached itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting isodate
  Downloading isodate-0.6.1-py2.py3-none-any.whl (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.7/41.7 KB 6.7 MB/s eta 0:00:00
Collecting markdown>=3.0
  Downloading Markdown-3.3.6-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.8/97.8 KB 443.7 kB/s eta 0:00:00
Collecting msgpack<1.1,>=1.0.0
  Downloading msgpack-1.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (322 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.4/322.4 KB 767.8 kB/s eta 0:00:00
Collecting pandas<1.3,>=1.2.2
  Downloading pandas-1.2.5-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (9.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.7/9.7 MB 2.4 MB/s eta 0:00:00
Collecting parsedatetime
  Using cached parsedatetime-2.6-py3-none-any.whl (42 kB)
Collecting pgsanity
  Using cached pgsanity-0.2.9-py3-none-any.whl
Collecting polyline
  Using cached polyline-1.4.0-py2.py3-none-any.whl (4.4 kB)
Collecting pyparsing<3.0.0,>=2.4.7
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting python-dateutil
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 600.9 kB/s eta 0:00:00
Collecting python-dotenv
  Downloading python_dotenv-0.19.2-py2.py3-none-any.whl (17 kB)
Collecting python-geohash
  Using cached python_geohash-0.8.5-cp38-cp38-linux_x86_64.whl
Collecting pyarrow<4.1,>=4.0.1
  Using cached pyarrow-4.0.1-cp38-cp38-manylinux2014_x86_64.whl (21.9 MB)
Collecting pyyaml>=5.4
  Downloading PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 701.2/701.2 KB 837.3 kB/s eta 0:00:00
Collecting PyJWT<2,>=1.7.1
  Using cached PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
Collecting redis
  Downloading redis-4.1.3-py3-none-any.whl (173 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 173.7/173.7 KB 885.0 kB/s eta 0:00:00
Collecting requests==2.26.0
  Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 KB 6.0 MB/s eta 0:00:00
Collecting selenium>=3.141.0
  Downloading selenium-4.1.0-py3-none-any.whl (958 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 958.8/958.8 KB 1.2 MB/s eta 0:00:00
Collecting simplejson>=3.15.0
  Downloading simplejson-3.17.6-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (139 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.5/139.5 KB 703.5 kB/s eta 0:00:00
Collecting slackclient==2.5.0
  Using cached slackclient-2.5.0-py2.py3-none-any.whl (54 kB)
Collecting sqlalchemy!=1.3.21,<1.4,>=1.3.16
  Downloading SQLAlchemy-1.3.24-cp38-cp38-manylinux2010_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 1.1 MB/s eta 0:00:00
Collecting sqlalchemy-utils<0.38,>=0.37.8
  Downloading SQLAlchemy_Utils-0.37.9-py3-none-any.whl (100 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.1/100.1 KB 484.1 kB/s eta 0:00:00
Collecting sqlparse==0.3.0
  Using cached sqlparse-0.3.0-py2.py3-none-any.whl (39 kB)
Collecting tabulate==0.8.9
  Downloading tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting typing-extensions<4,>=3.10
  Downloading typing_extensions-3.10.0.2-py3-none-any.whl (26 kB)
Collecting wtforms-json
  Using cached WTForms_JSON-0.3.3-py3-none-any.whl
Collecting convertdate
  Downloading convertdate-2.4.0-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.9/47.9 KB 198.5 kB/s eta 0:00:00
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting korean-lunar-calendar
  Using cached korean_lunar_calendar-0.2.1-py3-none-any.whl (8.0 kB)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.8-py2.py3-none-any.whl (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.7/138.7 KB 626.7 kB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.2/149.2 KB 666.5 kB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 KB 5.8 MB/s eta 0:00:00
Collecting aiohttp>3.5.2
  Downloading aiohttp-3.8.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 1.2 MB/s eta 0:00:00
Collecting packaging
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 KB 161.4 kB/s eta 0:00:00
Collecting webencodings
  Using cached webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Collecting vine==1.3.0
  Using cached vine-1.3.0-py2.py3-none-any.whl (14 kB)
Collecting billiard<4.0,>=3.6.3.0
  Downloading billiard-3.6.4.0-py3-none-any.whl (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.5/89.5 KB 5.8 MB/s eta 0:00:00
Collecting pytz>dev
  Downloading pytz-2021.3-py2.py3-none-any.whl (503 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 503.5/503.5 KB 797.8 kB/s eta 0:00:00
Collecting kombu<4.7,>=4.6.10
  Using cached kombu-4.6.11-py2.py3-none-any.whl (184 kB)
Collecting cffi>=1.12
  Downloading cffi-1.15.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (446 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 446.7/446.7 KB 1.0 MB/s eta 0:00:00
Collecting Jinja2<3.0,>=2.10.1
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting Werkzeug<2.0,>=0.15
  Using cached Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
Collecting WTForms<3.0.0
  Using cached WTForms-2.3.3-py2.py3-none-any.whl (169 kB)
Collecting Flask-JWT-Extended<4,>=3.18
  Using cached Flask_JWT_Extended-3.25.1-py2.py3-none-any.whl
Collecting jsonschema<5,>=3
  Downloading jsonschema-4.4.0-py3-none-any.whl (72 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.7/72.7 KB 332.0 kB/s eta 0:00:00
Collecting flask-wtf
  Using cached Flask_WTF-0.14.3-py2.py3-none-any.whl (13 kB)
Collecting email-validator<2,>=1.0.5
  Downloading email_validator-1.1.3-py2.py3-none-any.whl (18 kB)
Collecting marshmallow-enum<2,>=1.5.1
  Using cached marshmallow_enum-1.5.1-py2.py3-none-any.whl (4.2 kB)
Collecting marshmallow-sqlalchemy<0.27.0,>=0.22.0
  Downloading marshmallow_sqlalchemy-0.26.1-py2.py3-none-any.whl (15 kB)
Collecting prison<1.0.0,>=0.2.1
  Downloading prison-0.2.1-py2.py3-none-any.whl (5.8 kB)
Collecting Flask-Login<0.5,>=0.3
  Using cached Flask_Login-0.4.1-py2.py3-none-any.whl
Collecting marshmallow<4,>=3
  Downloading marshmallow-3.14.1-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 KB 196.0 kB/s eta 0:00:00
Collecting apispec[yaml]<4,>=3.3
  Using cached apispec-3.3.2-py2.py3-none-any.whl (27 kB)
Collecting Flask-OpenID<2,>=1.2.5
  Downloading Flask_OpenID-1.3.0-py3-none-any.whl (9.3 kB)
Collecting Flask-SQLAlchemy<3,>=2.4
  Downloading Flask_SQLAlchemy-2.5.1-py2.py3-none-any.whl (17 kB)
Collecting Flask-Babel<3,>=1
  Downloading Flask_Babel-2.0.0-py3-none-any.whl (9.3 kB)
Requirement already satisfied: setuptools>=3.0 in /home/zog/.virtualenvs/testing-superset/lib/python3.8/site-packages (from gunicorn>=20.1.0->apache-superset) (54.1.2)
Collecting importlib-metadata>=4.4
  Downloading importlib_metadata-4.11.1-py3-none-any.whl (17 kB)
Collecting numpy>=1.16.5
  Downloading numpy-1.22.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.8/16.8 MB 2.5 MB/s eta 0:00:00
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.9.2-py3-none-any.whl (16 kB)
Collecting trio~=0.17
  Downloading trio-0.19.0-py3-none-any.whl (356 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 356.4/356.4 KB 1.7 MB/s eta 0:00:00
Collecting brotli
  Using cached Brotli-1.0.9-cp38-cp38-manylinux1_x86_64.whl (357 kB)
Collecting alembic>=0.7
  Downloading alembic-1.7.6-py3-none-any.whl (210 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.4/210.4 KB 1.0 MB/s eta 0:00:00
Collecting geographiclib<2,>=1.49
  Downloading geographiclib-1.52-py3-none-any.whl (38 kB)
Collecting deprecated>=1.2.3
  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.3.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.7/158.7 KB 386.8 kB/s eta 0:00:00
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.0.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.3/121.3 KB 545.2 kB/s eta 0:00:00
Collecting attrs>=17.3.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 KB 7.5 MB/s eta 0:00:00
Collecting aiosignal>=1.1.2
  Downloading aiosignal-1.2.0-py3-none-any.whl (8.2 kB)
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.7.2-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (308 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 308.6/308.6 KB 509.1 kB/s eta 0:00:00
Collecting async-timeout<5.0,>=4.0.0a3
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting importlib-resources
  Downloading importlib_resources-5.4.0-py3-none-any.whl (28 kB)
Collecting Mako
  Downloading Mako-1.1.6-py2.py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.7/75.7 KB 332.8 kB/s eta 0:00:00
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 KB 537.5 kB/s eta 0:00:00
Collecting wrapt<2,>=1.10
  Downloading wrapt-1.13.3-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.6/84.6 KB 375.9 kB/s eta 0:00:00
Collecting dnspython>=1.15.0
  Downloading dnspython-2.2.0-py3-none-any.whl (266 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.0/267.0 KB 650.4 kB/s eta 0:00:00
Collecting Babel>=2.3
  Using cached Babel-2.9.1-py2.py3-none-any.whl (8.8 MB)
Collecting python3-openid>=2.0
  Using cached python3_openid-3.2.0-py3-none-any.whl (133 kB)
Collecting zipp>=0.5
  Downloading zipp-3.7.0-py3-none-any.whl (5.3 kB)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-2.0.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Downloading pyrsistent-0.18.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (119 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 KB 541.4 kB/s eta 0:00:00
Collecting amqp<2.7,>=2.6.0
  Using cached amqp-2.6.1-py2.py3-none-any.whl (48 kB)
Collecting sniffio
  Downloading sniffio-1.2.0-py3-none-any.whl (10 kB)
Collecting sortedcontainers
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting async-generator>=1.9
  Using cached async_generator-1.10-py3-none-any.whl (18 kB)
Collecting outcome
  Downloading outcome-1.1.0-py2.py3-none-any.whl (9.7 kB)
Collecting wsproto>=0.14
  Downloading wsproto-1.0.0-py3-none-any.whl (24 kB)
Collecting pyOpenSSL>=0.14
  Downloading pyOpenSSL-22.0.0-py2.py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 KB 238.0 kB/s eta 0:00:00
Collecting pymeeus<=1,>=0.3.13
  Downloading PyMeeus-0.5.11.tar.gz (5.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting defusedxml
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting h11<1,>=0.9.0
  Downloading h11-0.13.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.2/58.2 KB 257.1 kB/s eta 0:00:00
Building wheels for collected packages: apache-superset, pymeeus
  Building wheel for apache-superset (setup.py) ... done
  Created wheel for apache-superset: filename=apache_superset-1.4.1-py3-none-any.whl size=33671689 sha256=71a3e177ecc8435e1ebf6f24c27a630bc2825441c8d26df77a5ed41132b2b9c6
  Stored in directory: /home/zog/.cache/pip/wheels/60/1f/37/33225d83653fd7a93da87eab9f55ac37acde015716d0091978
  Building wheel for pymeeus (setup.py) ... done
  Created wheel for pymeeus: filename=PyMeeus-0.5.11-py3-none-any.whl size=730973 sha256=521a5820435792e11dee768844b1116c5a5cf82ffd5cd3304fae3ad31443125e
  Stored in directory: /home/zog/.cache/pip/wheels/a0/8b/b2/810ae5a6f970c8be4725353400d643c90de1c0f023a9884ee7
Successfully built apache-superset pymeeus
Installing collected packages: webencodings, typing-extensions, tabulate, sortedcontainers, pytz, python-geohash, pymeeus, PyJWT, pgsanity, parsedatetime, msgpack, korean-lunar-calendar, geographiclib, cron-descriptor, certifi, cachelib, brotli, billiard, zipp, wrapt, Werkzeug, vine, urllib3, sqlparse, sqlalchemy, sniffio, six, simplejson, pyyaml, python-dotenv, pyrsistent, pyparsing, pycparser, numpy, multidict, marshmallow, MarkupSafe, itsdangerous, idna, humanize, h11, gunicorn, graphlib-backport, geopy, frozenlist, dnspython, defusedxml, convertdate, colorama, click, charset-normalizer, backoff, Babel, attrs, async-timeout, async-generator, apispec, yarl, WTForms, wsproto, sqlalchemy-utils, requests, python3-openid, python-dateutil, pyarrow, prison, polyline, packaging, outcome, marshmallow-sqlalchemy, marshmallow-enum, Mako, Jinja2, isodate, importlib-resources, importlib-metadata, flask-talisman, email-validator, deprecated, cffi, amqp, aiosignal, wtforms-json, trio, redis, pandas, markdown, kombu, jsonschema, holidays, flask, deprecation, cryptography, croniter, bleach, alembic, aiohttp, trio-websocket, slackclient, pyOpenSSL, flask-wtf, Flask-SQLAlchemy, Flask-OpenID, Flask-Login, Flask-JWT-Extended, flask-compress, flask-caching, Flask-Babel, celery, flask-migrate, flask-appbuilder, selenium, apache-superset
Successfully installed Babel-2.9.1 Flask-Babel-2.0.0 Flask-JWT-Extended-3.25.1 Flask-Login-0.4.1 Flask-OpenID-1.3.0 Flask-SQLAlchemy-2.5.1 Jinja2-2.11.3 Mako-1.1.6 MarkupSafe-2.0.1 PyJWT-1.7.1 WTForms-2.3.3 Werkzeug-1.0.1 aiohttp-3.8.1 aiosignal-1.2.0 alembic-1.7.6 amqp-2.6.1 apache-superset-1.4.1 apispec-3.3.2 async-generator-1.10 async-timeout-4.0.2 attrs-21.4.0 backoff-1.11.1 billiard-3.6.4.0 bleach-3.3.1 brotli-1.0.9 cachelib-0.1.1 celery-4.4.7 certifi-2021.10.8 cffi-1.15.0 charset-normalizer-2.0.12 click-7.1.2 colorama-0.4.4 convertdate-2.4.0 cron-descriptor-1.2.24 croniter-1.2.0 cryptography-36.0.1 defusedxml-0.7.1 deprecated-1.2.13 deprecation-2.1.0 dnspython-2.2.0 email-validator-1.1.3 flask-1.1.4 flask-appbuilder-3.4.4 flask-caching-1.10.1 flask-compress-1.10.1 flask-migrate-3.1.0 flask-talisman-0.8.1 flask-wtf-0.14.3 frozenlist-1.3.0 geographiclib-1.52 geopy-2.2.0 graphlib-backport-1.0.3 gunicorn-20.1.0 h11-0.13.0 holidays-0.10.3 humanize-4.0.0 idna-3.3 importlib-metadata-4.11.1 importlib-resources-5.4.0 isodate-0.6.1 itsdangerous-1.1.0 jsonschema-4.4.0 kombu-4.6.11 korean-lunar-calendar-0.2.1 markdown-3.3.6 marshmallow-3.14.1 marshmallow-enum-1.5.1 marshmallow-sqlalchemy-0.26.1 msgpack-1.0.3 multidict-6.0.2 numpy-1.22.2 outcome-1.1.0 packaging-21.3 pandas-1.2.5 parsedatetime-2.6 pgsanity-0.2.9 polyline-1.4.0 prison-0.2.1 pyOpenSSL-22.0.0 pyarrow-4.0.1 pycparser-2.21 pymeeus-0.5.11 pyparsing-2.4.7 pyrsistent-0.18.1 python-dateutil-2.8.2 python-dotenv-0.19.2 python-geohash-0.8.5 python3-openid-3.2.0 pytz-2021.3 pyyaml-6.0 redis-4.1.3 requests-2.26.0 selenium-4.1.0 simplejson-3.17.6 six-1.16.0 slackclient-2.5.0 sniffio-1.2.0 sortedcontainers-2.4.0 sqlalchemy-1.3.24 sqlalchemy-utils-0.37.9 sqlparse-0.3.0 tabulate-0.8.9 trio-0.19.0 trio-websocket-0.9.2 typing-extensions-3.10.0.2 urllib3-1.26.8 vine-1.3.0 webencodings-0.5.1 wrapt-1.13.3 wsproto-1.0.0 wtforms-json-0.3.3 yarl-1.7.2 zipp-3.7.0
```

**Comment by jacobcroope** [comment] 2022-02-16 16:48
I had the same issue with Ubuntu 20.04 and moved to the docker compose version instead.

**Comment by JasbirCodeSpace** [comment] 2022-02-18 20:45
Try updating pip 
`pip install --upgrade pip`

If you got error **ImportError: cannot import name 'soft_unicode' from 'markupsafe'** while running _superset db upgrade_ then run following command:
`pip install markupsafe==2.0.1`

**Comment by jacobcroope** [comment] 2022-02-21 12:41
That did clear the original Flask Requirement Error and was able to finish the install after a complete reset of the venv.

**Comment by dat-linux** [comment] 2022-02-23 18:49
But superset installs the latest markupsafe, should that be uninstalled first before replacing it?

**Comment by jacobcroope** [comment] 2022-02-23 18:54
Looks relevant. https://stackoverflow.com/questions/5226311/installing-specific-package-versions-with-pip

**Comment by dat-linux** [comment] 2022-02-23 18:57
The problem is the install instructions for superset need to be updated. Because it will attempt to install latest package, which you then need to go back and add the extra uninstall/install step to fix it.

**Comment by jacobcroope** [comment] 2022-02-23 19:00
@dat-linux You can submit a PR on relevant docs. I ran into a similar issue with unclear documentation around docker install configuration.

**Comment by jacobcroope** [comment] 2022-02-23 19:14
@zhaoyongjie I believe this issue can be closed along with. #18888

**Comment by zhaoyongjie** [comment] 2022-02-25 03:14
This issue was resolved by [disscussion](https://github.com/apache/superset/issues/18723#issuecomment-1049107830).

**Closed by zhaoyongjie** 2022-02-25 03:14 UTC
Labels: #bug:cant-reproduce, install:terminal, #bug
