### ISSUE TITLE
there is a bug about mixed chart

### ISSUE THREAD

**Issue by sandbury** [apache/superset#27984] opened 2024-04-11 04:36 UTC
### Bug description

use mixed chat ,when the X-axis is number ,The histogram goes beyond the end of the x-axis
like
![1234](https://github.com/apache/superset/assets/163830391/cef0366c-411a-461c-86e0-538a36be772f)

I can solve it with string X-aix，but I still like that it would be a little better to use numbers as the x-axis

### How to reproduce the bug

1

### Screenshots/recordings

![1234](https://github.com/apache/superset/assets/163830391/5f46beb3-72c3-405b-bd4e-aa1701aabdd0)

### Superset version

4.0.0

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

1

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by sfirke** [comment] 2024-07-16 18:03
I believe this is a duplicate of #26254, see that conversation for more context.  Let me know if you disagree.

**Closed by sfirke** 2024-07-16 18:03 UTC
