### ISSUE TITLE
Chart tooltips not showing in Mozilla Firefox

### ISSUE THREAD

**Issue by rvabhijith** [apache/superset#9976] opened 2020-06-03 13:26 UTC
Chart(Pie, Bar, Line, etc.) tooltips not showing in Mozilla Firefox.

In chrome and opera tooltips are working.

Using apache superset - Master Branch

Please see the image
![Screenshot 2020-06-03 at 6 50 27 PM](https://user-images.githubusercontent.com/39004901/83641822-adbcd800-a5cb-11ea-9cc6-effab3e264fc.png)

**Comment by junlincc** [comment] 2020-12-04 15:08
@rvabhijith is it still an issue? we are not able to reproduce.

**Comment by john-bodley** [comment] 2021-04-21 21:31
Closing this as it seems we're unable to reproduce. @rvabhijith please re-open if this is still an issue.

**Closed by john-bodley** 2021-04-21 21:31 UTC
Labels: .pinned, browser:firefox, bug, cant-reproduce
