### ISSUE TITLE
Dashboard hangs when you Toggle Chart Description for more than one chart.

### ISSUE THREAD

**Issue by chr1s3sw0rthy** [apache/superset#19766] opened 2022-04-18 18:08 UTC
My Dashboard loads.
I click Toggle Chart Description on one chart. It shows.
I click Toggle Chart Description on a second chart. The browser hangs.

Same behaviour on Safari and Chrome.

### Expected results

I expect the Description to show on all the charts for which I have toggled chart description.

### Actual results

As described above.

#### Screenshots

![Screenshot 2022-04-18 at 19 50 03](https://user-images.githubusercontent.com/22027422/163850966-19c68af7-a528-481c-8778-fa64050f070c.png)
![Screenshot 2022-04-18 at 19 51 04](https://user-images.githubusercontent.com/22027422/163850983-8075167c-4517-47a0-a8af-1c4584cccc5c.png)

### Environment

(please complete the following information):

NAME                    CHART VERSION   APP VERSION
superset/superset       0.5.10          1.0        

Using the latest Helm chart.

- browser type and version: Safari and Chrome latest.
- superset version: `superset version` 1.0
- python version: `python --version` 3.8
- node.js version: `node -v`. None
- any feature flags active:  None

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [checking] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [unable to do that] I have reproduced the issue with at least the latest released version of superset.
- [ X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment] 2023-05-18 22:59
@yousoph @kasiazjc We don't even have this anymore... you can still add these descriptions, but they don't appear anywhere in the UI as far as I'm noticing. Was this by design or by mistake?

Tempted to close this bug, since... well, it's not a bug if the menu item is gone... but maybe this is even worse?

**Comment by michael-s-molina** [comment] 2024-02-23 21:04
Confirmed that the issue is fixed and works as intended in supported versions of Superset.

https://github.com/apache/superset/assets/70410625/c1cfb475-ccf0-44e0-afbd-9a3296e0db98

**Closed by michael-s-molina** 2024-02-23 21:04 UTC
Labels: #bug
