### ISSUE TITLE
"Create View As" functionality is broken after SQLLAB_BACKEND_PERSISTENCE is set to True

### ISSUE THREAD

**Issue by zhaorui2022** [apache/superset#21665] opened 2022-09-30 18:16 UTC
After we upgrade superset to 2.0.0, we got user reports saying "Create View As" is broken and it shows an error message saying "No stored results found, you need to re-run your query", and if rerunning, it will complain the view already exists. After disabling SQLLAB_BACKEND_PERSISTENCE, it solves the issue. But SQLLAB_BACKEND_PERSISTENCE is set to True by default in 2.0.0.

#### How to reproduce the bug

1. Go to SQL Lab's SQL editor
2. Select a database where it allows "Create View As"
3. Write any query
4. Click on "Create View As" button in the dropdown list next to "Run" button. And fill in the information as expected.
5. See the error on the UI.

### Expected results

The UI should show it has successfully created the view with a link to explore the view immediately.

### Actual results

Shows an error. 

#### Screenshots

<img width="527" alt="Screen Shot 2022-09-30 at 11 13 55 AM" src="https://user-images.githubusercontent.com/105950525/193331778-73925f89-a131-4a68-8d54-f8d052c7d045.png">

### Environment

(please complete the following information):

- browser type and version: N/A, not browser specific
- superset version: 2.0.0
- python version: 3.8
- node.js version: not specific to node.js version
- any feature flags active: has the error when SQLLAB_BACKEND_PERSISTENCE is set to true

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaorui2022** [comment] 2022-09-30 19:02
If anyone else also experience this issue, can we set this feature flag to False by default in upcoming patch releases? We had the feature flag enabled for 2 days, and after disabling it, users were reporting their previous query tabs were reset to the default one (no query history, and all queries become "SELECT * FROM WHERE")

**Comment by mayurnewase** [comment] 2022-10-12 18:30
couldn't reproduce on latest master (last sha: `8f74e46d45ca94f5656f7b881f1096c16657c829`)

**Comment by eschutho** [comment] 2022-10-13 17:54
I tested this in 2.0.1 and it seems to work, too. I'll close this ticket since it was verified as fixed on master as well.

**Closed by eschutho** 2022-10-13 17:54 UTC
Labels: #bug, v2.0
