### ISSUE TITLE
Combining Saved Metrics in Explore/Custom SQL panel

### ISSUE THREAD

**Issue by EBoisseauSierra** [apache/superset#19644] opened 2022-04-11 11:01 UTC
## The problem I have

I would like to combine a dataset's Saved Metrics to compute new ones and stay DRY. But it's currently not possible.

## The solution I'd like

Say I'm tracking my widget production, and record for each batch how many items have been produced and how long it took.
I can then define at the Dataset level the following Saved Metrics: 
* `SUM(quantity) AS production`, and
* `SUM(duration) AS work_hours`.

Imagine I'd now like to plot productivity over time: I would love to go to the Explore Panel, create a line chart which Metric would be `production / work_hours`. However, this is currently only possible with Calculated Columns, not Saved Metrics.

I could also want to be able to define `productivity` as a new Saved Metric (but I understand this might be trickier, due to definitions dependencies resolution).

## Some possible (sub-optimal) alternatives

It is obviously possible to define the `productivity` KPI as `SUM(quantity) / SUM(duration)` — either as a new Saved Metric or Custom SQL.

But this isn't DRY, what causes some issues should I want to change, say, how I compute `work_hours` (two Saved Metrics definition to change), or if my Saved Metrics are a bit convoluted (risk of errors in copy-pasta).

**Comment by rusackas** [comment] 2023-01-26 07:03
@EBoisseauSierra I realize this Issue has gone unattended for quite a while. Sorry about that :/

Are you still interested in this as a feature, or have you found a workable workaround/solution?  I'm not quite sure if we should close this issue as "stale" or move it to a Github Discussion under the Ideas thread. But I think it's fair to say the ol' open source adage that we're happy to review a PR if you're interested in tackling this, or considering a SIP if you think it's a larger effort you're willing to help usher through.

**Comment by ValeriyaKur** [comment] 2023-02-26 15:48
> @EBoisseauSierra I realize this Issue has gone unattended for quite a while. Sorry about that :/
> 
> Are you still interested in this as a feature, or have you found a workable workaround/solution? I'm not quite sure if we should close this issue as "stale" or move it to a Github Discussion under the Ideas thread. But I think it's fair to say the ol' open source adage that we're happy to review a PR if you're interested in tackling this, or considering a SIP if you think it's a larger effort you're willing to help usher through.

Hi!
The question is relevant. My company is transferring reports from Power BI to a superset. The PBI calmly coped with such a task.
On my own behalf, I will add that the ability to calculate metrics based on other metrics is needed not only in the set, but also in the charts metrics.
Because in the charts, when trying to enter a custom metric calculation:
`SELECT 
"DateTransit_WeekISO" AS "DateTransit_WeekISO",
"Reason_DR" AS "Reason_DR",
case
when the sum(qnt_rdr) exceeds(split into "DateTransit_WeekISO", "Reason_DR") = 0, then 0
else (sum(qnt_rdr) over(section by "Name", "AG", DateTransit_Week IS, is_virtual, OperType, Reason_DR, Reason_OD))/(SUM(qnt_rdr) over(section by DateTransit_WeekISO, Reason_DR))
ends AS Reason_DR_perce
from "OP_all_users".
Group "SSet_SupplyMonitor_transit_new" by transition date in a week, Reason_DR
LIMIT 10000;`

ClickHouse throws an error:
SQL error [215] [07000]: Code: 215. DB::Exception: The column `qnt_rdr` is not in the aggregate function and is not in the BY group. There are columns: ['Reason_DR','DateTransit_WeekISO']

**Comment by rusackas** [comment] 2024-02-22 17:32
Closing this as stale since it's been silent for so long, and is a feature request rather than a bug. If this is relevant in current versions (currently 3.x) please open a new Ideas discussion or a PR/SIP to address the problem.

**Closed by rusackas** 2024-02-22 17:32 UTC

**Comment by lirilkumar** [comment] 2024-06-04 09:27
@rusackas  Please reopen this as it wil be a great feature. Let me know if this feature is already in place.

**Comment by rusackas** [comment] 2024-06-04 15:57
This would be cool, and I've wished for it too... basically being able to create metrics/calculate columns based on other metrics/calculated columns, if I understand correctly. This leads to issues with dependency of these values being passed around, meaning there ought to be an order of operations to them. I don't think it's quite straightforward. That said, I think if anyone wants to propose and implement a solution, we would kindly welcome a SIP on the topic. Meanwhile, I think we ought to leave this closed, since it's a feature request, not a bug. Happy to reopen and convert it to a GitHub Discussion of the "Ideas" type if folks want to take it up there, but I still think the better move would be for someone to take up the flag and write a SIP if they're really interested.
