### ISSUE TITLE
[Dashboard][Share] Share related links are gone

### ISSUE THREAD

**Issue by graceguo-supercat** [apache/superset#14251] opened 2021-04-20 16:59 UTC
SHARE links (share url, share in email etc) are hidden in slice header dropdown list in dashboard:

#### Screenshots

<img width="1293" alt="Screen Shot 2021-04-20 at 9 53 47 AM" src="https://user-images.githubusercontent.com/27990562/115435706-f7e88100-a1be-11eb-99ec-7093feaf30a1.png">

#### How to reproduce the bug

1. Go to any dashboard
2. Click on dropdown list for any chart
3. Should be able to share chart by link, by email

### Environment

latest master

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Related to https://github.com/apache/superset/pull/14076. According to PR’s test description:
`check that sharing is menu option is shown by default for Admin/Gamma/Alpha`

But admin/alpha/gamma role didn't see share links.

CC @junlincc @zuzana-vej @amitmiran137

**Comment by amitmiran137** [comment] 2021-04-20 20:23
I'm unable to reproduce the issue
my steps:
1. make sure/remove from Admin/Alpha/Gamma 2 permissions named:
    a. can share dashboard on superset
    b. can share chart on superset
 2.   run **superset init**
 3. check Admin/Alpha/Gamma and see that the above permission does exist
 
 anyone else able to reproduce?

**Comment by graceguo-supercat** [comment] 2021-04-20 23:59
I can reproduce this way: 
- checkout open source master branch, 
- build and compile in your local environment,
- open any sample dashboard as Admin role.

**Comment by graceguo-supercat** [comment] 2021-04-21 01:40
Hi @amitmiran137 and @junlincc I found what is wrong here: in airbnb we reverted #13306 and #14148. But actually #14148 fixed a few permission related issues in the original PR #14076...So right now we are running with 14076 without extra permission related fixes. :(

**Comment by junlincc** [comment] 2021-04-21 03:46
@graceguo-supercat gotcha, glad that you found the cause. not sure what's the best way to fix this issue, but this issue will be added to our test case incase it actually happens. closing issue for now since it's not universal.

**Closed by junlincc** 2021-04-21 03:46 UTC
Labels: bug:regression, test:case, viz:dashboard:ui

**Comment by jinghua-qa** [comment] 2021-06-18 20:05
Testcase added
