### ISSUE TITLE
how to draw Heatmap - Discrete Mapping of Color

### ISSUE THREAD

**Issue by heimohe** [apache/superset#22089] opened 2022-11-10 13:15 UTC
how to draw picture like https://echarts.apache.org/examples/zh/editor.html?c=heatmap-large-piecewise

**Comment by rusackas** [comment] 2024-02-13 18:32
You'd have to add a new plugin or additional controls to an existing plugin. Closing this since it's not a bug, but we're open to GitHub Discussions or reviewing PRs :)

**Closed by rusackas** 2024-02-13 18:32 UTC
