### ISSUE TITLE
uploading file from the remote server

### ISSUE THREAD

**Issue by syamini227** [apache/superset#23032] opened 2023-02-08 07:12 UTC
I started superset from a remote Linux server on port 8088. While I am trying to upload a CSV file, it's showing the files from my local system, not from the remote server. How can I upload a CSV file from the remote server?

**Comment by rusackas** [comment] 2023-02-10 21:34
That's correct, most people upload files from their client machine up to the server... it's the typical workflow that the product was designed for. Can you just download the file from the remote server to your machine and then upload it to Superset? It might also be doable via the API or other methods, but I'm not sure that'd be worth the trouble.

Closing since this is not a bug, but you can open a discussion here on Github or on Slack.

**Closed by rusackas** 2023-02-10 21:34 UTC
