### ISSUE TITLE
Configure Superset in an AWS EC2 instance using docker

### ISSUE THREAD

**Issue by maliklamblin** [apache/superset#20255] opened 2022-06-03 10:08 UTC
Hello everyone,

I'm asking for your help because I need to configure apache Superset in a production environment (on an AWS EC2 instance) using docker.
I've looked everywhere but can't find anything, so if you have any ideas on how I can do this.

Thanks in advance

**Comment by rusackas** [comment] 2024-02-06 22:43
Closing this since it's not a bug (and it's also old) but I would encourage you to ask deployment/config questions in `#deploying-superset` on [Superset Slack](http://bit.ly/join-superset-slack)

**Closed by rusackas** 2024-02-06 22:43 UTC
