### ISSUE TITLE
Superset Fails to Start in Docker with Missing /app/docker/docker-bootstrap.sh Error

### ISSUE THREAD

**Issue by brownie1** [apache/superset#23484] opened 2023-03-24 19:05 UTC
Following the instructions here: https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/ Superset errors out with the following error:
```
Attaching to superset_app, superset_cache, superset_db, superset_init, superset_worker, superset_worker_beat
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/docker/docker-bootstrap.sh": stat /app/docker/docker-bootstrap.sh: no such file or directory: unknown
```
MacOS Version: Ventura 13.2.1
Docker Version: Docker version 23.0.1, build a5ee5b1dfc
Docker Compose Version: Docker Compose version 2.17.0

Looking through past bug reports I have seen similar issues, but nothing that fixes this issue.

**Comment by mdeshmu** [comment] 2023-03-25 18:43
Which superset version?

**Comment by nytai** [comment] 2023-03-27 01:52
That [file](https://github.com/apache/superset/blob/master/docker/docker-bootstrap.sh) should be volume mounted into the containers. Are you running this from the base of the cloned repo?

**Comment by msen7437** [comment] 2023-10-16 14:48
Hey there,
I am also encountering this error when i try to deploy superset with docker-compose in a google cloud engine.
I basically do exactly what is done in the docs and it works on my Linux OS (ubuntu) but not on the GCE (also ubuntu).
Here is what i did:

1. Clone the project and `cd superset`
2. Install a new docker-compose version since the default version on the GCE isn't compatible with the docker-compose file
```
curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/bin/docker-compose
chmod +x /usr/bin/docker-compose
```
I installed version: `Docker Compose version v2.22.0`
3. Running `docker-compose up`

Here is the output i receive:
```
root@my-host:/superset#  docker-compose up
[+] Building 0.0s (0/0)                                                  docker:default
[+] Running 7/7
 ✔ Network superset_default        Created                                         0.1s 
 ✔ Container superset_db           Created                                         0.1s 
 ✔ Container superset_cache        Created                                         0.1s 
 ✔ Container superset_init         Created                                         0.1s 
 ✔ Container superset_worker       Created                                         0.1s 
 ✔ Container superset_worker_beat  Created                                         0.0s 
 ✔ Container superset_app          Created                                         0.1s 
Attaching to superset_app, superset_cache, superset_db, superset_init, superset_worker, superset_worker_beat
superset_cache        | 1:C 16 Oct 2023 14:28:09.836 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
superset_cache        | 1:C 16 Oct 2023 14:28:09.836 * Redis version=7.2.1, bits=64, commit=00000000, modified=0, pid=1, just started
superset_cache        | 1:C 16 Oct 2023 14:28:09.836 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
superset_cache        | 1:M 16 Oct 2023 14:28:09.836 * monotonic clock: POSIX clock_gettime
superset_cache        | 1:M 16 Oct 2023 14:28:09.837 * Running mode=standalone, port=6379.
superset_cache        | 1:M 16 Oct 2023 14:28:09.838 * Server initialized
superset_cache        | 1:M 16 Oct 2023 14:28:09.838 * Loading RDB produced by version 7.2.1
superset_cache        | 1:M 16 Oct 2023 14:28:09.838 * RDB age 126 seconds
superset_cache        | 1:M 16 Oct 2023 14:28:09.838 * RDB memory usage when created 0.83 Mb
superset_cache        | 1:M 16 Oct 2023 14:28:09.838 * Done loading RDB, keys loaded: 0, keys expired: 0.
superset_cache        | 1:M 16 Oct 2023 14:28:09.838 * DB loaded from disk: 0.000 seconds
superset_cache        | 1:M 16 Oct 2023 14:28:09.838 * Ready to accept connections tcp
superset_db           | 
superset_db           | PostgreSQL Database directory appears to contain a database; Skipping initialization
superset_db           | 
superset_db           | 2023-10-16 14:28:09.968 UTC [1] LOG:  starting PostgreSQL 15.4 (Debian 15.4-2.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
superset_db           | 2023-10-16 14:28:09.968 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
superset_db           | 2023-10-16 14:28:09.968 UTC [1] LOG:  listening on IPv6 address "::", port 5432
superset_db           | 2023-10-16 14:28:09.975 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
superset_db           | 2023-10-16 14:28:09.987 UTC [29] LOG:  database system was shut down at 2023-10-16 14:26:02 UTC
superset_db           | 2023-10-16 14:28:09.997 UTC [1] LOG:  database system is ready to accept connections
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/app/docker/docker-bootstrap.sh": stat /app/docker/docker-bootstrap.sh: no such file or directory: unknown

```

I ran it as `root` in order to cancel out possible issues with file permissions (Only done for debugging). 
It worked just fine when i tried to deploy it on thursday and friday (12th and 13th of october 2023), so the issue is also pretty new for me.
Maybe the compute engine is missing a dependency or so, but i wasn't able to solve the issue.
Im looking forward to solving and resolving my issue!
Thanks in advance!

**Comment by mdeshmu** [comment] 2023-10-20 02:29
@sfirke this is good to close, I believe. 
We already have `cd superset` in [docs](https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/). If volume mounting is not happening for some reason, its likely not a superset issue.

**Comment by sfirke** [comment] 2023-10-20 18:45
I thought the same thing as nytai above, a user could see this error if they run `docker compose up` without having cloned the repo so they are missing the bash files and they then don't get mounted.  And @mdeshmu I agree it seems like this is not something actionable for the Superset project.  Feel free to continue troubleshooting this here, and then I'll plan to close this once activity dries up.

Heads up that @sebastianliebscher has an open PR in progress that might help with this: https://github.com/apache/superset/pull/25546  I believe it would eliminate the need to bound these bash files.  FYI Sebastian in case this is an example of why that PR will be an improvement.

**Comment by rusackas** [comment] 2024-04-08 02:59
Seems like things have indeed dried up on this thread. Let's go ahead and close this. Much has changed in Docker-land since this Issue was last touched, but if y'all think this needs to be re-opened, we can surely do so.

**Closed by rusackas** 2024-04-08 02:59 UTC
Labels: #bug

**Comment by nadersoliman** [comment] 2024-11-12 06:47
faced the same problem mounted the volume to `superset-checks`
```
    volumes:
      - ./scripts:/app/scripts  # Add this volume mount
```

**Comment by batje** [comment] 2026-01-06 12:04
While trying to install superset (image-tag) on Portainer, I ran into this issue.
