### ISSUE TITLE
Failed to execute 'fetch' on 'Window': Failed to read the 'signal' property from 'RequestInit': Failed to convert value to 'AbortSignal'.

### ISSUE THREAD

**Issue by CaptainHoangLe** [apache/superset#20084] opened 2022-05-16 15:18 UTC
I am using superset ver 1.4.0 .  dashboard uses nomal on almost device but when i use Ipad and reload dashboard , it throw me error
![image](https://user-images.githubusercontent.com/53038465/168625606-00cb0380-10d2-476c-b4f0-17f17eff94d0.png)

I have fixed it by remove signal on request param of 
![image](https://user-images.githubusercontent.com/53038465/168626240-99449282-8a67-4eb6-aad1-6d860e7a93a1.png)

but I don't know if that's a reasonable fix. So , i am looking forward to recieving a help from somebody, please
Thank you so much !

**Comment by diegomedina248** [comment] 2022-05-16 20:13
Hi @CaptainHoangLe,

Seems like the code in master is the same, at least around this function, though I cannot reproduce with the default dashboards.
Looking at this error, seems like it happens if the request is malformed, specially around the headers.
Can you post the curl request made for it here? (or a sample that can be reproduced)
Can you also test against the code in master?

Thanks!

**Comment by CaptainHoangLe** [comment] 2022-05-18 06:30
> Hi @CaptainHoangLe,
> 
> Seems like the code in master is the same, at least around this function, though I cannot reproduce with the default dashboards. Looking at this error, seems like it happens if the request is malformed, specially around the headers. Can you post the curl request made for it here? (or a sample that can be reproduced) Can you also test against the code in master?
> 
> Thanks!

uhm.... this bug may only appear on macos and ubuntu 20.04

**Comment by maxgillmaxgill** [comment] 2024-01-03 21:58
I am getting the same error running on Safari + Oracle Linux 8.8.

**Comment by rusackas** [comment] 2024-05-13 17:43
Closing this since we can no longer support Superset 1.4 bugs. We now officially support 3.1 and 4.0, so if you see this issue in those releases, we'd be happy to reopen this.

**Closed by rusackas** 2024-05-13 17:43 UTC
Labels: data:connect:oracle, #bug
