### ISSUE TITLE
Line chart tooltips broken on Firefox

### ISSUE THREAD

**Issue by CoryChaplin** [apache/superset#7822] opened 2019-07-04 15:23 UTC
### Expected results

Hover point on the line, see a tooltip.

### Actual results

No visible tooltip on Firefox (but it works on Chrome).

#### Screenshots

<img width="1063" alt="Capture d’écran 2019-07-04 à 17 18 16" src="https://user-images.githubusercontent.com/5139669/60676736-eca85200-9e7f-11e9-9062-43b4b9bded9c.png">

#### How to reproduce the bug

1. Go to Explore view or a Dashboard with a line chart
2. Hover a point on the line
3. See no tooltip

### Environment

(please complete the following information):

- superset version: 0.33.0.rc1
- python version: 3.6
- node.js version: 12.5.0
- npm version: 6.1.0

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by schoel-bis** [comment] 2019-07-26 11:46
I am seeing the same here. This is due to #7102, more precisely the style for the body element in ` superset/assets/stylesheets/less/index.less`.

The `position: absolute` setting on the `body` element causes Firefox to calculate the height (and consequently the `clientHeight`) of the `html` element as 0 as absolutely positioned elements have no influence on their parent's height. But NVD3 uses `document.documentElement.clientHeight` (`documentElement` is the `html` element) in the formula for calculating the position of the tooltip. Since it is always `0` on Firefox the calculation produces a grossly false result and places the tooltip off-screen.

My understanding of the change from the pull request above is that is meant to ensure that the body will always cover the entire window. A similar effect should be achievable with something like the following while avoiding the problem described above:

```less
html {
  height: 100%;
}

body {
  min-height: 100%;
  display: flex;
  flex-direction: column;
}
```

**Comment by etr2460** [comment] 2019-07-26 16:33
@schoel-bis Are you sure this is the issue here? I've been investigating this same issue and am pretty sure the root cause is here: https://github.com/apache-superset/superset-ui-plugins/blob/master/packages/superset-ui-legacy-preset-chart-nvd3/src/NVD3Vis.js#L1081

We're removing all tooltips on the page whenever we rerender a chart, which is problematic especially on dashboards where multiple charts could have tooltips in the DOM. If your fix solves the issue here, than awesome, but I think there's another deeper problem that needs to be solved with the nvd3 chart plugin

**Comment by schoel-bis** [comment] 2019-07-26 18:14
Well, frankly I wouldn't bet on this being the one and only problem with tooltips or NVD3 on Firefox or anywhere. Anyway, I wasn't seeing any tooltips whatsoever in Firefox and with that patch applied I have them back.

**Comment by CoryChaplin** [comment] 2019-07-26 18:26
@xtinec maybe you can confirm this as a side effect of your commit ?

**Comment by graceguo-supercat** [comment] 2019-08-30 21:23
@CoryChaplin This PR caused an issue: the standalone mode chart didn't show anymore. please see #7929 for details. We have reverted this PR from master branch.

**Comment by schoel-bis** [comment] 2019-09-02 09:29
So, if the fix has been reverted, this needs to be re-opened, I suppose. I can't find how to do that, though.

Although I do not currently have the time to investigate any further, I'd like to add a few observations:

* Embedded charts work just fine in Firefox with the fix (#7929). Chrome exhibits the behaviour described in the revert (#8147).
* With the fix, in Chrome, the `#chart-container` div is missing entirely from the embedded chart, so it looks like something is going badly wrong in the process of creating the chart. No exceptions are ever logged to the console, though.
* With the fix, Chrome does display the chart if you remove the `standalone=true` query – although this is not what you would want to have displayed when embedding things
* Embedded dashboards are *not* affected

**Comment by amicis31** [comment] 2020-02-06 16:27
Could you open a more general issue or assign `.pinned` to this?

**Comment by magor** [comment] 2020-03-26 11:46
Hi, we are expriencing the same issue with latest stable release, I understand the fix was reverted?

**Comment by saward** [comment] 2020-07-19 12:22
I'm having an issue like this, where hovering mouse over charts with firefox does not display any extra information.

**Comment by betodealmeida** [comment] 2021-04-21 20:41
This seems to be working on Firefox now, I couldn't repro.

![Screen Shot 2021-04-21 at 1 40 37 PM](https://user-images.githubusercontent.com/1534870/115618177-2fcaf380-a2a7-11eb-898b-cee1cd3f904f.png)

**Closed by betodealmeida** 2021-04-21 20:41 UTC
Labels: .pinned, browser:firefox, bug, good first issue, viz:chart-line
