### ISSUE TITLE
Create a color palette with conditional formatting for a Map 

### ISSUE THREAD

**Issue by maliklamblin** [apache/superset#23750] opened 2023-04-20 13:10 UTC
## Problem

I would like to know if it is possible to apply a conditional formatting of the color palettes for a map. 

## Screenshot

![image](https://user-images.githubusercontent.com/106805975/233373286-eab74cdd-eb8c-4695-ba0f-7d6c714ca282.png)

## More details

In relation to the graphics below, I actually want to set a color for a threshold. I work with rates, so for example :
- If the value is >=99%, then green
- If the value is <99% and >=95% then yellow
- If the value is < 95%, then red.

I already tried a lot of things with the css but I didn't find anything, if you have any ideas I'm interested !

Thanks in advance
mlamblin

**Comment by rusackas** [comment] 2023-04-20 20:36
I don't believe there is such a feature, but it's an interesting idea! Would you be willing to open a PR for this?

If you want to work on it, please feel free to join us in #contributing on [Slack](http://bit.ly/join-superset-slack). Or if you're just looking for input/discussion on the idea, you could also open an Ideas thread on the Discussions tab here on the repo.

Closing for now since it's not a bug, but happy to chat on those other fora.

**Closed by rusackas** 2023-04-20 20:36 UTC

**Comment by LeoDiep** [comment] 2023-08-18 03:11
+1 for this, with only 3 colors as default for conditional formating, it is so annoying

**Comment by DamiraReicherd** [comment] 2024-02-22 10:52
+1
