### ISSUE TITLE
Lisence

### ISSUE THREAD

**Issue by trixieboyle** [apache/superset#25186] opened 2023-09-05 14:51 UTC
/vendor/lib/soundfx/libbundlewrapper.so
/vendor/lib/soundfx/libdownmix.so
/vendor/lib/soundfx/libdynproc.so
/vendor/lib/soundfx/libeffectproxy.so
/vendor/lib/soundfx/libhapticgenerator.so
/vendor/lib/soundfx/libldnhncr.so
/vendor/lib/soundfx/libmyspace.so
/vendor/lib/soundfx/libreverbwrapper.so
/vendor/lib/soundfx/libvisualizer.so
/vendor/lib/vndk/libstagefright_omx_utils.so
/vendor/lib/vndk/libstagefright_xmlparser.so
//Written Offer for Source Code

**Comment by sfirke** [comment] 2023-09-05 16:01
Duplicate of #25136

**Closed by sfirke** 2023-09-05 16:01 UTC
