### ISSUE TITLE
SQLLab Query Results not appearing if we leave tabs open for a long time

### ISSUE THREAD

**Issue by pabrahamusa** [apache/superset#13066] opened 2021-02-10 22:33 UTC
SuperSet SQLLab query search will not display any results , even if there are results. This happens when we leave the browser open for a long time say 1-2 hours. Or we revisit the SqlLab (Chrome) after ~2 hours. 

As a workaround I have to close the tab and reopen the tab, Copy the SQL query across then run the query again a fresh.

### Expected results

I expect the SQL results to appear in SQLLab no matter how long I leave my browser open 

### Actual results

No Results for SQL search 

#### Screenshots

![image](https://user-images.githubusercontent.com/47830507/107581754-855b9380-6bc6-11eb-9b43-81047ae3e85e.png)

#### How to reproduce the bug

1. Go to SQLLab and open three tabs 
2. Go to each tab and execute some query, verify the results are appearing.
3. Now leave the browser for 1 to 2 hours. If Chrome close the browser tab and open again after 2 hours
    the same tabs will be reloaded from cache
4. Go to one of the tab , click Run . The SQL will be executed but results wont be displayed.

### Environment

(please complete the following information):

- superset version: 1.0.1 (build from master branch as of Feb 9 2021)
- python version: Python 3.7.9
- node.js version: `node -v`

### Additional context

As a workaround I have to Copy the SQL query from the broken tab, close the tab and reopen the tab, paste the SQL query across then run the query again a fresh. The main problem is sometimes we get confused that there are no results for a query then later only we realize this is a SuperSet UI issue.

**Comment by yousoph** [comment] 2021-11-30 00:49
Hi @pabrahamusa  - we were unable to reproduce this bug so closing this issue. If you are still able to repro on the latest version of Superset, feel free to reopen with more details. Thanks!

**Closed by yousoph** 2021-11-30 00:49 UTC
Labels: bug, sql_lab:editor
