### ISSUE TITLE
Load custom fonts in Superset

### ISSUE THREAD

**Issue by catadedu** [apache/superset#23442] opened 2023-03-21 13:38 UTC
Hello all,

Is there a way to load custom fonts in Superset.

thanks

**Comment by rusackas** [comment] 2023-04-05 21:55
Closing this since it's not a bug, but you can hit us up in the `#customizing-superset` channel on 

Long story short, if you want to make system-wide changes in Superset's code, there are thematic changes you can make (I'll publish a blog on this asap), but if you want to do it on a per-dashboard basis, you can do it with CSS, as seen in this recent blog post I wrote:
https://preset.io/blog/customizing-superset-dashboards-with-css/

**Closed by rusackas** 2023-04-05 21:55 UTC
