### ISSUE TITLE
X axis format on horizontal bar char numbers ("values") overlap and are cut in half

### ISSUE THREAD

**Issue by Vicinius** [apache/superset#25791] opened 2023-10-30 12:24 UTC
#### How to reproduce the bug

1. Go to Charts
2. Click on Bar Chart
3. Create an horizontal bar chart with data values above 99%

### Expected results

X axis on bar chart doesn't show up properly on a lot of situations. When you use the horizontal bar chart and you set the X axis format to %, on smaller screens they just can't be read, because they overlap. Also, with percentages like 99%ish (when you select SHOW VALUES) you get the numbers and %'s cut in half. Also on edit chart screen you get the same behaviour. I'm really interested in solving this but have literally no idea if the issue is on apache echarts or where else

PS: If this should be on "cosmetic issue" please tell me so I can change

#### Screenshots

![264450334-87ea38a2-3e89-419e-8e5f-6eea8045cbe1](https://github.com/apache/superset/assets/59844324/cef58cdf-99c6-4973-8431-b254ac81e04f)

![264450416-76969552-87cb-4d99-9857-66e0665c053e](https://github.com/apache/superset/assets/59844324/ab656885-87dd-483a-bffd-b710c16433ee)

![264450467-c5f3adfc-d067-4f65-aab7-9710597826e1](https://github.com/apache/superset/assets/59844324/c1578ccc-5352-4025-b915-bd7c9e8cd9a6)

### Environment

- browser type and version:
- superset version: `2.1.1` and 3.0
- python version: `3.11.4`
- node.js version: -
- any feature flags active: GENERIC_CHART_AXES

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

It happens both on 2.1.1 and on 3.0.0. The issue here is with horizontal bar chart and horizontal bar chart only. Even on bigger screens and fullscreen, the chart will cut the numbers because It probably does not work well with the (x axis on 2 decimal points, 0.00%)

**Comment by sfirke** [comment] 2023-10-31 16:27
Hello, this looks like an exact duplicate of #25791.  I'm going to close this so that the issue can be tracked in a single place.

I'm sorry no one has been able to address that other issue.  Unfortunately I also don't know where you'd start working on this.

**Closed by sfirke** 2023-10-31 16:27 UTC

**Comment by hk-the-analyst** [comment] 2024-04-17 03:42
I too have the same issue
