### ISSUE TITLE
Timestamp formats diplayed as NaN:NaN:NaN

### ISSUE THREAD

**Issue by unicornis-pl** [apache/superset#22841] opened 2023-01-24 10:04 UTC
In charts time fields are displayed as NaN:NaN

#### How to reproduce the bug

1. Run SQL query: `SELECT CURTIME()`
2. Result: `0 days 09:26:27`
3. Create chart to explore query results, add field to chart, chose any of available timestamp formats

### Expected results
Data displayed in chart as 09:26:27

### Actual results
Data displayed in chart as NaN:NaN:NaN

#### Screenshots
![Screenshot 2023-01-23 092020](https://user-images.githubusercontent.com/14240283/214250018-ee5c4353-6a74-4bff-bfc2-7d96a373a455.jpg)

### Environment

(please complete the following information):

- browser type and version on client: Chrome on Windows, 108.0.5359.126
- superset version: `Version: 2.0.1`
- python version: `Python 3.8.13`
- node.js version: `v12.22.12` on server, none on client
- any feature flags active: `superset run --host=0.0.0.0 -p 8008 --with-threads --reload --debugger`
- database: `mysql  Ver 15.1 Distrib 5.5.68-MariaDB, for Linux (x86_64) using readline 5.1`
```
pip list --local
Package                Version
aiohttp                3.8.3
aiosignal              1.3.1
alembic                1.9.1
amqp                   5.1.1
apache-superset        2.0.1
apispec                5.2.2
async-generator        1.10
async-timeout          4.0.2
attrs                  22.2.0
Babel                  2.11.0
backoff                2.2.1
billiard               3.6.4.0
bleach                 3.3.1
Brotli                 1.0.9
cachelib               0.4.1
celery                 5.2.7
certifi                2022.12.7
cffi                   1.15.1
charset-normalizer     2.1.1
click                  8.1.3
click-didyoumean       0.3.0
click-plugins          1.1.1
click-repl             0.2.0
colorama               0.4.6
convertdate            2.4.0
cron-descriptor        1.2.32
croniter               1.3.8
cryptography           3.4.7
deprecation            2.1.0
dnspython              2.2.1
email-validator        1.3.0
exceptiongroup         1.1.0
Flask                  2.2.2
Flask-AppBuilder       4.2.0
Flask-Babel            2.0.0
Flask-Caching          1.11.1
Flask-Compress         1.13
Flask-JWT-Extended     4.4.4
Flask-Login            0.6.2
Flask-Migrate          4.0.1
Flask-SQLAlchemy       2.5.1
flask-talisman         1.0.0
Flask-WTF              1.0.1
frozenlist             1.3.3
func-timeout           4.3.5
geographiclib          2.0
geopy                  2.3.0
graphlib-backport      1.0.3
gunicorn               20.1.0
h11                    0.14.0
hashids                1.3.1
hijri-converter        2.2.4
holidays               0.14.2
humanize               4.4.0
idna                   3.4
importlib-metadata     6.0.0
importlib-resources    5.10.2
isodate                0.6.1
itsdangerous           2.1.2
Jinja2                 3.1.2
jsonschema             4.17.3
kombu                  5.2.4
korean-lunar-calendar  0.3.1
Mako                   1.2.4
Markdown               3.4.1
MarkupSafe             2.1.1
marshmallow            3.19.0
marshmallow-enum       1.5.1
marshmallow-sqlalchemy 0.26.1
msgpack                1.0.4
multidict              6.0.4
mysql-connector-python 8.0.31
mysqlclient            2.1.1
numpy                  1.22.1
outcome                1.2.0
packaging              23.0
pandas                 1.3.5
parsedatetime          2.6
pgsanity               0.2.9
Pillow                 9.4.0
pip                    22.3.1
pkgutil_resolve_name   1.3.10
polyline               1.4.0
prison                 0.2.1
prompt-toolkit         3.0.36
protobuf               3.20.1
pyarrow                5.0.0
pycparser              2.21
PyJWT                  2.6.0
PyMeeus                0.5.12
PyMySQL                1.0.2
pyparsing              3.0.9
pyrsistent             0.19.3
PySocks                1.7.1
python-dateutil        2.8.2
python-dotenv          0.21.0
python-geohash         0.8.5
pytz                   2022.7
PyYAML                 6.0
redis                  4.4.1
selenium               4.7.2
setuptools             56.0.0
simplejson             3.18.1
six                    1.16.0
slackclient            2.5.0
sniffio                1.3.0
sortedcontainers       2.4.0
SQLAlchemy             1.3.24
SQLAlchemy-Utils       0.37.9
sqlparse               0.3.0
tabulate               0.8.9
trio                   0.22.0
trio-websocket         0.9.2
typing-extensions      3.10.0.2
urllib3                1.26.13
vine                   5.0.0
wcwidth                0.2.5
webencodings           0.5.1
Werkzeug               2.2.2
wsproto                1.2.0
WTForms                2.3.0
WTForms-JSON           0.3.5
yarl                   1.8.2
zipp                   3.11.0
```

**Comment by villebro** [comment] 2023-03-13 08:09
What database engine is this happening on @unicornis-pl?

**Comment by villebro** [comment] 2023-03-13 08:12
It appears the database is returning the timestamp in non standard string format. To make the table chart able to parse the date you should first convert it to ISO-8601 format (I assume there should be functions for this in MySQL).

**Comment by Shazad-khan** [comment] 2023-03-16 14:42
![image](https://user-images.githubusercontent.com/100838455/225652588-bd071ec5-8841-4cd3-857a-64de9c8dcb44.png)


It is working as expected please recheck it and close this issue

**Comment by unicornis-pl** [comment] 2023-03-17 09:33
I will and I'll let you know. Thank you

**Comment by sfirke** [comment] 2023-08-11 13:30
@unicornis-pl are you able to test this issue in 3.0.0rc2 release candidate?  I'm unable to reproduce it there, but I'm using a different data warehouse (MS SQL Server instead of your MySQL) so it would be nice to get confirmation that this has been fixed.

**Comment by unicornis-pl** [comment] 2023-08-11 15:13
I'll do it after my holiday

**Comment by rusackas** [comment] 2024-02-13 20:56
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

**Closed by rusackas** 2024-02-13 20:56 UTC
Labels: validation:required, #bug
