### ISSUE TITLE
Not able to Schedule Report  , some issue in the latest release

### ISSUE THREAD

**Issue by shafad1** [apache/superset#26335] opened 2023-12-22 05:37 UTC
I have configured one report to send over mail,  while scheduling getting the below error 

![image](https://github.com/apache/superset/assets/107529872/064c8dd2-db9a-467f-8763-beab9a2f85bd)

Please help me to solve this , past two months i am trying to fix this as the same issue was faced in the version 3.0.1 as well

**Comment by sfirke** [comment] 2023-12-27 16:48
Did you try searching the GitHub repo for your error message?  I searched "SQLite datetime" and found this issue where someone else was experiencing the same thing: https://github.com/apache/superset/issues/25969  It's better to post the error as text, not as an image, so that other people can find it via search.

They were using SQLite as a metadata db and they fixed the problem by switching to Postgres.

The Superset community voted to [remove support for SQLite as a metadata database](https://github.com/apache/superset/issues/8874), this is [scheduled to happen at the next major release](https://github.com/orgs/apache/projects/292/views/1?pane=issue&itemId=40454778) (4.0)

So while someone could theoretically try to fix this problem, in practice people should be migrating away from SQLite and this would be a poor investment of developer energy.  I'm going to close this as a duplicate of #25969 but please let us know if migrating to Postgres does not solve your problem.

**Closed by sfirke** 2023-12-27 16:48 UTC

**Comment by kha84** [comment] 2024-05-01 11:20
Actually there's an easy way to restore it back to work with SQLite.
You just need to modify superset/reports/models.py like this:
```
$ diff ./reports/models.py ./reports/models.py.original
36d35
< from sqlalchemy.types import TypeDecorator
205,213d203
< class MyDateTime(TypeDecorator):
<     impl = DateTime
<
<     def process_bind_param(self, value, dialect):
<         from datetime import datetime
<         if type(value) is str:
<             return datetime.strptime(value, '%Y-%m-%dT%H:%M:%S')
<         return value
<
225,227c215,217
<     scheduled_dttm = Column(MyDateTime, nullable=False)
<     start_dttm = Column(MyDateTime)
<     end_dttm = Column(MyDateTime)
---
>     scheduled_dttm = Column(DateTime, nullable=False)
>     start_dttm = Column(DateTime)
>     end_dttm = Column(DateTime)
```

Or, elaborated:

1) add this import somewhere to beginning:
```
from sqlalchemy.types import TypeDecorator
```
2) to add this class:
```
class MyDateTime(TypeDecorator):
    impl = DateTime

    def process_bind_param(self, value, dialect):
        from datetime import datetime
        if type(value) is str:
            return datetime.strptime(value, '%Y-%m-%dT%H:%M:%S')
        return value
```
3) to change ReportExecutionLog class to use MyDateTime like this:
```
class ReportExecutionLog(Model):  # pylint: disable=too-few-public-methods
    """
    Report Execution Log, hold the result of the report execution with timestamps,
    last observation and possible error messages
    """

    __tablename__ = "report_execution_log"
    id = Column(Integer, primary_key=True)
    uuid = Column(UUIDType(binary=True))

    # Timestamps
    scheduled_dttm = Column(MyDateTime, nullable=False)
    start_dttm = Column(MyDateTime)
    end_dttm = Column(MyDateTime)

    # (Alerts) Observed values
    value = Column(Float)
    value_row_json = Column(MediumText())

    state = Column(String(50), nullable=False)
    error_message = Column(Text)

    report_schedule_id = Column(
        Integer, ForeignKey("report_schedule.id"), nullable=False
    )
    report_schedule = relationship(
        ReportSchedule,
        backref=backref("logs", cascade="all,delete,delete-orphan"),
        foreign_keys=[report_schedule_id],
    )

    __table_args__ = (
        Index("ix_report_execution_log_report_schedule_id", report_schedule_id),
        Index("ix_report_execution_log_start_dttm", start_dttm),
    )
```

**Comment by shafad1** [comment] 2024-05-01 13:22
Hello
I am not able to apply dynamic filter using superset jinja by
inputting filter values to the sql query .. superset is adding additional
where clause on top of my query who will not give proper result.. totally
feel superset is not  good option for reporting . currently need to solve
for existing customers .

apache superset automatically adding outer query while using jinja which is
restricting to achieve proper dynamic filtering..  i am not able to execute
this query properlySELECT * FROM RPT_CBI_PAYMENT_ILL
WHERE CUSTOMER_ID < (
    {% for value in filter_values('CUSTOMER_ID') %}
        '{{ value }}'
    {% endfor %}
    '')
6:46
<https://apache-superset.slack.com/archives/CK1P3L23E/p1714569402801279>

query will print like this .SELECT `TRANSACTION_DATE` AS `TRANSACTION_DATE`,
       `CUSTOMER_ID` AS `CUSTOMER_ID`,
       `ACCOUNT_ID` AS `ACCOUNT_ID`,
       `PAYMENT` AS `PAYMENT`,
       `ACCOUNT_CODE` AS `ACCOUNT_CODE`,
       `CREATE_TIME` AS `CREATE_TIME`
FROM
  (SELECT *
   FROM RPT_CBI_PAYMENT_ILL
   WHERE CUSTOMER_ID < ('1000020889603' '')) AS virtual_table
WHERE `CUSTOMER_ID` IN (1000020889603)






6:46
<https://apache-superset.slack.com/archives/CK1P3L23E/p1714569414052269>

**Comment by sfirke** [comment] 2024-05-01 13:35
Hi @shafad1 that seems like a different problem.  Please search for existing GitHub issues, I tried searching "jinja" "where" and found this which appears to be your issue but you can look further as many hits were returned: https://github.com/apache/superset/issues/23846#issuecomment-1528858466

In short, can you use dashboard filter scoping controls to stop that filter from applying on that chart?

Also Superset does not have "customers" as it is open-source free software.  If you are able to contribute to improving it, whether to the code or documentation or helping others, please do so.
