### ISSUE TITLE
[chart]queries with order by have no effect on bar chart

### ISSUE THREAD

**Issue by Riskatri** [apache/superset#13807] opened 2021-03-26 09:26 UTC
I'm using a bar chart, because I want my chart to be ordered by month so I added orders by month in my query but the result doesn't have any effect.

this is my result 
![image](https://user-images.githubusercontent.com/59104917/112610882-c2ff3d80-8e4f-11eb-83c3-9384fe3ca7a5.png)

and this is result of sql lab

![image](https://user-images.githubusercontent.com/59104917/112611071-f215af00-8e4f-11eb-93a5-8357adba93a5.png)

**Comment by junlincc** [comment] 2021-03-27 05:31
yup, order by doesn't work in nvd3 bar chart...not sure that's a historical issue or regression(unlikely)..
We won't be fixing it at this point since Echarts Bar will be available soon, but a quick fix PR is still welcome.

**Closed** 2021-04-21 20:20 UTC
Labels: bug, viz:chart-bar
