### ISSUE TITLE
Save and Discard button missing in Edit Dashboards.

### ISSUE THREAD

**Issue by MalavikaN1** [apache/superset#24516] opened 2023-06-26 10:09 UTC
When I choose the edit dashboard option, I can edit the dashboard, add new charts and delete charts. However, I see no save or discard button.
The version I use is 2.1.0

![savebtn](https://github.com/apache/superset/assets/60867680/2d40d0fc-f0dd-4fe2-8942-ab918cd722a0)

Earlier I used ` latest` tag in the docker image and the version was 0.0.0-dev and I could see the save and discard button. 
But now I've changed the version to 2.1.0, there is no edit or discard button.

**Comment by Gurbrinder0031** [comment] 2023-06-26 10:50
Getting the Same Issue also draft and publish also not working.

**Comment by sfirke** [comment] 2023-06-29 13:37
What roles are affected by this - admin, alpha, gamma, etc?

**Comment by MalavikaN1** [comment] 2023-06-29 13:46
@sfirke Admin role ws affected by this.

**Comment by sfirke** [comment] 2023-06-29 19:58
An admin user on a clean install of 2.1.0 should see those buttons.  I wonder if something broke when you went from `latest` back to 2.1.0?  @Gurbrinder0031 , did you come to 2.1.0 from a `latest` or other version?

**Comment by MalavikaN1** [comment] 2023-06-30 06:24
@sfirke I went from latest to version 2.1.0

**Comment by lulucici** [comment] 2023-07-19 10:24
I met the same problem when I went from latest to 2.1.0 as well, after removing all volumes, a clean version can work.

**Comment by MalavikaN1** [comment] 2023-07-21 05:38
@lulucici Thanks

**Comment by juanmongevankpay** [comment] 2023-08-17 03:42
Is there a solution for this aside from removing all volumes? 

I did the same. I went from latest to 2.1.0 and the save button disappeared.

**Comment by natechoiniere** [comment] 2023-08-17 18:01
Also looking for a solution to this. Started using latest tagged Docker image, couldn't login from an external wifi network after portforwarding 8088 on the Superset host, downgraded to 2.1.0 and now I can log in but not change my Dashboards. Fml

**Comment by xsahban** [comment] 2023-10-11 09:49
Facing same issue with 2.1.0, Is it fixed in newer versions?

**Comment by rusackas** [comment] 2024-03-19 22:35
I'm not sure if this is still an issue in current versions of Superset (3.x). If it is, we can re-open this, or feel free to open a new issue with updated context and a reproducible case using example data. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale.

**Closed by rusackas** 2024-03-19 22:35 UTC
