### ISSUE TITLE
spark sql connection has query issue

### ISSUE THREAD

**Issue by cometta** [apache/superset#22206] opened 2022-11-23 10:37 UTC
1 bug)
on the sql lab page -> `SEE TABLE SCHEMA` selectbox throw pop up error when press `refresh` icon,  the `schema` select box is working fine. the custom query textbox also working fine. see screenshot

![image](https://user-images.githubusercontent.com/187495/203525553-41a153e5-3fe1-42ee-9028-0a2bb8443184.png)

2 bug)
settings-> database connection-> select existing `Apache Spark SQL` -> click edit
basic tab show empty, pop up
`An error occurred while fetching databases: Object of type bytes is not JSON serializable`

![image](https://user-images.githubusercontent.com/187495/203525881-49c6d49b-d4bf-4346-ba6a-c95fdbbad37f.png)

**Comment by eschutho** [comment] 2022-11-23 23:52
HI @cometta. Which version of the app are you on?

**Comment by eschutho** [comment] 2022-12-01 17:45
There was an existing issue on this, which I believe has been resolved. Can you pull again from master and test?

**Comment by eschutho** [comment] 2022-12-02 22:24
I don't have spark sql set up, but I'm unable to reproduce on other databases. Can you confirm by testing this on another database to make sure that it's not just happening on spark? If it's still happening with say postgres or even sqlite, then I would try to delete your docker images and pull from docker latest again instead of pulling from github.

**Comment by meyergin** [comment] 2022-12-23 12:46
> 

I've pulled latest master branch, this bug only happens on spark which used pyhive package.

**Comment by si1verwind17** [comment] 2023-01-03 09:52
I also have this problem as well when connect with sparksql, it show an error when clicking at "SEE TABLE SCHEMA". However, it work fine when I query with sql statement (SELECT * FROM table)

**Comment by xiaotiao** [comment] 2023-04-28 09:05
it seems the json.dumps method error becase of wrong driver type when using Apache Spark. I modified the code as below and the response is right when click edit databse button

`
# method: models.core.Database.driver
    def driver(self) -> str:
        if isinstance(self.url_object.get_driver_name(),bytes):
            return bytes(self.url_object.get_driver_name()).decode("utf-8")
        return self.url_object.get_driver_name()
`

**Comment by eschutho** [comment] 2023-04-28 22:52
I just tested this with the pyhive driver and didn't have any errors:
```
from sqlalchemy.engine.url import make_url
make_url('hive://').get_driver_name() 
```
returns `b'thrift'`
Is this where the error is happening for you @xiaotiao?

**Comment by xiaotiao** [comment] 2023-05-14 04:28
> 

I discovered that json.dumps cannot deserialize bytes data, so I converted the b'thrift' object to a string using the decode() method.

**Comment by xiaotiao** [comment] 2023-05-14 04:28
> I just tested this with the pyhive driver and didn't have any errors:
> 
> ```
> from sqlalchemy.engine.url import make_url
> make_url('hive://').get_driver_name() 
> ```
> 
> returns `b'thrift'` Is this where the error is happening for you @xiaotiao?

I discovered that json.dumps cannot deserialize bytes data, so I converted the b'thrift' object to a string using the decode() method.

**Comment by xiaotiao** [comment] 2023-05-14 04:31
> I just tested this with the pyhive driver and didn't have any errors:
> 
> ```
> from sqlalchemy.engine.url import make_url
> make_url('hive://').get_driver_name() 
> ```
> 
> returns `b'thrift'` Is this where the error is happening for you @xiaotiao?

yes, my superset verison is 2.1.0, when click edit database button it will report exception: Object of type bytes is not JSON serializable, and I discovered that json.dumps cannot deserialize bytes data, so I converted the b'thrift' object to a string using the decode() method.

**Comment by Udutta52** [comment] 2023-05-19 20:51
The issue is with the pyhive package installed in your machine.
You can resolve it by installing this version of pyhive:
`pip install git+https://github.com/dropbox/PyHive.git`

**Comment by rusackas** [comment] 2024-03-04 18:59
Hopefully, the answer above is sufficient to close this thread. I'll do so anyway since it's been so long since there was a comment here. If this needs revisiting/reopening, just say the word.

**Closed by rusackas** 2024-03-04 18:59 UTC
Labels: data:connect:sparksql, #bug
