### ISSUE TITLE
ERROR: Could not load database driver: AzureSynapseSpec

### ISSUE THREAD

**Issue by handita** [apache/superset#15700] opened 2021-07-15 01:29 UTC
I have tested superset with this url sqlalchemy
I have installed pip install pymssql

mssql+pymssql://sa@12345JK@127.0.0.1:1433/SKU

### Actual results

It said 
`ERROR: Could not load database driver: AzureSynapseSpec`

#### How to reproduce the bug

1. Go to 'Database'
2. Click on '+ DATABASE'
3. Add url to mssql uri 
![image](https://user-images.githubusercontent.com/2508835/125713554-d2b72b8f-2b49-4a05-9e3d-14c9e7de0028.png)

### Environment

(please complete the following information):

- superset version: `Superset 1.2.0`
- python version: `Python 3.9.5`
- node.js version: `v14.17.3`

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

I have googling with those keyword, But I can't find the answer.

**Comment by srinify** [comment] 2021-07-19 14:27
H @handita this error is usually thrown when the database driver isn't installed / available in the same python context that Superset runs in.

- If you're using Python + pip + virtual environments, make sure you `pip install pymssql`  in the same Python context that you're running Superset in. 

- If you're using Docker, you need to modify a requirements file and reload Docker or Docker Compose. You can read more about that here: https://superset.apache.org/docs/databases/dockeradddrivers

I'm closing this for now, as this is not a bug but a configuration issue.

**Closed by srinify** 2021-07-19 14:27 UTC
Labels: #bug

**Comment by cyberop5** [comment] 2022-04-01 21:17
Updated link for adding database drivers for Docker: [https://superset.apache.org/docs/databases/docker-add-drivers]()
