### ISSUE TITLE
Docker Container keep not responding

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [apache/superset#18565] opened 2022-02-03 06:55 UTC
We use superset in docker-compose. But many times we get the 504 error while accessing the UI page.

Then we do restart the `superset_app` container to bring it back. 

This is error we got from the syslog.
```bash
time="2022-02-03T06:39:12.214565365Z" level=warning msg="Health check for container 656caa8ad556ccaef7627c607822b26f9f4fcb437ccf5ea9534a94ec201b8be1 error: context deadline exceeded"
```

And from the docker status almost all the containers are unhealthy. 

```
docker ps
```
![image](https://user-images.githubusercontent.com/47310439/152295396-80fbcf8a-d8b7-482a-baec-8153e37567e6.png)

**Comment by srinify** [comment] 2022-02-03 15:01
Hi @BhuviTheDataGuy Github Discussions or the Superset Slack is the right place for debugging help & suggestions. I'm closing this issue for now since it's not a bug :] 

However, as a quick comment, I would try increasing the memory allocated for Docker. I wonder if your containers are starved for resources and Docker is killing them early.

**Closed by srinify** 2022-02-03 15:01 UTC
