### ISSUE TITLE
German Translation not correctly implemented?

### ISSUE THREAD

**Issue by CFM90** [apache/superset#19431] opened 2022-03-30 11:54 UTC
The German translation is very much incomplete. But I suspect a bug not an incomplete tanslation per se, because as the screnshots  by @hbruch in [PR17525 ](https://github.com/apache/superset/pull/17525) indicate, the German translation is way more complete compared what I can find on a fresh install. So there may be a good German translation which is not correctly included in superset itself. This would be a pitty for all German users and the creator of the translation.

#### How to reproduce the bug
1. Install Superset from Scratch following [this](https://superset.apache.org/docs/installation/installing-superset-from-scratch). (so not using docker)
2. Add the following to the superset_config:

```
BABEL_DEFAULT_LOCALE = "de"
BABEL_DEFAULT_FOLDER = "superset/translations"

LANGUAGES = {
    'en': {'flag': 'us', 'name': 'English'},
    'de': {'flag': 'de', 'name': 'German'}
}
```
### Expected results
A German translation similar to those visible on the screenshots by @hbruch  in: 
[PR17525 ](https://github.com/apache/superset/pull/17525 ) 

### Actual results & Screenshots
![grafik](https://user-images.githubusercontent.com/24831579/160825258-81b93c6f-c8df-44bb-b217-175405c0b951.png)

![grafik](https://user-images.githubusercontent.com/24831579/160825354-440fab08-d0bd-4ceb-b7a4-83b6636055ec.png)

![grafik](https://user-images.githubusercontent.com/24831579/160825404-3612be18-6994-432f-aecd-56a6a64ea9e8.png)

You can see that there are terms which are translated to German and others which are not. The overall impression is very incomplete and incomprehensive. 

### Environment
- browser type and version: Mozilla Firefox V 98.02
- superset version: `1.4.2`, the most recent one
- python version: `3.8.10`
- node.js version: `v10.19.0`
- any feature flags active:

```
FEATURE_FLAGS = {
  "DASHBOARD_CACHE": True,
  "ALERT_REPORTS": True,
  "DASHBOARD_RBAC": True,  
  "LISTVIEWS_DEFAULT_CARD_VIEW" : True,
  "ENABLE_EXPLORE_DRAG_AND_DROP": True,
  "OMNIBAR" : True,
  "CLIENT_CACHE": True
}
```

### Checklist
Make sure to follow these steps before submitting your issue - thank you!
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional Information
I also worked on a translation (because I thought the existing one is just incomplete). I was able to translate more words and terms using the .mo files as seen on the screenshots here from the fresh install. So the translation from the fresh install is not incomplete because the englisch words are not included in the babel process.

**Comment by rusackas** [comment] 2023-01-23 04:03
I think this is not a bug, per se, but rather a piece of technical debt that needs to be worked on. The configuration itself even admits this:
```
# Turning off i18n by default as translation in most languages are
# incomplete and not well maintained.
```
I'll close this since it's been open for upward of a year and hasn't gotten any attention. Suffice it to say that we would LOVE to see some PRs in this area, and incrementally make the situation better for German and other languages as well. If you'd like assistance, please reach out. 

Thanks!

**Closed by rusackas** 2023-01-23 04:03 UTC
Labels: i18n:german, #bug

**Comment by hbruch** [comment] 2023-04-07 22:04
With https://github.com/apache/superset/pull/23402 merged just now, a next bunch of German translations has been added. Helas, it did not make it into the 2.1.0 release, so you would need to build it from `master`. 

There will still be some messages  which are not localized, as i18n is still to be done. See https://github.com/apache/superset/pull/21479 

Note: the .po files need to be compiled, e.g. using `pybabel compile -d superset/translations`. When using docker, this is already be taken care of.
