### ISSUE TITLE
superset-frontend: upgrade version of react, webpack, ant-design etc.

### ISSUE THREAD

**Issue by wenqi73** [apache/superset#22384] opened 2022-12-11 13:05 UTC
*Please make sure you are familiar with the SIP process documented*
(here)[https://github.com/apache/superset/issues/5602]. The SIP will be numbered by a committer upon acceptance.

### Motivation
Current frontend version is old, any plans to upgrade to react@18, webpack@5, ant-design@5?
Includes the `@superset-ui/core` and the plugins.

**Comment by rusackas** [comment] 2022-12-12 23:15
Closing this since it's not a bug. Happy to open this thread in the Ideas section of Github Discussions, if you'd like!

In general, we do try to keep things current, but major version upgrades often cause a lot of regressions, so they tend to happen slowly after extensive testing and tech debt catchup.

Webpack is already bumped to V5. 

It'd be lovely to bump to AntD 5, but there will be a LOT of cosmetic regressions. We're ramping up our visual regression testing to help get ready for this.

React 18 sounds lovely, but there's no active plan here to my recollection. PRs on any of the above are more than welcomed (no SIP required, I'd say). Please feel free to join us on the #contributing channel of Slack, or here on Discussions, if you'd like to discuss that process further. Thanks!

**Closed by rusackas** 2022-12-12 23:15 UTC
