### ISSUE TITLE
Bar chart: how to show a value inside the space it belongs to

### ISSUE THREAD

**Issue by GinkoValery** [apache/superset#25462] opened 2023-09-29 12:32 UTC
Hi everyone!
My question is about bar charts: is it possible to show values in the space the value belongs to? Now the values are shown above, but not inside appropriate squere.
![image](https://github.com/apache/superset/assets/113714043/b4e8c30f-5de7-49cc-a675-90fc9b94cf7f)

**Comment by sfirke** [comment] 2023-09-29 13:44
I am playing with this and no, I don't see how to do that.  The labels seem to always go on top of the category.  Inside would be a nice option.  Could you check and see if something like that exists as a feature request, either in Github Issues or GitHub Discussions (which is where it should go) and if not, create one in GitHub Discussions?  You could use your screenshot and link back to this issue by mentioning it.

I'm going to close this as it's not a bug report.  By the way I see you have opened multiple issues recently - have you checked out the Superset Slack chat?  It's a good place to start for things that are questions / not bug reports.

**Closed by sfirke** 2023-09-29 13:44 UTC
