### ISSUE TITLE
Developing Custom Native Filter 

### ISSUE THREAD

**Issue by santoshmallah** [apache/superset#23310] opened 2023-03-08 10:09 UTC
I want to develop a custom native filer in superset that can have a ```simple text box``` from which I can get value and validate and then get that value to use for calculation in the chart or filter the chart.

I have followed the steps from [https://superset.apache.org/docs/contributing/creating-viz-plugins/](url)
but I think this will create charts only not filters.
Even Superset Yeoman Generator only has 2 options for ```chart only``` as shown in the image

![image](https://user-images.githubusercontent.com/51262721/223683778-407427a5-bd00-48ae-8ded-3f3d7efe7535.png)

I there any way to develop a custom filter in apache superset 

It will be really helpful if anyone can guide me.

Thank you.

- browser type and version: `Chrome`
- superset version: `2.0.1`
- python version: `3.8.0`
- node.js version: `16.14.2`

**Comment by HeathLee** [comment] 2023-05-30 10:57
+1 need doc to create new custome filter

**Comment by sundaram-dubey** [comment] 2023-09-08 10:32
Has any progress been made on this ?

**Comment by rusackas** [comment] 2024-03-08 21:10
Closing this since it is not a bug... if you want to build custom filters, you'd have to dissect the existing ones. If you do, we'd love any blogs or documentation you might want to contribute to the effort to help others. Contributing to the yeoman generator is also welcome, though I'm not 100% sure we'll keep that approach forever... it hasn't been the easiest to maintain.

**Closed by rusackas** 2024-03-08 21:10 UTC
Labels: #bug
