### ISSUE TITLE
saved queries - schema with null value

### ISSUE THREAD

**Issue by mchogithub** [apache/superset#18716] opened 2022-02-14 14:30 UTC
After saving the queries the schema is not valorized, the null value remains and it is not possible to update it in subsequent saves

#### How to reproduce the bug

1. Go to SQL Lab > SQL Editor
2. Click on Database and select one
3. Click on Schema and select one
4. Edit and run query
4. Click on Save button
5. Click on Data > Saved Queries and open the newly saved query
6. Click on Run button and the following is shown
![image](https://user-images.githubusercontent.com/5494498/153882571-52d4b4f9-5fab-43f1-aef0-d322abfc1009.png)

### Expected results

the "Schema" should remain saved

### Actual results

the "Schema" always remains valued at null, even when a different value is selected from the drop-down menu
#### Screenshots

![image](https://user-images.githubusercontent.com/5494498/153882443-01dfdcf7-e012-4217-892e-4ff0208a445b.png)

### Environment

- docker-compose -f docker-compose-non-dev.yml up (1.4.1)
- helm chart superset-0.5.8
 
### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by zhaoyongjie** [comment] 2022-02-16 06:17
Hi @mchogithub, according to [MySQL Reference Manual](https://dev.mysql.com/doc/refman/8.0/en/glossary.html#glos_schema) said
> In MySQL, physically, a schema is synonymous with a database. You can substitute the keyword SCHEMA instead of DATABASE in MySQL SQL syntax, for example using CREATE SCHEMA instead of CREATE DATABASE. 

`schema` and `database` is the same namespace, so `schema` put null value on MySQL driver make sense.

I try this issue on PostgreSQL 12 on my local machine. The schema can be successfully saved.

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/2016594/154207478-f605290b-708e-42a7-80f3-60f36a141ed1.png">

**Comment by mchogithub** [comment] 2022-02-16 13:23
Thanks @zhaoyongjie 
I have tried also with the pre installed postgresql database "examples" but it still sets the schema to NULL:
![image](https://user-images.githubusercontent.com/5494498/154272040-37145efa-5c98-4c8a-90e0-aae3defdb28a.png)

Current Database settings:
Default PSQL:
![image](https://user-images.githubusercontent.com/5494498/154272318-d736cc83-2614-4bb1-a0c3-b8aaf6c3a606.png)

MySQL:
![image](https://user-images.githubusercontent.com/5494498/154272428-11ac81f0-ba55-412a-a820-326dcef13ae9.png)


In the currently installed version we had the same problem, but going to edit, we could set correctly the schema:
![image](https://user-images.githubusercontent.com/5494498/154272085-04cb87fb-7430-4e72-8c9b-003ccf47813b.png)

What log can I check to better verify this issue ?

**Comment by zhaoyongjie** [comment] 2022-02-16 13:45
@mchogithub It's weird. Do you use `docker-compose -f docker-compose-non-dev.yml up` on the 1.4.1 tag?

**Comment by mchogithub** [comment] 2022-02-16 17:15
unfortunately yes, I also tried with kubernetes via microk8s (0.5.8):
helm repo add superset https://apache.github.io/superset
helm upgrade --install superset/superset

**Comment by timnick-snow** [comment] 2022-02-18 01:21
I got the  similar error.

1. go sql editor. select database and edit a sql then run
2. save to saved queries.
3. go [sql lab] -> [saved queries], edit the saved queries, will open sql edit
4. click run

MySQL  error
Unable to connect to database "null".


![image](https://user-images.githubusercontent.com/33312542/154598012-e14a5704-d1ed-49ac-adf3-ba874ffa225b.png)

**Comment by rusackas** [comment] 2023-01-14 05:41
Are folks still experiencing this issue in Superset 2.0?

**Comment by rusackas** [comment] 2023-01-26 16:05
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!

**Closed by rusackas** 2023-01-26 16:05 UTC
Labels: sqllab, sqllab:saved_queries, #bug
