### ISSUE TITLE
[Superset SPA] Set up lazy loading of the various "apps"

### ISSUE THREAD

**Issue by nytai** [apache/superset#12896] opened 2021-02-02 18:36 UTC
Part of superset SPA frontend project 

https://github.com/apache/superset/projects/10

**Comment by rusackas** [comment] 2022-12-21 00:00
@nytai I think we can close this out since it's not a bug, per se. I think the project board which it was written for can most likely be closed, too would you agree?

**Comment by rusackas** [comment] 2024-02-14 22:04
This doesn't seem needed anymore. Holler if you disagree :D

**Closed by rusackas** 2024-02-14 22:04 UTC
Labels: enhancement:committed
