### ISSUE TITLE
(native-filters) Filter is hierarchical dropdown does not list all options

### ISSUE THREAD

**Issue by PowerPlop** [apache/superset#16724] opened 2021-09-17 07:00 UTC
### Expected results

When selection the option 'Filter is hierarchical', you can choose which filter is the parent filter.

### Actual results

When opening the dropdown (which shows max 8 entries) and scrolling to the next 8 entries, the dropdown is automatically closed you cannot select a field.

#### Screenshots

![dropdown](https://user-images.githubusercontent.com/2457335/133738868-3ad82961-1acc-4c58-878f-029bc13d3f28.gif)

#### How to reproduce the bug

1. Go to native filters settings
2. Click on hieraichical filter
3. Scroll down to next entries
4. dropdown closes

### Environment

- superset version: v1.3.1

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by michael-s-molina** [comment] 2021-09-17 18:07
@PowerPlop Can you confirm the browser version?

**Comment by junlincc** [comment] 2021-09-17 18:21
@PowerPlop can you also confirm this is reproducible in latest master? it might have been fixed 
also, do you see this behavior in other select dropdown in native filter?

**Comment by PowerPlop** [comment] 2021-09-20 06:45
@michael-s-molina  Chrome Version 93.0.4577.82 ; same in firefox

@junlincc I can replicate it in a preset workspace (which uses latest master I assume?)

**Comment by michael-s-molina** [comment] 2021-09-20 13:19
@PowerPlop Thanks for sharing the browser information. We tested here with Chrome, Firefox, and Safari and we're still not able to reproduce the problem. I noticed though that the design of the screen is different, particularly the button colors and the scroll bar of the modal which leads me to think you overrode some CSS props. This can or cannot be related to the problem. Can you share your CSS overrides?

**Comment by junlincc** [comment] 2021-09-20 16:24
so far we've spent 2 hours reproducing this issue but no luck yet, we will give another try today, if still can't, let's table it for now. 
cc @jinghua-qa

**Comment by PowerPlop** [comment] 2021-09-20 17:09
@junlincc  do you have a public test instance of superset where I can try to replicate? That way we can rule out any local settings that might cause this?

**Comment by michael-s-molina** [comment] 2021-09-21 12:56
@PowerPlop We were able to reproduce the problem when we have a filter box inside the dashboard. The fix in #16702 will be included in 1.3.1rc2 that is going to be put up for voting shortly. Thank you so much for reporting the issue.

**Comment by PowerPlop** [comment] 2021-09-21 13:16
@michael-s-molina  Thanks for the effort on your side!!

Currently we still use the combination of native-filters and filter boxes as we feel that the native-filter is less suitable when you want to target 1 graph on the dashboard. While the highlighting of the chart tries to solve this, we prefer an additional filter box.

**Comment by junlincc** [comment] 2021-09-22 04:38
> we feel that the native-filter is less suitable when you want to target 1 graph on the dashboard.

Hi @PowerPlop, Filterbox will co-exist with native filter until the end of the year, we wanna make sure native filter reaches full feature parity and is an overall better solution for dashboard filtering before removing the filterbox. Can you elaborate on why native-filter is not ideal for targeting 1 chart on the dashboard. And what's the reason behind adding only 1 chart to the dashboard? 

@michael-s-molina since this s an edge case and we are deprecating filterbox soon. i suggest not to invest more time making Filterbox and Nativefilter compatible. 🙏

**Comment by PowerPlop** [comment] 2021-09-22 07:07
@junlincc 
Lets say you have a dashboard with 5 charts (and more tabs with more charts).
3 charts are generic total counts and should not be filtered on anything. Below you have more detailed charts that can be filtered on time or one instance (e.g. a specific client).
When all filters are located in the native-filter side bar, it is not clear which filters will apply to which charts.
By using a filter box and placing them next to the impacted charts (+ a descriptive title), the user understands that the top 3 charts will not be filtered, and the filter has to be used for the more specific charts.

**Comment by michael-s-molina** [comment] 2021-09-30 18:14
Closed by #16702

**Closed by michael-s-molina** 2021-09-30 18:14 UTC
Labels: need:validation, P2, viz:dashboard:native-filter, bug:regression, #bug
