### ISSUE TITLE
[🎉New Feature for Testing]Dashboard native filter and cascading filter are HERE!

### ISSUE THREAD

**Issue by junlincc** [apache/superset#12148] opened 2020-12-19 16:21 UTC
Highly requested from the community for a couple of years, Superset's new Dashboard Native Filter and Cascading Filter are finally available, ready for testing in master!! We welcome your feedback and comments! 

It has been a six months long collaborative project leading by @suddjian, with the dedicated effort from multiple developers. 
Credit goes to the below awesome contributors ♥️ 
@suddjian @villebro @pkdotson @rusackas @mihir174(design)
@agatapst @adam-stasiak 
@amitmiran137 @simchaNielsen

special thanks to @graceguo-supercat @ktmud @zuzana-vej for user research and code review! 

This feature is currently behind a feature flag, to turn on
1. go to `docker/pythonpath_dev/superset_config.py`
2. add below
```
 FEATURE_FLAGS = {
    "DASHBOARD_NATIVE_FILTERS": True,
}

```

Features include
Changes included in [feat(dashboard): Dashboard-Native Filters #11814](https://github.com/apache/incubator-superset/pull/11814) and [feat: Native filters fast-follow #12138](https://github.com/apache/incubator-superset/pull/12138):

- Dashboard-native filters can be created, edited, and deleted from the Dashboard in View Dashboard mode
- Filters can be scoped to specific dashboard panels
- Filter indicator compatibility
- Cascading filters(setting parent filter)
- Instant apply value
- Default values
- Collapsible left panel 
- Reset all
- and much better UX!
- ....... 
WIP
- Time range filter

Create new filter
<img width="921" alt="create new filter" src="https://user-images.githubusercontent.com/67837651/102693826-33078300-41d2-11eb-9d3c-6779c20a2956.png">
Filter scoping
<img width="558" alt="scoping" src="https://user-images.githubusercontent.com/67837651/102693832-3d298180-41d2-11eb-8e7d-4a1a0dd709d1.png">
Cascading filter hierarchy setting
<img width="416" alt="Screen Shot 2020-12-19 at 8 10 40 AM" src="https://user-images.githubusercontent.com/67837651/102693837-49154380-41d2-11eb-96c8-97851d30f90f.png">
<img width="567" alt="Screen Shot 2020-12-19 at 8 13 40 AM" src="https://user-images.githubusercontent.com/67837651/102693839-4fa3bb00-41d2-11eb-91cb-faebf822b508.png">
Open and Collapse side bar
![open:co](https://user-images.githubusercontent.com/67837651/102693938-d8baf200-41d2-11eb-858d-8feb4a53e375.gif)

**Comment by junlincc** [comment] 2020-12-21 08:38
[dashboard]native filter sidebar styling and width should be consistent with the Data panel in Explore
Data Panel in Explore
<img width="281" alt="Screen Shot 2020-12-21 at 12 30 50 AM" src="https://user-images.githubusercontent.com/67837651/102756433-c355dd00-4324-11eb-9ced-29ac6a864041.png">
Native Filter in Dashboard
<img width="81" alt="Screen Shot 2020-12-21 at 12 32 10 AM" src="https://user-images.githubusercontent.com/67837651/102756463-cfda3580-4324-11eb-8002-f25d17018c7c.png">

**Comment by junlincc** [comment] 2020-12-21 08:41
[dashboard]native filter RESET ALL button does not work properly 

https://user-images.githubusercontent.com/67837651/102756804-45460600-4325-11eb-8251-d326b0173f80.mov

**Comment by junlincc** [comment] 2020-12-21 08:48
[dashboard]new native filter loading state should show Superset infinite loading icon instead of "No Results"

https://user-images.githubusercontent.com/67837651/102757345-095f7080-4326-11eb-9ca3-deea6df33143.mov

**Comment by zhaoyongjie** [comment] 2020-12-21 15:40
[dashboard] This looks like the Native Filter and Chart filter indicator do not match.

![image](https://user-images.githubusercontent.com/2016594/102793885-7be35580-43e5-11eb-81d4-54cff49fdd57.png)

**Comment by zhaoyongjie** [comment] 2020-12-21 15:49
[dashboard] timestamp-like column is not handled correctly

### filter setting
![image](https://user-images.githubusercontent.com/2016594/102794670-a97cce80-43e6-11eb-8739-cc7d454973fb.png)

### error
![image](https://user-images.githubusercontent.com/2016594/102794622-9c5fdf80-43e6-11eb-8263-2496575be0f4.png)

**Comment by zhaoyongjie** [comment] 2020-12-21 16:13
[dashboard] Apply to specific panels not work.

https://user-images.githubusercontent.com/2016594/102797331-82c09700-43ea-11eb-935b-c31c14825387.mov

**Comment by amitmiran137** [comment] 2020-12-21 17:57
@zhaoyongjie thank you for sharing 
we will take of it 
cc: @junlincc @villebro @simchaNielsen

**Comment by adam-stasiak** [comment] 2020-12-21 22:20
[DASHBOARD]
SCENARIO:
To tabbed dashboard add filter with country name default value: United States
Save
Apply filter With name CHINA
Click on Reset -> Now filter box shows the default value
Click on APPLY -> Default Filter value is not applied

Expected: After click on APPLY it should be current field value applied.
https://user-images.githubusercontent.com/25153919/102827412-cfa06f80-43e2-11eb-9bff-3591138f97ae.mov

**Comment by adam-stasiak** [comment] 2020-12-21 22:34
[dashboard]
Scenario:
Create Filter with reference to dataset
Delete this dataset
Go back to Filter Configuration and Scoping:

Observed: You can find that *FIELD has looped loading animation with name of not available field. After I choose different datasource I still see this old type of field as an option in field box.

Expected: We should indicate somehow that Filter is malformed(@junlincc) and do not propose not available options to set.

https://user-images.githubusercontent.com/25153919/102828444-07a8b200-43e5-11eb-9f82-0e4351590e7b.mov

**Comment by adam-stasiak** [comment] 2020-12-21 23:02
[dashboard]
Steps to reproduce:
Add very long name of filter

Observed: You can see that UI glitches. We should handle this better -> I suggest adding in the left side section "..." at the end of too long names or splitting into lines.

https://user-images.githubusercontent.com/25153919/102829427-64a56780-43e7-11eb-9817-cc3034564a83.mov

**Comment by adam-stasiak** [comment] 2020-12-21 23:08
[dashboard]
Weird behavior for me.

When I add two new filters and:
* first is correctly filled
* second is partially filled
And I click on Save on first filter -> I do not get information that this SAVE will not keep my filter when I quit this modal.

We should indicate that progress will be lost and:
- force user to finish or remove remaining filters before exit
- discard not valid filter entries 
- keep them as draft not applicable for usage

@junlincc I think we should consider options for this.

**Comment by adam-stasiak** [comment] 2020-12-21 23:15
> [dashboard] This looks like the Native Filter and Chart filter indicator do not match.
> 
> ![image](https://user-images.githubusercontent.com/2016594/102793885-7be35580-43e5-11eb-81d4-54cff49fdd57.png)

I agree- > When we set Native Filter set then we can clearly see number indicator so we should place there native filters as well and update the counter

**Comment by adam-stasiak** [comment] 2020-12-21 23:40
[dashboard]

Default value for filter is not exported with dashboard.
Scenario:
Create Filter with default value.
Export dashboard
Import json file of dashboard

You can see that Default Value for filter was not exported - > Information about Parent relation was exported so I think it should be as well.

**Comment by simchaNielsen** [comment] 2020-12-22 10:10
> [dashboard] Apply to specific panels not work.
> 
>  Screen.Recording.2020-12-22.at.12.10.32.AM.mov

We will process fix for it in few steps.
1. UI Config Modal fix:
https://gitlab.com/nielsen-media/maf/webinfra-admin-frontend/-/merge_requests/275
cc: @amitmiran137 @villebro

**Comment by adam-stasiak** [comment] 2020-12-22 16:53
[dashboard]
When only 1 option is available in filter then it is displayed 1 option()
![image](https://user-images.githubusercontent.com/25153919/102913116-9a495f80-447e-11eb-88d1-18fce90c322e.png)

**Comment by thoo** [comment] 2021-01-07 16:57
We have an option to sort values in filterbox. #6523    
It would be nice to have it in the native filter too. 
![image](https://user-images.githubusercontent.com/487433/49884421-aeffb100-fde9-11e8-9c29-fb9eba3ce1af.png)

**Comment by adam-stasiak** [comment] 2021-01-12 17:50
> #6523

@thoo Could you describe this wider in seperated ticket? :)

**Comment by rmgpinto** [comment] 2021-02-18 09:46
Two suggestions for native filters:

1- Possibility to change the order of the filters
2- Possibility to change the sorting of the values on the filters (I have a values filter and they appear in a random order)

**Comment by junlincc** [comment] 2021-02-20 03:34
1. Reorder the filter list from the bar? - yes, ideally by drag and drop.
2. Can you describe your use case in details? @rmgpinto

**Comment by rmgpinto** [comment] 2021-02-20 10:43
I saw now that 2. is the same as what @thoo requested.

**Comment by cccs-jc** [comment] 2021-03-03 14:16
We use Superset in the context of Security information and event management (SIEM). Our data often include IP values which users want to filter by adhoc IP ranges (using CIDR notation).

For example when the user inputs a filter value of 192.168.0.0/24 this filter is converted into a range query on the server side. We leverage jinja templating to convert the IP range into an SQL statement like

((IP_COLUMN >= lowIP) AND (IP_COLUMN <= highIP))

This works quite well however there is no validation of the text provided by the user. Ideally we would like to validate the input in the client a bit like is done in the explorer UI.

We would like to be able to provide custom validators to the native filters.

**Comment by junlincc** [comment] 2021-03-12 05:06
@thoo @eugeniamz @rmgpinto

Now dashboard native filter and sort value!! 🎉 thanks to @villebro and @simcha90 🙏

<img width="1031" alt="Screen Shot 2021-03-11 at 9 05 46 PM" src="https://user-images.githubusercontent.com/67837651/110894918-9ecb2a80-82ad-11eb-9d33-d2415ad2b1e9.png">

**Comment by junlincc** [comment] 2021-03-12 05:09
Now Dashboard native filter can add multiple time columns!!!🎉 
thanks to  filter team(R2) @villebro @simcha90 @zhaoyongjie  🙏
<img width="1885" alt="Screen Shot 2021-03-11 at 9 08 03 PM" src="https://user-images.githubusercontent.com/67837651/110895105-f6699600-82ad-11eb-93ab-54a2c2bad7cc.png">

**Comment by amitmiran137** [comment] 2021-04-09 10:54
closing this due to the phase 2 followup announcement #13591

**Closed by amitmiran137** 2021-04-09 10:54 UTC
Labels: good first issue, release:feature, viz:dashboard:native-filter

**Comment by mlmaverick** [comment] 2022-07-18 10:54
@junlincc Hi, thank you for your efforts in creating this wonderful tool. I was wondering if there is a way to increase the filter limit which is not set to 1000 by default. 

Thanks!

![image](https://user-images.githubusercontent.com/105640903/179496905-c99b0fad-cf91-41a1-adc2-2cf52c13efd9.png)

**Comment by progettoautomazione** [comment] 2022-08-23 15:37
> @junlincc Hi, thank you for your efforts in creating this wonderful tool. I was wondering if there is a way to increase the filter limit which is not set to 1000 by default.
> 
> Thanks!
> 
> ![image](https://user-images.githubusercontent.com/105640903/179496905-c99b0fad-cf91-41a1-adc2-2cf52c13efd9.png)

many many UP!
