### ISSUE TITLE
time_grain always return None in jinja

### ISSUE THREAD

**Issue by jordiisidro** [apache/superset#22774] opened 2023-01-18 12:19 UTC
#### How to reproduce the bug
The variable time_grain used in SQL templating is always None
Other variables like from_dttm work fine.

Sample query:

select date_trunc(
	{%- if time_grain == 'P1D' -%}
	'day'
	{%- elif time_grain == 'P1W' -%}
	'week'
	{%- elif time_grain == 'P1M' -%}
	'month'
	{%- elif time_grain == 'P3M' -%}
	'quarter'
	{%- elif time_grain == 'P1Y' -%}
	'year'
	{%- elif time_grain == 'P1Y' -%}
	'year'
	{% else %}
	'month'
	{%- endif -%}
, data) as data
	, tecnologia, proveidor, count(distinct id_ticket) as incidencies
from inc_pet i 
where  {% if from_dttm is not none %}
i.data >= '{{ from_dttm }}' AND
{% endif %}
{% if to_dttm is not none %}
i.data < '{{ to_dttm }}' AND
{% endif %}
1=1
group by  date_trunc(
	{%- if time_grain == 'P1D' -%}
	'day'
	{%- elif time_grain == 'P1W' -%}
	'week'
	{%- elif time_grain == 'P1M' -%}
	'month'
	{%- elif time_grain == 'P3M' -%}
	'quarter'
	{%- elif time_grain == 'P1Y' -%}
	'year'
	{%- elif time_grain == 'P1Y' -%}
	'year'
	{% else %}
	'month'
	{%- endif -%}
, data)
	, tecnologia, proveidor
	

### Expected results
I expect that when Granularity chances the time_grain value changes

### Actual results

time_grain always return None

### Environment

- superset version: 2.0.1

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by jordiisidro** [comment] 2023-01-19 06:51
I think is related with GENERIC_CHART_AXES flag.
With charts with GENERIC_CHART_AXES=False it works well, but when I deploy with GENERIC_CHART_AXES=True only works with the chart type Table, with line or bar char doesn't work. In both cases I select for the x axe a date column.

Table chart assigns the time_grain correctly
![imatge](https://user-images.githubusercontent.com/19467312/213374691-42ec82ab-98d0-4c4f-8675-59f8c038c590.png)

Line chart, doesn't assign the time_grain
![imatge](https://user-images.githubusercontent.com/19467312/213374816-2d451d30-a2f3-4d50-9ed0-ebd84c29ad9c.png)

**Comment by jordiisidro** [comment] 2023-03-16 07:38
Solved in last version

**Comment by jordiisidro** [comment] 2023-03-24 08:47
closed incorrectly.
With the latest version the same problem still happens

**Comment by villebro** [comment] 2023-03-25 07:39
@jordiisidro thanks for raising, I'll take a look next week (feel free to nag me if I don't open a PR before next weekend)

**Comment by MaksymilianME** [comment] 2023-04-17 14:33
@villebro did you open a PR for this issue? I have the same problem with latest version for time_grains in Jinja. Thanks

**Comment by itziarmj** [comment] 2023-04-18 11:27
The same happens to me in version 2.1.0 with from_dttm in the edit chart. It does not happen in the charts contained in the dashboard.

**Comment by MaksymilianME** [comment] 2023-04-18 12:29
In my opinion from_dttm works fine both for chart edition and on dasboards. But time grain parameter does not work on any chart. Only on simple Table it looks fine.

**Comment by itziarmj** [comment] 2023-04-18 14:33
I think is somehow related, I have managed to get time_grain None together with from_dttm None and to_dttm None.

**Comment by mtrentz** [comment] 2023-05-16 08:55
I am currently having the same problem. For me it seems to be related to the type of charts. For example, for Pivot Tables the `{{ time_grain }}` will always return None. But for Pivot Table (legacy) it will work.

**Comment by villebro** [comment] 2023-05-16 10:35
@itziarmj @mtrentz I think I was able to reproduce this issue - out of curiosity, have you enabled the `GENERIC_CHART_AXES` feature flag?

**Comment by itziarmj** [comment] 2023-05-16 10:37
Yes, this happens when GENERIC_CHART_AXES is enabled.

**Comment by mtrentz** [comment] 2023-05-16 11:02
@villebro no, i have the following feature flags enabled.

```
FEATURE_FLAGS = {
        "ALERT_REPORTS": True,
        "ENABLE_TEMPLATE_PROCESSING": True,
        "DASHBOARD_RBAC": True,
        "DRILL_BY": True,
        "DRILL_TO_DETAIL": True,
    }
```

**Comment by villebro** [comment] 2023-05-16 12:16
Ok thank's for confirming @mtrentz @itziarmj - I think I know what's going on, I can probably get this fixed this week to get it into 2.1.1

**Comment by MaksymilianME** [comment] 2023-06-02 11:03
Hi @villebro did you manage to fix this issue? This holds me back from moving from 2.0 to 2.1. Cant wait to start using 2.1.
Thanks!

**Comment by mapledan** [comment] 2023-07-03 08:27
> 
This PR(#23652 ) change the default value of GENERIC_CHART_AXES to true.

**Comment by unnyns-307** [comment] 2023-07-11 09:40
Hello, also facing the same problem.
We cannot disable GENERIC_AXIS_CHART on Superset cause there are many charts created based one the chart types enabled from this feature flag.
Do we have other alternatives for this case or specific fixing on the code could resolve this too?

**Comment by howardcho** [comment] 2023-09-11 17:52
@villebro did the fix for `from_dttm` make it into version 2.1? I'm using 2.0, and am seeing this issue as well.

I have the following feature flags:
```
FEATURE_FLAGS = {
        "ALERT_REPORTS": True,
        "ENABLE_TEMPLATE_PROCESSING": True,
        "GENERIC_CHART_AXES": True
}
```

**Comment by duvenagep** [comment] 2023-09-11 22:03
@villebro Any status on this issue. Currently using Superset 3.0.0rc2 and now GENERIC_CHART_AXES=true is the default this issues still seems to persist. Can confirm it works normally on tables but not on line graphs

**Comment by rumbin** [comment] 2023-10-26 07:02
The issue still exists in 3.0.1, as it seems. @villebro, you seemed confident to know what needs to be fixed. Any update on this?

**Comment by mapledan** [comment] 2023-10-26 07:21
I create the PR #25429 that fix for the from_dttm return None, but I'm not sure about the time_grain issue.

**Comment by WojtekWaga** [comment] 2023-10-30 07:52
Hey, it looks like it does not help for time_grain

**Comment by rzzldzzl** [comment] 2023-11-03 19:18
Running the latest dev version of superset -
Regardless of "GENERIC_CHART_AXES" being set to True||False, `time_grain` returns `None` on the line & bar charts.  `time_grain` does return correctly on the table chart, however.

**Comment by Vitor-Avila** [comment] 2023-11-16 15:26
I believe this got fixed with https://github.com/apache/superset/pull/25842 cc @rusackas

**Comment by stepcheunghk** [comment] 2023-11-22 05:56
> I believe this got fixed with #25842 cc @rusackas

Thanks for the update @Vitor-Avila, however it seems it only works for v3.0?

**Comment by Vitor-Avila** [comment] 2024-01-12 13:30
@stepcheunghk unsure about the version the PR got associated with. @rusackas would you be able to assist determining that? I believe we're also good to close this bug.

**Comment by mtrentz** [comment] 2024-01-15 12:38
@Vitor-Avila Hey, coincidentally I've just tested this out. Using docker the 3.0.2 version fixed this issue for me while the 3.0.0 hadn't done so beforehand.

**Comment by rusackas** [comment] 2024-01-19 22:33
Thanks for the update @mtrentz - sounds like we ca close this one then :)

**Closed by rusackas** 2024-01-19 22:33 UTC
Labels: #bug

**Comment by Keveen-ghori** [comment] 2025-04-01 05:19
SELECT '{{ time_grain }}' AS time_grain;

Always None value for any selected time grain option from filter in dashboard. Issue raising for version 4.1.2. Any solution?

**Comment by Keveen-ghori** [comment] 2025-04-01 12:39
@Vitor-Avila it is happening for the table chart. For other chart it is working.

**Comment by Vitor-Avila** [comment] 2025-04-01 12:48
thanks for the confirmation! I believe this issue is fixed with this PR then: https://github.com/apache/superset/pull/32871

**Comment by Vitor-Avila** [comment] 2025-04-01 12:48
not sure which Superset version would get it tho
