### ISSUE TITLE
'Explore' button on SQL Lab view disabled when connected to Apache Pinot as a database

### ISSUE THREAD

**Issue by ayush1705** [apache/superset#13623] opened 2021-03-15 14:24 UTC
I connected superset to pinot successfully and was able to build SQL lab queries only to find out that Superset does not support Exploring of SQL Lab virtual data as a chart if the connected database is Apache Pinot. (The “Explore” button is disabled)

I am using Superset version 1.0.1

#### Screenshot
![image](https://user-images.githubusercontent.com/17423001/111168535-86dafb80-8578-11eb-87ea-3e5058e4d4cb.png)

**Comment by pjpringle** [comment] 2021-09-10 15:11
Looks like it's related to the fact that pinot does not support nested queries.  For other databases superset creates a virtual table dataset which is used as the FROM table in the explore query.

**Comment by rusackas** [comment] 2023-01-04 20:51
@yousoph I _think_ we can probably close this issue since (a) it appears this button is disabled on purpose, so it's not quite a bug, and (b) The issue is a bit vintage in terms of superset version.

That said, if the button is disabled intentionally, do you think it's reasonable to have a tooltip explaning why?

Also, I'm trying to get my hands on a Pinot test DB to see if this works in the newer workflow where we DO NOT create a virtual dataset by default. If anyone can help test this, it'd be appreciated

**Comment by etadelta222** [comment] 2023-11-17 19:41
Hi @rusackas , were you able to test this by any chance? With Pinot having V2 engine in beta (which supports joins), can this button be enabled?

**Comment by pjpringle** [comment] 2023-11-18 02:24
It would be quite a game changer.

**Comment by sfirke** [comment] 2023-12-19 04:00
Sounds like @ege-st is experiencing this still, alas. @rusackas were you ever able to test this out?  Is there a committer or community member who could tackle this - maybe we could reach out to the Pinot project since it is also under the Apache Software Foudnation?

**Comment by rusackas** [comment] 2024-02-01 20:18
Nope... I'm afraid I wasn't able to test, and don't have a Pinot DB currently. Not sure if @sadpandajoe has one handy. @john-bodley do we have any Pinot-sipping friends to reach out to?

**Comment by soumitra-st** [comment] 2024-05-06 04:37
I work in StarTree and volunteer to help resolve the issue. Found why the `CREATE CHART` is disabled for Pinot:

1. Button is disabled [HERE](https://github.com/apache/superset/blob/master/superset-frontend/src/SqlLab/components/ExploreResultsButton/index.tsx#L40) if allows_subquery is not defined or false
2. For [PinotEngineSpec](https://github.com/apache/superset/blob/master/superset/db_engine_specs/pinot.py#L28) , allows_subqueries is false
3. [Features](https://github.com/apache/superset/blob/master/superset/db_engine_specs/README.md#features) table summarizes the capabilities of all db engines

We have several Superset dashboards using Pinot in our dev and QA environments. Why does `CREATE CHART` depend on subquery support? Pinot supports subquery, join, etc., using the multi-stage query engine. We can enable this mode for all features depending on the subquery support. We can enable the multi-stage engine based on an engine configuration, and then the features requiring subqueries will only work in this mode, but the current mode will also be there.

**Comment by rusackas** [comment] 2024-05-06 21:53
Thanks for looking into it! I think @betodealmeida might be best qualified to answer that.

**Comment by soumitra-st** [comment] 2024-05-06 21:57
Testing out changes in my local setup, I will create a PR soon.

**Comment by betodealmeida** [comment] 2024-05-06 23:16
> Why does CREATE CHART depend on subquery support?

Because the chart builder wraps the SQL in a subquery — the SQL from SQL Lab becomes the inner query, and the controls in the chart builder define the outer query.

> Pinot supports subquery, join, etc., using the multi-stage query engine. We can enable this mode for all features depending on the subquery support. We can enable the multi-stage engine based on an engine configuration, and then the features requiring subqueries will only work in this mode, but the current mode will also be there.

If that's the case we should change `allows_subqueries` to `True` in the Pinot DB engine spec, and have good error messaging when the user tries to build a chart in a Pinot deployment that's not configured with the multi-stage engine (a message that says something like "In order to explore data in Pinot you need an engine with support for subqueries", eg.

**Comment by soumitra-st** [comment] 2024-05-06 23:34
Thanks @betodealmeida for suggestion, let me create the PR and we can iterate on that to improve the user experience.

**Comment by soumitra-st** [comment] 2024-05-07 01:34
Created PR https://github.com/apache/superset/pull/28364

**Closed** 2024-07-05 13:32 UTC
Labels: data:connect:pinot, #bug

**Comment by sfirke** [comment] 2024-07-05 13:37
I merged #28364 to address this.  But now I see the suggestion from Beto above that says:
> Have good error messaging when the user tries to build a chart in a Pinot deployment that's not configured with the multi-stage engine (a message that says something like "In order to explore data in Pinot you need an engine with support for subqueries"
It would be great to get that implemented now that this condition can be encountered.  @soumitra-st you mention "we can iterate on that to improve the user experience," could you take a shot at this PR?

Also it would be great if folks who have commented above asking for this feature can test out the Superset master branch where this is now merged.
