### ISSUE TITLE
Use static (uploaded) image as dashboard thumbnail

### ISSUE THREAD

**Issue by EBoisseauSierra** [apache/superset#18872] opened 2022-02-23 11:50 UTC
## **Is your feature request related to a problem? Please describe.**

Users like having dashboard thumbnails. These thumbnails are generated as a screenshot of the *first tab* of a given dashboard.

However, this makes that the thumbnail is not always truly representative of the content of *the whole dashboard* (when, e.g., the tabs feature very different data). 
That makes it somewhat confusing for some users (e.g. Alice want to go to “the dashboard with the world map”… yet there is no map on any of the thumbnails, because it's in tab 2.)

Another confusing scenario is when multiple dashboards have the same structure — so visually similar thumbnails — e.g. when reporting the same metrics on different company/market/region: in that situation, all thumbnails look alike and thus aren't very informative.

## **Describe the solution you'd like**

I would like to be able to choose whether **I want a dashboard thumbnail to be**:

* a screenshot of the (first tab of the) dashboard,
* **a manually uploaded static picture** (e.g. logo of the company/market/region, or icon representing what the dashboard is about).

This could happen in the “`⋮`/Edit” Dashboard properties menu of a dashboard, where one could chose between either options, and, if the “static picture” option is chosen, then a button would allow the user to open a upload menu to upload the picture to use.

## **Describe alternatives you've considered**

Make the first tab of the dashboard to be the picture I want to have as an icon (+ tweak thumbnail caching so I *could* remove it once the screenshot has been captured)… but this doesn't sound like something reasonable.

**Comment by rusackas** [comment] 2024-01-29 16:19
@EBoisseauSierra @dinesh-zemoso are either of you willing to pick up the PR from last year to close the loop on this? If not, I think we should close both the issue and the PR.

**Comment by rusackas** [comment] 2024-05-31 15:49
Closing the issue, since it's not a bug. We can leave the PR open for now in hopes of getting it merged 🤞 Let us know if either of you need help moving it forward. We certainly appreciate the contribution!

**Closed by rusackas** 2024-05-31 15:49 UTC
Labels: nice-to-have
