### ISSUE TITLE
Annotations intermittently fail to display for many chart types

### ISSUE THREAD

**Issue by seo01** [apache/superset#20441] opened 2022-06-20 19:09 UTC
When adding Event or Interval annotations creates a chart that intermittently fails to render for many chart types.

#### How to reproduce the bug

Chart types I've confirmed this does happen with: Time-series Line Chart, Time-series Area Chart, Time-series Bar Chart v2, Mixed Time Series
Chart types I've confirmed this does not happen with: Line Chart, Bar Chart

Annotations types I've confirmed this does happen with: Event (with Superset Annotation Source), Interval (with Superset Annotation Source)
Annotations types I've confirmed this does not happen with: Formula

1. Go to 'Create New Chart'
2. Click on 'Time-series Line Chart'
3. Choose a dataset
4. Drag in a metric (e.g. the default count)
5. Click Annotations and Layers
6. Click Add annotation Layer
7. Select 'Interval' for the annotation type
8. Type anything for the name, e.g. "foobar"
9. Select 'superset annotation' from the annotation source
10. Select an annotation layer
11. Click 'OK'
12. Click 'Create Chart' <-- Sometimes this will trigger the issue
13. Type a name for the chart in the top left box (e.g. "foo bar")
14. Click "Save" and confirm the Save <-- This generally triggers the issue

### Expected results

I expect a chart to be displayed with areas blocked out.

### Actual results

An "Unexpected error" box is displayed.

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/736239/174659699-104e0a5b-d576-42ee-beaf-05d91d639d3d.png">

Looking at the console it appears the data to load the graph is not fully loaded into the front end.

<img width="786" alt="image" src="https://user-images.githubusercontent.com/736239/174660053-f73bc267-bbd3-41fb-8416-0e2f40cb2db2.png">

The bug is intermittent occurring ~90% of the time.

### Environment

(please complete the following information):

- browser type and version: Chrome 102.0.5005.115
- superset version: 0.0.0dev (helm default)
- python version: 3.8.12
- node.js version: Node not installed
- any feature flags active: DASHBOARD_RBAC

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by chaoticefx** [comment] 2022-07-06 04:14
I just experienced this too when attempting to come up with a POC for my company, sharing more of my observations for what its worth.

It starts to happen once I've saved a chart with annotations. In this case I'm using Time-series Bar Chart v2 as mentioned above.

![Directus-2022-07-06-12-03-53](https://user-images.githubusercontent.com/79575739/177466338-21e40532-3ab7-4ea3-85c6-570d940a1db8.jpg)

If I open the Annotation modal and hit Apply or OK the query goes through and the chart reloads with no issues

![Directus-2022-07-06-12-04-03](https://user-images.githubusercontent.com/79575739/177466411-f71d6baf-9dbf-46e3-a01f-12523d6a15d5.jpg)

![Directus-2022-07-06-12-04-13](https://user-images.githubusercontent.com/79575739/177466430-c23e2d3b-ce0a-4854-b852-6093a2fd75f6.jpg)

However once I hit "Save" for the chart in the top right the query stops working once more.

![Directus-2022-07-06-12-04-21](https://user-images.githubusercontent.com/79575739/177466475-5f456626-c99a-4b9c-aefd-70d34bac4c33.jpg)

This also affects the same chart inside a dashboard:

![Directus-2022-07-06-12-04-25](https://user-images.githubusercontent.com/79575739/177466497-f99b7516-606a-402c-9166-df75221c54c6.jpg)

**Environment**

browser type and version: Version 103.0.5060.53
superset version: 0.0.0dev (docker image from https://hub.docker.com/r/apache/superset)
python version: 3.8.13
node.js version: Node not installed
any feature flags active: DASHBOARD_CROSS_FILTERS

**Comment by BeckersJ** [comment] 2022-07-18 12:54
We are updating to 2.0.0, this issue is blocking our rollout 😢.

![image](https://user-images.githubusercontent.com/96041225/179515561-0e887560-1051-4b9c-a761-06aede7b2e3c.png)

**Comment by inakianduaga** [comment] 2022-08-02 08:54
happening to us as well

**Comment by mayurnewase** [comment] 2022-10-12 18:13
couldn't reproduce in latest master (last commit sha: 8f74e46d45ca94f5656f7b881f1096c16657c829)

used time series line chart, superset annotation for interval.

![Screenshot from 2022-10-12 23-42-42](https://user-images.githubusercontent.com/12967587/195417339-c7dfd668-9cdf-4ad7-a23c-b4cfe89c7854.png)

possible to test this on lates master?

**Comment by chaoticefx** [comment] 2022-10-13 01:20
Looks fixed on my end! I'm not seeing this any more on the latest docker tag

**Comment by sfirke** [comment] 2022-11-03 19:38
duplicate of #20845 ?

**Comment by Shazad-khan** [comment] 2023-03-16 15:02
![image](https://user-images.githubusercontent.com/100838455/225658567-cfb3befe-7343-4df7-b99a-6f568c13f0bb.png)

It has been fixed please check and close this issue

**Closed** 2024-02-12 20:45 UTC
Labels: #bug, preset:cares
