### ISSUE TITLE
Filter Bar Orientation Resets to Vertical After Reopening Dashboard

### ISSUE THREAD

**Issue by aprendizlaura** [apache/superset#30046] opened 2024-08-29 09:18 UTC
Hello everyone, I have a question. In several dashboards, I have configured the filter bar to appear horizontally (on top) instead of vertically. However, when I close the dashboard and reopen it, this configuration doesn't stay, and it goes back to appearing vertically. Any ideas on how to fix this?

**Comment by sfirke** [comment] 2024-08-29 18:10
Huh, I have never experienced this.  Does this happen to all of your dashboards with horizontal filter bars?  Any more detail you can provide to reproduce the problem?  What version of Superset are you using?

**Comment by aprendizlaura** [comment] 2024-09-02 10:53
@sfirke Hello!! Honestly, I don't quite understand the logic behind the issue because, without making any updates, I've been running some tests, and it hasn't changed on its own again; it's staying as it is. If it happens again, I'll let you know why.

**Comment by sfirke** [comment] 2024-09-02 12:34
Thanks for following up! I'm glad to hear the problem seems to have resolved itself. Given that we can't reproduce it, I'll close this issue, but feel free to comment again if you learn anything else or if it recurs.

**Closed** 2024-09-02 12:34 UTC
Labels: validation:required

**Comment by aprendizlaura** [comment] 2024-09-05 14:11
Hi @sfirke!!

I just discovered the issue with the orientation. I took some screenshots, although a video might be more ideal in this case, but I hope I can explain it clearly. I noticed the error when I created a new dashboard. As you can see in the images, there's an empty dashboard, I add a couple of sample visualizations and set the filter orientation, as well as adding a sample filter. When I reload the dashboard page for the first time after setting this, instead of it appearing as I left it, the dashboard appears as if I had clicked "Edit", and when I cancel, for example, that’s when the filters switch to vertical format. I hope I’ve explained it well, and if this helps in any way, then great.

![Captura de pantalla 2024-09-05 154130](https://github.com/user-attachments/assets/014aa803-9a9f-4ae4-8304-c328feda9425)
![Captura de pantalla 2024-09-05 154256](https://github.com/user-attachments/assets/e10d1382-2da2-42a6-9987-8a4ece28fc6e)
![Captura de pantalla 2024-09-05 154320](https://github.com/user-attachments/assets/faaa9bd4-dfa3-4cb8-8a08-17890fab114e)
![image](https://github.com/user-a
![Captura de pantalla 2024-09-05 154347](https://github.com/user-attachments/assets/4dc769c1-780b-4c04-9305-1df9679a6916)
ttachments/assets/524f6e70-2ee8-4a30-b76a-e3abb86bcee6)


another example

![Captura de pantalla 2024-09-05 154951](https://github.com/user-attachments/assets/a1e6e59e-2b81-4bb2-8154-bd25d7630ce2)
![Captura de pantalla 2024-09-05 155001](https://github.com/user-attachments/assets/9bbf928a-6706-4dff-a29a-9a068ec82d0e)
![Captura de pantalla 2024-09-05 155039](https://github.com/user-attachments/assets/a465dbc2-e7fa-4158-a60b-eb098754bcdc)
![Captura de pantalla 2024-09-05 155051](https://github.com/user-attachments/assets/2d1db0dd-1e9e-44c3-a034-3b2f8554c87b)
![Captura de pantalla 2024-09-05 155119](https://github.com/user-attachments/assets/343384fc-f780-4d28-bcd9-b116af81e8ab)
![Captura de pantalla 2024-09-05 155130](https://github.com/user-attachments/assets/726e5c73-eeef-4adb-81f9-5861ff821c54)

**Comment by sfirke** [comment] 2024-09-05 14:22
Thanks for providing additional documentation!  What version of Superset are you running?

The testing environment for the next release of Superset is here: http://35.94.8.142:8080/ (user: admin, password: admin, remember to clear any data that you add)  If that test environment is still up, you could try to replicate the bug there to see if persists in the latest version.

**Comment by aprendizlaura** [comment] 2024-09-05 14:27
I'm using version 4.0.0.
I've tried to replicate it in the test environment, but the functionality to change the orientation of the filters is not active.
I will try updating Superset, and if this issue persists, I will let you know.
Thank you so much, Sam! @sfirke
