### ISSUE TITLE
4.0 - Imported charts shows error on embedding

### ISSUE THREAD

**Issue by ss-ravi** [apache/superset#28446] opened 2024-05-13 04:04 UTC
### Bug description

「Guest user cannot modify chart payload」 Error is displayed for imported charts.
It's related to this issue, but with a specific reproduction flow. (https://github.com/apache/superset/issues/27177)

### How to reproduce the bug

1. Create 2 superset 4.0 instances
2. Create a dashboard with a few charts (tested with "big-number" chart)
3. Export the dashboard and import it into the other superset instance
4. Try to embed the dashboard (using the sdk) into a web app
5. 「Guest user cannot modify chart payload」Error is displayed for each chart

### Screenshots/recordings

![image](https://github.com/apache/superset/assets/91879999/b4863ea6-ad08-40bf-9dbd-e9c1c2ca727f)

### Superset version

4.0.0

### Python version

3.9

### Node version

16

### Browser

Chrome

### Additional context

It seems that the export/import functionality doesn't copy the `query_context` field. (It becomes `null` after import)
I believe the `query_context` became important after this PR: https://github.com/apache/superset/pull/27484/files

### Workaround
I noticed that just by opening the imported chart in the superset side updates the `query_context` and the embed starts working for that chart. We can't use this workaround as we have hundreds of charts for each of our clients.

### Checklist

- [X] I have searched Superset docs and Slack and didn't find a solution to my problem.
- [X] I have searched the GitHub issue tracker and didn't find a similar bug report.
- [X] I have checked Superset's logs for errors and if I found a relevant Python stacktrace, I included it here as text in the "additional context" section.

**Comment by ss-ravi** [comment] 2024-05-14 01:22
I actually tried to call the update api to see if the `query_context` would be automatically created, but it wasn't. I would have to know the exact json to put there, which I don't. Even if it were doable, It still feels that the `query_context` should also be copied with the import functionality.

**Comment by ss-ravi** [comment] 2024-05-14 01:26
I also noticed a different related issue.
When you are embedding standalone charts, if the chart has no `query_context` it will try to update the chart from the iframe, and since the Public role doesn't have permission to update the chart, it ends up redirecting to the login page and you end up having iframes with login pages showing on them.

**Comment by rusackas** [comment] 2024-05-14 14:51
@betodealmeida am I taking crazy pills or does this sound like the issue you fixed in unblocking 4.0?

**Comment by lindenh** [comment] 2024-05-17 13:48
I think the issue blocking 4.0 previously was without imports, embeds would show that error for certain charts. This is a blocker for us though, as we use a multi-environment setup and have to use imports to deploy to higher environments. Adding a new manual step to an already cumbersome pipeline wouldn't bode well.

**Comment by Kev1000000** [comment] 2024-06-04 21:02
We're also experiencing this issue and have not updated to 4.x.x because of this.  Was working fine on 3.x.  There are some nice improvements within 4.x we'd like to take advantage of, but this is currenty blocking us from updating.

**Comment by rusackas** [comment] 2024-06-04 22:58
@michael-s-molina do you have any context on this, perchance?

**Comment by michael-s-molina** [comment] 2024-06-05 11:20
@rusackas I think this was caused by a change made by @betodealmeida https://github.com/apache/superset/pull/27484

**Comment by ablanchard** [comment] 2024-06-14 08:54
From my understanding of the problem:
 - When you export charts, query_context is present in the exported files but the id for the datasource and the slice are not converted to uuid so the query_context is useless when you import it to a different instance.
 - To avoid [a bug when you import, a process has been added](https://github.com/apache/superset/pull/23582) to remove the query_context entirely, [still present in master](https://github.com/preset-io/superset/blob/daf37cbe585515afe725d266ee6ac292b2a00c44/superset/commands/importers/v1/assets.py#L118)
 - Then the new security layer fails because the query context is empty
 
So a fix could be around properly export the charts in the first place and stop removing the query_context when importing.

A temporary workaround is to update the charts using the api, based on the exported query_context. Of course if you are exporting and importing on a different instance, you need to change ids references in the query_context

**Comment by xavier-GitHub76** [comment] 2024-06-19 13:53
Hello,
the context seems to be solely about importing dashboards for all of you.
On my side, I tried to embed a dashboard that was created directly (all elements (dashboard, chart, dataset are created from scratch).
I got the same error message. 
![image](https://github.com/apache/superset/assets/82046143/ad802b34-8961-4941-973c-56be4e90fc60)

The dasboard in Superset :
![image](https://github.com/apache/superset/assets/82046143/060c72f6-525e-46d0-8a16-f8f4c37a2ba0)

My tests were carried out on version 3.1.1

Best regards.

**Comment by kidusmakonnen** [comment] 2024-06-24 07:47
We have also faced this issue after upgrading to 4.0.0

![image](https://github.com/apache/superset/assets/8809047/e8f6c317-e697-4f1e-b6a6-a6e43731af9d)

**Comment by StaSotiro** [comment] 2024-07-09 13:56
Any news on this ? I have the same problem in 3.1.1

**Comment by rusackas** [comment] 2024-07-09 19:17
Nope, no news yet. Anyone here is welcome to explore a fix... I'm guessing @betodealmeida is just a bit too busy to get to it right now.

**Comment by betodealmeida** [comment] 2024-07-10 19:48
Sorry, I missed this. Let me take a look, seems like we need to fix the import/export.

**Comment by marianysilva** [comment] 2024-08-06 14:55
Workaround: You can open the Chart using Superset Interface, load the data, and then go to your Embedded dashboard and reload it. It should work.

`FROM apache/superset:4.0.2-py310`

![Screenshot 2024-08-06 at 11 51 32](https://github.com/user-attachments/assets/af22d651-d013-484f-a6e2-3ea5f1614a03)

**Comment by Kev1000000** [comment] 2024-08-19 18:00
Hey @betodealmeida, and updates on this by chance?

**Comment by sandeepr43** [comment] 2024-08-26 13:46
cannot upgrade to 4.0.2 because of this issue. we are still using 3.0.2.

we are using multi-environment set up and saving each charts in each instance isn't practical.

 any turnaround for this issue?

**Comment by lindenh** [comment] 2024-11-10 11:51
Sorry for the delay. PR up here: https://github.com/apache/superset/pull/30887 @betodealmeida / @rusackas

**Closed** 2024-11-22 18:14 UTC
Labels: embedded

**Comment by lindenh** [comment] 2025-03-28 15:15
For people that come across this later due to API calls using a guest token, there was a slight miss that affects dashboard imports. The exports for charts when exported with dashboards will contain a slice_id param, which isn't being corrected until the chart is resaved in superset, and then the checks from the API continue to use that slice_id, which fails on a check to see if the slice id matches the saved one.

On our fork, we've introduced a very small fix on imports here:

![Image](https://github.com/user-attachments/assets/7f0f2073-1677-4e57-b6f8-cdc1f8d86561)

I don't have time to fully test this out and PR this myself, but hopefully this helps someone in the future.
