### ISSUE TITLE
Feature Request for FHIR Database support

### ISSUE THREAD

**Issue by T-Herrmann-WI** [apache/superset#23879] opened 2023-04-29 16:18 UTC
Are there plans to support FHIR as connector in Superset?

https://de.wikipedia.org/wiki/Fast_Healthcare_Interoperability_Resources

**Comment by sfirke** [comment] 2023-05-01 15:32
Just speaking as a community member of the project: Superset gets database connectors when someone writes the necessary code and submits it.  As far as I know there are not stated plans for developing any additional connectors, but no doubt they will continue to get added as the community creates them.  That process is described in this blog post: https://preset.io/blog/building-database-connector/ and this followup: https://preset.io/blog/improving-apache-superset-integration-database-sqlalchemy/.

If the data source can be queried with SQL, it should be doable, but someone would have to execute it.

**Comment by rusackas** [comment] 2023-05-11 16:40
> Thank you for this info. How much work (days) would be development of this Superset FHIR connector for a good developer?

That depends... some are simple to just tack on, but if you add docs, add the logo to the website, add proper tests, etc, it could get a little more complex (but going that extra mile helps the project a LOT). 

I would post it on a github discussion as an "Ideas" thread if you want to seek further community engagement, or if (from the sound of it) you're looking to contract it out, you might want to explore posting it on the `#jobs` channel on [Superset Slack](http://bit.ly/join-superset-slack) 

Meanwhile, closing this particular Issue since it's not a bug :)

**Closed by rusackas** 2023-05-11 16:40 UTC
