### ISSUE TITLE
[color consistency][pie chart] Dashboard color scheme conflict

### ISSUE THREAD

**Issue by dc0709** [apache/superset#25517] opened 2023-10-04 13:48 UTC
Different groups are represented with the same color.

#### How to reproduce the bug

1. Create a pie chart from your data 
2. Create a dashboard and insert the pie chart created in 1.
3. Select a dashboard color scheme (in the example: *Preset Colors*)
4. Observe the colors of sections

### Expected results

Different sections should have different colors.

### Actual results

Different sections have the same color.

##### Actual
<img width="591" alt="pie_chart_actual" src="https://github.com/apache/superset/assets/105289372/15c7ce4e-dee0-4a63-ab1c-bf7e346a155d">

##### Expected
<img width="472" alt="pie_chart_expected" src="https://github.com/apache/superset/assets/105289372/cb346700-75eb-4130-8971-b0f96cf248fb">

### Environment

- browser type and version: Chrome 117.0.5938.132
- superset version: 2.1.0
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment] 2024-03-19 22:07
Closing this since there have been several improvements in this area and I was generally unable to reproduce it. We're also not supporting Superset 2.x, but if this still exists in Superset 3.x, I'm happy to re-open. Let me know if there's a repro using example datasets so we can better play along. Also, have you by any chance set any series/label colors in your Dashboard Properties, perchance? CC @geido for good measure.

**Closed by rusackas** 2024-03-19 22:07 UTC

**Comment by rusackas** [comment] 2024-03-19 22:09
<img width="675" alt="image" src="https://github.com/apache/superset/assets/812905/aacc36bf-bf88-4a51-9c9c-fe3a1c113761">
 ¯\\\_(ツ)_/¯
