### ISSUE TITLE
[Question]Are there any plans to automatically display all filtering values in the “Charts Filters” section of the Charts page, instead of requiring manual entry of filter items?

### ISSUE THREAD

**Issue by yuanoOo** [apache/superset#23630] opened 2023-04-09 12:47 UTC
Are there any plans to automatically display all filtering values in the “Charts Filters” section of the Charts page, instead of requiring manual entry of filter items?

**Comment by rusackas** [comment] 2024-02-23 22:51
Closing this since it's not a bug and is nearly a year old, but I'm not quite sure what you're asking for. Feel free to open a Discussion in the "Ideas" section and propose some examples/use cases.

**Closed by rusackas** 2024-02-23 22:51 UTC
