### ISSUE TITLE
[mixed time-series]can not add chart to the dashboard

### ISSUE THREAD

**Issue by junlincc** [apache/superset#15877] opened 2021-07-23 21:34 UTC
See video for repro steps and error. 

https://user-images.githubusercontent.com/67837651/126843874-76f6da5d-d067-409a-9a46-37a6c5140897.mov

**Comment by junlincc** [comment] 2021-07-26 22:49
@villebro 🙏

**Comment by zhaoyongjie** [comment] 2021-07-27 03:57
I am unable to reproduce at the latest mater branch.

https://user-images.githubusercontent.com/2016594/127093000-358d4e92-0244-43ae-8e94-98ac72bd0fda.mov

**Comment by villebro** [comment] 2021-07-27 13:05
I am also not able to repro (did the exact same steps as in the recording). Did "See more" on the error message say anything of value?

**Comment by junlincc** [comment] 2021-07-28 14:48
https://user-images.githubusercontent.com/67837651/127339692-597d7c00-7f6f-49e1-bf3e-b61cceef2fde.mov

still seeing the error from my end :(

**Comment by suddjian** [comment] 2021-07-29 18:08
@junlincc what feature flags are you running with? And also just to make sure, have you reset docker and pulled the master branch?

**Comment by rusackas** [comment] 2021-08-01 10:21
I tried this with the main flags we're testing (`ENABLE_EXPLORE_DRAG_AND_DROP`, `DASHBOARD_NATIVE_FILTERS`, and `DASHBOARD_CROSS_FILTERS `) and was unable to reproduce. Added in `DASHBOARD_NATIVE_FILTERS_SET` and `DASHBOARD_FILTERS_EXPERIMENTAL` as @junlincc pictured, and still couldn't reproduce. Tempted to close this one.

**Closed** 2021-08-02 02:07 UTC
Labels: #bug, P1, cant-reproduce, viz:echarts-combo

**Comment by rwspielman** [comment] 2021-09-10 00:53
I'm getting this error in 1.3.0 with async and cache on. I didn't seeing anything in `CHANGELOG.md` about a fix pertaining to this, but have **not** tested on master yet.

I'm noticing flip-flopping API calls to 2 different endpoints to get the chart data. It seems to only be affecting this mixed time-series chart from what I've tested so far.

It will make a call using the `/api/v1/chart/data?form_data={{sliceID}}` endpoint
This succeeds. It returns an object with `result` property and then the data for the chart
![image](https://user-images.githubusercontent.com/20442310/132781074-05640176-6e08-408d-9d30-9dd31278d6ed.png)


It also makes a call using the `/api/v1/chart/{{sliceID}}` endpoint
This one fails. It returns an object that has a `result` property, but doesn't contain the data needed. 
![image](https://user-images.githubusercontent.com/20442310/132781170-e36b723e-8dfd-41ca-b991-e64fa22ad586.png)

**Comment by yongchand** [comment] 2021-09-25 16:51
@rwspielman @junlincc Any updates for this issue? I experiencing similar issue. #16834
