### ISSUE TITLE
How to change the url in superset?

### ISSUE THREAD

**Issue by sedanursayer** [apache/superset#22842] opened 2023-01-24 11:24 UTC
I want to change the url prefix in apache superset. As of now in the browser it looks like '<my_site>/superset/welcome or <my_site>/superset/sqllab . can we change this to something like <my_site>/my_name/welcome etc.

**Comment by rusackas** [comment] 2023-01-24 18:42
There's no convenient way that I'm aware of. I believe you'd have to make code modifications to both the back end serving the jinja templates and handling requests, as well as the React router. There hasn't been any significant number of people asking for this, so it's not easily configurable. Closing this out since it's not a bug, per se, but some folks on #customizing-superset in the Slack workspace might be able to help, or you could try a Github Discussion.

**Closed by rusackas** 2023-01-24 18:42 UTC

**Comment by sedanursayer** [comment] 2023-01-25 08:19
thanks for reply. i actually want the URL to look exactly like this. I've seen a few studies on this, but couldn't find anything on how it's done. Like typing "localhost/mycompany/welcome" instead of "localhost/superset/welcome". or as it looks like localhost/mycompany/sqllab

**Comment by rusackas** [comment] 2023-01-26 06:38
I think you're going to have to go spelunking in the code. I don't suspect anyone would _mind_ if the `/superset/` was gone or configurable. I hate to throw out the typical open source "PRs welcome" statement, but I think that might be the case if others don't see this as urgent.
