### ISSUE TITLE
[Bug report] The 2nd Y-axis on the right side in the Mixed Time-Series does not allow Label to be vertically aligned on the side!

### ISSUE THREAD

**Issue by GolamRashed** [apache/superset#18597] opened 2022-02-07 12:25 UTC
## Screenshot

![image](https://user-images.githubusercontent.com/1528712/152787247-b4f2e62b-5beb-45ae-8f17-635f1912dd1c.png)

## Description

Currently, the 2nd Y-axis on the right side in the Mixed Time-Series does not allow Label to be vertically oriented on the side. Can this be fixed?

## Design input

Naturally, the label should behave the same as the left Y-Axis (which is oriented vertically).

**Comment by rumbin** [comment] 2022-02-08 06:50
Duplicate of #129472

**Comment by GolamRashed** [comment] 2022-02-08 07:00
@rumbin Thanks for pointing that out, should I close this?

**Comment by rumbin** [comment] 2022-02-08 07:09
I think it makes sense to close this one.

**Closed** 2022-02-08 07:10 UTC
Labels: bug:cosmetic
