### ISSUE TITLE
Can't get UI to change again

### ISSUE THREAD

**Issue by aortiz-WW** [apache/superset#22829] opened 2023-01-23 19:17 UTC
### A clear and concise description of what the bug is.
I'm trying to change the UI of superset. I want to add a banner at the top of the page and at the bottom. I have already done so by following these links:
* https://superset.apache.org/docs/installation/installing-superset-using-docker-compose/
* https://github.com/apache/superset/issues/22758

#### How to reproduce the bug
I first clone the repo. Then I go inside the `superset-frontend/src/views/components/` directory. Inside the Menu.tsx, I add to the Menuwrapper component my banner as such:
```
return <>

           <div id='banner'  style={{backgrounColor: 'green', color: 'white', textAlign: 'center}}>Unclassified</div>
           <Menu data={newMenuData} {...rest}/>
</>
```
Then I run the docker-compose pull and up explained in the first link above.
### Expected results
I expect to see changes in the banner after adding changes. It appeared once I made the changes and then if I want to make other changes, it doesn't appear

### Actual results

Nothing changes after the initial change

### Environment

Using apache/superset on windows hosted VM running Ubuntu 22. Everything is ran using vs code.

**Comment by rusackas** [comment] 2023-01-24 18:35
Closing since it's not a bug, but a developer experience issue. I assure you, it does work! 

When running the vanilla `docker-compose up` in your terminal, and you make a file change in the frontend directory, you'll see in your terminal that Webpack starts rebuilding. This takes time! You will not see the changes right away, but they will happen, and you will need to refresh the browser when they do.

Also, you can start a second terminal process, cd into `superset-frontend` and do `npm run dev-server`. This runs a dev mode process (with hot reloading) that proxies to your original Superset server process, and runs on port 9000 instead. However, this means you have TWO webpack builds running concurrently, so you might want to turn off the original docker webpack process by commenting out a line in the `docker-frontend` file. 

Hope that helps!

**Closed by rusackas** 2023-01-24 18:35 UTC
Labels: #bug

**Comment by aortiz-WW** [comment] 2023-01-26 18:26
> Closing since it's not a bug, but a developer experience issue. I assure you, it does work!
> 
> When running the vanilla `docker-compose up` in your terminal, and you make a file change in the frontend directory, you'll see in your terminal that Webpack starts rebuilding. This takes time! You will not see the changes right away, but they will happen, and you will need to refresh the browser when they do.
> 
> Also, you can start a second terminal process, cd into `superset-frontend` and do `npm run dev-server`. This runs a dev mode process (with hot reloading) that proxies to your original Superset server process, and runs on port 9000 instead. However, this means you have TWO webpack builds running concurrently, so you might want to turn off the original docker webpack process by commenting out a line in the `docker-frontend` file.
> 
> Hope that helps!

How much time would you say? In my case, I have waited more than half an hour and nothing happened

**Comment by rusackas** [comment] 2023-01-26 21:21
Oh jeez... should be less than a minute, depending on computer. Try the other approach I mentioned running webpack separately in a second terminal.
