### ISSUE TITLE
Unable to use Propagate feature on timeseries charts

### ISSUE THREAD

**Issue by at-tn** [apache/superset#10166] opened 2020-06-25 19:40 UTC
We are unable to use the Propagate option on charts. It is available through customize chart action for "Time Series" chart (a line chart for example). Our use case is to trigger updates in other charts in the parent dashboard when the time range in one of the child chart is updated. 
Our environment:
OS: Debian GNU/Linux 10 
Superset version: 0.35.2

### Expected results
Selecting Propagate on one chart should reflect selection on other charts in the same dashboard. 
Alternatively some documentation on how to get the propagate feature to work would be tremendously helpful.

### Actual results
Selecting Propagate on one chart does not reflect selection on other charts in the same dashboard. 

### Environment
OS: Debian GNU/Linux 10 
- superset version: 0.35.2
- python version: Python 3.6.10
- node.js version:  v. 12
- npm version: n/a

### Checklist

Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rumbin** [comment] 2020-06-26 11:43
I can confirm this bug on 0.35

**Comment by ibotheperfect** [comment] 2020-11-20 07:20
This bug still exist on 0.37.2

**Comment by graceguo-supercat** [comment] 2022-03-16 16:52
close this since no recent follow-up.

**Closed by graceguo-supercat** 2022-03-16 16:52 UTC
Labels: !deprecated-label:bug
