### ISSUE TITLE
connect hive error

### ISSUE THREAD

**Issue by qianxiaoning** [apache/superset#23676] opened 2023-04-13 08:30 UTC
#### How to reproduce the bug

1. add hive to database connection
2. Click test link is ok
3. Click save button is error

### Expected results

add database connection successful

### Actual results

add database connection fail

#### Screenshots
1.Click test link is ok
![微信截图_20230413160840](https://user-images.githubusercontent.com/19730980/231697608-32f93d3f-28db-4f9d-beec-c14f8fbed72f.png)

2.click save button is error
![微信截图_20230413160854](https://user-images.githubusercontent.com/19730980/231697717-f32e23a1-483f-4b6b-b2cf-8c9a9067df54.png)

3.edit the database connection is error
![微信截图_20230413160915](https://user-images.githubusercontent.com/19730980/231697895-58ee7ea3-8dfd-47a7-a999-4ce7886ac9c9.png)

4.when I add dataset, can show hive databases successful, but when I select tables, will error
![微信截图_20230413160932](https://user-images.githubusercontent.com/19730980/231698220-6f89eb06-5fcd-469a-850d-1505723b591e.png)

5.my hive metastore log
![image](https://user-images.githubusercontent.com/19730980/231698611-f94de0ab-7d78-4b49-b756-76a73062310d.png)

6.docker container log
![微信截图_20230413164430](https://user-images.githubusercontent.com/19730980/231705886-63208848-0fd3-4e72-9fcd-508ecde4231b.png)
![微信截图_20230413164509](https://user-images.githubusercontent.com/19730980/231705902-29b70b30-fbde-42ee-913a-0aa7b5afdf83.png)

### Environment

(please complete the following information):

- browser type and version: chrome
- superset version: `superset version`
![image](https://user-images.githubusercontent.com/19730980/231700460-ac2141ad-7999-4540-b8ba-cbabf5942756.png)
![image](https://user-images.githubusercontent.com/19730980/231700744-dc107acc-7da4-45a8-89b1-f9a12bfdd569.png)

- python version: `python --version`
I used Docker to load it
- node.js version: `node -v`
- I used Docker to load it
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

### Additional context

Maybe I have some wrong config in somewhere, could help me and tell me some directions？

**Comment by sfirke** [comment] 2023-07-10 19:34
Possible duplicate of https://github.com/apache/superset/issues/23676

**Comment by sfirke** [comment] 2023-08-02 15:21
Possibly related to https://github.com/apache/superset/issues/24031 ?

**Comment by rusackas** [comment] 2024-03-06 21:54
This still a problem in Superset 3.x? Tempted to close this thread out as stale.

**Closed** 2024-04-18 16:04 UTC
Labels: data:connect:hive, #bug
