### ISSUE TITLE
Chart holder too big for charts

### ISSUE THREAD

**Issue by teresamorins** [apache/superset#23067] opened 2023-02-13 08:50 UTC
## Screenshot

![image](https://user-images.githubusercontent.com/85219774/218406670-17edf8ee-82e9-46f1-ba9d-fc07a3dff800.png)

## Description

Hi there! One thing that is quite important in the dashboard world is the ability to place charts on top of each other so it looks like is just one. This is something that I can't figure out how to do in Superset (v2.0.0.1). For example, I need to create a table with dynamic column names, and in the provider ss, that would be the last 6 months. I can't do that in Superset but I can create another chart with only the month names and pretend that it is the header of the table. Now, I can't position the chart with the month names on top of the table with the values because everytime I try to decrease the height of the month names chart, the names are always going up until I can't read anything there. The same goes for the table itself, because if I want to add a total column at the end, I also can't!
 There is always a huge gap between the chart and the chart holder. This scenario also applies for instance for bar charts, for dynamic headers, dynamic titles and so on.

## Design input
Is there anything that I can do from my side to make this happen? Like with CSS for example? If not, please allow the possibility to place charts on top of each other without gaps. Building a dashboard is so much more than just placing charts here and there :)

**Comment by rusackas** [comment] 2023-02-17 05:07
Yes, you can use CSS to tweak the dashboard layout. When the dashboard is in edit mode, you can click the button with the three dots to the right of the Save button, and you'll see Edit CSS. From there you're a bit on your own, but hopefully you can find your way. I'll try to write a blog post on the topic soon to cover more of this.

Also, are these Handlebars charts? if so, would it make sense to just... make them all one chart? Obviously I do't know your data, so maybe not, but I thought I should ask :)

Closing this since it's not a bug, but we can try to continue the discussion here if needed, or you can ping me on Slack.

**Closed by rusackas** 2023-02-17 05:07 UTC

**Comment by teresamorins** [comment] 2023-02-17 08:06
Hi! Thank you for your reply! I'm working with Superset for some time already and I know that we can do a lot with CSS, but this one I just can't figure out a way to do it! And no, this is not Handelbars, is actually just a simple table visualization with some tweaks in SQL :).  Unfortunately Handelbars is still not working for us. I will take the opportunity to say that indeed a bit more of guidance regarding CSS and Handelbars, particularly for people with no background in these, would be really, really nice!
