### ISSUE TITLE
Fatal error exporting CSV when using jinja templates

### ISSUE THREAD

**Issue by saward** [apache/superset#14834] opened 2021-05-26 02:55 UTC
I've applied a jinja template to a query, so that I can use filters or query values as part of the query.  For example, I've tested both of these options:

```
{% set cutoffold = cache_key_wrapper(url_param('cutoff')) %}
{% set cutoff = filter_values('report_period')[0] %}
```
And use them in a query:

```
...
WHERE (approved >= ('{{cutoff}} 06:00'::timestamptz - INTERVAL '24 hour') OR approved IS NULL)
...
```

The table works fine.  I can see the results filtered as expected.  However, when it comes time to export the CSV, it seems that the filter and/or query parameter values are not available to the query for that purpose.

### Expected results

Download CSV

### Actual results

"Fatal error" reported, and looking at the superset logs, it's complaining about that value being empty:

```
invalid input syntax for type timestamp with time zone: "{{ no such element: list object[0] }} 06:00"
```

My assumption here is that whatever values are made available to the query template via url's or filters are not available by the method used to download the CSV.

#### How to reproduce the bug

1. Create a query that relies on a url field, provided by jinja template
2. Create a table that uses this query
3. View table, with parameter added to URL, and observe that results appear
4. Download CSV, and observe fatal error response

### Environment

- superset version: 1.1.0
- python version: Python 3.8.9 (running inside docker)
- node.js version: Not installed, presumably completed as part of docker build step and not included in container

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [X] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by junlincc** [comment] 2021-05-27 16:10
@betodealmeida 🙏

**Comment by Ashish7129** [comment] 2022-03-15 07:31
@saward @junlincc @betodealmeida We are using superset version 1.2 and the issue is still there. By any chance, Is this Issue resolved ? If Yes, Please share the PRs/Superset Version link?

**Comment by rusackas** [comment] 2023-01-11 23:30
Is anyone here able to validate whether or not this is still an issue in 2.0.x? Hoping this is no long an issue and we can close it 🤞

**Comment by rusackas** [comment] 2024-02-15 16:46
Closing this as stale since it's been silent for so long, and we're trying to steer toward a more actionable Issues backlog. If people are still encountering this in current versions (currently 3.x) please re-open this issue, open a new Issue with updated context, or raise a PR to address the problem. Thanks!

**Closed by rusackas** 2024-02-15 16:46 UTC
Labels: validation:required, data:csv, global:jinja
