### ISSUE TITLE
sync columns from source not working

### ISSUE THREAD

**Issue by cooley-pe** [apache/superset#16479] opened 2021-08-27 04:17 UTC
The `sync columns from source` button in the chart data source editor fails.

### Expected results
When I click the `sync column` button, superset will update the columns available in the chart per the data source.

### Actual results

I get an error and the column that was added to the datasource isn't available.

#### Screenshots

![Screen Shot 2021-08-26 at 9 04 54 PM](https://user-images.githubusercontent.com/64038793/131070293-2aba14da-4d4b-46f8-8d23-cdffa31eed02.png)

<img width="346" alt="Screen Shot 2021-08-26 at 9 16 50 PM" src="https://user-images.githubusercontent.com/64038793/131070987-82b84b9d-1dfe-4ee5-9b6b-39cb6f95998f.png">

#### How to reproduce the bug

1. Run a query in sqllab only selecting a subset of columns.
2. Click `Explore` to make a chart.
3. Click on `Edit datasource`
4. Add a column to the datasource
5. Click save
6. Click on `Edit datasource`
7. Click on the `Columns` tab.
8. Click `sync columns from source`

### Environment

(please complete the following information):

- superset version: `1.3`
- python version: `3.8.9`
- node.js version: n/a
- any feature flags active: 
  - ENABLE_TEMPLATE_PROCESSING
  - ALERT_REPORTS
  - DASHBOARD_CROSS_FILTERS
  - DASHBOARD_NATIVE_FILTERS

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by villebro** [comment] 2021-08-31 10:20
As a temporary workaround, you can rename the dataset to something without slashes (`/`), after which it should work ok

**Comment by heoun** [comment] 2021-08-31 15:07
My datasets don't have any slashes. Don't believe that is the issue here

**Comment by villebro** [comment] 2021-08-31 16:24
In that case please post more context on your problem so we can assess ehat the problem is (the problem in this issue has already been resolved)

**Comment by cooley-pe** [comment] 2021-08-31 18:21
@villebro I can confirm that the workaround seems to have fixed the issue on my end.

**Comment by heoun** [comment] 2021-09-02 10:03
@villebro - so potentially did some digging and it seems that my schema was not set when setting datasets through queries. Could be a bug from that end as well thats flowing into sync columns? Are there any workarounds to get charts to sync without having to recreate the dataset + charts from scratch?

**Comment by villebro** [comment] 2021-09-06 12:04
@heoun if you need to change the schema you should be able to do it in the save chart editor modal. If this doesn't work please open a new ticket with detailed reproduction steps. Closing this ticket as this bug is fixed on the forthcoming version 1.3.1.

**Closed by villebro** 2021-09-06 12:04 UTC
Labels: #bug, v1.3
