### ISSUE TITLE
Superset could not be embed in micro frontend application as a sub-app by single-spa or qiankun tools

### ISSUE THREAD

**Issue by godliness** [apache/superset#15439] opened 2021-06-29 06:41 UTC
From now on, i think that superset-frontend is a little complex, it's hard to embed in micro frontend application as a sub-app 
by single-spa(https://single-spa.js.org/) or even qiankun(https://qiankun.umijs.org/) which is inspired by single-spa.

superset-frontend has multi entries and its a little complex for me to embed it into micro frontend application.

Do you have any ideas or successful example about who has already embed superset into any micro frontend application or how i could embed superset into a big application? exclude iframe, any good ideas?

**Comment by suddjian** [comment] 2021-06-29 22:08
Duplicate of https://github.com/apache/superset/issues/15383

**Closed by suddjian** 2021-06-29 22:08 UTC
