### ISSUE TITLE
Point Color not reported in deck.gl multilayer

### ISSUE THREAD

**Issue by cphilibien** [apache/superset#23259] opened 2023-03-01 22:24 UTC
I create a map layer (deck.gl Scatterplot) and define categorical color for point. The color is defin in shema of dashboard
but when I add this one in deck.gl multi layer, the color is not reported by categories…

![image](https://user-images.githubusercontent.com/112178756/222278326-8264bda0-0d3b-42a9-a731-3fadad3b56fa.png)

#### Screenshots
result in deck.gl Scatterplot:
![image](https://user-images.githubusercontent.com/112178756/222278476-2e2540af-176a-4d72-817d-9fcaa80c3740.png)

result in deck.gl multi layer:
![image](https://user-images.githubusercontent.com/112178756/222278544-5bbe19cd-934b-4ebb-8656-93eed069639b.png)

### Environment

(please complete the following information):

- browser type and version: chrome Version 110.0.5481.177 
- superset version: `superset version` Version: 2.0.0

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [x] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by cphilibien** [comment] 2023-06-13 15:25
To up my issue. Same issue with new superset version 2.1

**Comment by rusackas** [comment] 2024-02-29 22:25
Still happening in 3.x/4.x, but this is a duplicate of another issue. Trying to find that one so I can link it and close whichever is older or has less context...

**Comment by rusackas** [comment] 2024-02-29 22:29
Closing in favor of the older issue, https://github.com/apache/superset/issues/23259

**Closed by rusackas** 2024-02-29 22:29 UTC
Labels: viz:charts:deck.gl, #bug
