### ISSUE TITLE
deck.dl visualization from Oracle DB source

### ISSUE THREAD

**Issue by mehanat** [apache/superset#26361] opened 2023-12-26 14:18 UTC
Hello, I'm trying to create deck.dl vis, using an Oracle datasource
My version of oracle doesn't have a specific Json data type, so I store geo-json data in the BLOB type column

The problem is when I'm trying to visualize the data, Superset gives me an error:
ORA-00932: Incosistent datatypes: expected - got BLOB

Could you help me please, are there any workarounds?

**Comment by sfirke** [comment] 2023-12-27 20:05
Hello, sorry you are having this difficulty.  This is not a bug in Superset, this is happening between SQLAlchemy (which Superset uses to read data) and your Oracle DB.  The proper fixes include upgrading to a version of Oracle that supports Geo JSON, or using a different DB type that does.  If those are not options, you could try to hack together a workaround.

This is not a Superset-specific issue so I'm going to close it.  Feel free to try searching the Superset Slack chat to see if anyone has discussed this topic, otherwise I expect Oracle forums or that community would be the best bet.  Or possibly search to see if anyone has a way to do this via SQLAlchemy modification.  Good luck!

**Closed by sfirke** 2023-12-27 20:05 UTC
Labels: data:connect:oracle
