### ISSUE TITLE
database test does not exist，and image 404

### ISSUE THREAD

**Issue by billy98** [apache/superset#12723] opened 2021-01-25 04:11 UTC
I used docker-compose to deploy the superset, which is version v1.0.0,
Test database does not exist during initialization
Unable to open it after login.

```
superset_app             | INFO:superset.utils.logging_configurator:logging was configured successfully
superset_app             | INFO:superset.utils.logging_configurator:logging was configured successfully
superset_worker          | INFO:superset.utils.logging_configurator:logging was configured successfully
superset_tests_worker    | INFO:superset.utils.logging_configurator:logging was configured successfully
superset_db              | 2021-01-25 02:51:53.376 UTC [31] FATAL:  database "test" does not exist
superset_tests_worker    | /usr/local/lib/python3.7/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
superset_tests_worker    |   "Flask-Caching: CACHE_TYPE is set to null, "
superset_tests_worker    | ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) FATAL:  database "test" does not exist
superset_tests_worker    | 
superset_tests_worker    | (Background on this error at: http://sqlalche.me/e/13/e3q8)
superset_tests_worker    | Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
superset_tests_worker exited with code 1
superset_init            | INFO:superset.utils.logging_configurator:logging was configured successfully
superset_init            | /usr/local/lib/python3.7/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
superset_init            |   "Flask-Caching: CACHE_TYPE is set to null, "
superset_init            | INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
superset_init            | INFO  [alembic.runtime.migration] Will assume transactional DDL.
superset_init            | Loaded your LOCAL configuration at [/app/docker/pythonpath_dev/superset_config.py]
superset_worker          | /usr/local/lib/python3.7/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
superset_worker          |   "Flask-Caching: CACHE_TYPE is set to null, "
superset_worker          | /usr/local/lib/python3.7/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
superset_worker          | absolutely not recommended!

......

superset_init            | INFO:superset.models.helpers:Updating table_columns yt_other
superset_init            | INFO:superset.models.helpers:Updating table_columns gender
superset_init            | INFO:superset.datasets.commands.importers.v1.utils:Loading data inside the import transaction
Exception in thread Thread-22:
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 380, in _make_request
  File "http/client.py", line 1331, in getresponse
  File "http/client.py", line 297, in begin
  File "http/client.py", line 258, in _read_status
  File "socket.py", line 586, in readinto
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 638, in urlopen
  File "site-packages/urllib3/util/retry.py", line 368, in increment
  File "site-packages/urllib3/packages/six.py", line 686, in reraise
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 386, in _make_request
  File "site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "compose/cli/log_printer.py", line 214, in watch_events
  File "compose/project.py", line 493, in yield_loop
  File "compose/project.py", line 461, in build_container_event
  File "compose/container.py", line 48, in from_id
  File "site-packages/docker/utils/decorators.py", line 19, in wrapped
  File "site-packages/docker/api/container.py", line 755, in inspect_container
  File "site-packages/docker/utils/decorators.py", line 46, in inner
  File "site-packages/docker/api/client.py", line 230, in _get
  File "site-packages/requests/sessions.py", line 537, in get
  File "site-packages/requests/sessions.py", line 524, in request
  File "site-packages/requests/sessions.py", line 637, in send
  File "site-packages/requests/adapters.py", line 529, in send
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

superset_init            | /app/docker/docker-init.sh: line 79:    36 Killed                  superset load_examples
superset_db              | 2021-01-25 02:56:12.771 UTC [39] LOG:  unexpected EOF on client connection with an open transaction
superset_app             | /usr/local/lib/python3.7/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
superset_app             |   "Flask-Caching: CACHE_TYPE is set to null, "
superset_app             | 192.168.20.46 - - [25/Jan/2021 02:56:12] "GET / HTTP/1.1" 302 -

.....
superset_app             | 192.168.20.46 - - [25/Jan/2021 02:57:00] "GET /superset/welcome HTTP/1.1" 200 -
superset_app             | INFO:werkzeug:192.168.20.46 - - [25/Jan/2021 02:57:00] "GET /superset/welcome HTTP/1.1" 200 -
superset_app             | 192.168.20.46 - - [25/Jan/2021 02:57:00] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -
superset_app             | INFO:werkzeug:192.168.20.46 - - [25/Jan/2021 02:57:00] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -
superset_app             | DEBUG:superset.stats_logger:[stats_logger] (incr) welcome
superset_app             | 192.168.20.46 - - [25/Jan/2021 02:57:01] "GET /superset/welcome HTTP/1.1" 200 -
superset_app             | INFO:werkzeug:192.168.20.46 - - [25/Jan/2021 02:57:01] "GET /superset/welcome HTTP/1.1" 200 -
superset_app             | 192.168.20.46 - - [25/Jan/2021 02:57:01] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -
superset_app             | INFO:werkzeug:192.168.20.46 - - [25/Jan/2021 02:57:01] "GET /static/assets/images/loading.gif HTTP/1.1" 404 -

```
![image](https://user-images.githubusercontent.com/13307862/105660304-af922d80-5f05-11eb-8d0d-06d9c17392e5.png)

**Comment by dpgaspar** [comment] 2021-01-25 15:51
seems like a internet connection problem:

```
superset_init            | INFO:superset.datasets.commands.importers.v1.utils:Loading data inside the import transaction
Exception in thread Thread-22:
Traceback (most recent call last):
  File "site-packages/urllib3/connectionpool.py", line 384, in _make_request
  File "<string>", line 2, in raise_from
  File "site-packages/urllib3/connectionpool.py", line 380, in _make_request
  File "http/client.py", line 1331, in getresponse
  File "http/client.py", line 297, in begin
  File "http/client.py", line 258, in _read_status
  File "socket.py", line 586, in readinto
socket.timeout: timed out
```

**Comment by jesperbagge** [comment] 2021-01-25 18:41
I have the same issue when running docker-compose up from a Mac running latest Docker Desktop. There's no evidence of network errors in the startup logs, but I have flask_appbuilder errors. And the end result is the same - a blank page with broken image links and buttons.

```
db_1                     | CREATE DATABASE
db_1                     |
db_1                     |
db_1                     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1                     |
db_1                     | 2021-01-25 18:27:34.546 UTC [48] LOG:  received fast shutdown request
db_1                     | waiting for server to shut down....2021-01-25 18:27:34.547 UTC [48] LOG:  aborting any active transactions
db_1                     | 2021-01-25 18:27:34.549 UTC [48] LOG:  worker process: logical replication launcher (PID 55) exited with exit code 1
db_1                     | 2021-01-25 18:27:34.551 UTC [50] LOG:  shutting down
db_1                     | 2021-01-25 18:27:34.563 UTC [48] LOG:  database system is shut down
db_1                     |  done
db_1                     | server stopped
db_1                     |
db_1                     | PostgreSQL init process complete; ready for start up.
db_1                     |
db_1                     | 2021-01-25 18:27:34.659 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1                     | 2021-01-25 18:27:34.659 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1                     | 2021-01-25 18:27:34.661 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1                     | 2021-01-25 18:27:34.672 UTC [76] LOG:  database system was shut down at 2021-01-25 18:27:34 UTC
db_1                     | 2021-01-25 18:27:34.677 UTC [1] LOG:  database system is ready to accept connections
superset_node            | npm WARN using --force I sure hope you know what you are doing.
superset_app             |  * Serving Flask app "superset.app:create_app()" (lazy loading)
superset_app             |  * Environment: development
superset_app             |  * Debug mode: on
superset_app             |  * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)
superset_app             |  * Restarting with stat
superset_tests_worker    | INFO:superset.utils.logging_configurator:logging was configured successfully
db_1                     | 2021-01-25 18:27:38.783 UTC [83] FATAL:  database "test" does not exist
superset_tests_worker    | /usr/local/lib/python3.7/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
superset_tests_worker    |   "Flask-Caching: CACHE_TYPE is set to null, "
superset_tests_worker    | ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) FATAL:  database "test" does not exist
superset_tests_worker    |
superset_tests_worker    | (Background on this error at: http://sqlalche.me/e/13/e3q8)
```

**Comment by billy98** [comment] 2021-01-26 02:19
> seems like a internet connection problem:
> 
> ```
> superset_init            | INFO:superset.datasets.commands.importers.v1.utils:Loading data inside the import transaction
> Exception in thread Thread-22:
> Traceback (most recent call last):
>   File "site-packages/urllib3/connectionpool.py", line 384, in _make_request
>   File "<string>", line 2, in raise_from
>   File "site-packages/urllib3/connectionpool.py", line 380, in _make_request
>   File "http/client.py", line 1331, in getresponse
>   File "http/client.py", line 297, in begin
>   File "http/client.py", line 258, in _read_status
>   File "socket.py", line 586, in readinto
> socket.timeout: timed out
> ```

I can guarantee that my network is good

**Comment by lihongjie224** [comment] 2021-01-26 04:09
Yeah, I have the same issue too. How to fix it?

**Comment by deddu** [comment] 2021-01-26 05:09
```
docker-compose ps
 
        Name                       Command                   State                     Ports              
----------------------------------------------------------------------------------------------------------
superset_app            /usr/bin/docker-entrypoint ...   Up (unhealthy)   8080/tcp, 0.0.0.0:8088->8088/tcp
superset_cache          docker-entrypoint.sh redis ...   Up               127.0.0.1:6379->6379/tcp        
superset_db             docker-entrypoint.sh postgres    Up               127.0.0.1:5432->5432/tcp        
superset_init           /usr/bin/docker-entrypoint ...   Up (unhealthy)   8080/tcp                        
superset_node           docker-entrypoint.sh /app/ ...   Up                                               
superset_tests_worker   /usr/bin/docker-entrypoint ...   Exit 1                                           
superset_worker         /usr/bin/docker-entrypoint ...   Up (unhealthy)   8080/tcp                        
```

I encountered this error following the tutorial too. (`git clone`,`git checkout latest`, `docker-compose up`) on mac os. 
Let me say that I do not know much about this project, but this connection error comes from the test_worker, and I don't know if the tests_worker is really necessary in the demo.

It fails because is looking for a local test postgres database in the host network. see https://github.com/apache/superset/blob/master/docker-compose.yml#L93

``` yml
  superset-tests-worker:
    image: *superset-image
    container_name: superset_tests_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: docker/.env
    environment:
      DATABASE_HOST: localhost
      DATABASE_DB: test
      REDIS_CELERY_DB: 2
      REDIS_RESULTS_DB: 3
      REDIS_HOST: localhost
    network_mode: host
    depends_on: *superset-depends-on
    user: "root"
    volumes: *superset-volumes
```

**Comment by deddu** [comment] 2021-01-26 05:20
I think the problem is in the `superset_node` container, this seems a more likely kind of cause..
```
superset_node            | npm WARN tarball tarball data for typescript@4.0.3 (sha512-tEu6DGxGgRJPb/mVPIZ48e69xCn2yRmCgYmDugAVwmJ6o+0u1RI18eO7E7WBTLYLaEVVOhwQmcdhQHweux/WPg==) seems to be corrupted. Trying one more time.
superset_node            | npm WARN tarball tarball data for echarts@5.0.0 (sha512-6SDcJbLVOcfQyjPg+spNU1+JVrkU1B9fzUa5tpbP/mMNUPyigCOJwcEIQAJSbp9jt5UP3EXvQR0vtYXIo9AjyA==) seems to be corrupted. Trying one more time.
superset_node            | npm WARN tarball tarball data for datamaps@0.5.9 (sha512-GUXpO713URNzaExVUgBtqA5fr2UuxUG/fVitI04zEFHVL2FHSjd672alHq8E16oQqRNzF0m1bmx8WlTnDrGSqQ==) seems to be corrupted. Trying one more time.
superset_node            | npm WARN tar ENOENT: no such file or directory, open '/app/superset-frontend/node_modules/.staging/datamaps-264ee032/dist/datamaps.cod.js'
superset_node            | npm WARN tar ENOENT: no such file or directory, futime
```

but maybe it's just very very slow to compile the frontend?

**Comment by gee-m** [comment] 2021-01-31 12:27
Try increasing the RAM to 7-8gb and restarting docker, fixed it for me

**Comment by JakeXu** [comment] 2021-02-06 16:07
> I have the same issue when running docker-compose up from a Mac running latest Docker Desktop. There's no evidence of network errors in the startup logs, but I have flask_appbuilder errors. And the end result is the same - a blank page with broken image links and buttons.
> 
> ```
> db_1                     | CREATE DATABASE
> db_1                     |
> db_1                     |
> db_1                     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
> db_1                     |
> db_1                     | 2021-01-25 18:27:34.546 UTC [48] LOG:  received fast shutdown request
> db_1                     | waiting for server to shut down....2021-01-25 18:27:34.547 UTC [48] LOG:  aborting any active transactions
> db_1                     | 2021-01-25 18:27:34.549 UTC [48] LOG:  worker process: logical replication launcher (PID 55) exited with exit code 1
> db_1                     | 2021-01-25 18:27:34.551 UTC [50] LOG:  shutting down
> db_1                     | 2021-01-25 18:27:34.563 UTC [48] LOG:  database system is shut down
> db_1                     |  done
> db_1                     | server stopped
> db_1                     |
> db_1                     | PostgreSQL init process complete; ready for start up.
> db_1                     |
> db_1                     | 2021-01-25 18:27:34.659 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> db_1                     | 2021-01-25 18:27:34.659 UTC [1] LOG:  listening on IPv6 address "::", port 5432
> db_1                     | 2021-01-25 18:27:34.661 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> db_1                     | 2021-01-25 18:27:34.672 UTC [76] LOG:  database system was shut down at 2021-01-25 18:27:34 UTC
> db_1                     | 2021-01-25 18:27:34.677 UTC [1] LOG:  database system is ready to accept connections
> superset_node            | npm WARN using --force I sure hope you know what you are doing.
> superset_app             |  * Serving Flask app "superset.app:create_app()" (lazy loading)
> superset_app             |  * Environment: development
> superset_app             |  * Debug mode: on
> superset_app             |  * Running on http://0.0.0.0:8088/ (Press CTRL+C to quit)
> superset_app             |  * Restarting with stat
> superset_tests_worker    | INFO:superset.utils.logging_configurator:logging was configured successfully
> db_1                     | 2021-01-25 18:27:38.783 UTC [83] FATAL:  database "test" does not exist
> superset_tests_worker    | /usr/local/lib/python3.7/site-packages/flask_caching/__init__.py:192: UserWarning: Flask-Caching: CACHE_TYPE is set to null, caching is effectively disabled.
> superset_tests_worker    |   "Flask-Caching: CACHE_TYPE is set to null, "
> superset_tests_worker    | ERROR:flask_appbuilder.security.sqla.manager:DB Creation and initialization failed: (psycopg2.OperationalError) FATAL:  database "test" does not exist
> superset_tests_worker    |
> superset_tests_worker    | (Background on this error at: http://sqlalche.me/e/13/e3q8)
> ```

After changing to the CentOS environment with RAM 8G, everything is well done, fixed it for me, you can try it

**Comment by deddu** [comment] 2021-02-07 06:16
I just tried again on the latest master. Mac os, 9gb ram in my docker setup. Not fixed afaict. still blank page after the login. 

I could run the frontend manually in the host, after the superset-node container crashed,  by cd'ing into the frontend folder, installing the deps via `npm i` and then `npm run dev`.

**Comment by svizi** [comment] 2021-02-12 18:17
Same here. Blank page after the login.
MacOS version : 11.2.1
Docker Desktop : 3.1.0
8GB Memory allocated to Docker.

**Comment by swdmike** [comment] 2021-02-19 00:58
#10773 
check this, you need wait for a while

**Comment by martinstuga** [comment] 2021-03-03 18:13
> Try increasing the RAM to 7-8gb and restarting docker, fixed it for me

This worked for me. Thanks @gee-m , you made my day.

**Comment by harrywang** [comment] 2021-03-24 00:08
Same problem:

MacOS version : 11.2.3
Docker Desktop : 3.2.2
7.5GB Memory allocated to Docker
Latest master branch (cloned 3/23/2021)

Errors:

<img width="594" alt="Screen Shot 2021-03-23 at 8 06 50 PM" src="https://user-images.githubusercontent.com/595772/112234714-7b8c6d80-8c13-11eb-8313-0accf849e7be.png">


<img width="1046" alt="Screen Shot 2021-03-23 at 8 07 06 PM" src="https://user-images.githubusercontent.com/595772/112234721-7e875e00-8c13-11eb-9fec-36b6c5035efe.png">


<img width="784" alt="Screen Shot 2021-03-23 at 8 07 43 PM" src="https://user-images.githubusercontent.com/595772/112234729-81824e80-8c13-11eb-9edf-e7f13fd5021c.png">


<img width="1045" alt="Screen Shot 2021-03-23 at 8 07 52 PM" src="https://user-images.githubusercontent.com/595772/112234731-83e4a880-8c13-11eb-8081-d8874e345d63.png">

**Comment by harrywang** [comment] 2021-03-24 01:53
> Same problem:
> 
> MacOS version : 11.2.3
> Docker Desktop : 3.2.2
> 7.5GB Memory allocated to Docker
> Latest master branch (cloned 3/23/2021)
> 
> `$ docker-compose up` is used.
> 
> Errors:
> 
> <img alt="Screen Shot 2021-03-23 at 8 06 50 PM" width="594" src="https://user-images.githubusercontent.com/595772/112234714-7b8c6d80-8c13-11eb-8313-0accf849e7be.png">
> 
> <img alt="Screen Shot 2021-03-23 at 8 07 06 PM" width="1046" src="https://user-images.githubusercontent.com/595772/112234721-7e875e00-8c13-11eb-9fec-36b6c5035efe.png">
> 
> <img alt="Screen Shot 2021-03-23 at 8 07 43 PM" width="784" src="https://user-images.githubusercontent.com/595772/112234729-81824e80-8c13-11eb-9edf-e7f13fd5021c.png">
> 
> <img alt="Screen Shot 2021-03-23 at 8 07 52 PM" width="1045" src="https://user-images.githubusercontent.com/595772/112234731-83e4a880-8c13-11eb-8081-d8874e345d63.png">

I just did the following to make it work:

1. change to master branch `git checkout master`
2. change redis from 3.2 to latest in `docker-compose-non-dev.yml`
<img width="307" alt="Screen Shot 2021-03-23 at 9 51 25 PM" src="https://user-images.githubusercontent.com/595772/112242317-f9577580-8c21-11eb-807f-db9c1fdd04c7.png">
3. use `docker-compose -f docker-compose-non-dev.yml up` to start the server
4. wait sometime and superset_init exited with 0 is expected - it does not affect the server:
<img width="468" alt="Screen Shot 2021-03-23 at 9 47 56 PM" src="https://user-images.githubusercontent.com/595772/112242376-1d1abb80-8c22-11eb-8393-75ff66cc196f.png">

**Comment by zuzana-vej** [comment] 2021-04-20 04:24
as per the label resolved this question seems answered --> closing

**Closed by zuzana-vej** 2021-04-20 04:24 UTC
Labels: install:docker, resolved
