### ISSUE TITLE
With latest update to Chrome, Scroll is missing while using Create Charts functionality

### ISSUE THREAD

**Issue by PraneshVG** [apache/superset#18072] opened 2022-01-18 08:37 UTC
## Screenshot

[drag & drop image(s) here!]

## Description

When tried creating charts, the scroll option for Query section is missing. Due to which users are not able to access some of the functionality.

## Design input
Scrolling CSS is missing for <div class='css-gcs5mj'>

**Comment by geido** [comment] 2022-01-18 16:49
Hello @PraneshVG please provide more information, such as your Superset version. Videos / GIFs are also appreciated. Thank you!

**Comment by geido** [comment] 2022-01-18 16:56
Duplicate of #18047

**Closed by geido** 2022-01-18 16:56 UTC
Labels: need:more-info
