### ISSUE TITLE
Why is there no example data after logging in to the superset system

### ISSUE THREAD

**Issue by 8debug** [apache/superset#18140] opened 2022-01-23 06:33 UTC
I installed the boot system according to the documentation（Execute `docker-compose -f docker-compose-non-dev.yml up` command）, Why is there no example data after logging in to the superset system ?

**Comment by ad-m** [comment] 2022-01-23 17:08
Could you provide logs `docker-compose logs` eg. via GitHub Gist?

**Comment by 8debug** [comment] 2022-01-24 13:22
> Could you provide logs `docker-compose logs` eg. via GitHub Gist?

And after executing `docker-compose -f docker-compose.yml up`, the webpage displays an error.

![image](https://user-images.githubusercontent.com/3394927/150790158-0b609ce0-291d-4fc3-8823-98f2d397ebc0.png)

### You can try it out according to the steps in the documentation，Replace `docker-compose -f docker-compose-non-dev.yml up` with `docker-compose -f docker-compose.yml up`

**Comment by ad-m** [comment] 2022-01-25 02:56
I had the same experience. In my case it was caused by the lack of building a front-end, because it takes a while to build. You have to wait longer or provide logs of containers.

**Comment by srinify** [comment] 2022-01-27 13:54
@ad-m is spot on, this is a common issue that occurs when the frontend hasn't finished building yet.

If you want to quickly try Superset, then I would recommend using `docker-compose -f docker-compose-non-dev.yml up`. Your screenshot is still showing `docker-compose -f docker-compose.yml up` instead.

While this is certainly annoying, this isn't a bug that needs fixing or investigation so I'll be closing this issue for now. Please post in Github Discussions or in the Superset Slack if you'd like more help from the community here! (https://superset.apache.org/community has a link to join the Slack)

**Closed by srinify** 2022-01-27 13:54 UTC
Labels: need:validation, question & help wanted
