### ISSUE TITLE
Chart Explorer: table visualization does not check for empty COLUMNS control

### ISSUE THREAD

**Issue by cccs-jc** [apache/superset#13635] opened 2021-03-15 21:29 UTC
In the Chart explorer the table visualization lets you choose aggregate or raw mode. In raw mode the COLUMNS control should report an error when no columns are chosen. For example something like this.

![image](https://user-images.githubusercontent.com/56140112/111223415-81e76d80-85b3-11eb-81f4-a63b5ed88bae.png)

#### How to reproduce the bug

1. Go to Chart explorer UI
2. Choose Table visualization
3. Choose QUERY MODE = RAW RECORDS
4. RUN query

However the table visualization does not check that the COLUMNS control is empty and lets you execute the query with no selection. This results in an "Unexpected Error, Error: Empty query?"

It would be better if the COLUMNS control checked for the empty state and reported the issue like depicted above.

**Comment by geido** [comment] 2022-03-16 16:29
Hello @cccs-jc this seems to work as intended in master. Please have a look. I will close this issue for now. Thanks

**Closed by geido** 2022-03-16 16:29 UTC
Labels: #bug
