### ISSUE TITLE
Country map - Saudi Arabia only recognizing one state

### ISSUE THREAD

**Issue by PowerDinosaur** [apache/superset#25071] opened 2023-08-24 11:10 UTC
#### How to reproduce the bug

1. Prepare data with the expected ISO codes (SA-01, SA-02,etc...)
2. Create a country map visual

### Expected results

See all states of Saudi Arabia

### Actual results

Only SA-14 (Asir) is displayed

#### Screenshots

![kép](https://github.com/apache/superset/assets/137398193/fd1def82-070b-4996-824d-914ad314e946)

### Environment

- browser type and version: mozilla firefox 116.0.3
- superset version: 2.1 non-dev
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active: FEATURE_FLAGS = {"ALERT_REPORTS": True}
FEATURE_FLAGS = {"ALERT_REPORTS": True,"DASHBOARD_CROSS_FILTERS": True,"DRILL_TO_DETAIL": True,"DRILL_BY": True,"HORIZONTAL_FILTER_BAR": True}

**Comment by PowerDinosaur** [comment] 2023-08-24 11:19
Actually u can see another state while pretty small (see the picture below) If i search the states i can see different values but still looking like this. I guess the map file is bad.  (sometimes there are 2 little cirlces)
![kép](https://github.com/apache/superset/assets/137398193/1679163b-185e-49ba-9f9f-514b0ca63e46)

**Comment by rusackas** [comment] 2024-03-08 19:12
It seems like this is likely fixed by now (the GeoJson has since been regenerated), and the issue is pretty out of date if not. If people are still encountering this in current versions (3.x) please open a new Issue with updated context or a PR to address the problem. Thanks!

**Closed by rusackas** 2024-03-08 19:12 UTC
