### ISSUE TITLE
[Dashboard]Deleting an existing tab immediately after having created a new tab with title does not work

### ISSUE THREAD

**Issue by geido** [apache/superset#13158] opened 2021-02-16 18:30 UTC
👍  Hi @geido thanks for PR it looks good changes, I just found some buggy behavior, can you look please:

https://user-images.githubusercontent.com/56388545/107982543-e91dfc00-6fcc-11eb-99d9-3986b30f00ad.mov

_Originally posted by @simcha90 in https://github.com/apache/superset/issues/12773#issuecomment-779390572_

**Comment by geido** [comment] 2021-02-16 18:38
Specific steps to reproduce:

1. Create a new tab and give it a title
2. Create another tab and give it a title
3. Now without moving the focus to it,  click on the "X" icon of the **previous** tab to delete it
4. Observe the issue. The Delete modal will remain stuck


https://user-images.githubusercontent.com/60598000/108106681-f7d0e580-7096-11eb-8d6e-7b35f5f82ed8.mp4

**Comment by rusackas** [comment] 2021-05-05 22:56
Unable to reproduce... closing issue, but will continue to track the related PR linked above which should make sure the story ends here.

**Closed by rusackas** 2021-05-05 22:56 UTC
Labels: bash!, bug, viz:dashboard:tab
