### ISSUE TITLE
Superset backup and restore solution

### ISSUE THREAD

**Issue by yangtian9999** [apache/superset#17998] opened 2022-01-11 08:11 UTC
**Is your feature request related to a problem? Please describe.**
Any solution of content backup and restore solution for superset.

**Describe the solution you'd like**
Easy one click full content backup and restore. including chart, dababase config, dashboard, user info, user auth......

Thanks, superset team.

**Comment by ad-m** [comment] 2022-01-20 09:50
User authentications depends on authentication methods which is configured, so backup user authentication might be out of scope of Apache Superset at all.

Chart, database connections, dashboards are stored in PostgreSQL database. Powinny być wystarczające są standardowe mechanizmy backupu dla PostgreSQL. Standard backup mechanisms for PostgreSQL should be sufficient. Their detailed implementation depends on the environment (cloud offering vs. on-premise) and requirements eg. block device snapshots, logical backup, physical backup, delayed replica, WAL archiving. See https://www.postgresql.org/docs/9.1/backup.html .

**Comment by srinify** [comment] 2022-01-27 13:59
Hi @yangtian9999 closing this for now as it's not a bug or an enhancement request within the scope of Superset. The challenge here is that you can use multiple database systems for your metadata database. So this is better handled as part of the software development lifecycle, where you're better off just backing up and restoring the Superset metadata database you're using.

If you have more questions here or want to start a discussion, I encourage you to use Github Discussions or join the Superset Slack (https://superset.apache.org/community)

**Closed by srinify** 2022-01-27 13:59 UTC
Labels: enhancement:request
