### ISSUE TITLE
Not possible to configure native filters in 1.4.1 / mapping filters gets lost when editing native filters

### ISSUE THREAD

**Issue by marinej-BR** [apache/superset#19277] opened 2022-03-21 10:58 UTC
When native filters are edited, the configuration about mapping filter is removed.

#### How to reproduce the bug

1. Create a dashboard that includes at least two charts et one filter box. The filter box should only apply to one of the two charts
2. Open the native filters properties using the "Edit" action
3. Make an edit and save
4. Reopen the Dashboard

### Expected results

The filter mapping works normally.

### Actual results

The configuration about mapping filter is removed.

#### Screenshots

none added

### Environment

- Browser type and version: Google Chrome Version 99.0.4844.51 (Oficial build) (x86_64)
- Superset version: 1.4.1
- Python version: 3.8.12
- Node.js version: doesn’t apply, I run on Kubernetes, using gunicorn as server
- Source : AWS Athena
- Any feature flags active: ALERT_REPORTS, ENABLE_TEMPLATE_PROCESSING, DASHBOARD_NATIVE_FILTERS

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [X] I have reproduced the issue with at least the latest released version of superset.
- [X] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by amitmiran137** [comment] 2022-04-29 15:18
@villebro does a 1.5.1 is planned?
Maybe it can include that issue

**Comment by villebro** [comment] 2022-05-03 07:14
@amitmiran137 yes, a 1.5.1 is indeed planned. I'm unfortunately not able to work on this right now, but this seems like a fairly simple fix. Ping @stephenLYZ or @simcha90 if you are able to take this on?

**Comment by stephenLYZ** [comment] 2022-05-03 16:12
@villebro I will take on it.

**Comment by villebro** [comment] 2022-05-04 12:57
Thanks a lot @stephenLYZ - please feel free to ping me for a review if needed!

**Comment by stephenLYZ** [comment] 2022-05-06 08:33
@villebro It looks like I can't reproduce on the latest master. Are there more screenshots or demos about this issue?

**Comment by rusackas** [comment] 2023-01-26 16:03
@andrey-zayats took a look at this and was unable to reproduce the issue. I'm going to go ahead and remove the `validation:required` label and close the issue. If anyone sees this happening in Superset 2.0.x or later, or on `master`, we're open to revisiting this conversation, re-opening the ticket, or triaging a new Issue with updated context. Thank you!

**Closed by rusackas** 2023-01-26 16:03 UTC
Labels: dashboard:native-filters, #bug, v1.4, v1.5
