### ISSUE TITLE
Applying `GROUP BY` on `Time-series (Bar) Chart` Omits NULL group values

### ISSUE THREAD

**Issue by andrewscarani** [apache/superset#15566] opened 2021-07-07 00:09 UTC
### Expected results
Total counts of stacked bar chart should be the same before/after `GROUP BY` has been introduced.

### Actual results
Total counts of stacked bar chart with `GROUP BY` applied are **wonky** and don't match those without `GROUP BY` applied. It seems likely that this only occurs when using a `GROUP BY` on a column where the column's value could be `NULL`.

### Steps to recreate:
1. Query:
```
SELECT 'group1' as test, 10 AS count, CURRENT_DATE() AS date
UNION ALL
SELECT NULL as test, 5 AS count, CURRENT_DATE() AS date
UNION ALL
SELECT 'group3' as test, 5 AS count, CURRENT_DATE() AS date
UNION ALL
SELECT 'group4' as test, 5 AS count, CURRENT_DATE() AS date
```
2. Create Time Series Stacked Bar Chart (ECharts) without GROUP BY
![Screen Shot 2021-07-06 at 5 08 02 PM](https://user-images.githubusercontent.com/4078980/124681121-b9d53200-de7c-11eb-91fb-2d1539082c16.png)

3. Compare with GROUP BY and observe some other weird behavior here where the two stacked colors exclude the 3rd non-null group...
![Screen Shot 2021-07-06 at 5 08 27 PM](https://user-images.githubusercontent.com/4078980/124681177-c8bbe480-de7c-11eb-9f1e-dfe84a40da14.png)

#### Other Screenshots
Without:
<img width="1034" alt="Screen Shot 2021-07-06 at 4 57 15 PM" src="https://user-images.githubusercontent.com/4078980/124680415-3830d480-de7b-11eb-8e06-66d6b7d4a835.png">

With `GROUP BY`:
<img width="1025" alt="Screen Shot 2021-07-06 at 4 47 25 PM" src="https://user-images.githubusercontent.com/4078980/124679731-d9b72680-de79-11eb-82b0-a80a291b3bcd.png">

### Environment

Not sure. Using Preset.io latest

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [x] I have reproduced the issue with at least the latest released version of superset.
- [] I have checked the issue tracker for the same issue and I haven't found one similar. - Maybe this one is similar? https://github.com/apache/superset/issues/13850

**Comment by junlincc** [comment] 2021-07-08 21:55
Reproduced. 
observation: Behavior is inconsistent in Timeseries Bar, Echarts Bar and regular Bar🤦🏾‍♀️
Timeseries Bar & Echarts Bar - no Null in both legend and chart
Regular Bar - showing Null in both legend and chart
it's still controversial how we should handle NULLs in Superset chart.  

Regular bar
<img width="947" alt="Screen Shot 2021-07-08 at 2 45 57 PM" src="https://user-images.githubusercontent.com/67837651/124994844-532a5280-dffb-11eb-85eb-fb85dc3b27a9.png">
<img width="756" alt="Screen Shot 2021-07-08 at 2 50 29 PM" src="https://user-images.githubusercontent.com/67837651/124995574-6a1d7480-dffc-11eb-9dc1-5853e839f97c.png">

@andrewbastian sorry it's a bit of a mess here. what's your use case of displaying NULL count?

**Comment by andrewscarani** [comment] 2021-07-09 00:45
@junlincc 100% agree to show NULLs. They are a valid category group and without them, data becomes skewed. I would prefer if the new ECharts behaved in the same manner as the existing Bar Charts. I really don't understand why anyone would disagree tbh.

**Comment by andrewscarani** [comment] 2022-05-02 16:41
Does anyone know if this has been fixed? This is an incredibly important bug to fix, more than a feature

**Comment by andrewscarani** [comment] 2022-05-02 16:44
![Screen Shot 2022-05-02 at 9 44 24 AM](https://user-images.githubusercontent.com/4078980/166289311-500a53f9-e2ce-47fe-bcf1-20e8553117b7.png)
It appears that this may have already been fixed?

**Comment by rusackas** [comment] 2023-01-06 23:48
Indeed, I believe this issue was fixed. I'm struggling to find the PR I'm thinking of, but I believe it resolved at least a couple of quirky/glitchy issues in the way ECharts was erroneously handling null values in bar charts (stacked ones in particular IIRC). I'll close this since it's been quiet for a while, but we can certainly re-open if this is still an issue in Superset 2.0.1

**Closed by rusackas** 2023-01-06 23:48 UTC
Labels: viz:charts:bar, #bug, test:case, need:consensus
