### ISSUE TITLE
[cosmetic]multiple cosmetic issues in Explore

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14570] opened 2021-05-11 18:07 UTC
1.  spacing in between is gone..
<img width="539" alt="Screen Shot 2021-05-11 at 11 00 22 AM" src="https://user-images.githubusercontent.com/67837651/117863516-b6407880-b248-11eb-9b33-b8df5bb4b709.png">
2. Autocomplete filter checkbox moved to the next line...
<img width="424" alt="Screen Shot 2021-05-11 at 10 58 59 AM" src="https://user-images.githubusercontent.com/67837651/117863586-c8bab200-b248-11eb-8c6b-4cfd367ed3df.png">
3. Pill for column with no datatype looks funky  
<img width="858" alt="Screen Shot 2021-05-11 at 10 58 44 AM" src="https://user-images.githubusercontent.com/67837651/117863711-ec7df800-b248-11eb-9924-86ec914e050a.png">

**Comment by rusackas** [comment] 2021-05-12 01:40
Can't seem to repro #1. Looking into the others...

**Comment by rusackas** [comment] 2021-05-12 02:07
Not seeing #2 either, in Chrome... starting to wonder why I'm seeing something different 😜

I definitely see #3 though... on the case.

**Comment by rusackas** [comment] 2021-05-12 04:59
PR for #3 open: #14585 - if that's enough to close this issue (since I can't reproduce the others) let me know.

**Comment by junlincc** [comment] 2021-05-12 16:42
<img width="568" alt="Screen Shot 2021-05-12 at 9 32 02 AM" src="https://user-images.githubusercontent.com/67837651/118012820-4db7d100-b306-11eb-920f-a56b0ced8f7f.png">

@pkdotson can you add a few px in between? thanks 😊

**Comment by pkdotson** [comment] 2021-05-13 00:48
pr is out for the explore err message: https://github.com/apache/superset/pull/14597

**Comment by suddjian** [comment] 2021-05-13 22:22
I am able to repro 1 and 2, will fix

**Comment by suddjian** [comment] 2021-05-19 21:04
fix for 2 merged https://github.com/apache/superset/pull/14701

**Comment by suddjian** [comment] 2021-05-20 00:20
fix for 1 merged in #14679

**Closed by suddjian** 2021-05-20 00:20 UTC
Labels: bash!, bug:cosmetic
