### ISSUE TITLE
Unable to download original raw file on selecting "Export to original" in pivot table.

### ISSUE THREAD

**Issue by vaijayanthisundaram** [apache/superset#25805] opened 2023-10-31 05:59 UTC
I created a pivot table and on clicking "Drill to detail"->"Edit chart" - > "Export to original .csv" , I expected to be able to download a file containing all the raw records (not the summary shown in the pivot table).

 But downloaded file contains only summary.

- browser type and version: Chrome Version 118.0.5993.117
- superset version: `superset version` 3.0.1

<img width="551" alt="Pivot table download original" src="https://github.com/apache/superset/assets/142204309/d02633ac-0740-4938-aee2-c41c6673fae2">

<img width="712" alt="Pivot table download" src="https://github.com/apache/superset/assets/142204309/361e4f8f-0a93-45c9-8b86-f5db0f9e9c8c">

**Comment by rusackas** [comment] 2024-04-04 02:19
This is currently open as a feature request discussion here: https://github.com/apache/superset/discussions/19705

I'll close this thread in favor of that one, since it's not a bug per se, but rather a feature request. You can, of course, always pivot in your spreadsheet tool in the meantime.

**Closed by rusackas** 2024-04-04 02:19 UTC
