### ISSUE TITLE
[listview]remove unnecessary scroll bar and empty space from list view 

### ISSUE THREAD

**Issue by junlincc** [apache/superset#14800] opened 2021-05-24 23:23 UTC
https://user-images.githubusercontent.com/67837651/119418133-27057d00-bcac-11eb-9652-5ab9f0542278.mov

**Comment by geido** [comment] 2021-05-27 17:38
I am picking this up

**Comment by eschutho** [comment] 2021-05-28 20:24
@AAfghahi also took a look at this but neither of us were able to reproduce.

**Comment by geido** [comment] 2021-06-02 16:15
Same. Could not reproduce even in different resolutions

**Comment by pkdotson** [comment] 2021-06-11 20:06
Can't reproduce. Gonna close this for now!

**Closed by pkdotson** 2021-06-11 20:06 UTC
Labels: P2, bash!, bug:cosmetic
