### ISSUE TITLE
Pivot Table show columns total  question

### ISSUE THREAD

**Issue by ab291478089** [apache/superset#23560] opened 2023-04-03 11:50 UTC
#### How to reproduce the bug

1. As shown in the screenshot，the total calculation involving rates is not what is expected.

### Expected results
 total calculation  is sum(num_boys)* 1.0 / sum(num) no groupby

### Actual results

what actually happens.

#### Screenshots
![image](https://user-images.githubusercontent.com/48116873/229499533-7d8971fd-f5d6-4733-8464-d2fc457254f4.png)

### Environment

(please complete the following information):

- browser type and version:
- superset version: `superset version`
- python version: `python --version`
- node.js version: `node -v`
- any feature flags active:

### Checklist

Make sure to follow these steps before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if there are any.
- [ ] I have reproduced the issue with at least the latest released version of superset.
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar.

**Comment by rusackas** [comment] 2023-04-07 16:20
Could you elaborate on the expected behavior here? I didn't break out the calculator, but at a glance, the math all looks correct to me, even if the column formats are perhaps undesirable (only the third column is actually a percentage, really). The sums look accurate too, even if summing percentages is an odd thing to do.

**Comment by pandinug** [comment] 2023-04-07 17:07
I have this exact same question too and because of this am not using the Pivot table chart as much as I would like, at least not for percentages or averages.

The expected result would be that the resulting number in the totals row would follow the same calculation as the other rows. 
So sum(num_boys) / sum(num) should show the total percentage boys over all states (around 60% I would guess) and not the sum of the percentage of all rows.

**Comment by ab291478089** [comment] 2023-04-11 01:38
> Could you elaborate on the expected behavior here? I didn't break out the calculator, but at a glance, the math all looks correct to me, even if the column formats are perhaps undesirable (only the third column is actually a percentage, really). The sums look accurate too, even if summing percentages is an odd thing to do.

Yes, I expect the same result as my friend downstairs.    I have this exact same question too and because of this am not using the Pivot table chart as much as I would like, at least not for percentages or averages.

The expected result would be that the resulting number in the totals row would follow the same calculation as the other rows.
So sum(num_boys) / sum(num) should show the total percentage boys over all states (around 60% I would guess) and not the sum of the percentage of all rows.

**Comment by ShubhamDalmia** [comment] 2023-04-12 16:49
Even I'm facing the same issue. Ratio / Percentage values are non-aggregatable (nonag or nag) values and as mentioned in the screenshot, 657.67 % is not the correct value, because what we're trying to calculate is percentage out of 100.
Example : 

Speed = Distance / Time

Speed Distance Time
10		100		10
25     	100		4

TOTAL : (INCORRECT)(AS PER SUPERSET)
35      200     14

TOTAL : (CORRECT)
14.28      200     14

**Comment by pandinug** [comment] 2023-04-12 17:20
The interesting thing here is that the Table viz total row does correctly calculate these metrics, so the behavior on the Pivot table seems to be designed this way for a reason.

**Comment by ShubhamDalmia** [comment] 2023-04-12 19:48
As per my basic investigation, when it is Table viz, the Total is calculated from the backend and comes as API response from the /chart/data endpoint.
Whereas, in case of Pivot viz, the total is being calculated in the frontend itself when the "Show Column Total" checkBox is clicked. The data coming from /chart/data endpoint is just granular data, and sum is being calculated in frontend.

**Comment by alexanderdrobyshev** [comment] 2023-08-03 18:07
Has anyone found a solution to this?

**Comment by mtthsbrr** [comment] 2023-09-27 09:28
Linking a similar issue: https://github.com/apache/superset/issues/16952. Also no solution unfortunately.

FWIW I found the "Table" chart producing the correct/expected values in "Total". Getting this also in the Pivot Table chart would still be very desirable.

![image](https://github.com/apache/superset/assets/49281986/690b0527-c072-4c46-a9a6-2e4a6df01691)

**Comment by rusackas** [comment] 2024-03-18 21:50
It's been six months since this thread was last commented on, so it's at risk of being closed as stale. PRs welcome, of course, but it would be great to at least get confirmation that this is still happening on Superset 3.x or newer to keep it open, since we no longer support 2.0.

**Comment by ppalyafari** [comment] 2024-03-31 14:42
> It's been six months since this thread was last commented on, so it's at risk of being closed as stale. PRs welcome, of course, but it would be great to at least get confirmation that this is still happening on Superset 3.x or newer to keep it open, since we no longer support 2.0.

Hello! This is still an issue in Superset 3.x, and this problem has actually been popping up in the past, just to link a few:

#20076 
#16952 
#18548 

As I was looking for a workaround, I bumped into a thread in the Slack channel, where @ETselikov shared a list of their Superset modifications, and this was on the list:

"New total/subtotal calculation mode which will calculate values via a separate query. This is mostly used for percentage metrics for which it is not possible to calculate totals by simply aggregating rows in a table."

I've read the thread and there was a discussion about sharing some of their modifications with the community, but the last comment on that thread was 4 months ago, so no idea what was discussed after that. If anyone knows anything about this, please share! I guess it wouldn't make sense to start working on this feature if it is going to be contributed.

**Comment by rusackas** [comment] 2024-04-02 21:46
I'm not sure if @ETselikov is planning to contribute this or not, but surely it would be a much-welcomed PR :)

**Comment by rusackas** [comment] 2024-04-02 21:47
...or @TechAuditBI for that matter...

**Comment by rusackas** [comment] 2024-06-03 16:57
Closing this issue in favor of another that sums it up nicely: https://github.com/apache/superset/issues/25747

**Closed** 2024-06-03 17:07 UTC
Labels: #bug
