### ISSUE TITLE
Error when enabling GENERIC_CHART_AXES feature in Apache Superset

### ISSUE THREAD

**Issue by vvsiv** [apache/superset#24527] opened 2023-06-27 11:28 UTC
Hello there,

I have encountered an issue when enabling the GENERIC_CHART_AXES feature in Apache Superset. The problem is with the following chart types: Calendar Heatmap, Event Flow, Horizon Chart, Paired t-test Table.

When trying to create a new chart of these types or editing an existing one, I receive the following error message: "Datetime column not provided as part table configuration and is required by this type of chart."

Steps to reproduce:

Enable GENERIC_CHART_AXES feature in Apache Superset.
Attempt to create or edit a chart of the types: Calendar Heatmap, Event Flow, Horizon Chart, Paired t-test Table.
Expected result:
The charts should be created/edited without any errors.

Actual result:
The error "Datetime column not provided as part table configuration and is required by this type of chart" is displayed.
![2023-06-27 14 25 07](https://github.com/apache/superset/assets/80745752/e0702be6-e48f-4258-b69e-ecdde671a76d)

This issue prevents me from utilizing these specific chart types while using the GENERIC_CHART_AXES feature. Any assistance with resolving this issue would be greatly appreciated.

Thank you for your help.

**Comment by sfirke** [comment] 2023-06-27 15:32
What version of Superset are you using?

**Comment by vvsiv** [comment] 2023-06-27 15:44
I am using Apache Superset version 2.1.

**Comment by sfirke** [comment] 2023-07-10 18:21
I can confirm this issue on 2.1.0 for these chart types, agreed this seems like a bug.  Seems related to https://github.com/apache/superset/issues/23766.

**Comment by sfirke** [comment] 2023-07-10 18:22
I wonder if this fixed it, merged on May 1: https://github.com/apache/superset/pull/23865

**Comment by sfirke** [comment] 2023-09-08 19:34
@vvsiv are you able to test this with the just-released version 2.1.1?

**Comment by rusackas** [comment] 2024-03-11 22:46
Hi there, and sorry this has gone quiet for so long. We're no longer supporting Superset 2.x or prior, and it's been a while since this thread saw any activity, so I'm closing this as stale. If it is still an issue in Superset 3.x (where this feature flag is on by default now!), we can re-open this, or feel free to open a new issue with updated context.

**Closed by rusackas** 2024-03-11 22:46 UTC
